### ISSUE TITLE
The 'out_file' trait of a RenameOutputSpec instance must be a file name, but a value of '/root/src/fmriprep/fsaverage.nii' <class 'str'> was specified.

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1016]
Could be an infrastructure issue. Adding so we could see if this comes up more often

```
	 [Node] Error on "_rename_src0" (/root/src/fmriprep/work/fmriprep_wf/single_subject_202_wf/func_preproc_task_walkstatement_run_01_wf/bold_surf_wf/rename_src/mapflow/_rename_src0)
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 339, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 487, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 571, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 517, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 614, in aggregate_outputs
    raise error
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 607, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_types.py", line 1493, in validate
    self.error( object, name, value )
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'out_file' trait of a RenameOutputSpec instance must be a file name, but a value of '/root/src/fmriprep/fsaverage.nii' <class 'str'> was specified.
```

https://openneuro.org/datasets/ds001225/versions/00003?app=FMRIPREP&version=53&job=5a971b93df832f000104dd16

**Comment by effigies** [comment]
Is this still an issue?

**Comment by cmpetty** [comment]
Yes .. attaching a crash report from a recent subject

[crash-20180818-031928-af155-rename_src-06923c63-7c38-4d2d-a79e-bcce6c9e5626.txt](https://github.com/poldracklab/fmriprep/files/2303902/crash-20180818-031928-af155-rename_src-06923c63-7c38-4d2d-a79e-bcce6c9e5626.txt)

**Comment by effigies** [comment]
Thanks for the report. What version of fMRIPrep are you running, and how is it installed (Docker, Singularity, pip, etc.)?

**Comment by cmpetty** [comment]
v1.1.2 ... I have both a relatively fresh install from 7/9 as well as the singularity version 

`[cmp12@blade24 ~]$ fmriprep --version
fmriprep v1.1.2

[cmp12@blade24 ~]$ singularity run /usr/local/packages/singularity/images/fmriprep.simg --version
fmriprep v1.1.2
`

**Comment by oesteban** [comment]
@cmpetty I think this is related to #936 and #1217 that seem to have been fixed in version 1.1.3 that pinned Nipype to 1.1.1. Could you please update and check whether we indeed fixed this issue?

The latest stable release is 1.1.4. There are a bunch of features in that release that I would recommend over 1.1.2.

**Comment by cmpetty** [comment]
@oesteban Thanks.  I updated to 1.1.4 and issue seems to be resolved.

**Comment by effigies** [comment]
Great! Closing this for now.
