### ISSUE TITLE
Running subjects in parallel with --write-graph flag can lead to a conflict

### ISSUE THREAD

**Issue by eort** [poldracklab/fmriprep#1028]
Hi, 

I was running fmriprep via singularity on an HTConder cluster 21 subjects in parallel with this command:

~~~.python
# SUB is a placeholder that was filled at runtime
PYTHONPATH="" singularity run -H /home/data/foraging 
/home/data/foraging/code/poldracklab_fmriprep_1.0.8-2018-02-23-e5a227027e57.img 
/home/data/foraging/ /home/data/foraging/scratch/fmriPrep participant 
 --participant-label SUB 
-w /home/data/foraging/scratch/tmp_work 
--output-space T1w fsaverage5 template  
--use-syn-sdc --low-mem --nthreads 1 --ignore slicetiming fieldmaps 
--write-graph 
--fs-license-file /home/data/foraging/license.txt
~~~

It worked fine for all but 2 participants. For those two, fmriprep crashed with this error message: 

~~~
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.8', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 259, in main
    fmriprep_wf.write_graph(graph2use="colored", format='svg', simple_form=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 438, in write_graph
    outfname = format_dot(dotfilename, format=format)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/utils.py", line 1313, in format_dot
    formatted_dot, _ = _run_dot(dotfilename, format_ext=format)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/utils.py", line 1330, in _run_dot
    resource_monitor=False).run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 516, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 1023, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 960, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
dot -Tsvg -o"/home/data/foraging/scratch/tmp_work/fmriprep_wf/graph.svg" "/home/data/foraging/scratch/tmp_work/fmriprep_wf/graph.dot"
Standard output:

Standard error:
Error: /home/data/foraging/scratch/tmp_work/fmriprep_wf/graph.dot: syntax error in line 5639 near 'led'
Return code: 1
~~~

When re-running both subjects again (in parallel), one worked fine, the other one crashed. And when re-running the last one once again, it worked also fine for this subject. 

Not sure what the problem was, but could it be some sort of conflict when two different runs are trying to access. `graph.dot` at the same time?

**Comment by effigies** [comment]
Yes, writing the graph will occur in the common work directory. I see three options:

1) Run each subject with a separate work/scratch directory. This will cause little issue, as there is very little common computation.
2) Write graphs only for one subject. These graphs can be very large, so graphing multiple subjects' workflows will probably add more clutter than clarity.
3) Run all of your subjects with the same work directory and no `--write-graph`, and then run a final `fmriprep` for all subjects with `--write-graph`. This should re-use all of your data, so you won't be recomputing, but it may take some time, as large workflows require time to verify inputs/outputs of each node.
