### ISSUE TITLE
ValidateImage: SVD did not converge

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1069]
https://openneuro.org/datasets/ds001339/versions/00002/logs/FMRIPREP%2Fdefault%2F3e2efe47-45d7-44e8-ab35-f661d7889a34

```
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
/usr/local/miniconda/lib/python3.6/site-packages/nibabel/nifti1.py:1012: RuntimeWarning: invalid value encountered in true_divide
  R = RZS / zooms
/usr/local/miniconda/lib/python3.6/site-packages/numpy/linalg/linalg.py:1821: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
180426-04:13:54,826 workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_05_wf.func_preproc_task_iaps_run_04_wf.bold_reference_wf.validate" (/root/src/fmriprep/work/fmriprep_wf/single_subject_05_wf/func_preproc_task_iaps_run_04_wf/bold_reference_wf/validate)
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.11', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 274, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 602, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 168, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 487, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 571, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 516, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/images.py", line 431, in _run_interface
    img.set_qform(img.get_sform(), sform_code)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/nifti1.py", line 1890, in set_qform
    self._header.set_qform(affine, code, strip_shears)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/nifti1.py", line 1024, in set_qform
    P, S, Qs = npl.svd(R)
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 1404, in svd
    u, s, vt = gufunc(a, signature=signature, extobj=extobj)
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 99, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.linalg.LinAlgError: SVD did not converge
```

Could be an indication of input data header issue that should be checked in the validator.

**Comment by effigies** [comment]
fslhd showing the sform of a failing image:

```
sform_name     Scanner Anat
sform_code     1
sto_xyz:1      0.000000  0.000000  0.000000  0.000000
sto_xyz:2      0.000000  0.000000  0.000000  0.000000
sto_xyz:3      0.000000  0.000000  0.000000  0.000000
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
```

**Comment by effigies** [comment]
We can check for this and similar possible issues, but this should probably be a validation error. An invalid sform should not have a valid code.

**Comment by chrisfilo** [comment]
how's the qform for this image? Agree this should be added to the BIDS validator, but can we make the sanitizer more robust?

**Comment by effigies** [comment]
```
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      3.125000  0.000000  0.000000  0.000000
qto_xyz:2      0.000000  3.125000  0.000000  0.000000
qto_xyz:3      0.000000  0.000000  3.000000  0.000000
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Left-to-Right
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
```

**Comment by chrisfilo** [comment]
Thx. FMRIPREP should handle this better. Will also open an issue for the validator.

**Comment by effigies** [comment]
Yes, we can make the sanitizer more robust.
