### ISSUE TITLE
ModuleNotFoundError: No module named 'future' (fresh fmriprep-install)

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1079]
```
filo@MSI MINGW64 ~
$ conda create --name wrapper_test python=3.6
Solving environment: done

## Package Plan ##

  environment location: C:\Users\filo\Anaconda3\envs\wrapper_test

  added / updated specs:
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2018.4.16          |           py36_0         143 KB

The following NEW packages will be INSTALLED:

    certifi:        2018.4.16-py36_0
    pip:            9.0.3-py36_0
    python:         3.6.5-h0c2934d_0
    setuptools:     39.0.1-py36_0
    vc:             14-h0510ff6_3
    vs2015_runtime: 14.0.25123-3
    wheel:          0.31.0-py36_0
    wincertstore:   0.2-py36h7fe50ca_0

Proceed ([y]/n)? y


Downloading and Extracting Packages
certifi 2018.4.16################################################################################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > activate wrapper_test
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#


filo@MSI MINGW64 ~
$ source activate wrapper_test
(wrapper_test)
filo@MSI MINGW64 ~
$
(wrapper_test)
filo@MSI MINGW64 ~
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import future
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'future'
>>>
KeyboardInterrupt
>>> exit()
(wrapper_test)
filo@MSI MINGW64 ~
$ pip install --upgrade fmriprep-docker
Collecting fmriprep-docker
  Downloading https://files.pythonhosted.org/packages/1b/46/0513ef5eed5622dbb859ef5d3fe40fc69f442a036d08866d9d3c37921f00/fmriprep-docker-1.0.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\filo\AppData\Local\Temp\pip-build-xwxz93fl\fmriprep-docker\setup.py", line 43, in <module>
        main()
      File "C:\Users\filo\AppData\Local\Temp\pip-build-xwxz93fl\fmriprep-docker\setup.py", line 14, in main
        info = runpy.run_path(op.join(this_path, 'fmriprep_docker.py'))
      File "C:\Users\filo\Anaconda3\envs\wrapper_test\lib\runpy.py", line 263, in run_path
        pkg_name=pkg_name, script_name=fname)
      File "C:\Users\filo\Anaconda3\envs\wrapper_test\lib\runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "C:\Users\filo\Anaconda3\envs\wrapper_test\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Users\filo\AppData\Local\Temp\pip-build-xwxz93fl\fmriprep-docker\fmriprep_docker.py", line 19, in <module>
        from future import standard_library
    ModuleNotFoundError: No module named 'future'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\filo\AppData\Local\Temp\pip-build-xwxz93fl\fmriprep-docker\
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
Reported at https://neurostars.org/t/trouble-installing-fmriprep-docker/1614.

It's weird because future is listed as requirements at https://github.com/poldracklab/fmriprep/blob/master/wrapper/setup.py#L30

**Comment by oesteban** [comment]
Why don't we just drop future? Since we dropped python 2 it was left there just in case I made some catches. But, at the point it creates more trouble than it solves... we can just drop it.

**Comment by chrisfilo** [comment]
That would be ideal if possible.
