### ISSUE TITLE
CI: Tests failing on ds005

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1090]
Is this just a case of the cache needing bumping? Merged that last PR before I realized current master is failing.

**Comment by effigies** [comment]
2 errors (at least from one log):

```
	 [Node] Running "ica_aroma" ("niworkflows.interfaces.segmentation.ICA_AROMARPT"), a CommandLine Interface with command:
ICA_AROMA.py -den nonaggr -i /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/smooth/vol0000_xform-00000_merged_smooth.nii.gz -meldir /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/melodic -mc /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/bold_hmc_wf/normalize_motion/motion_params.txt -o out
180501-06:50:26,787 workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_01_wf.func_preproc_task_mixedgamblestask_run_01_wf.ica_aroma_wf.ica_aroma" (/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/ica_aroma)
180501-06:50:26,821 workflow ERROR:
	 Node ica_aroma failed to run on host e3751766a815.
180501-06:50:26,825 workflow ERROR:
	 Saving crash info to /out/fmriprep/sub-01/log/20180501-062426_5a7b4148-59ac-4e81-b138-d7cc3247b644/crash-20180501-065026-root-ica_aroma-05cc8a84-adab-4017-890b-6a192243aa77.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 520, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/report_base.py", line 51, in _run_interface
    ReportCapableInterface, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 1020, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 957, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
ICA_AROMA.py -den nonaggr -i /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/smooth/vol0000_xform-00000_merged_smooth.nii.gz -meldir /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/melodic -mc /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/bold_hmc_wf/normalize_motion/motion_params.txt -o out
Standard output:

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
  - The existing/specified MELODIC directory will be used.
  - The MELODIC directory does not contain the required 'stats' folder. Mixture modeling on the Z-statistical maps will be run.
Standard error:
Traceback (most recent call last):
  File "/opt/ICA-AROMA/ICA_AROMA.py", line 193, in <module>
    aromafunc.runICA(fslDir, inFile, outDir, melDir, mask, dim, TR)
  File "/opt/ICA-AROMA/ICA_AROMA_functions.py", line 60, in runICA
    os.makedirs(melDir)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'out/melodic.ica'
Return code: 1
```

```
180501-06:53:35,553 workflow INFO:
	 [MultiProc] Running 2 tasks, and 12 jobs ready. Free memory (GB): 3.79/4.00, Free processors: 0/2.
                     Currently running:
                       * fmriprep_wf.single_subject_01_wf.func_preproc_task_mixedgamblestask_run_01_wf.bold_confounds_wf.signals
                       * fmriprep_wf.single_subject_01_wf.func_preproc_task_mixedgamblestask_run_02_wf.ica_aroma_wf.ica_aroma
180501-06:53:37,89 workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_01_wf.func_preproc_task_mixedgamblestask_run_02_wf.ica_aroma_wf.ica_aroma" (/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_02_wf/ica_aroma_wf/ica_aroma)
180501-06:53:37,174 workflow ERROR:
	 Node ica_aroma failed to run on host e3751766a815.
180501-06:53:37,175 workflow ERROR:
	 Saving crash info to /out/fmriprep/sub-01/log/20180501-062426_5a7b4148-59ac-4e81-b138-d7cc3247b644/crash-20180501-065337-root-ica_aroma-16aaade3-05a0-488b-bc9f-aaf2b67e88c4.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 520, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/report_base.py", line 60, in _run_interface
    self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/segmentation.py", line 157, in _post_run_hook
    outputs = self.aggregate_outputs(runtime=runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 618, in aggregate_outputs
    raise error
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 611, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/traits_extension.py", line 112, in validate
    self.info_text, value))
traits.trait_errors.TraitError: The trait 'nonaggr_denoised_file' of an ICA_AROMAOutputSpecRPT instance is an existing file name, but the path  '/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_02_wf/ica_aroma_wf/ica_aroma/out/denoised_func_data_nonaggr.nii.gz' does not exist.
```

**Comment by oesteban** [comment]
I don't know, I found out this yesterday.

We noticed some weirdness on the work directory (https://github.com/poldracklab/fmriprep/pull/1064#issuecomment-383394408).

Right now I'm debugging with ssh to see if this is related to some permissions issue (and a cache needing to be pruned).

**Comment by oesteban** [comment]
Okay, first trace is that `/tmp/ds005/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_02_wf` exists. But those folders are owned by `root:root`.

**Comment by oesteban** [comment]
I wonder how ICA-AROMA ever worked :D

**Comment by oesteban** [comment]
Okay, new findings:

- It may not be possible to run ICA-AROMA on ds054 (I guess it is too downsampled): https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;b4cd57d7.1210
- MELODIC is the one bit failing in #1099 at the moment. It seems like the failure happens in ICA-AROMA because of nipy/nipype#2567.

I will roll back to ds005 (although that will increase that job's run time).

**Comment by oesteban** [comment]
(Note: when I moved ICA-AROMA to ds054 the aroma errors migrated  https://circleci.com/gh/poldracklab/fmriprep/2965)

**Comment by oesteban** [comment]
Reopened as per https://neurostars.org/t/ica-aroma-error-path-does-not-exist/1917

```
[Node] Error on "fmriprep_wf.single_subject_01_wf.func_preproc_ses_4_task_rest_wf.ica_aroma_wf.ica_aroma" (/root/src/fmriprep/work/fmriprep_wf/single_subject_01_wf/func_preproc_ses_4_task_rest_wf/ica_aroma_wf/ica_aroma)
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 314, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 162, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 224, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/segmentation.py", line 164, in _post_run_hook
    outputs = self.aggregate_outputs(runtime=runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 620, in aggregate_outputs
    raise error
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 613, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 112, in validate
    self.info_text, value))
traits.trait_errors.TraitError: The trait 'nonaggr_denoised_file' of an ICA_AROMAOutputSpecRPT instance is an existing file name, but the path  '/root/src/fmriprep/work/fmriprep_wf/single_subject_01_wf/func_preproc_ses_4_task_rest_wf/ica_aroma_wf/ica_aroma/out/denoised_func_data_nonaggr.nii.gz' does not exist.
```

**Comment by effigies** [comment]
Is this a thing that happens if no noise components are found? This may instead be a problem where the `ICA_AROMAOutputSpec.nonaggr_denoised_file` trait should not have an `exists=True`.

**Comment by oesteban** [comment]
That is a solid theory, I just opened an issue in nipype and will look into this ASAP.

**Comment by effigies** [comment]
Do we have a dataset where we can reliably reproduce this condition?

**Comment by kfinc** [comment]
Hi!
Here you can find data for one subject on which I've produced this error:
https://www.dropbox.com/s/789nm7yeu68c2u7/LB_BIDS_raw_test.zip?dl=0

Thanks,
Karolina

**Comment by jdkent** [comment]
Hi Karolina, 

Thanks!
You may want to deface the anatomical image with [pydeface](https://github.com/poldracklab/pydeface) or some similar tool unless sharing facial (identifiable) information about your participants is approved by your ethics board (speaking from personal experience).

**Comment by kfinc** [comment]
Thanks for advice, I'll do this definitely!

**Comment by jdkent** [comment]
I wasn't able to reproduce the error with the data given (e.g. finished successfully)

Here is the fmriprep-docker version I used
```
$ fmriprep-docker --version
fmriprep v1.1.1
```

Here is the call I used
```
fmriprep-docker \
    --fs-license-file ~/mnt/vosslabhpc/UniversalSoftware/freesurfer_license.txt \
    ~/LB_BIDS_raw_test/ \
    ~/LB_BIDS_raw_test/derivatives \
    -w ~/LB_BIDS_raw_test/derivatives/work \
    --longitudinal \
    --fs-no-reconall \
    --use-aroma \
    --n_cpus 14
```

And here is the contents of `classified_motion_ICs.txt`:
```
4,13,15,18,24,34,41,42,43,44,50,54,56,57
```


[here is the report](https://jdkent.github.io/cmapRepository/sub-01.html), nothing looks too out of place to me.

I'm re-running with freesurfer in case that makes the difference.

**Comment by jdkent** [comment]
I didn't reproduce the error running with freesurfer either.
@kfinc could you re-run the participant with an explicitly set working directory (e.g. `-w ~/LB_BIDS_raw_test/derivatives/work`), I don't think that should make a difference in your error output, but at least we will have all the intermediate data that came before the error.

**Comment by kfinc** [comment]
Thanks for help! After your feedback I upgraded ubuntu, reinstalled docker and fmriprep, and pipeline finally started to work with --use-aroma. I'm not sure what was the cause of error, but I suppose that maybe some issues with permissions to folders and/or low memory on my root directory.

**Comment by oesteban** [comment]
Maybe you unexpectedly updated ICA-AROMA. Glad you figured it out, and also thanks for sharing the solution with the community. Please reopen if the issue regresses.
