### ISSUE TITLE
Module t1_2_mni has no input called lesion_mask

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1111]
```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 510, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 202, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 410, in init_single_subject_wf
    num_t1w=len(subject_data['t1w']))
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/anatomical.py", line 320, in init_anat_preproc_wf
    (mni_tpms, outputnode, [('output_image', 'mni_tpms')]),
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 214, in connect
    '\n'.join(['Some connections were not found'] + infostr))
Exception: Some connections were not found
Module t1_2_mni has no input called lesion_mask
```

I guess we need to release a new niworkflows?

**Comment by oesteban** [comment]
I can see the pinning. Maybe my cached results are causing this.

**Comment by oesteban** [comment]
Okay. I'm embarrassed to even tell (using docker and `-v`, patching an old niworkflows in). Sorry for the noise
