### ISSUE TITLE
"Network is unreachable"

### ISSUE THREAD

**Issue by brainconnectome** [poldracklab/fmriprep#1164]
Hi,

When I ran a singularity image of fmriprep on a supercomputer (Argonne national lab-Theta), I got this error. 

My command:
`singularity run /lus/theta-fs0/projects/AD_Brain_Imaging/app/poldracklab_fmriprep_latest-2018-05-17-12b9eed9cd9e.img \
/lus/theta-fs0/projects/AD_Brain_Imaging/image03/bids/ \
/lus/theta-fs0/projects/AD_Brain_Imaging/fmriprep_out \
participant \
--participant-label sub-0001 \
--fs-license-file license.txt \
-w /tmp \
--ignore fieldmaps \
 --debug \
--nthreads 64 \
--omp-nthreads 64`

Errors I got:

> 
180607-20:21:56,729 sentry.errors ERROR:
	 Sentry responded with an error: <urlopen error [Errno 101] Network is unreachable> (url: https://sentry.io/api/1137693/store/)
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/miniconda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/miniconda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/miniconda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/miniconda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/miniconda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/miniconda/lib/python3.6/site-packages/raven/utils/http.py", line 31, in connect
    timeout=self.timeout,
  File "/usr/local/miniconda/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/miniconda/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/raven/transport/threaded.py", line 165, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/usr/local/miniconda/lib/python3.6/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/usr/local/miniconda/lib/python3.6/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/miniconda/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/miniconda/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/miniconda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/miniconda/lib/python3.6/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/miniconda/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
180607-20:21:56,730 sentry.errors.uncaught ERROR:
	 ['ValueError: not enough values to unpack (expected 2, got 1)', '  File "bin/fmriprep", line 11, in <module>', '  File "fmriprep/cli/run.py", line 322, in main', '  File "fmriprep/viz/reports.py", line 284, in generate_reports', '  File "fmriprep/viz/reports.py", line 284, in <listcomp>', '  File "fmriprep/viz/reports.py", line 274, in run_reports', '  File "fmriprep/viz/reports.py", line 177, in generate_report', '  File "jinja2/asyncsupport.py", line 76, in render', '  File "jinja2/environment.py", line 1008, in render', '  File "jinja2/environment.py", line 780, in handle_exception', '  File "jinja2/_compat.py", line 37, in reraise', '  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/report.tpl", line 134, in top-level template code']

**Comment by chrisfilo** [comment]
Could you try with `--notrack` option?

**Comment by brainconnectome** [comment]
it worked!
