### ISSUE TITLE
t1 processing (?) error

### ISSUE THREAD

**Issue by brainconnectome** [poldracklab/fmriprep#1165]
`singularity run /lus/theta-fs0/projects/AD_Brain_Imaging/app/poldracklab_fmriprep_latest-2018-05-17-12b9eed9cd9e.img \
/lus/theta-fs0/projects/AD_Brain_Imaging/anal/EMBARC/image03/bids/ \
/lus/theta-fs0/projects/AD_Brain_Imaging/anal/EMBARC/fmriprep_out \
participant \
--participant-label sub-UM0120UMMR1R1 \
--fs-license-file license.txt \
-w /tmp \
--ignore fieldmaps \
 --debug \
--nthreads 64 \
--omp-nthreads 64 \
--notrack`

ERROR:

> 180607-21:09:34,463 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_UM0120UMMR1R1_wf.func_preproc_RESTSTATE2_fMRI_20151120122457_901_wf.bold_confounds_wf.dvars".
180607-21:09:38,422 workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_UM0120UMMR1R1_wf.anat_preproc_wf.anat_derivatives_wf.t1_name
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.15', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 322, in main
    errno += generate_reports(subject_list, output_dir, work_dir, run_uuid)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 284, in generate_reports
    for subject_label in subject_list
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 284, in <listcomp>
    for subject_label in subject_list
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 274, in run_reports
    return report.generate_report()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 177, in generate_report
    report_render = report_tpl.render(sections=self.sections, errors=self.errors)
  File "/usr/local/miniconda/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/miniconda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/report.tpl", line 134, in top-level template code
    {% for name, spec in error.inputs %}
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by oesteban** [comment]
Hi @brainconnectome, sorry for getting back to this late.

Can you post the file structure under `/lus/theta-fs0/projects/AD_Brain_Imaging/anal/EMBARC/image03/bids/`?

It seems you have several T1w images but I'm not sure what is going on.

**Comment by oesteban** [comment]
Also: fmriprep version? Have you tried with the latest 1.1.3?
