### ISSUE TITLE
Could not create directory /work/fmriprep_wf

### ISSUE THREAD

**Issue by bababen** [poldracklab/fmriprep#1173]
I am trying to run fmriprep use singularity:

PYTHONPATH="" singularity run /lustre/haven/user/ballen50/poldracklab_fmriprep_latest-2018-05-17-57854ec819a5.img     /home/Nifti/ /home/fmri_prep_sub2_sdc_aroma_output     participant     --fs-license-file /home/license.txt --use-syn-sdc --use-aroma --output-space T1w template

I am getting the following error:

* Run identifier: 20180618-170607_5979d3a5-9b11-4039-bed3-4beb35f2c736.

180618-17:06:08,757 workflow IMPORTANT:
         Creating bold processing workflow for "/home/Nifti/sub-02/func/sub-02_task-rest_bold.nii" (0.14 GB / 165                                                    TRs). Memory resampled/largemem=0.58/0.81 GB.
180618-17:06:09,81 workflow IMPORTANT:
         Slice-timing correction will be included.
180618-17:06:09,223 workflow WARNING:
         SDC: no fieldmaps found or they were ignored. Using EXPERIMENTAL "fieldmap-less SyN" correction for datas                                                   et /home/Nifti/sub-02/func/sub-02_task-rest_bold.nii.
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/utils/filemanip.py", line 749, in make                                                   dirs
    os.makedirs(path)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/work/fmriprep_wf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.15', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 314, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 59                                                   4, in run
    self._write_report_info(self.base_dir, self.name, execgraph)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 61                                                   6, in _write_report_info
    makedirs(report_dir, exist_ok=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/utils/filemanip.py", line 753, in make                                                   dirs
    raise OSError('Could not create directory %s' % path)
OSError: Could not create directory /work/fmriprep_wf

**Comment by effigies** [comment]
If you're using Singularity, you should pass `-w <work_dir>` to some directory that you control.

**Comment by effigies** [comment]
Glad to hear it! Please let us know if you have any further issues.
