### ISSUE TITLE
3dTshift fails to run

### ISSUE THREAD

**Issue by RdoubleA** [poldracklab/fmriprep#1188]
Hello,

I run into this error when it tries to process my resting state BOLD:

> Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 314, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 162, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 224, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/afni/base.py", line 110, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 1044, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 981, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
3dTshift -ignore 2 -prefix sub-hcp_task-rest_bold_valid_tshift.nii.gz -tpattern @/root/src/fmriprep/work/fmriprep_wf/single_subject_hcp_wf/func_preproc_task_rest_wf/bold_stc_wf/create_custom_slice_timing_file/timings.1D -TR 0.72s /root/src/fmriprep/work/fmriprep_wf/single_subject_hcp_wf/func_preproc_task_rest_wf/bold_stc_wf/slice_timing_correction/sub-hcp_task-rest_bold_valid.nii.gz
Standard output:
Standard error:
++ 3dTshift: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
** AFNI converts NIFTI_datatype=512 (UINT16) in file /root/src/fmriprep/work/fmriprep_wf/single_subject_hcp_wf/func_preproc_task_rest_wf/bold_stc_wf/slice_timing_correction/sub-hcp_task-rest_bold_valid.nii.gz to FLOAT32
     Warnings of this type will be muted for this session.
     Set AFNI_NIFTI_TYPE_WARN to YES to see them all, NO to see none.
*+ WARNING:   If you are performing spatial transformations on an oblique dset,
  such as /root/src/fmriprep/work/fmriprep_wf/single_subject_hcp_wf/func_preproc_task_rest_wf/bold_stc_wf/slice_timing_correction/sub-hcp_task-rest_bold_valid.nii.gz,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running:
     3dWarp -deoblique
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:/root/src/fmriprep/work/fmriprep_wf/single_subject_hcp_wf/func_preproc_task_rest_wf/bold_stc_wf/slice_timing_correction/sub-hcp_task-rest_bold_valid.nii.gz is 23.120794 degrees from plumb.
Killed
Return code: 137

I've looked through similar issues and my SliceTiming is not larger than my TR, and it doesn't indicate any clear fatal errors. I'm not sure how to proceed from here, do you guys have any suggestions?

I'm trying to process data from the Human Connectome Project which is not very BIDS friendly so I manually created all the JSON files. I'm sure I covered every necessary field, but a mistake there is very possible.

**Comment by effigies** [comment]
The process is being killed, presumably by the OS, which makes me think that you're exceeding your memory constraints. How much memory are you allocating to Docker?

**Comment by RdoubleA** [comment]
So I increased the memory limit for Docker from 2 GB to 8 GB. Now I'm running into new errors:

> [Node] Error on "fmriprep_wf.single_subject_hcp_wf.func_preproc_task_rest_wf.bold_hmc_wf.mcflirt" (/root/src/fmriprep/work/fmriprep_wf/single_subject_hcp_wf/func_preproc_task_rest_wf/bold_hmc_wf/mcflirt)
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 314, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 162, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 224, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 1044, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 981, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
mcflirt -in /root/src/fmriprep/work/fmriprep_wf/single_subject_hcp_wf/func_preproc_task_rest_wf/bold_reference_wf/validate/sub-hcp_task-rest_bold_valid.nii.gz -out /root/src/fmriprep/work/fmriprep_wf/single_subject_hcp_wf/func_preproc_task_rest_wf/bold_hmc_wf/mcflirt/sub-hcp_task-rest_bold_valid_mcf.nii.gz -reffile /root/src/fmriprep/work/fmriprep_wf/single_subject_hcp_wf/func_preproc_task_rest_wf/bold_reference_wf/gen_ref/ref_image.nii.gz -mats -plots
Standard output:
Standard error:
Killed
Return code: 137

Is there a suggested memory limit to run fMRIprep?

**Comment by effigies** [comment]
We've generally suggested a minimum of 8GiB, but for larger datasets, it's sometimes going to have higher requirements. Also, it appears that your kernel probably has a strict over-commit policy, so our heuristics may not be well suited. You can try telling fmriprep to use a smaller amount of memory than you actually have available, so that our internal scheduling will not try to fill the available memory.

I haven't tried running on HCP (@oesteban I think at one point someone else tried this... do you remember?), but I think they're fairly large sessions. If 20GiB doesn't do the job, something else might be wrong, but up until that I would probably stick with "give it more memory" as a first pass at troubleshooting.

Also, the specific job that failed there shouldn't have consumed too many resources, so my guess is that it was an unlucky job that failed while other jobs were taking up the bulk of the memory. It may succeed if you re-run with the same working directory. If you pass `-w` flag to `fmriprep-docker`, you can have a persistent working directory across multiple executions, allowing you to re-use portions of the workflow that have already been run successfully.

**Comment by oesteban** [comment]
Hi @RdoubleA, did you finally overcome this problem?

If not, how can I help?
