### ISSUE TITLE
Error running pipeline: matvec: non-3D image input!

### ISSUE THREAD

**Issue by shirareznik** [poldracklab/fmriprep#1197]
Hi,

Reporting the error found in the following log:
https://drive.google.com/file/d/1jGspQinQv_wWNMJKbd_rhxxMQXlUfp7Z/view?usp=sharing

> THD_rota3D_matvec: non-3D image input!\n\n*** THD_rota3D_matvec: non-3D image input!\n\n*** THD_rota3D_matvec: non-3D image input!\n\n*** THD_rota3D_matvec: non-3D image input!\n\n*** mri_3dalign_setup: cannot use nD images!\x07\n** Can\'t initialize first pass alignment algorithm\nReturn code: 1\n', '  File "bin/fmriprep", line 11, in <module>', '  File "fmriprep/cli/run.py", line 314, in main', '  File "niworkflows/nipype/pipeline/engine/workflows.py", line 595, in run', '  File "niworkflows/nipype/pipeline/plugins/base.py", line 168, in run', '  File "niworkflows/nipype/pipeline/plugins/base.py", line 227, in _clean_queue']
RUNNING: docker run --rm -it -v D:\license.txt:/opt/freesurfer/license.txt:ro -v D:\bids\pilot_bat4:/data:ro -v D:\batpilot_fmriprep:/out poldracklab/fmriprep:1.0.12 /data /out participant --debug --write-graph --resource-monitor --fs-no-reconall
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues

**Comment by effigies** [comment]
Does your data pass the [BIDS validator](https://incf.github.io/bids-validator/)? Would it be possible to share `sub-r001/func/sub-r001_task-batns_run-1_bold.nii.gz`?

**Comment by shirareznik** [comment]
Thanks- already checking if this is because of a problematic nifti
conversion- will update soon.

**Comment by shirareznik** [comment]
Hi,
I haven't executed the BIDS validator yet, but the error is now different (found some problematic data and removed it), but please review the current error (I'll install the validator, on the meantime):

> 	 [Node] Running "skullstrip_first_dilate" ("niworkflows.nipype.interfaces.fsl.maths.DilateImage"), a CommandLine Interface with command:
fslmaths -dt char /root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_first_pass/ref_image_corrected_brain_mask.nii.gz -kernel sphere 6.0000 -dilF /root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_first_dilate/ref_image_corrected_brain_mask_dil.nii.gz
180710-14:00:18,819 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_p002_wf.func_preproc_task_restnostress_run_1_wf.bold_hmc_wf.fsl2itk".
180710-14:00:18,852 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.skullstrip_first_dilate".
180710-14:00:19,538 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.skullstrip_first_mask" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_first_mask".
180710-14:00:19,541 workflow INFO:
	 [Node] Running "skullstrip_first_mask" ("niworkflows.nipype.interfaces.fsl.maths.ApplyMask"), a CommandLine Interface with command:
fslmaths /root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_first_pass/ref_image_corrected_brain.nii.gz -mas /root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_first_dilate/ref_image_corrected_brain_mask_dil.nii.gz /root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_first_mask/ref_image_corrected_brain_masked.nii.gz
180710-14:00:19,629 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.skullstrip_first_mask".
180710-14:00:20,403 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_p002_wf.func_preproc_task_restnostress_run_2_wf.bold_hmc_wf.fsl2itk" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_restnostress_run_2_wf/bold_hmc_wf/fsl2itk".
180710-14:00:20,408 workflow INFO:
	 [Node] Running "fsl2itk" ("fmriprep.interfaces.itk.MCFLIRT2ITK")
180710-14:00:21,558 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.unifize" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/unifize".
180710-14:00:21,562 workflow INFO:
	 [Node] Running "unifize" ("niworkflows.nipype.interfaces.afni.utils.Unifize"), a CommandLine Interface with command:
3dUnifize -clfrac 0.2 -rbt 18.3 65.0 90.0 -prefix uni.nii.gz -T2 -input /root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/unifize/ref_image_corrected_brain_masked.nii.gz
180710-14:00:23,941 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.unifize".
180710-14:00:26,206 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.fixhdr_unifize" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/fixhdr_unifize".
180710-14:00:26,208 workflow INFO:
	 [Node] Running "fixhdr_unifize" ("niworkflows.interfaces.utils.CopyXForm")
180710-14:00:26,260 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.fixhdr_unifize".
180710-14:00:27,200 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_p002_wf.func_preproc_task_restnostress_run_2_wf.bold_hmc_wf.fsl2itk".
180710-14:00:27,563 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.skullstrip_second_pass" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_second_pass".
180710-14:00:27,566 workflow INFO:
	 [Node] Running "skullstrip_second_pass" ("niworkflows.nipype.interfaces.afni.preprocess.Automask"), a CommandLine Interface with command:
3dAutomask -apply_prefix uni_xform_masked.nii.gz -dilate 1 -prefix uni_xform_mask.nii.gz /root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_second_pass/uni_xform.nii.gz
180710-14:00:27,730 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.skullstrip_second_pass".
180710-14:00:29,978 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_p002_wf.func_preproc_task_restnostress_run_1_wf.bold_bold_trans_wf.bold_transform" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_restnostress_run_1_wf/bold_bold_trans_wf/bold_transform".
180710-14:00:29,983 workflow INFO:
	 [Node] Running "bold_transform" ("fmriprep.interfaces.itk.MultiApplyTransforms")
180710-14:00:30,117 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.fixhdr_skullstrip2" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/fixhdr_skullstrip2".
180710-14:00:30,119 workflow INFO:
	 [Node] Running "fixhdr_skullstrip2" ("niworkflows.interfaces.utils.CopyXForm")
180710-14:00:30,157 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.fixhdr_skullstrip2".
180710-14:00:31,493 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.combine_masks" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/combine_masks".
180710-14:00:31,495 workflow INFO:
	 [Node] Running "combine_masks" ("niworkflows.nipype.interfaces.fsl.maths.BinaryMaths"), a CommandLine Interface with command:
fslmaths /root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_first_pass/ref_image_corrected_brain_mask.nii.gz -mul /root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/fixhdr_skullstrip2/uni_xform_mask_xform.nii.gz /root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/combine_masks/ref_image_corrected_brain_mask_maths.nii.gz
180710-14:00:31,546 workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.combine_masks".
180710-14:00:33,455 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_confounds_wf.dvars" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_confounds_wf/dvars".
180710-14:00:33,458 workflow INFO:
	 [Node] Running "dvars" ("niworkflows.nipype.algorithms.confounds.ComputeDVARS")
180710-14:00:33,556 workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_p002_wf.func_preproc_task_nd_wf.bold_confounds_wf.dvars" (/root/src/fmriprep/work/fmriprep_wf/single_subject_p002_wf/func_preproc_task_nd_wf/bold_confounds_wf/dvars)
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.12', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 314, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 168, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 520, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 145, in _run_interface
    intensity_normalization=self.inputs.intensity_normalization)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 901, in compute_dvars
    np.float32), 1)[:, 0]
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 91, in apply_along_axis
    res = func1d(arr[tuple(i.tolist())], *args, **kwargs)
IndexError: index 0 is out of bounds for axis 0 with size 0

Thanks!
