### ISSUE TITLE
Broken Processing Pool - Python

### ISSUE THREAD

**Issue by aureliooo** [poldracklab/fmriprep#1207]
Hello! I keep running into the same broken process pool error when using fmriprep.

Though the script still runs when it reaches this step, I have left it running for two extra days to see if fmriprep can finish preprocessing, but it does not move from this point.

Any recommendation on what to do?

```
"[Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
exception calling callback for <Future at 0x7f5a65035400 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
exception calling callback for <Future at 0x7f5a5fea1cf8 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending."
```

**Comment by chrisfilo** [comment]
Maybe it was killed because it run out of memory? How much RAM did you expose to Docker in Docker Settings?

**Comment by oesteban** [comment]
Did increasing the memory limits solve your issue @aureliooo ?

**Comment by aureliooo** [comment]
Not entirely. By increasing the memory available to Docker in the preferences to 8 (the highest it can go through that interface), fmriprep did run much longer. But ultimately it ended in a single error. Anyway I can increase the RAM beyond 8 GiB?

Sorry, I'm very new to Docker in general as well

**Comment by effigies** [comment]
8 GiB of RAM is really the lowest we recommend, and if you have a large dataset, you could expect that to be insufficient. I don't think we have a "minimum guaranteed run" number, but if you can get a machine with >16GiB of RAM, you should run into problems only with very large datasets, and I don't think I've heard of a problem for people able to throw 24 GiB at it.

**Comment by oesteban** [comment]
@aureliooo is this issue fixed? can I close it?

**Comment by aureliooo** [comment]
@oesteban Yes, I had to use a machine w more RAM in the end, but this is all good now. Thank you!
