### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by nehaes** [poldracklab/fmriprep#1208]
Attempting to run fMRIprep and ran into this error:

Sentry responded with an error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)> (url: https://sentry.io/api/1137693/store/)
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/miniconda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/miniconda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/miniconda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/miniconda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/miniconda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/miniconda/lib/python3.6/site-packages/raven/utils/http.py", line 38, in connect
    sock, ca_certs=ca_certs, cert_reqs=ssl.CERT_REQUIRED)
  File "/usr/local/miniconda/lib/python3.6/ssl.py", line 1149, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/miniconda/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/miniconda/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/miniconda/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/raven/transport/threaded.py", line 165, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/usr/local/miniconda/lib/python3.6/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/usr/local/miniconda/lib/python3.6/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/miniconda/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/miniconda/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/miniconda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/miniconda/lib/python3.6/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/miniconda/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>
['RuntimeError: Traceback (most recent call last):\n  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node\n    result[\'result\'] = node.run(updatehash=updatehash)\n  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run\n    result = self._run_interface(execute=True)\n  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface\n    return self._run_command(execute)\n  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command\n    result = self._interface.run(cwd=outdir)\n  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run\n    runtime = self._run_interface(runtime)\n  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface\n    out = function_handle(**args)\n  File "<string>", line 3, in create_custom_slice_timing_file_func\n  File "<string>", line 3, in <listcomp>\nTypeError: must be real number, not str\n', '  File "bin/fmriprep", line 11, in <module>', '  File "fmriprep/cli/run.py", line 316, in main', '  File "nipype/pipeline/engine/workflows.py", line 595, in run', '  File "nipype/pipeline/plugins/base.py", line 162, in run', '  File "nipype/pipeline/plugins/base.py", line 224, in _clean_queue']
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues
elodie-mac:fmriprep studentaccount$ python3.6 fmriprep_docker.py 
Warning: <8GB of RAM is available within your Docker environment.
Some parts of fMRIPrep may fail to complete.
Continue anyway? [y/N]y
RUNNING: docker run --rm -it -v /Applications/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /Users/studentaccount/Documents/fmriprep:/data:ro -v /Users/studentaccount/Documents/fmriprep:/out poldracklab/fmriprep:1.1.2 /data /out participant
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 385, in build_workflow
    bids_dir, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 89, in collect_participants
    'may need to adjust your "File sharing" preferences.', bids_dir)
fmriprep.utils.bids.BIDSError: 
---------- BIDS root folder: "/data" ----------
           Could not find participants. Please make sure the BIDS data structure is present and correct. Datasets can be validated online using the BIDS Validator (http://incf.github.io/bids-validator/).
If you are using Docker for Mac or Docker for Windows, you may need to adjust your "File sharing" preferences.
-----------------------------------------------

Any ideas on what to do?

**Comment by effigies** [comment]
There are two issues here. The first is this:

> Could not find participants. Please make sure the BIDS data structure is present and correct. Datasets can be validated online using the BIDS Validator (http://incf.github.io/bids-validator/).
If you are using Docker for Mac or Docker for Windows, you may need to adjust your "File sharing" preferences.

If you need help with these instructions, please let us know.

The second issue is one that we should catch and dispose of. It's a failure (probably one-off) of the system we use to get usage statistics. It should have no effect on the actual running of fMRIPrep, and is in any event not the user's concern. We should simply warn that we were unable to submit a report.

**Comment by chrisfilo** [comment]
New SDK should be more robust to such issues.
