### ISSUE TITLE
All workflows require T1w images. Exception

### ISSUE THREAD

**Issue by relyativist** [poldracklab/fmriprep#1211]
Running fMRIPREP version 1.1.2:
      * BIDS dataset path: /data.
      * Participant list: ['001'].
      * Run identifier: 20180719-110412_ef367dd7-6434-45c7-a9b6-aafb1c4dbb23.
    
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 512, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 202, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 369, in init_single_subject_wf
    "All workflows require T1w images.".format(subject_id))
Exception: No T1w images found for participant 001. All workflows require T1w images.
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues

i have a data set with only func data: here is a .tsv: 
data  cd:
func  sub-001_scans.tsv

example_dcm_file | series_id | dcm_dir_name
-- | -- | --
IM-0005-0001.dcm | 1-RESTING FOR {....}/1 | Localizers_1
IM-0001-0001.dcm | 3-RESTING FOR {....}/3 | FSPGR_BRAVO_10mm_AX_3
IM-0002-0001.dcm | 4-RESTING FOR {....}/5 | fMRI_WG_WORDS_4
IM-0003-0001.dcm | 5-GRANT ARTEM/7 | fMRI_Wernicke_5
IM-0004-0001.dcm | 6-RESTING FOR {....}/6 | resting_state_6

how to disable T1w data?

**Comment by oesteban** [comment]
At the moment, fmriprep won't work without T1w data. We are working changing this, though (#808)

**Comment by effigies** [comment]
Closing as duplicate.
