### ISSUE TITLE
TraitError: The trait 'out_files' of a SplitOutputSpec instance is an existing file name

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1217]
I've just received via email the following error

```
180723-13:45:02,726 workflow ERROR:
	 Node bold_split failed to run on host hpc205.
180723-13:45:02,734 workflow ERROR:
	 Saving crash info to [redacted path 1]/output/fmriprep/sub-01/log/20180723-131939_b51df0ea-fdb1-4218-9555-cd6e12a8271d/crash-20180723-134502-kehg3633-bold_split-7619f81e-d7f6-472f-9a4c-8937d6c6f643.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 662, in _run_command
    _save_resultfile(result, outdir, self.name)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 244, in save_resultfile
    result.outputs.set(**modify_paths(outputs, relative=True, basedir=cwd))
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/util/deprecated.py", line 32, in wrapper
    return fn(*args, **kw)
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/has_traits.py", line 1551, in set
    trait_change_notify=trait_change_notify, **traits)
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/has_traits.py", line 1543, in trait_set
    setattr( self, name, value )
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 341, in validate
    value = super(MultiObject, self).validate(object, name, newvalue)
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_types.py", line 2336, in validate
    return TraitListObject( self, object, name, value )
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_handlers.py", line 2313, in __init__
    raise excp
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_handlers.py", line 2305, in __init__
    value = [ validate( object, name, val ) for val in value ]
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_handlers.py", line 2305, in <listcomp>
    value = [ validate( object, name, val ) for val in value ]
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 112, in validate
    self.info_text, value))
traits.trait_errors.TraitError: The trait 'out_files' of a SplitOutputSpec instance is an existing file name, but the path  '[redacted path 2]/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_ambigfig_run_2_wf/bold_split/vol0000.nii.gz' does not exist.
```

This error is a potential duplicate of #936, and may also be related to nipy/nipype#2380.

First of all, I would really appreciate that you provided the contents of the file at the beginning, where it says "Saving crash info to...", so this file -> `[redacted path 1]/output/fmriprep/sub-01/log/20180723-131939_b51df0ea-fdb1-4218-9555-cd6e12a8271d/crash-20180723-134502-kehg3633-bold_split-7619f81e-d7f6-472f-9a4c-8937d6c6f643.txt`

I can see that the output path ``[redacted path 1]/output/``` is different, but similar to the working directory (``[redacted path 2]/work``). Please check whether either ``[redacted path 1]`` or ``[redacted path 2]`` are real paths (i.e. they are not just links).

Finally, what do you see if you run:
```
ls [redacted path 2]/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_ambigfig_run_2_wf/bold_split/
```

(please remember to replace the `[redacted path 2]` bit with the path you have in your logs.

**Comment by oesteban** [comment]
As per https://github.com/nipy/nipype/issues/2380#issuecomment-407453500, we'll need to wait for the next release of nipype, with (nipy/nipype#2639) that addresses this.

**Comment by oesteban** [comment]
Apparently, the person experiencing this problem managed to fix the problem.
