### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'trait_get'

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/fmriprep#1266]
```
login1.ls5(1061)$ cat sub-002/log/20180829-223857_529d2cb5-3be1-43c6-a289-ab42894c73ff/crash-20180829-223951-poldrack-summary-edc98c1e-7073-4c20-a381-0b2849ac91b5.txt
Node: fmriprep_wf.single_subject_002_wf.summary
Working directory: /scratch/01329/poldrack/NARPS/workdir/fmriprep/fmriprep_wf/single_subject_002_wf/summary

Node inputs:

bold = ['/scratch/01329/poldrack/NARPS/ds001205/sub-002/func/sub-002_task-MGT_run-01_bold.nii.gz', '/scratch/01329/poldrack/NARPS/ds001205/sub-002/func/sub-002_task-MGT_run-02_bold.nii.gz', '/scratch/01329/poldrack/NARPS/ds001205/sub-002/func/sub-002_task-MGT_run-03_bold.nii.gz', '/scratch/01329/poldrack/NARPS/ds001205/sub-002/func/sub-002_task-MGT_run-04_bold.nii.gz']
output_spaces = ['template', 'fsaverage5']
subject_id = sub-002
subjects_dir = <undefined>
t1w = ['/scratch/01329/poldrack/NARPS/ds001205/sub-002/anat/sub-002_T1w.nii.gz']
t2w = <undefined>
template = MNI152NLin2009cAsym

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 535, in _get_inputs
    output_value = results.outputs.trait_get()[output_name]
AttributeError: 'NoneType' object has no attribute 'trait_get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 308, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 417, in run
    cached, updated = self.is_cached()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 303, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 497, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 537, in _get_inputs
    output_value = results.outputs.dictcopy()[output_name]
AttributeError: 'NoneType' object has no attribute 'dictcopy'
```

**Comment by oesteban** [comment]
Could not replicate. Will reopen if suddenly shows up in Sentry or Neurostars.
