### ISSUE TITLE
OSError: [Errno 5] Input/output error   ?

### ISSUE THREAD

**Issue by xxunming** [poldracklab/fmriprep#1292]
Hello,
I'm running fmriprep 1.1.6 on a workstation with 64G RAM using docker for windows and not mounting a working directory. I repeatedly encountered the error below.

>......[Node] Running "bold_to_mni_transform" ("fmriprep.interfaces.itk.MultiApplyTransforms")
180920-04:15:08,405 nipype.workflow INFO:
         [Node] Finished "fmriprep_wf.single_subject_02_wf.func_preproc_task_TemporalOrder_run_4_wf.bold_mni_trans_wf.bold_to_mni_transform".
180920-04:15:09,432 nipype.workflow INFO:
         [Node] Setting-up "fmriprep_wf.single_subject_02_wf.func_preproc_task_TemporalOrder_run_4_wf.bold_mni_trans_wf.merge" in "/tmp/work/fmriprep_wf/single_subject_02_wf/func_preproc_task_TemporalOrder_run_4_wf/bold_mni_trans_wf/merge".
180920-04:15:09,463 nipype.workflow INFO:
         [Node] Running "merge" ("fmriprep.interfaces.nilearn.Merge")
180920-04:17:18,976 nipype.workflow INFO:
         [Node] Finished "fmriprep_wf.single_subject_02_wf.func_preproc_task_TemporalOrder_run_4_wf.bold_mni_trans_wf.merge".
180920-04:17:33,793 nipype.workflow WARNING:
         [Node] Error on "fmriprep_wf.single_subject_02_wf.func_preproc_task_TemporalOrder_run_4_wf.func_derivatives_wf.ds_bold_mni" (/tmp/work/fmriprep_wf/single_subject_02_wf/func_preproc_task_TemporalOrder_run_4_wf/func_derivatives_wf/ds_bold_mni)
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 308, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/bids.py", line 258, in _run_interface
    self._results['compression'].append(_copy_any(fname, out_file))
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/bids.py", line 429, in _copy_any
    copyfile(src, dst, copy=True, use_hardlink=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/utils/filemanip.py", line 472, in copyfile
    shutil.copyfile(originalfile, newfile)
  File "/usr/local/miniconda/lib/python3.6/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
OSError: [Errno 5] Input/output error

>During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 344, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 184, in run
    self._send_procs_to_workers(updatehash=updatehash, graph=graph)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    'traceback': traceback
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 224, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 308, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/bids.py", line 258, in _run_interface
    self._results['compression'].append(_copy_any(fname, out_file))
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/bids.py", line 429, in _copy_any
    copyfile(src, dst, copy=True, use_hardlink=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/utils/filemanip.py", line 472, in copyfile
    shutil.copyfile(originalfile, newfile)
  File "/usr/local/miniconda/lib/python3.6/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
OSError: [Errno 5] Input/output error

> Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds

The input data of each participant has 4 runs with 574MB each, uncompressed. 

Thanks!

**Comment by xxunming** [comment]
seems that the error will not occur if I only run one run of data at a time, but failed with more than one run

**Comment by effigies** [comment]
I'm going to guess it's a filesystem error, probably related to running on Windows. A number of users have found Windows-related complications with Docker.

**Comment by xxunming** [comment]
No errors if running in Linux. Thank you.
