### ISSUE TITLE
Phase difference field maps fail if BOLD is missing PhaseEncodingDirection metadata

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1304]
A better approach would be to check for PE direction when needed, and, if missing, print a warning and disable fieldmaps.

**Comment by effigies** [comment]
Running on DS000117, with [this sidecar](https://openneuro.org/datasets/ds000117/versions/1.0.1/file-display/task-facerecognition_bold.json):

```JSON
{
    "RepetitionTime": 2, 
    "TaskName": "facerecognition",
    "EchoTime": 0.03,
    "FlipAngle": 78,
    "PulseSequenceType": "EPI",
    "Manufacturer": "Siemens",
    "ManufacturersModelName": "TIM TRIO",
    "MagneticFieldStrength": 3,
    "NumberOfVolumesDiscardedByScanner": 3,
    "NumberOfVolumesDiscardedByuser": 2
}
```

Traceback:

```
Traceback (most recent call last):                                                                                                      
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>                                                                        
    sys.exit(main())                                                                                                                    
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 343, in main
    fmriprep_wf.run(**plugin_settings)                                                                                                  
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 585, in run                         
    execgraph = generate_expanded_graph(deepcopy(flatgraph))                                                                            
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 995, in generate_expanded_graph         
    graph_in = _remove_nonjoin_identity_nodes(graph_in, keep_iterables=True)                                                            
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 880, in _remove_nonjoin_identity_nodes  
    _remove_identity_node(graph, node)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 905, in _remove_identity_node           
    portinputs)                                                                                                                         
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 982, in _propagate_internal_output      
    value = evaluate_connect_function(src[1], src[2], value)                                                                            
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 736, in evaluate_connect_function       
    output_value = func(first_arg, *list(args))                                                                                         
  File "<string>", line 2, in _get_pedir_fugue                                                                                          
KeyError: 'PhaseEncodingDirection'
```
