### ISSUE TITLE
[BUG] Installation issues & RTDs broken for that reason

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#133]
```python setup.py install``` does not work.

The problem is related to the installation of niworkflows, which requires nipype. However, since we are using here the latest master and there the latest release, installation of niworkflows breaks (see at the bottom). Could this be related to nipype installation @satra, @chrisfilo ? - If you ```pip install niworkflows``` or ```python setup.py install``` it, niworkflows installs correctly. Then, it also works if you try to install fmriprep with niworkflows installed, either way (pip, setuptools).

I think this is a general problem with setuptools. And, this is probably duplicated from #88, because I have the impression that ```pip install -e``` uses setuptools to do ```python setup.py develop``` on the dependencies. @shoshber, please confirm if this is the same issue trying to replicate your problem and comparing the tracebacks.

Apparently, the good practice would be using the requirements.txt and ```pip install``` for development and the install_requires and ```python setup.py install``` for production:

https://caremad.io/2013/07/setup-vs-requirement/
https://www.reddit.com/r/Python/comments/3uzl2a/setuppy_requirementstxt_or_a_combination/

RTDs builds fail because of this problem.

```
Searching for niworkflows
Reading https://pypi.python.org/simple/niworkflows/
Downloading https://pypi.python.org/packages/f9/f3/b438f0dd85276b294a986b0c71d374e65d30da6921334a106763560184c4/niworkflows-0.0.2.tar.gz#md5=8c725a63cb444d6ea734278caaf0dccf
Best match: niworkflows 0.0.2
Processing niworkflows-0.0.2.tar.gz
Writing /var/folders/l9/0lkn3g4s27bgkk75n6jj778r0000gp/T/easy_install-aieYSi/niworkflows-0.0.2/setup.cfg
Running niworkflows-0.0.2/setup.py -q bdist_egg --dist-dir /var/folders/l9/0lkn3g4s27bgkk75n6jj778r0000gp/T/easy_install-aieYSi/niworkflows-0.0.2/egg-dist-tmp-zo9poE
Traceback (most recent call last):
  File "setup.py", line 104, in <module>
    main()
  File "setup.py", line 95, in main
    'Programming Language :: Python :: 3.5',
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 409, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 645, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 696, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 741, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1098, in best_match
    return self.obtain(req, installer)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1110, in obtain
    return installer(requirement)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 664, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 694, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 875, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1100, in run_setup
    run_setup(setup_script, args)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/sandbox.py", line 249, in run_setup
    raise
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/sandbox.py", line 197, in setup_context
    yield
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/sandbox.py", line 168, in save_modules
    saved_exc.resume()
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/sandbox.py", line 143, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/sandbox.py", line 197, in setup_context
    yield
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/sandbox.py", line 246, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/sandbox.py", line 276, in run
    return func()
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/sandbox.py", line 245, in runner
    _execfile(setup_script, ns)
  File "/Users/oesteban/anaconda2/envs/testenv/lib/python2.7/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/folders/l9/0lkn3g4s27bgkk75n6jj778r0000gp/T/easy_install-aieYSi/niworkflows-0.0.2/setup.py", line 11, in <module>
    from mriqc import (__version__, __description__, __license__,
  File "/var/folders/l9/0lkn3g4s27bgkk75n6jj778r0000gp/T/easy_install-aieYSi/niworkflows-0.0.2/niworkflows/__init__.py", line 14, in <module>
  File "/var/folders/l9/0lkn3g4s27bgkk75n6jj778r0000gp/T/easy_install-aieYSi/niworkflows-0.0.2/niworkflows/anat/__init__.py", line 7, in <module>
  File "/var/folders/l9/0lkn3g4s27bgkk75n6jj778r0000gp/T/easy_install-aieYSi/niworkflows-0.0.2/niworkflows/anat/skullstrip.py", line 6, in <module>
ImportError: No module named nipype.pipeline
```

**Comment by oesteban** [comment]
A workaround for RTD would be using ```pip install -r requirements.txt``` before installing fmriprep

**Comment by oesteban** [comment]
RTD is working! http://fmriprep.readthedocs.io/en/latest/
