### ISSUE TITLE
parts of skull missing from T1w image during acquisition

### ISSUE THREAD

**Issue by bababen** [poldracklab/fmriprep#1341]
I had a subject with a large head and the T1w image includes the brain but not all of the skull.  I tried running the subject through fmriprep as usual with the following command:

docker run --rm -it -v /home/ben/license.txt:/opt/freesurfer/license.txt:ro -v /mnt/barracuda/utmc_pilot2_processed:/data:ro -v /mnt/barracuda/utmc_pilot2_processed/fmriprep_output:/out poldracklab/fmriprep:1.1.0 /data /out participant --ignore slicetiming --use-syn-sdc --use-aroma --output-space T1w template fsaverage fsnative --participant_label 203

Here is the error that pops up before it stops:

[Node] Error on "fmriprep_wf.single_subject_203_wf.summary" (/root/src/fmriprep/work/fmriprep_wf/single_subject_203_wf/summary)

My best guess it is having trouble with the T1w image (see below).  But I'm not sure how to salvage this subject.

![screenshot](https://user-images.githubusercontent.com/21152566/47369647-28183d00-d6b2-11e8-92c2-66e4880ec496.png)

I'm not sure how best to handle

**Comment by bababen** [comment]
I got an error with --n-cpus 1

fmriprep: error: unrecognized arguments: --n-cpus 1

so I used --omp-nthreads 1 instead.  Let me know if this is what you need!


RUNNING: docker run --rm -it -v /home/ben/license.txt:/opt/freesurfer/license.txt:ro -v /mnt/barracuda/utmc_pilot2_processed:/data:ro -v /mnt/barracuda/utmc_pilot2_processed/fmriprep_output:/out poldracklab/fmriprep:1.1.0 /data /out participant --omp-nthreads 1 --ignore slicetiming --use-syn-sdc --use-aroma --output-space T1w template fsaverage fsnative --participant_label 203
181023-15:32:13,906 workflow IMPORTANT:

    Running fMRIPREP version 1.1.0:
      * BIDS dataset path: /data.
      * Participant list: ['203'].
      * Run identifier: 20181023-153213_997cac23-9339-4bd9-8941-83e1aee70a0b.

181023-15:32:15,866 workflow IMPORTANT:
         Creating bold processing workflow for "/data/sub-203/func/sub-203__task-rest_bold.nii.gz" (0.09 GB / 165 TRs). Memory resampled/largemem=0.37/0.52 GB.
181023-15:32:16,430 workflow WARNING:
         SDC: no fieldmaps found or they were ignored. Using EXPERIMENTAL "fieldmap-less SyN" correction for dataset /data/sub-203/func/sub-203__task-rest_bold.nii.gz.
181023-15:32:17,390 workflow IMPORTANT:
         Creating BOLD surface-sampling workflow.
181023-15:32:36,804 workflow INFO:
         [Node] Setting-up "fmriprep_wf.single_subject_203_wf.func_preproc__task_rest_wf.bold_reference_wf.validate" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_203_wf/func_preproc__task_rest_wf/bold_reference_wf/validate".
181023-15:32:36,809 workflow INFO:
         [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
181023-15:32:36,818 workflow INFO:
         [Node] Finished "fmriprep_wf.single_subject_203_wf.func_preproc__task_rest_wf.bold_reference_wf.validate".
181023-15:32:36,850 workflow INFO:
         [Node] Setting-up "fmriprep_wf.single_subject_203_wf.bidssrc" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_203_wf/bidssrc".
181023-15:32:36,853 workflow INFO:
         [Node] Running "bidssrc" ("fmriprep.interfaces.bids.BIDSDataGrabber")
181023-15:32:36,855 interface WARNING:
         No 'flair' images found for sub-<undefined>
181023-15:32:36,855 interface WARNING:
         No 'fmap' images found for sub-<undefined>
181023-15:32:36,855 interface WARNING:
         No 'sbref' images found for sub-<undefined>
181023-15:32:36,856 interface WARNING:
         No 'roi' images found for sub-<undefined>
181023-15:32:36,862 workflow INFO:
         [Node] Finished "fmriprep_wf.single_subject_203_wf.bidssrc".
181023-15:32:39,3 workflow INFO:
         [Node] Setting-up "fmriprep_wf.single_subject_203_wf.func_preproc__task_rest_wf.bold_split" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_203_wf/func_preproc__task_rest_wf/bold_split".
181023-15:32:39,8 workflow INFO:
         [Node] Running "bold_split" ("nipype.interfaces.fsl.utils.Split"), a CommandLine Interface with command:
fslsplit /data/sub-203/func/sub-203__task-rest_bold.nii.gz -t
181023-15:32:40,644 workflow INFO:
         [Node] Setting-up "fmriprep_wf.single_subject_203_wf.func_preproc__task_rest_wf.bold_reference_wf.gen_ref" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_203_wf/func_preproc__task_rest_wf/bold_reference_wf/gen_ref".
181023-15:32:40,647 workflow INFO:
         [Node] Running "gen_ref" ("niworkflows.interfaces.registration.EstimateReferenceImage")
181023-15:32:40,740 workflow WARNING:
         [Node] Error on "fmriprep_wf.single_subject_203_wf.summary" (/root/src/fmriprep/work/fmriprep_wf/single_subject_203_wf/summary)
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 339, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 96, in _run_interface
    return super(SubjectSummary, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 63, in _run_interface
    segment = self._generate_segment()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 123, in _generate_segment
    for series in bold_series)
  File "/usr/local/miniconda/lib/python3.6/collections/__init__.py", line 535, in __init__
    self.update(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.6/collections/__init__.py", line 622, in update
    _count_elements(self, iterable)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 123, in <genexpr>
    for series in bold_series)
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.1.0', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 314, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 184, in run
    self._send_procs_to_workers(updatehash=updatehash, graph=graph)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 347, in _send_procs_to_workers
    'traceback': traceback
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 224, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 339, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 96, in _run_interface
    return super(SubjectSummary, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 63, in _run_interface
    segment = self._generate_segment()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 123, in _generate_segment
    for series in bold_series)
  File "/usr/local/miniconda/lib/python3.6/collections/__init__.py", line 535, in __init__
    self.update(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.6/collections/__init__.py", line 622, in update
    _count_elements(self, iterable)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 123, in <genexpr>
    for series in bold_series)
TypeError: 'NoneType' object is not subscriptable

Sentry is attempting to send 1 pending error messages

**Comment by effigies** [comment]
It looks like you don't have any BOLD images? If this is intentional, use `--anat-only`. If not, has your dataset passed the [bids validator](https://bids-standard.github.io/bids-validator/)?

**Comment by bababen** [comment]
Ah, I had a double underscore in the filename for the BOLD images.  It is running now.  I am still concerned the T1w image quality might cause some trouble with the recon-all, but we'll see I suppose.

Sorry for the simple error but thanks for the help!
