### ISSUE TITLE
`bold_mni_ref` connection failing when specifying --output-space T1w

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1348]
CLI:

```
RUNNING: docker run --rm -it \
    -v /data/cjmarkie/Projects/crn/fmriprep/fmriprep:/usr/local/miniconda/lib/python3.6/site-packages/fmriprep:ro \
    -v /data/cjmarkie/Projects/crn/niworkflows/niworkflows:/usr/local/miniconda/lib/python3.6/site-packages/niworkflows:ro \
    -v /opt/freesurfer/license.txt:/opt/freesurfer/license.txt:ro \
    -v /data/bids/ds000114:/data:ro \
    -v /data/out/ds000114/derivatives:/out \
    -v /data/scratch/ds000114:/scratch \
    poldracklab/fmriprep:1.1.8 /data /out participant \
    --output-space T1w --participant-label 07 -t fingerfootlips --notrack -w /scratch
```

Using poldracklab/niworkflows/master and #1343, and a fresh scratch directory.

```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 343, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 585, in run
    execgraph = generate_expanded_graph(deepcopy(flatgraph))
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 995, in generate_expanded_graph
    graph_in = _remove_nonjoin_identity_nodes(graph_in, keep_iterables=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 880, in _remove_nonjoin_identity_nodes
    _remove_identity_node(graph, node)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 905, in _remove_identity_node
    portinputs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 980, in _propagate_internal_output
    value = getattr(node.inputs, field)
AttributeError: 'DynamicTraitedSpec' object has no attribute 'bold_mni_ref'
```

Haven't tracked down where this is, yet. Just running with MNI.

**Comment by bbfrederick** [comment]
I just hit this same error with 1.2.1.  Did you find anything?

**Comment by effigies** [comment]
Haven't really looked at it yet. I resolved it in the short term by targeting the template (`--output-space T1w template`).

**Comment by billbrod** [comment]
Has anyone looked into this? We're still running into this issue using version 1.2.6

**Comment by effigies** [comment]
Not yet, sorry. I'll try to have a look today, if I get a minute. If you'd like to have a look, we'll be looking for a `'bold_mni_ref'` connection that is created even when `'template'` is not a specified output space.

The short-term fix remains to include `template` in your `--output-space` list.

**Comment by billbrod** [comment]
Okay, thanks! From poking around briefly, I'm not seeing an obvious place where a connection is created with `'bold_mni_ref'` when `'template'` is not the output space.
