### ISSUE TITLE
Broken Process Pool - maybe not RAM related

### ISSUE THREAD

**Issue by BSegula** [poldracklab/fmriprep#1448]
I keep running into the same problem trying to run my analysis in fmriprep.

This is the command I'm running in the Mac terminal:
`docker run -m="11.5g" --memory-swap="40g"  -ti --rm -v /Users/Blake/Documents/angular/Nifti:/data:ro -v /Users/Blake/Documents/angular:/out -v /Users/Blake/licenses/freesurfer/license.txt:/opt/freesurfer/license.txt poldracklab/fmriprep:latest /data /out/out participant --ignore fieldmaps`

And I keep getting this same error:
> exception calling callback for <Future at 0x7f9f2a882240 state=finished raised BrokenProcessPool>
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
>     callback(self)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
>     result = args.result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
>     return self.__get_result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
> exception calling callback for <Future at 0x7f9f2a805e80 state=finished raised BrokenProcessPool>
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
>     callback(self)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
>     result = args.result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
>     return self.__get_result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
> exception calling callback for <Future at 0x7f9f2a7c3438 state=finished raised BrokenProcessPool>
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
>     callback(self)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
>     result = args.result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
>     return self.__get_result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
> exception calling callback for <Future at 0x7f9f2a727ba8 state=finished raised BrokenProcessPool>
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
>     callback(self)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
>     result = args.result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
>     return self.__get_result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
> exception calling callback for <Future at 0x7f9f2a769f98 state=finished raised BrokenProcessPool>
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
>     callback(self)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
>     result = args.result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
>     return self.__get_result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
> exception calling callback for <Future at 0x7f9f2a757c88 state=finished raised BrokenProcessPool>
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
>     callback(self)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
>     result = args.result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
>     return self.__get_result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
> exception calling callback for <Future at 0x7f9f2a796940 state=finished raised BrokenProcessPool>
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
>     callback(self)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
>     result = args.result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
>     return self.__get_result()
>   File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
> concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

- I've updated to fmriprep 1.2.5 (I was getting the same error on 1.2.3 before I updated)
- Also manually updated nipype after receiving the same error several times
- Tried running the analysis on just one participant after I kept getting the same error trying to run it on nine. Running it one participant just lead to me arriving at the same error faster.

Any help would be much appreciated and I can send through more information if necessary.

**Comment by BSegula** [comment]
I managed to get it working by using the plugin you suggested, thank you.
