### ISSUE TITLE
Docs no longer building

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1449]
Unclear why this started happening.

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/usr/local/miniconda/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/usr/local/miniconda/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/usr/local/miniconda/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sphinx/util/logging.py", line 261, in pending_warnings
    memhandler.flushTo(logger)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sphinx/util/logging.py", line 224, in flushTo
    logger.handle(record)
  File "/usr/local/miniconda/lib/python3.6/logging/__init__.py", line 1453, in handle
    self.callHandlers(record)
  File "/usr/local/miniconda/lib/python3.6/logging/__init__.py", line 1515, in callHandlers
    hdlr.handle(record)
  File "/usr/local/miniconda/lib/python3.6/logging/__init__.py", line 860, in handle
    rv = self.filter(record)
  File "/usr/local/miniconda/lib/python3.6/logging/__init__.py", line 719, in filter
    result = f.filter(record)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sphinx/util/logging.py", line 412, in filter
    raise SphinxWarning(message)
sphinx.errors.SphinxWarning: autodoc: failed to import module 'base' from module 'fmriprep.workflows'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 24, in <module>
    from niworkflows.interfaces.bids import (
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/__init__.py", line 6, in <module>
    from .masks import BETRPT as BET
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/masks.py", line 21, in <module>
    from seaborn import color_palette
  File "/usr/local/miniconda/lib/python3.6/site-packages/seaborn/__init__.py", line 6, in <module>
    from .rcmod import *
  File "/usr/local/miniconda/lib/python3.6/site-packages/seaborn/rcmod.py", line 5, in <module>
    from . import palettes, _orig_rc_params
  File "/usr/local/miniconda/lib/python3.6/site-packages/seaborn/palettes.py", line 12, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "/usr/local/miniconda/lib/python3.6/site-packages/seaborn/utils.py", line 17, in <module>
    pandas_has_categoricals = LooseVersion(pd.__version__) >= "0.15"
  File "/usr/local/miniconda/lib/python3.6/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/usr/local/miniconda/lib/python3.6/distutils/version.py", line 335, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
```

**Comment by oesteban** [comment]
Shouldn't that be python 3.7 since #1398?

**Comment by oesteban** [comment]
This is the probable cause of this problem: https://github.com/poldracklab/fmriprep/pull/1438/files#diff-85987f48f1258d9ee486e3191495582dL60

Cleaning up dependencies I cleared that up by mistake.
