### ISSUE TITLE
Image Exception : #3 :: Attempted to divide images/ROIs of different sizes

### ISSUE THREAD

**Issue by tragus1** [poldracklab/fmriprep#1492]
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.8', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 267, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 602, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 168, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 487, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 571, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 516, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 1023, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 960, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
fugue --despike --despikethreshold=2.1 --loadfmap=/root/src/fmriprep/work/fmriprep_wf/single_subject_ACTIGLIA011BL_wf/func_preproc_task_rest_wf/phdiff_wf/demean/sub-ACTIGLIA011BL_acq-rest_phasediff_rads_unwrapped_filt_demean.nii.gz --savefmap=sub-ACTIGLIA011BL_acq-rest_phasediff_rads_unwrapped_filt_demean_fieldmap.nii.gz --mask=/root/src/fmriprep/work/fmriprep_wf/single_subject_ACTIGLIA011BL_wf/func_preproc_task_rest_wf/phdiff_wf/bet/sub-ACTIGLIA011BL_acq-rest_magnitude1_ras_corrected_brain_mask.nii.gz
Standard output:

Standard error:
Image Exception : #3 :: Attempted to divide images/ROIs of different sizes
terminate called after throwing an instance of 'RBD_COMMON::BaseException'
Aborted (core dumped)
Return code: 134

**Comment by oesteban** [comment]
Could you share some data to replicate this?

**Comment by tragus1** [comment]
Thank you very much. I´ve sent you an email with the link to the download of the data.
Best regards
Boris

**Comment by effigies** [comment]
Hi @tragus1 can you verify that this issue persists in the most recent release of fMRIPrep (1.3.0.post2)?
