### ISSUE TITLE
fmriprep recon-all

### ISSUE THREAD

**Issue by RemiJanet** [poldracklab/fmriprep#1554]
Hi everybody,
I am new user with python and fmriprep and I tried to run the fmriprep using fieldmap less correction of distortions.
I couldn't succed in for the moment and I am looking for some feedbacks to solve this. I put a copy of the message here: 

```
fmriprep-docker /home/rjanet/Desktop/SERODOM_BIDS /home/rjanet/Desktop/SERODOM_BIDS_Preprocess/Test_19_mars_v3 participant --participant_label 01 --fs-license-file /home/rjanet/Desktop/Freesurfer_licence --use-syn-sdc --anat-only --n_cpus 1 --output-space fsnative --debug
RUNNING: docker run --rm -it -e DOCKER_VERSION_8395080871=18.03.1-ce -v /home/rjanet/Desktop/Freesurfer_licence:/opt/freesurfer/license.txt:ro -v /home/rjanet/Desktop/SERODOM_BIDS:/data:ro -v /home/rjanet/Desktop/SERODOM_BIDS_Preprocess/Test_19_mars_v3:/out poldracklab/fmriprep:1.3.1.post2 /data /out participant --participant_label 01 --use-syn-sdc --anat-only --n_cpus 1 --output-space fsnative --debug
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
This dataset appears to be BIDS compatible.
        Summary:                  Available Tasks:        Available Modalities: 
        13 Files, 744.85MB        DFET                    T1w                   
        1 - Subject               SDL1                    bold                  
        1 - Session               RL                                            
                                  SDL2                                          
                                  rest                                          

If you have any questions please post on https://neurostars.org/tags/bids

/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/site-packages/nilearn/datasets/neurovault.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container
/usr/local/miniconda/lib/python3.7/site-packages/skimage/__init__.py:80: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/pytest.py' mode='r' encoding='utf-8'>
  imp.find_module('pytest')
190320-12:59:11,589 nipype.workflow WARNING:
	 SyN SDC correction requires T1 to MNI registration, but "template" is not specified in "--output-space" arguments. Option --use-syn will be cowardly dismissed.
190320-12:59:11,639 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.3.1.post2:
      * BIDS dataset path: /data.
      * Participant list: ['01'].
      * Run identifier: 20190320-125911_df9099ae-03fa-4061-96d3-9fe1e737002c.
    
190320-12:59:11,639 nipype.workflow WARNING:
	 Option --debug is deprecated and has no effect
/usr/local/miniconda/lib/python3.7/site-packages/networkx/classes/reportviews.py:95: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, Set, Iterable
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/site-packages/nilearn/datasets/neurovault.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container
/usr/local/miniconda/lib/python3.7/site-packages/skimage/__init__.py:80: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/pytest.py' mode='r' encoding='utf-8'>
  imp.find_module('pytest')
190320-12:59:15,803 nipype.workflow IMPORTANT:
	 Works derived from this fMRIPrep execution should include the following boilerplate:


Results included in this manuscript come from preprocessing
performed using *fMRIPrep* 1.3.1.post2
(@fmriprep1; @fmriprep2; RRID:SCR_016216),
which is based on *Nipype* 1.1.9
(@nipype1; @nipype2; RRID:SCR_002502).

Anatomical data preprocessing

: The T1-weighted (T1w) image was corrected for intensity non-uniformity (INU)
with `N4BiasFieldCorrection` [@n4], distributed with ANTs 2.2.0 [@ants, RRID:SCR_004757], and used as T1w-reference throughout the workflow.
The T1w-reference was then skull-stripped using `antsBrainExtraction.sh`
(ANTs 2.2.0), using OASIS30ANTs as target template.
Brain surfaces were reconstructed using `recon-all` [FreeSurfer 6.0.1,
RRID:SCR_001847, @fs_reconall], and the brain mask estimated
previously was refined with a custom variation of the method to reconcile
ANTs-derived and FreeSurfer-derived segmentations of the cortical
gray-matter of Mindboggle [RRID:SCR_002438, @mindboggle].
Spatial normalization to the
*ICBM 152 Nonlinear Asymmetrical template version 2009c* [@mni152nlin2009casym, RRID:SCR_008796]
was performed through nonlinear registration with `antsRegistration`
(ANTs 2.2.0), using brain-extracted versions of both T1w volume
and template.
Brain tissue segmentation of cerebrospinal fluid (CSF),
white-matter (WM) and gray-matter (GM) was performed on
the brain-extracted T1w using `fast` [FSL 5.0.9, RRID:SCR_002823,
@fsl_fast].


Many internal operations of *fMRIPrep* use
*Nilearn* 0.5.0 [@nilearn, RRID:SCR_001362],
mostly within the functional processing workflow.
For more details of the pipeline, see [the section corresponding
to workflows in *fMRIPrep*'s documentation](https://fmriprep.readthedocs.io/en/latest/workflows.html "FMRIPrep's documentation").


### References


Captured warning (<class 'ImportWarning'>): can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
Captured warning (<class 'ImportWarning'>): can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
Captured warning (<class 'ImportWarning'>): can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
Captured warning (<class 'DeprecationWarning'>): Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
Captured warning (<class 'ResourceWarning'>): unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/pytest.py' mode='r' encoding='utf-8'>
190320-12:59:24,60 nipype.workflow WARNING:
	 Some nodes demand for more threads than available (1).
Captured warning (<class 'PendingDeprecationWarning'>): the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/site-packages/nilearn/datasets/neurovault.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container
Captured warning (<class 'PendingDeprecationWarning'>): the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
190320-12:59:26,188 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.bidssrc" in "/tmp/work/fmriprep_wf/single_subject_01_wf/bidssrc".
190320-12:59:26,190 nipype.workflow INFO:
	 [Node] Running "bidssrc" ("niworkflows.interfaces.bids.BIDSDataGrabber")
190320-12:59:26,192 nipype.interface WARNING:
	 No "t2w" images found for sub-<undefined>
190320-12:59:26,192 nipype.interface WARNING:
	 No "flair" images found for sub-<undefined>
190320-12:59:26,192 nipype.interface WARNING:
	 No "fmap" images found for sub-<undefined>
190320-12:59:26,192 nipype.interface WARNING:
	 No "sbref" images found for sub-<undefined>
190320-12:59:26,192 nipype.interface WARNING:
	 No "roi" images found for sub-<undefined>
190320-12:59:26,198 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_01_wf.bidssrc".
190320-12:59:28,151 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.anat_template_wf.t1_template_dimensions" in "/tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_template_wf/t1_template_dimensions".
190320-12:59:28,153 nipype.workflow INFO:
	 [Node] Running "t1_template_dimensions" ("niworkflows.interfaces.images.TemplateDimensions")
190320-12:59:28,256 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.anat_template_wf.t1_template_dimensions".
190320-12:59:30,461 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.anat_derivatives_wf.t1_name" in "/tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_derivatives_wf/t1_name".
190320-12:59:30,463 nipype.workflow INFO:
	 [Node] Running "t1_name" ("nipype.interfaces.utility.wrappers.Function")
190320-12:59:30,467 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.anat_derivatives_wf.t1_name".
190320-12:59:32,176 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.anat_template_wf.t1_conform" in "/tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_template_wf/t1_conform".
190320-12:59:32,180 nipype.workflow INFO:
	 [Node] Setting-up "_t1_conform0" in "/tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_template_wf/t1_conform/mapflow/_t1_conform0".
190320-12:59:32,182 nipype.workflow INFO:
	 [Node] Running "_t1_conform0" ("niworkflows.interfaces.images.Conform")
190320-12:59:32,209 nipype.workflow INFO:
	 [Node] Finished "_t1_conform0".
190320-12:59:32,210 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.anat_template_wf.t1_conform".
190320-12:59:34,178 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.surface_recon_wf.fov_check" in "/tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/fov_check".
190320-12:59:34,180 nipype.workflow INFO:
	 [Node] Running "fov_check" ("nipype.interfaces.utility.wrappers.Function")
190320-12:59:34,635 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.surface_recon_wf.fov_check".
/usr/local/miniconda/lib/python3.7/site-packages/skimage/__init__.py:80: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/miniconda/lib/python3.7/site-packages/pytest.py' mode='r' encoding='utf-8'>
  imp.find_module('pytest')
190320-12:59:36,462 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.surface_recon_wf.recon_config" in "/tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/recon_config".
190320-12:59:36,464 nipype.workflow INFO:
	 [Node] Running "recon_config" ("niworkflows.interfaces.freesurfer.FSDetectInputs")
190320-12:59:36,488 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.surface_recon_wf.recon_config".
190320-12:59:38,180 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.skullstrip_ants_wf.t1_skull_strip" in "/tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip".
190320-12:59:38,183 nipype.workflow INFO:
	 [Node] Running "t1_skull_strip" ("nipype.interfaces.ants.segmentation.BrainExtraction"), a CommandLine Interface with command:
antsBrainExtraction.sh -a /data/sub-01/ses-1/anat/sub-01_ses-1_T1w.nii.gz -m /tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/tpl-OASIS30ANTs_res-01_label-brain_probseg.nii.gz -e /opt/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz -d 3 -f /opt/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_desc-BrainCerebellumExtraction_mask.nii.gz -s nii.gz -k 1 -o highres001_ -q 1 -u 1
190320-13:29:40,87 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.skullstrip_ants_wf.t1_skull_strip".
190320-13:29:50,262 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.bids_info" in "/tmp/work/fmriprep_wf/single_subject_01_wf/bids_info".
190320-13:29:50,264 nipype.workflow INFO:
	 [Node] Running "bids_info" ("niworkflows.interfaces.bids.BIDSInfo")
190320-13:29:50,747 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_01_wf.bids_info".
190320-13:29:54,363 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.surface_recon_wf.autorecon1" in "/tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/autorecon1".
190320-13:29:54,611 nipype.interface INFO:
	 resume recon-all : recon-all -autorecon1 -noskullstrip -openmp 8 -subjid sub-01 -sd /out/freesurfer 
190320-13:29:54,612 nipype.workflow INFO:
	 [Node] Running "autorecon1" ("nipype.interfaces.freesurfer.preprocess.ReconAll"), a CommandLine Interface with command:
recon-all -autorecon1 -noskullstrip -openmp 8 -subjid sub-01 -sd /out/freesurfer 
190320-13:29:54,614 nipype.interface INFO:
	 resume recon-all : recon-all -autorecon1 -noskullstrip -openmp 8 -subjid sub-01 -sd /out/freesurfer 
190320-13:29:56,122 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_01_wf.anat_preproc_wf.surface_recon_wf.autorecon1" (/tmp/work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/surface_recon_wf/autorecon1)
190320-13:29:56,265 nipype.workflow ERROR:
	 Node autorecon1 failed to run on host 1350f8924bf1.
190320-13:29:56,405 nipype.workflow ERROR:
	 Saving crash info to /out/fmriprep/sub-01/log/20190320-125911_df9099ae-03fa-4061-96d3-9fe1e737002c/crash-20190320-132956-root-autorecon1-04492bbd-d838-47ca-a996-159ef3b9a6cc.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 758, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 695, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
recon-all -autorecon1 -noskullstrip -openmp 8 -subjid sub-01 -sd /out/freesurfer 
Standard output:
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
INFO: SUBJECTS_DIR is /out/freesurfer
Actual FREESURFER_HOME /opt/freesurfer
-rw-rw-r-- 1 root root 34452 Mar 20 11:33 /out/freesurfer/sub-01/scripts/recon-all.log
Linux 1350f8924bf1 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.39-1+deb8u1~bpo70+1 (2017-02-24) x86_64 x86_64 x86_64 GNU/Linux
'/opt/freesurfer/bin/recon-all' -> '/out/freesurfer/sub-01/scripts/recon-all.local-copy'
#--------------------------------------------
#@# MotionCor Wed Mar 20 13:29:55 UTC 2019
ERROR: no run data found in /out/freesurfer/sub-01/mri. Make sure to
have a volume called 001.mgz in  /out/freesurfer/sub-01/mri/orig.
If you have a second run of data call it 002.mgz, etc.
See also: http://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/Conversion
Linux 1350f8924bf1 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.39-1+deb8u1~bpo70+1 (2017-02-24) x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-01 exited with ERRORS at Wed Mar 20 13:29:55 UTC 2019

For more details, see the log file /out/freesurfer/sub-01/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Standard error:

Return code: 1

Preprocessing did not finish successfully. Errors occurred while processing data from participants: 01 (1). Check the HTML reports for details.
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.3.1.post2', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 436, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 599, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 161, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 224, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 758, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 695, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
recon-all -autorecon1 -noskullstrip -openmp 8 -subjid sub-01 -sd /out/freesurfer 
Standard output:
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
INFO: SUBJECTS_DIR is /out/freesurfer
Actual FREESURFER_HOME /opt/freesurfer
-rw-rw-r-- 1 root root 34452 Mar 20 11:33 /out/freesurfer/sub-01/scripts/recon-all.log
Linux 1350f8924bf1 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.39-1+deb8u1~bpo70+1 (2017-02-24) x86_64 x86_64 x86_64 GNU/Linux
'/opt/freesurfer/bin/recon-all' -> '/out/freesurfer/sub-01/scripts/recon-all.local-copy'
#--------------------------------------------
#@# MotionCor Wed Mar 20 13:29:55 UTC 2019
ERROR: no run data found in /out/freesurfer/sub-01/mri. Make sure to
have a volume called 001.mgz in  /out/freesurfer/sub-01/mri/orig.
If you have a second run of data call it 002.mgz, etc.
See also: http://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/Conversion
Linux 1350f8924bf1 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.39-1+deb8u1~bpo70+1 (2017-02-24) x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-01 exited with ERRORS at Wed Mar 20 13:29:55 UTC 2019

For more details, see the log file /out/freesurfer/sub-01/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Standard error:

Return code: 1

Sentry is attempting to send 2 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues
```

**Comment by effigies** [comment]
Did you already have a `/home/rjanet/Desktop/SERODOM_BIDS_Preprocess/Test_19_mars_v3 participant/freesurfer` directory with a `sub-01` folder in it? It looks like we detected a folder and didn't try to add the T1w file, but the file hadn't previously been added. I would suggest deleting that directory and trying again.

**Comment by RemiJanet** [comment]
So I change the directory and add a working directory.

fmriprep-docker /home/rjanet/Desktop/SERODOM_BIDS /home/rjanet/Desktop/SERODOM_BIDS_Preprocess/Test_19_mars_v4 participant --participant_label 01 --fs-license-file /home/rjanet/Desktop/Freesurfer_licence/license.txt --use-syn-sdc --anat-only --n_cpus 1 --output-space fsnative --w /home/rjanet/Desktop/SERODOM_bids_Preprocess/TMP2

Now I have another error:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 101, in _python_exit
    thread_wakeup.wakeup()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 89, in wakeup
    self._writer.send_bytes(b"")
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
Sentry is attempting to send 0 pending error messages

Any suggestion?
Thanks a lot !

**Comment by effigies** [comment]
That's a bug in the telemetry code at the end, but given that it's not attempting to send any error messages, that looks fine. Are your output reports present, and are there any errors reported at the end?

**Comment by RemiJanet** [comment]
Yes I could find and have a look to the output report and there is no error at the end. Every thing looks good.
Thanks for your feedbacks.
