### ISSUE TITLE
Circle CI failure reporting

### ISSUE THREAD

**Issue by shoshber** [poldracklab/fmriprep#160]
see https://github.com/poldracklab/fmriprep/pull/157

**Comment by shoshber** [comment]
Potentially related--contradicting info on failure between crash file and logs, ex in https://circleci.com/gh/shoshber/fmriprep/62#artifacts/containers/0:

log says:
```
161006-23:27:19,392 workflow ERROR:
	 [u'Node aCompCor.a3 failed to run on host bc79e72a3ab8.']
161006-23:27:19,393 workflow INFO:
	 Saving crash info to /out/log/crash-20161006-232719-root-aCompCor.a3-f4bf662f-724a-4676-9679-cd4f32856e47.pklz
161006-23:27:19,393 workflow INFO:
	 Traceback (most recent call last):
  File "/root/src/src/nipype/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/root/src/src/nipype/nipype/pipeline/engine/nodes.py", line 367, in run
    self._run_interface()
  File "/root/src/src/nipype/nipype/pipeline/engine/nodes.py", line 477, in _run_interface
    self._result = self._run_command(execute)
  File "/root/src/src/nipype/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/root/src/src/nipype/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/root/src/src/nipype/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/root/src/src/nipype/nipype/algorithms/confounds.py", line 333, in _run_interface
    voxel_timecourses = imgseries[mask > 0]
IndexError: index 35 is out of bounds for axis 2 with size 34
Interface CompCor failed to run. 
```
crash file says:
```
$ nipype_display_crash crash-20161006-232719-root-aCompCor.a3-f4bf662f-724a-4676-9679-cd4f32856e47.pklz
161007-00:36:15,483 workflow DEBUG:
         networkx 1.4 dev or higher detected
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/python2/bin/nipype_display_crash", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/fmriprep/src/nipype/bin/nipype_display_crash", line 85, in <module>
    debug, args.directory)
  File "/home/ubuntu/fmriprep/src/nipype/bin/nipype_display_crash", line 17, in display_crash_files
    crash_data = loadcrash(crashfile)
  File "/home/ubuntu/fmriprep/src/nipype/nipype/utils/filemanip.py", line 489, in loadcrash
    return loadpkl(infile)
  File "/home/ubuntu/fmriprep/src/nipype/nipype/utils/filemanip.py", line 514, in loadpkl
    unpkl = pickle.load(pkl_file)
  File "/home/ubuntu/anaconda3/envs/python2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/home/ubuntu/anaconda3/envs/python2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/ubuntu/anaconda3/envs/python2/lib/python2.7/pickle.py", line 1223, in load_build
    setstate(state)
  File "/home/ubuntu/anaconda3/envs/python2/lib/python2.7/site-packages/traits/has_traits.py", line 1442, in __setstate__
    self.trait_set( trait_change_notify = trait_change_notify, **state )
  File "/home/ubuntu/anaconda3/envs/python2/lib/python2.7/site-packages/traits/has_traits.py", line 1541, in trait_set
    setattr( self, name, value )
  File "/home/ubuntu/fmriprep/src/nipype/nipype/interfaces/traits_extension.py", line 89, in validate
    self.error(object, name, value)
  File "/home/ubuntu/anaconda3/envs/python2/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'realigned_file' trait of a CompCorInputSpec instance must be an existing file name, but a value of u'/scratch/work/workflow_enumerator/100185/EPI_HMC/_epi_..data..ds054..sub-100185..func..sub-100185_task-machinegame_run-04_bold.nii.gz/EPI_hmc/sub-100185_task-machinegame_run-04_bold_brain_mcf.nii.gz' <type 'unicode'> was specified.
```

**Comment by shoshber** [comment]
Consider reducing logging in circle so the entire thing can be saved; or make full logs an artifact?

**Comment by shoshber** [comment]
A node _node.pklz, result_*.pklz are also erroneously (?) reporting files not found--see artifacts here: https://circleci.com/gh/shoshber/fmriprep/96#artifacts/containers/0 for TopUpApply (EPIUnwarpWorkflow/SDC_unwarp/..../TopUpApply

**Comment by shoshber** [comment]
Update: 

The main scary issue has been fixed (https://circleci.com/gh/poldracklab/fmriprep/269). Circle CI should properly report exit codes now. To prevent this sort of thing from happening again, we can add a test that we know will fail and check the exit code.

Answers still needed for: Crash files, _node.pklz, result_*.pklz not reporting the correct error

**Comment by shoshber** [comment]
https://circleci.com/gh/shoshber/fmriprep/126

Failures inside input-manipulation functions (http://nipy.org/nipype/0.11.0/users/tutorial_103.html#modifying-inputs-to-pipeline-nodes) do not trigger a failure. However, I think this might originate in nipype itself, not fmriprep.

**Comment by chrisfilo** [comment]
It would be good to be able to see the end of the log file (it's currently truncated at 40k lines) to investigate this better. Speaking of silent CircleCI failures: did you ever get round to performing the tests I suggested here https://github.com/poldracklab/fmriprep/pull/157#issuecomment-252029826 ?

Re: crashfiles. AFAIK when a crashfile is loaded the interface is initialized from the pickle file - that means its inputs are being set (and validated) again. If between the time the crashfile was created and loaded one of the input files was removed or the crashfile was loaded in a different environment (for example a different machine) you will get input validation errors. 

It would be good to consider a simpler more portable crashfile format in the future (WDYT @satra).

**Comment by satra** [comment]
@chrisfilo - changing the crashfile format would be a fundamental change and we should think about it. the crashfile literally re-initializes the interface so one can rerun and debug. therefore portability was not the critical issue. that being said, i have loaded crashfiles from other machines by hacking the pickling class and disabling trait validation for file(exists).

i agree we should think about how to do this better and whether there should be an option to package the inputs as well. another option would simply be to suppress traits validation for any file/directory trait, which we could do, since we override those traits.

**Comment by chrisfilo** [comment]
Closing because of https://github.com/nipy/nipype/issues/1184
