### ISSUE TITLE
SyN-SDC fails for non-default template spaces

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#1665]
See [Neurostars #4381](https://neurostars.org/t/fmriprep1-4-0-does-not-work-using-syn-distortion-correction/4381).

```
traits.trait_errors.TraitError: The ‘transforms’ trait of an ApplyTransformsInputSpec instance must be a list of items which are an existing file name or ‘identity’, but a value of [’/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_facelocalizer_wf/sdc_wf/syn_sdc_wf/ref_2_t1/transform0GenericAffine.mat’, ‘/scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration/ants_t1_to_mniInverseComposite.h5’, ‘/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/fmap_atlas_2_MNI152NLin6Asym_affine.mat’] <class ‘list’> was specified.

Error setting node input:
Node: atlas_2_ref
input: transforms
results_file: /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_facelocalizer_wf/sdc_wf/syn_sdc_wf/transform_list/result_transform_list.pklz
value: [’/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_facelocalizer_wf/sdc_wf/syn_sdc_wf/ref_2_t1/transform0GenericAffine.mat’, ‘/scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration/ants_t1_to_mniInverseComposite.h5’, ‘/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/fmap_atlas_2_MNI152NLin6Asym_affine.mat’]
```

**Comment by effigies** [comment]
We're missing affine transformations from the fieldmap atlas to other templates.

**Comment by oesteban** [comment]
This should go into TemplateFlow (it is one of its inception principles and requirements)

**Comment by alexlicohen** [comment]
Hi all,
I just realized this is still not working; is there a way around this for now?

>Node Name: fmriprep_wf.single_subject_NDARAU530GLJ_wf.func_preproc_task_rest_run_2_wf.sdc_wf.syn_sdc_wf.atlas_2_ref
File: /out/fmriprep/sub-NDARAU530GLJ/log/20190707-141844_d5b13a54-1df0-4efa-8851-0b634a2e2e6b/crash-20190708-094223-root-atlas_2_ref-593063a6-e1ca-48d4-80e2-4dde6cfe0d1e.txt
Working Directory: /tmp/work/fmriprep_wf/single_subject_NDARAU530GLJ_wf/func_preproc_task_rest_run_2_wf/sdc_wf/syn_sdc_wf/atlas_2_ref
Inputs: 
args:
default_value: 0.0
dimension:
environ: {'NSLOTS': '7'}
float: False
input_image: /usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/fmap_atlas.nii.gz
input_image_type:
interpolation: Linear
interpolation_parameters:
invert_transform_flags: [True, False, False]
num_threads: 7
out_postfix: _trans
output_image:
print_out_composite_warp_file:
reference_image:
transforms:

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 410, in run
    cached, updated = self.is_cached()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 296, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 493, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 540, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 278, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'transforms' trait of an ApplyTransformsInputSpec instance must be a list of items which are an existing file name or 'identity', but a value of ['/tmp/work/fmriprep_wf/single_subject_NDARAU530GLJ_wf/func_preproc_task_rest_run_2_wf/sdc_wf/syn_sdc_wf/ref_2_t1/transform0GenericAffine.mat', '/tmp/work/fmriprep_wf/single_subject_NDARAU530GLJ_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration/ants_t1_to_mniInverseComposite.h5', '/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/fmap_atlas_2_MNI152NLin6Asym_affine.mat']  was specified.

Error setting node input:
Node: atlas_2_ref
input: transforms
results_file: /tmp/work/fmriprep_wf/single_subject_NDARAU530GLJ_wf/func_preproc_task_rest_run_2_wf/sdc_wf/syn_sdc_wf/transform_list/result_transform_list.pklz
value: ['/tmp/work/fmriprep_wf/single_subject_NDARAU530GLJ_wf/func_preproc_task_rest_run_2_wf/sdc_wf/syn_sdc_wf/ref_2_t1/transform0GenericAffine.mat', '/tmp/work/fmriprep_wf/single_subject_NDARAU530GLJ_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration/ants_t1_to_mniInverseComposite.h5', '/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/data/fmap_atlas_2_MNI152NLin6Asym_affine.mat']
```

**Comment by JeroenBlommaert** [comment]
Dear all,

This issue is still present on v. 1.5.0
I suspect it failing because I also use aroma and it seems to be looking for the template aroma adds.
I'm trying to re-run now everything with an explicit --output-spaces with all spaces in correct order: 
`singularity run --cleanenv  ${VSC_DATA}/fmriprep.simg --output-spaces MNI152NLin2009cAsym anat MNI152NLin6Asym:res-2 --nthreads 36 \
--output-spaces anat --use-aroma --fs-license-file ./license.txt --use-syn-sdc \
--work-dir . --resource-monitor --nthreads 36 --mem-mb 189000 --fs-no-reconall \
data fmriprep_out2 participant`

I will keep you updated how this works.
For now the error-log I get:

`191112-11:05:41,737 nipype.workflow WARNING:
	 Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at 
https://github.com/nipy/nipype/issues adding the following information:

	Node: fmriprep_wf.single_subject_Ct07_wf.func_preproc_task_rest_wf.sdc_wf.syn_sdc_wf.atlas_2_ref
	Interface: niworkflows.interfaces.fixes.FixHeaderApplyTransforms
	Traceback:
Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 337, in _local_hash_check
    cached, updated = self.procs[jobid].is_cached()

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 297, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 494, in _get_hashval
    self._get_inputs()

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 541, in _get_inputs
    self.set_input(key, deepcopy(output_value))

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 279, in set_input
    setattr(self.inputs, parameter, deepcopy(val))

  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )

traits.trait_errors.TraitError: The 'transforms' trait of an ApplyTransformsInputSpec instance must be a list of items which are a pathlike object or string representing an existing fi
le or 'identity', but a value of ['/ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_wf/single_subject_Ct07_wf/func_preproc_task_rest_wf/sdc_wf/syn_sdc_wf/ref_2_t1/tran
sform0GenericAffine.mat', '/ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_wf/single_subject_Ct07_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registrati
on/ants_t1_to_mniInverseComposite.h5', '/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/data/fmap_atlas_2_MNI152NLin6Asym_affine.mat'] <class 'list'> was specified.

Error setting node input:
Node: atlas_2_ref
input: transforms
results_file: /ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_wf/single_subject_Ct07_wf/func_preproc_task_rest_wf/sdc_wf/syn_sdc_wf/transform_list/result_transform_li
st.pklz
value: ['/ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_wf/single_subject_Ct07_wf/func_preproc_task_rest_wf/sdc_wf/syn_sdc_wf/ref_2_t1/transform0GenericAffine.mat', 
'/ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_wf/single_subject_Ct07_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration/ants_t1_to_mniInverseCo
mposite.h5', '/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/data/fmap_atlas_2_MNI152NLin6Asym_affine.mat']

191112-11:05:46,208 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_Ct07_wf.func_preproc_task_rest_wf.sdc_wf.syn_sdc_wf.atlas_2_ref" in "/ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmr
iprep_wf/single_subject_Ct07_wf/func_preproc_task_rest_wf/sdc_wf/syn_sdc_wf/atlas_2_ref".
191112-11:05:47,639 nipype.workflow ERROR:
	 Node atlas_2_ref failed to run on host r23i27n18.
191112-11:05:47,650 nipype.workflow ERROR:
	 Saving crash info to /ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_out2/fmriprep/sub-Ct07/log/20191112-110350_f89f92b4-7a2c-4acd-9d71-4cac4172f9ce/crash-20
191112-110547-vsc32466-atlas_2_ref-137b4a86-7a53-49b8-b65c-e1bd0a02bf93.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 411, in run
    cached, updated = self.is_cached()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 297, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 494, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 541, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 279, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'transforms' trait of an ApplyTransformsInputSpec instance must be a list of items which are a pathlike object or string representing an existing fi
le or 'identity', but a value of ['/ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_wf/single_subject_Ct07_wf/func_preproc_task_rest_wf/sdc_wf/syn_sdc_wf/ref_2_t1/tran
sform0GenericAffine.mat', '/ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_wf/single_subject_Ct07_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registrati
on/ants_t1_to_mniInverseComposite.h5', '/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/data/fmap_atlas_2_MNI152NLin6Asym_affine.mat'] <class 'list'> was specified.

Error setting node input:
Node: atlas_2_ref
input: transforms
results_file: /ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_wf/single_subject_Ct07_wf/func_preproc_task_rest_wf/sdc_wf/syn_sdc_wf/transform_list/result_transform_li
st.pklz
value: ['/ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_wf/single_subject_Ct07_wf/func_preproc_task_rest_wf/sdc_wf/syn_sdc_wf/ref_2_t1/transform0GenericAffine.mat', 
'/ddn1/vol1/site_scratch/leuven/324/vsc32466/testfmriprep/fmriprep_wf/single_subject_Ct07_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration/ants_t1_to_mniInverseCo
mposite.h5', '/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/data/fmap_atlas_2_MNI152NLin6Asym_affine.mat']

191112-11:05:49,638 nipype.workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_Ct07_wf.func_preproc_task_rest_wf.sdc_wf.syn_sdc_wf.atlas_2_ref`

**Comment by rnair07** [comment]
Hi - just wondering if there is a solution to this in any of the newer releases? We are doing analysis in subject space and would like to use syn-sdc for distortion correction. Thanks.

**Comment by JeroenBlommaert** [comment]
> Hi - just wondering if there is a solution to this in any of the newer releases? We are doing analysis in subject space and would like to use syn-sdc for distortion correction. Thanks.

The work-around works perfectly, just specify explicitly the necessary atlas space

**Comment by rnair07** [comment]
> > Hi - just wondering if there is a solution to this in any of the newer releases? We are doing analysis in subject space and would like to use syn-sdc for distortion correction. Thanks.
> 
> The work-around works perfectly, just specify explicitly the necessary atlas space

@JeroenBlommaert : could you elaborate on this please. What is the work around?

**Comment by JeroenBlommaert** [comment]
> > > Hi - just wondering if there is a solution to this in any of the newer releases? We are doing analysis in subject space and would like to use syn-sdc for distortion correction. Thanks.
> > 
> > 
> > The work-around works perfectly, just specify explicitly the necessary atlas space
> 
> @JeroenBlommaert : could you elaborate on this please. What is the work around?

I was referring to [this thread]( https://neurostars.org/t/fmriprep1-4-0-does-not-work-using-syn-distortion-correction/4381/2) mentioned above.
Basically, you have to add MNI152NLin2009cAsym to your output spaces
