### ISSUE TITLE
Error running fmriprep

### ISSUE THREAD

**Issue by MLopezAguirre** [poldracklab/fmriprep#1677]
Hello everyone,

I'm trying to make my first steps with fmriprep but I'm having some trouble when I try to run it. The error what I get is the next one:

```
Running fMRIPREP version 1.4.0:
      * BIDS dataset path: /media/miguellopez/BetaDisk_2Tb/Test_Trial
      * Participant list: ['01'].
      * Run identifier: 20190621-153209_b87c21c2-7211-4524-9002-feb61ad1e355.
Process Process-2:
Traceback (most recent call last):
  File "/home/miguellopez/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/miguellopez/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/fmriprep/cli/run.py", line 608, in build_workflow
    work_dir=str(work_dir),
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 258, in init_fmriprep_wf
    use_syn=use_syn,
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 549, in init_single_subject_wf
    skull_strip_template=skull_strip_template,
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/smriprep/workflows/anatomical.py", line 230, in init_anat_preproc_wf
    normalization_quality='precise' if not debug else 'testing')
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/niworkflows/anat/ants.py", line 180, in init_brain_extraction_wf
    template_spec['suffix'] = template_spec.get('suffix', bids_suffix)
AttributeError: 'str' object has no attribute 'get'
 ```

Because this is my first try using fmriprep, I have decided to use a very simple dataset with only one task and its respective anatomical T1 (I've already verified it with bids-validator).  
I don't know if it helps but and I'm using Ubuntu 16.04 with python 3.6.8.

Thank you very much for your time.
   Miguel.

**Comment by oesteban** [comment]
Hi Miguel,

First, what is your exact command line?

Second, could you try again with the latest version (1.4.1rc4)? I think that one should fix your issue.

**Comment by MLopezAguirre** [comment]
Hi Oscar, 

The command I'm using is:
                   `fmriprep  dir_in  dir_out  participant --participant_label 'sub-01'`
where ''dir_in" is the directory where I have my dataset and "dir_out" is the output directory (I've also tried it without the participant label).

Another issue. I'm trying to update fmriprep but I can't. The last version that detect the "pip" command is 1.4.0.
               `python3.6 -m pip install --upgrade  fmriprep`
I've also tried to download the last version from the git source and installed it with the line: 
               `python3.6  directory... /fmriprep-master/setup.py install --user`
but what I get is: 

```
running install
running bdist_egg
running egg_info
creating UNKNOWN.egg-info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
skipping 'fmriprep/utils/maths.c' Cython extension (up-to-date)
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/fmriprep
creating build/bdist.linux-x86_64/egg/fmriprep/utils
copying build/lib.linux-x86_64-3.6/fmriprep/utils/maths.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/fmriprep/utils
creating stub loader for fmriprep/utils/maths.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/fmriprep/utils/maths.py to maths.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/UNKNOWN-0+unknown-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing UNKNOWN-0+unknown-py3.6-linux-x86_64.egg
removing '/home/miguellopez/.local/lib/python3.6/site-packages/UNKNOWN-0+unknown-py3.6-linux-x86_64.egg' (and everything under it)
creating /home/miguellopez/.local/lib/python3.6/site-packages/UNKNOWN-0+unknown-py3.6-linux-x86_64.egg
Extracting UNKNOWN-0+unknown-py3.6-linux-x86_64.egg to /home/miguellopez/.local/lib/python3.6/site-packages
UNKNOWN 0+unknown is already the active version in easy-install.pth

Installed /home/miguellopez/.local/lib/python3.6/site-packages/UNKNOWN-0+unknown-py3.6-linux-x86_64.egg
Processing dependencies for UNKNOWN==0+unknown
Finished processing dependencies for UNKNOWN==0+unknown
```

(I'm sorry but I don't have much experience with python so it's probably that I'm doing something wrong )

Thank you very much for your help,
              Miguel.

**Comment by sweetneuron** [comment]
Hej,

thanks, Oscar, 1.4.1rc4 appears to solve this issue.

Miguel, try the following:
pip3 uninstall fmriprep
pip3 install git+https://github.com/poldracklab/fmriprep.git@1.4.1rc4

All best,
Ronny

**Comment by effigies** [comment]
You should also be able to use:

```
pip install fmriprep==1.4.1rc4
```

**Comment by MLopezAguirre** [comment]
It works!!!  Thank you all very much for your help!!!
