### ISSUE TITLE
node bold_std_trans_wf: 'fixed_image' is an existing file name, but the path does not exist

### ISSUE THREAD

**Issue by albamrt** [poldracklab/fmriprep#1679]
Hello,

I am running fmriprep (version 1.4.0) with the following command:

`fmriprep-docker --fs-license /archive/albamrt/MRI/license.txt /archive/albamrt/MRI/BIDS /archive/albamrt/MRI/fmriprep participant --participant_label C15 -w /archive/albamrt/MRI/work -t wm --ignore slicetiming --bold2t1w-dof 6 --no-submm-recon --fs-no-reconall --write-graph -v --output-spaces MNI152NLin6Asym:res-2 MNI152NLin6Sym:res-2 --write-graph --n_cpus 8 --nthreads 8
`

And I have encountered the following error, that seems to come from the bold_std_trans_wf node: 

```
190620-17:52:45,963 nipype.workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_C15_wf.func_preproc_ses_01_task_wm_run_02_wf.bold_std_trans_wf.gen_ref.a1
190620-17:52:45,975 nipype.workflow INFO:
	 crashfile: /out/fmriprep/sub-C15/log/20190620-123408_4016b296-f55d-441c-9783-878db7f68697/crash-20190620-161839-root-gen_ref.a1-ca774671-da17-489f-b683-d261e69c38c0.txt
190620-17:52:45,975 nipype.workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_C15_wf.func_preproc_ses_01_task_wm_run_01_wf.bold_std_trans_wf.gen_ref.a1
190620-17:52:45,986 nipype.workflow INFO:
	 crashfile: /out/fmriprep/sub-C15/log/20190620-123408_4016b296-f55d-441c-9783-878db7f68697/crash-20190620-161843-root-gen_ref.a1-8502f3cf-1355-4f86-b159-fa962a691186.txt
190620-17:52:45,986 nipype.workflow INFO:
```

After looking in the scratch directory and the crashfiles it seems like it is fine with the MNI152NLin6Asym standard space but not with the MNI152NLin6Sym. This is the content of the crashfile:

```
Node: fmriprep_wf.single_subject_C15_wf.func_preproc_ses_01_task_wm_run_02_wf.bold_std_trans_wf.gen_ref
Working directory: /scratch/fmriprep_wf/single_subject_C15_wf/func_preproc_ses_01_task_wm_run_02_wf/bold_std_trans_wf/_key_MNI152NLin6Sym/gen_ref

Node inputs:

fixed_image = <undefined>
fov_mask = None
keep_native = True
moving_image = <undefined>
xform_code = None

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 410, in run
    cached, updated = self.is_cached()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 296, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 493, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 540, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 278, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 112, in validate
    self.info_text, value))
traits.trait_errors.TraitError: The trait 'fixed_image' of a GenerateSamplingReferenceInputSpec instance is an existing file name, but the path  '[]' does not exist.

Error setting node input:
Node: gen_ref
input: fixed_image
results_file: /scratch/fmriprep_wf/single_subject_C15_wf/func_preproc_ses_01_task_wm_run_02_wf/bold_std_trans_wf/_key_MNI152NLin6Sym/select_tpl/result_select_tpl.pklz
value: []
```

I am not sure of what is the problem and why it works with one of the reference files but not with the other, so it would be great if you could help me. Thank you in advance!!

**Comment by oesteban** [comment]
I believe this has been fixed with version 1.4.1rc4.

**Comment by oesteban** [comment]
Hi @albamrt, did you have an opportunity to check this has been fixed?

**Comment by albamrt** [comment]
Yes, thank you so much!
