### ISSUE TITLE
compcor_variance_plot error

### ISSUE THREAD

**Issue by MLopezAguirre** [poldracklab/fmriprep#1680]
Hi everyone,

When I was running fmriprep with this command: 

`fmriprep dir_in dir_out participant --participant_label 'sub-01'`

after a few hour of computing  I get the next error (I let you a few more lines before to help its location):
```
190626-19:05:43,402 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_01_wf.func_preproc_task_galvan_wf.bold_std_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.combine_masks".
190626-19:05:45,338 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.func_preproc_task_galvan_wf.bold_std_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.apply_mask" in "/home/miguellopez/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_galvan_wf/bold_std_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/_key_MNI152NLin2009cAsym/apply_mask".
190626-19:05:45,339 nipype.workflow INFO:
[Node] Running "apply_mask" ("nipype.interfaces.fsl.maths.ApplyMask"), a CommandLine Interface with command:
fslmaths /home/miguellopez/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_galvan_wf/bold_std_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/_key_MNI152NLin2009cAsym/fixhdr_unifize/uni_xform.nii.gz -mas /home/miguellopez/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_galvan_wf/bold_std_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/_key_MNI152NLin2009cAsym/combine_masks/ref_bold_corrected_brain_mask_maths.nii.gz /home/miguellopez/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_galvan_wf/bold_std_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/_key_MNI152NLin2009cAsym/apply_mask/uni_xform_masked.nii.gz
190626-19:05:45,420 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_01_wf.func_preproc_task_galvan_wf.bold_std_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.apply_mask".
190626-19:05:49,277 nipype.workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_01_wf.func_preproc_task_galvan_wf.bold_confounds_wf.compcor_plot
fMRIPrep failed: Workflow did not execute cleanly. Check log for details
Preprocessing did not finish successfully. Errors occurred while processing data from participants: 01 (1). Check the HTML reports for details.
```

When I go to the crash report this is what I get:
```
Node: fmriprep_wf.single_subject_01_wf.func_preproc_task_galvan_wf.bold_confounds_wf.compcor_plot
Working directory: /home/miguellopez/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_galvan_wf/bold_confounds_wf/compcor_plot

Node inputs:

metadata_files = ['/home/miguellopez/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_galvan_wf/bold_confounds_wf/tcompcor/component_metadata.tsv', '/home/miguellopez/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_galvan_wf/bold_confounds_wf/acompcor/component_metadata.tsv']
metadata_sources = ['tCompCor', 'aCompCor']
out_file = None
variance_thresholds = (0.5, 0.7, 0.9)

Traceback (most recent call last):
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/niworkflows/interfaces/plotting.py", line 118, in _run_interface
    varexp_thresh=self.inputs.variance_thresholds
  File "/home/miguellopez/anaconda3/lib/python3.6/site-packages/niworkflows/viz/plots.py", line 647, in compcor_variance_plot
    ax[m].text(varexp[thr][0], 25,
IndexError: invalid index to scalar variable.
```
Does someone know what could be the cause of the error? I think that the error is inside of an internal fmriprep function but I'm not totally sure.

Thank you very much for your time,
         Miguel

**Comment by oesteban** [comment]
Hey @rciric, any ideas? this seems a fairly easy problem to fix - just ensure that `varexp[thr]` is actually a list, correct?
