### ISSUE TITLE
Allowing re-use of freesurfer 6.0.0 <-> 6.0.1

### ISSUE THREAD

**Issue by alexlicohen** [poldracklab/fmriprep#1685]
Per here: [https://fmriprep.readthedocs.io/en/stable/workflows.html?highlight=freesurfer#surface-preprocessing](url)

Freesurfer outputs can be re-used; however fmriprep (appropriately) checks the build-stamp.txt to make sure they match. Since 6.0.0 to 6.0.1 was just to allow for the env_variable licensing, can we make this a flexible match? (many of the large datasets like the CMI-HBN are available with 6.0.0 outputs; allowing those to be used would save a lot of computational time (1500+ subjects)

Per the FS mailing list [https://mail.nmr.mgh.harvard.edu/pipermail//freesurfer/2018-December/059787.html](url):
> Hi Kirstie, sorry for the lack of documentation – there’s practically no
> difference between 6.0.0 and 6.0.1. The only update in 6.0.1 is the ability
> to point to an external license using the FS_LICENSE environment variable.

**Comment by effigies** [comment]
Hi @alexlicohen, reprocessing is based on the files found in the reconstruction directories, and not on any version check. A subject fully processed with 6.0.0 will not be further processed, except insofar as we add a `midthickness` surface for each hemisphere if it is missing.

**Comment by alexlicohen** [comment]
Hmmm, so will FS files in output/freesurfer be used if I add the:
`--fs-no-reconall` switch?

Without that, it crashes out when trying to run autorecon1 (b/c FS does do a version check...)

**Comment by effigies** [comment]
No, `--fs-no-reconall` skips over FreeSurfer entirely.

> Without that, it crashes out when trying to run autorecon1 (b/c FS does do a version check...)

Could you post the error? This surprises me.

**Comment by alexlicohen** [comment]
This is running HBN/Site-CBIC/sub-NDARAB348EWR, with their FS output:
`derivatives/fmriprep/sub-NDARAB348EWR/log/20190702-210427_c8fecc50-8851-416b-b676-2ad937224bf8/crash-20190702-211850-root-autorecon1-2d22612c-8acb-49c1-ae6a-78e469ad40b3.txt`

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 758, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 695, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
recon-all -autorecon1 -T2 /data/sub-NDARAB348EWR/anat/sub-NDARAB348EWR_acq-VNavNorm_T2w.nii.gz -noskullstrip -cw256 -hires -openmp 8 -subjid sub-NDARAB348EWR -sd /out/freesurfer -expert /tmp/work/fmriprep_wf/single_subject_NDARAB348EWR_wf/anat_preproc_wf/
surface_recon_wf/autorecon1/expert.opts 
Standard output:
INFO: hi-res volumes are conformed to the min voxel size
INFO: FreeSurfer build stamps do not match
Subject Stamp: 
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
INFO: SUBJECTS_DIR is /out/freesurfer
Actual FREESURFER_HOME /opt/freesurfer
Standard error:
cp: not writing through dangling symlink '/out/freesurfer/sub-NDARAB348EWR/scripts/build-stamp.txt'
cat: /out/freesurfer/sub-NDARAB348EWR/scripts/build-stamp.txt: No such file or directory
cp: not writing through dangling symlink '/out/freesurfer/sub-NDARAB348EWR/scripts/lastcall.build-stamp.txt'
/out/freesurfer/sub-NDARAB348EWR/scripts/recon-all.cmd: No such file or directory.
Return code: 1

Hmm... this may be due to using a symbolic link back to their files instead of moving them. Let me try it one more time; but I thought that I had this issue a few weeks ago with a different dataset.

**Comment by effigies** [comment]
It's attempting to run `recon-all -autorecon1 -T2 /data/sub-NDARAB348EWR/anat/sub-NDARAB348EWR_acq-VNavNorm_T2w.nii.gz -noskullstrip -cw256 -hires -openmp 8 -subjid sub-NDARAB348EWR -sd /out/freesurfer -expert /tmp/work/fmriprep_wf/single_subject_NDARAB348EWR_wf/anat_preproc_wf/
surface_recon_wf/autorecon1/expert.opts`

This would indicate that we're not detecting most of the completed files. For example, if we found `mri/nu.mgz`, then we would expect to see `-nonuintensitycor` in the command. It's pretty opaque, but [this data structure](https://github.com/nipy/nipype/blob/e722d6170593583f16ddfcb95473e5d30b5f1d7c/nipype/interfaces/freesurfer/preprocess.py#L954-L971) indicates the files that we look for.

This could result from a symlink issue, as well. A dangling symlink might be interpreted as a missing file. I'd have to check to be sure, but if you have `mri/nu.mgz` in your reconstructed subject directory, then that's very likely the case.

**Comment by alexlicohen** [comment]
Now with no symbolic links but still failing? Is this a version mismatch issue (why is it asking for 001.mgz when the FS results are already there?):

Node: fmriprep_wf.single_subject_NDARAB348EWR_wf.anat_preproc_wf.surface_recon_wf.autorecon1
Working directory: /tmp/work/fmriprep_wf/single_subject_NDARAB348EWR_wf/anat_preproc_wf/surface_recon_wf/autorecon1

Node inputs:

FLAIR_file = <undefined>
T1_files = ['/tmp/work/fmriprep_wf/single_subject_NDARAB348EWR_wf/anat_preproc_wf/anat_template_wf/t1_merge/sub-NDARAB348EWR_acq-HCP_run-01_T1w_template.nii.gz']
T2_file = /data/sub-NDARAB348EWR/anat/sub-NDARAB348EWR_acq-VNavNorm_T2w.nii.gz
args = <undefined>
big_ventricles = <undefined>
brainstem = <undefined>
directive = autorecon1
environ = {}
expert = <undefined>
flags = ['-noskullstrip', '-cw256']
hemi = <undefined>
hippocampal_subfields_T1 = <undefined>
hippocampal_subfields_T2 = <undefined>
hires = True
mprage = <undefined>
mri_aparc2aseg = <undefined>
mri_ca_label = <undefined>
mri_ca_normalize = <undefined>
mri_ca_register = <undefined>
mri_edit_wm_with_aseg = <undefined>
mri_em_register = <undefined>
mri_fill = <undefined>
mri_mask = <undefined>
mri_normalize = <undefined>
mri_pretess = <undefined>
mri_remove_neck = <undefined>
mri_segment = <undefined>
mri_segstats = <undefined>
mri_tessellate = <undefined>
mri_watershed = <undefined>
mris_anatomical_stats = <undefined>
mris_ca_label = <undefined>
mris_fix_topology = <undefined>
mris_inflate = -n 50
mris_make_surfaces = <undefined>
mris_register = <undefined>
mris_smooth = <undefined>
mris_sphere = <undefined>
mris_surf2vol = <undefined>
mrisp_paint = <undefined>
openmp = 8
parallel = <undefined>
subject_id = sub-NDARAB348EWR
subjects_dir = /out/freesurfer
talairach = <undefined>
use_FLAIR = <undefined>
use_T2 = <undefined>
xopts = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 758, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 695, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
recon-all -autorecon1 -T2 /data/sub-NDARAB348EWR/anat/sub-NDARAB348EWR_acq-VNavNorm_T2w.nii.gz -noskullstrip -cw256 -hires -openmp 8 -subjid sub-NDARAB348EWR -sd /out/freesurfer -expert /tmp/work/fmriprep_wf/single_subject_NDARAB348EWR_wf/anat_preproc_wf/
surface_recon_wf/autorecon1/expert.opts 
Standard output:
INFO: hi-res volumes are conformed to the min voxel size
INFO: FreeSurfer build stamps do not match
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
INFO: SUBJECTS_DIR is /out/freesurfer
Actual FREESURFER_HOME /opt/freesurfer
-rwxrwxrwx 1 4135 1003 555398 Jul  3 15:19 /out/freesurfer/sub-NDARAB348EWR/scripts/recon-all.log
Linux ee7b98d860de 3.10.0-957.21.2.el7.x86_64 #1 SMP Wed Jun 5 14:26:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
'/opt/freesurfer/bin/recon-all' -> '/out/freesurfer/sub-NDARAB348EWR/scripts/recon-all.local-copy'
-cw256 option is now persistent (remove with -clean-cw256)
#--------------------------------------------
#@# T2/FLAIR Input Wed Jul  3 17:17:01 UTC 2019
/out/freesurfer/sub-NDARAB348EWR

 mri_convert --no_scale 1 /data/sub-NDARAB348EWR/anat/sub-NDARAB348EWR_acq-VNavNorm_T2w.nii.gz /out/freesurfer/sub-NDARAB348EWR/mri/orig/T2raw.mgz 

mri_convert.bin --no_scale 1 /data/sub-NDARAB348EWR/anat/sub-NDARAB348EWR_acq-VNavNorm_T2w.nii.gz /out/freesurfer/sub-NDARAB348EWR/mri/orig/T2raw.mgz 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /data/sub-NDARAB348EWR/anat/sub-NDARAB348EWR_acq-VNavNorm_T2w.nii.gz...
TR=3200.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (0.998243, -0.0436063, 0.0401168)
j_ras = (0.0436415, 0.999047, 2.19496e-08)
k_ras = (-0.0400786, 0.00175073, 0.999195)
writing to /out/freesurfer/sub-NDARAB348EWR/mri/orig/T2raw.mgz...
#--------------------------------------------
#@# MotionCor Wed Jul  3 17:17:06 UTC 2019
ERROR: no run data found in /out/freesurfer/sub-NDARAB348EWR/mri. Make sure to
have a volume called 001.mgz in  /out/freesurfer/sub-NDARAB348EWR/mri/orig.
If you have a second run of data call it 002.mgz, etc.
See also: http://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/Conversion
Linux ee7b98d860de 3.10.0-957.21.2.el7.x86_64 #1 SMP Wed Jun 5 14:26:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-NDARAB348EWR exited with ERRORS at Wed Jul  3 17:17:06 UTC 2019

For more details, see the log file /out/freesurfer/sub-NDARAB348EWR/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Standard error:

Return code: 1

**Comment by effigies** [comment]
So I see a couple things here.

```
recon-all -autorecon1 \
    -T2 /data/sub-NDARAB348EWR/anat/sub-NDARAB348EWR_acq-VNavNorm_T2w.nii.gz \
    -noskullstrip -cw256 -hires -openmp 8 -subjid sub-NDARAB348EWR -sd /out/freesurfer \
    -expert /tmp/work/fmriprep_wf/single_subject_NDARAB348EWR_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts
```

First, the directory obviously exists, and correspondingly there is no `-i` flag. Nipype uses the existence of the directory to indicate that all T1w images have already been imported and does not try to re-import, as FreeSurfer doesn't do any comparisons automatically, and would thus just keep adding a new `00<X>.mgz` file every time you tried to remove.

It looks like `001.mgz` is not present, so either `recon-all -i <T1w>` was never run, or the file was deleted later.

Then there's the absence of any `-no` flags (except `-noskullstrip`, which we add ourselves) indicating that the expected outputs of those steps are not present.

At least on its face, it looks like `recon-all` has not been run, or many of the early stage contents have been removed, which is causing an abortive attempt to rerun. If this was done in a space-saving effort, then we will probably need to write a special interface to identify whether all of the necessary outputs are present. Off the top of my head, I think we directly use at some point:

```
sub-<label>/
  mri/
    T1.mgz
  surf/
    lh.pial
    lh.smoothwm
    lh.sphere
    lh.white
    rh.pial
    rh.smoothwm
    rh.sphere
    rh.white
```

In addition we'll need whatever transforms are needed for registration to `fsaverage`.

**Comment by alexlicohen** [comment]
To help track this down, here is what the HBN is distributing:
[http://fcon_1000.projects.nitrc.org/indi/cmi_healthy_brain_network/sharing_neuro.html](url)

`HBN/Site-CBIC/derivatives/sub-NDARYA955CY1/T1w_HCP_run-01/freesurfer`:

```
.
├── [ 30M]  label
│   ├── [4.0K]  aparc.annot.a2009s.ctab
│   ├── [1.9K]  aparc.annot.ctab
│   ├── [1.9K]  aparc.annot.DKTatlas.ctab
│   ├── [ 810]  BA_exvivo.ctab
│   ├── [ 810]  BA_exvivo.thresh.ctab
│   ├── [1.1M]  lh.aparc.a2009s.annot
│   ├── [1.1M]  lh.aparc.annot
│   ├── [1.1M]  lh.aparc.DKTatlas.annot
│   ├── [148K]  lh.BA1_exvivo.label
│   ├── [ 36K]  lh.BA1_exvivo.thresh.label
│   ├── [267K]  lh.BA2_exvivo.label
│   ├── [ 74K]  lh.BA2_exvivo.thresh.label
│   ├── [116K]  lh.BA3a_exvivo.label
│   ├── [ 41K]  lh.BA3a_exvivo.thresh.label
│   ├── [196K]  lh.BA3b_exvivo.label
│   ├── [ 65K]  lh.BA3b_exvivo.thresh.label
│   ├── [129K]  lh.BA44_exvivo.label
│   ├── [ 57K]  lh.BA44_exvivo.thresh.label
│   ├── [146K]  lh.BA45_exvivo.label
│   ├── [ 55K]  lh.BA45_exvivo.thresh.label
│   ├── [185K]  lh.BA4a_exvivo.label
│   ├── [ 77K]  lh.BA4a_exvivo.thresh.label
│   ├── [126K]  lh.BA4p_exvivo.label
│   ├── [ 46K]  lh.BA4p_exvivo.thresh.label
│   ├── [453K]  lh.BA6_exvivo.label
│   ├── [231K]  lh.BA6_exvivo.thresh.label
│   ├── [1.1M]  lh.BA_exvivo.annot
│   ├── [1.1M]  lh.BA_exvivo.thresh.annot
│   ├── [5.7M]  lh.cortex.label
│   ├── [ 53K]  lh.entorhinal_exvivo.label
│   ├── [ 20K]  lh.entorhinal_exvivo.thresh.label
│   ├── [117K]  lh.MT_exvivo.label
│   ├── [ 30K]  lh.MT_exvivo.thresh.label
│   ├── [ 54K]  lh.perirhinal_exvivo.label
│   ├── [ 22K]  lh.perirhinal_exvivo.thresh.label
│   ├── [252K]  lh.V1_exvivo.label
│   ├── [183K]  lh.V1_exvivo.thresh.label
│   ├── [467K]  lh.V2_exvivo.label
│   ├── [199K]  lh.V2_exvivo.thresh.label
│   ├── [1.1M]  rh.aparc.a2009s.annot
│   ├── [1.1M]  rh.aparc.annot
│   ├── [1.1M]  rh.aparc.DKTatlas.annot
│   ├── [140K]  rh.BA1_exvivo.label
│   ├── [ 31K]  rh.BA1_exvivo.thresh.label
│   ├── [232K]  rh.BA2_exvivo.label
│   ├── [ 97K]  rh.BA2_exvivo.thresh.label
│   ├── [112K]  rh.BA3a_exvivo.label
│   ├── [ 49K]  rh.BA3a_exvivo.thresh.label
│   ├── [137K]  rh.BA3b_exvivo.label
│   ├── [ 65K]  rh.BA3b_exvivo.thresh.label
│   ├── [203K]  rh.BA44_exvivo.label
│   ├── [ 32K]  rh.BA44_exvivo.thresh.label
│   ├── [182K]  rh.BA45_exvivo.label
│   ├── [ 40K]  rh.BA45_exvivo.thresh.label
│   ├── [188K]  rh.BA4a_exvivo.label
│   ├── [ 49K]  rh.BA4a_exvivo.thresh.label
│   ├── [137K]  rh.BA4p_exvivo.label
│   ├── [ 45K]  rh.BA4p_exvivo.thresh.label
│   ├── [409K]  rh.BA6_exvivo.label
│   ├── [233K]  rh.BA6_exvivo.thresh.label
│   ├── [1.1M]  rh.BA_exvivo.annot
│   ├── [1.1M]  rh.BA_exvivo.thresh.annot
│   ├── [5.6M]  rh.cortex.label
│   ├── [ 48K]  rh.entorhinal_exvivo.label
│   ├── [ 33K]  rh.entorhinal_exvivo.thresh.label
│   ├── [ 95K]  rh.MT_exvivo.label
│   ├── [ 14K]  rh.MT_exvivo.thresh.label
│   ├── [ 33K]  rh.perirhinal_exvivo.label
│   ├── [ 15K]  rh.perirhinal_exvivo.thresh.label
│   ├── [276K]  rh.V1_exvivo.label
│   ├── [188K]  rh.V1_exvivo.thresh.label
│   ├── [478K]  rh.V2_exvivo.label
│   └── [217K]  rh.V2_exvivo.thresh.label
├── [ 43M]  mri
│   ├── [439K]  aparc.a2009s+aseg.mgz
│   ├── [401K]  aparc+aseg.mgz
│   ├── [399K]  aparc.DKTatlas+aseg.mgz
│   ├── [215K]  aseg.auto.mgz
│   ├── [1.5K]  aseg.auto_noCCseg.label_intensities.txt
│   ├── [214K]  aseg.auto_noCCseg.mgz
│   ├── [337K]  aseg.mgz
│   ├── [215K]  aseg.presurf.hypos.mgz
│   ├── [215K]  aseg.presurf.mgz
│   ├── [1.3M]  brain.finalsurfs.mgz
│   ├── [1.3M]  brainmask.auto.mgz
│   ├── [1.3M]  brainmask.mgz
│   ├── [1.3M]  brain.mgz
│   ├── [546K]  ctrl_pts.mgz
│   ├── [132K]  filled.mgz
│   ├── [112K]  lh.ribbon.mgz
│   ├── [ 11K]  mri_nu_correct.mni.log
│   ├── [6.3K]  mri_nu_correct.mni.log.bak
│   ├── [1.4M]  norm.mgz
│   ├── [112K]  rh.ribbon.mgz
│   ├── [211K]  ribbon.mgz
│   ├── [ 120]  segment.dat
│   ├── [1.5K]  talairach.label_intensities.txt
│   ├── [ 214]  talairach.log
│   ├── [ 214]  talairach_with_skull.log
│   ├── [ 31M]  transforms
│   │   ├── [1.7K]  cc_up.lta
│   │   ├── [ 193]  talairach.auto.xfm
│   │   ├── [1.5K]  talairach.auto.xfm.lta
│   │   ├── [ 87K]  talairach_avi.log
│   │   ├── [  92]  talairach_avi_QA.log
│   │   ├── [1.5K]  talairach.lta
│   │   ├── [ 31M]  talairach.m3z
│   │   ├── [1.5K]  talairach_with_skull.lta
│   │   ├── [ 193]  talairach.xfm
│   │   └── [ 353]  talsrcimg_to_711-2C_as_mni_average_305_t4_vox2vox.txt
│   ├── [392K]  wm.asegedit.mgz
│   ├── [393K]  wm.mgz
│   ├── [448K]  wmparc.mgz
│   └── [427K]  wm.seg.mgz
├── [862K]  scripts
│   ├── [  58]  build-stamp.txt
│   ├── [ 337]  IsRunning.lh+rh
│   ├── [  58]  lastcall.build-stamp.txt
│   ├── [   1]  patchdir.txt
│   ├── [ 451]  pctsurfcon.log
│   ├── [ 451]  pctsurfcon.log.old
│   ├── [ 208]  ponscc.cut.log
│   ├── [ 37K]  recon-all.cmd
│   ├── [ 570]  recon-all.done
│   ├── [1.9K]  recon-all.env
│   ├── [320K]  recon-all.local-copy
│   ├── [493K]  recon-all.log
│   └── [3.7K]  recon-all-status.log
├── [147K]  stats
│   ├── [9.6K]  aseg.stats
│   ├── [ 11K]  lh.aparc.a2009s.stats
│   ├── [6.2K]  lh.aparc.DKTatlas.stats
│   ├── [6.5K]  lh.aparc.pial.stats
│   ├── [6.5K]  lh.aparc.stats
│   ├── [4.3K]  lh.BA_exvivo.stats
│   ├── [4.3K]  lh.BA_exvivo.thresh.stats
│   ├── [ 16K]  lh.curv.stats
│   ├── [6.6K]  lh.w-g.pct.stats
│   ├── [ 11K]  rh.aparc.a2009s.stats
│   ├── [6.2K]  rh.aparc.DKTatlas.stats
│   ├── [6.5K]  rh.aparc.pial.stats
│   ├── [6.5K]  rh.aparc.stats
│   ├── [4.3K]  rh.BA_exvivo.stats
│   ├── [4.3K]  rh.BA_exvivo.thresh.stats
│   ├── [ 16K]  rh.curv.stats
│   ├── [6.6K]  rh.w-g.pct.stats
│   └── [ 11K]  wmparc.stats
├── [148M]  surf
│   ├── [556K]  lh.area
│   ├── [556K]  lh.area.mid
│   ├── [556K]  lh.area.pial
│   ├── [556K]  lh.avg_curv
│   ├── [556K]  lh.curv
│   ├── [556K]  lh.curv.pial
│   ├── [566K]  lh.defect_borders
│   ├── [566K]  lh.defect_chull
│   ├── [566K]  lh.defect_labels
│   ├── [4.9M]  lh.inflated
│   ├── [556K]  lh.inflated.H
│   ├── [556K]  lh.inflated.K
│   ├── [5.0M]  lh.inflated.nofix
│   ├── [556K]  lh.jacobian_white
│   ├── [4.9M]  lh.orig
│   ├── [5.0M]  lh.orig.nofix
│   ├── [4.9M]  lh.pial
│   ├── [5.0M]  lh.qsphere.nofix
│   ├── [4.9M]  lh.smoothwm
│   ├── [556K]  lh.smoothwm.BE.crv
│   ├── [556K]  lh.smoothwm.C.crv
│   ├── [556K]  lh.smoothwm.FI.crv
│   ├── [556K]  lh.smoothwm.H.crv
│   ├── [556K]  lh.smoothwm.K1.crv
│   ├── [556K]  lh.smoothwm.K2.crv
│   ├── [556K]  lh.smoothwm.K.crv
│   ├── [5.0M]  lh.smoothwm.nofix
│   ├── [556K]  lh.smoothwm.S.crv
│   ├── [4.9M]  lh.sphere
│   ├── [4.9M]  lh.sphere.reg
│   ├── [556K]  lh.sulc
│   ├── [556K]  lh.thickness
│   ├── [556K]  lh.volume
│   ├── [569K]  lh.w-g.pct.mgh
│   ├── [4.9M]  lh.white
│   ├── [556K]  lh.white.H
│   ├── [556K]  lh.white.K
│   ├── [4.9M]  lh.white.preaparc
│   ├── [556K]  lh.white.preaparc.H
│   ├── [556K]  lh.white.preaparc.K
│   ├── [555K]  rh.area
│   ├── [555K]  rh.area.mid
│   ├── [555K]  rh.area.pial
│   ├── [555K]  rh.avg_curv
│   ├── [555K]  rh.curv
│   ├── [555K]  rh.curv.pial
│   ├── [565K]  rh.defect_borders
│   ├── [565K]  rh.defect_chull
│   ├── [565K]  rh.defect_labels
│   ├── [4.9M]  rh.inflated
│   ├── [555K]  rh.inflated.H
│   ├── [555K]  rh.inflated.K
│   ├── [5.0M]  rh.inflated.nofix
│   ├── [555K]  rh.jacobian_white
│   ├── [4.9M]  rh.orig
│   ├── [5.0M]  rh.orig.nofix
│   ├── [4.9M]  rh.pial
│   ├── [5.0M]  rh.qsphere.nofix
│   ├── [4.9M]  rh.smoothwm
│   ├── [555K]  rh.smoothwm.BE.crv
│   ├── [555K]  rh.smoothwm.C.crv
│   ├── [555K]  rh.smoothwm.FI.crv
│   ├── [555K]  rh.smoothwm.H.crv
│   ├── [555K]  rh.smoothwm.K1.crv
│   ├── [555K]  rh.smoothwm.K2.crv
│   ├── [555K]  rh.smoothwm.K.crv
│   ├── [5.0M]  rh.smoothwm.nofix
│   ├── [555K]  rh.smoothwm.S.crv
│   ├── [4.9M]  rh.sphere
│   ├── [4.9M]  rh.sphere.reg
│   ├── [555K]  rh.sulc
│   ├── [555K]  rh.thickness
│   ├── [555K]  rh.volume
│   ├── [568K]  rh.w-g.pct.mgh
│   ├── [4.9M]  rh.white
│   ├── [555K]  rh.white.H
│   ├── [555K]  rh.white.K
│   ├── [4.9M]  rh.white.preaparc
│   ├── [555K]  rh.white.preaparc.H
│   └── [555K]  rh.white.preaparc.K
└── [ 21K]  touch
    ├── [ 231]  aparc.a2009s2aseg.touch
    ├── [ 277]  aparc.DKTatlas2aseg.touch
    ├── [  42]  apas2aseg.touch
    ├── [  34]  asegmerge.touch
    ├── [ 179]  ca_label.touch
    ├── [ 146]  ca_normalize.touch
    ├── [ 299]  ca_register.touch
    ├── [ 206]  conform.touch
    ├── [ 161]  cortical_ribbon.touch
    ├── [ 246]  em_register.touch
    ├── [ 124]  fill.touch
    ├── [  41]  inorm1.touch
    ├── [  84]  inorm2.touch
    ├── [ 236]  lh.aparc2.touch
    ├── [ 200]  lh.aparcstats2.touch
    ├── [ 206]  lh.aparcstats3.touch
    ├── [ 183]  lh.aparcstats.touch
    ├── [ 226]  lh.aparc.touch
    ├── [ 136]  lh.avgcurv.touch
    ├── [ 119]  lh.curvstats.touch
    ├── [ 146]  lh.final_surfaces.touch
    ├── [  79]  lh.inflate1.touch
    ├── [ 172]  lh.inflate2.touch
    ├── [  68]  lh.inflate.H.K.touch
    ├── [  88]  lh.jacobian_white.touch
    ├── [  44]  lh.pctsurfcon.touch
    ├── [ 146]  lh.pial_surface.touch
    ├── [  77]  lh.qsphere.touch
    ├── [  75]  lh.smoothwm1.touch
    ├── [  78]  lh.smoothwm2.touch
    ├── [ 179]  lh.sphmorph.touch
    ├── [ 255]  lh.sphreg.touch
    ├── [  44]  lh.surfvolume.touch
    ├── [  72]  lh.tessellate.touch
    ├── [  23]  lh.topofix.touch
    ├── [  36]  lh.white.H.K.touch
    ├── [ 135]  lh.white_surface.touch
    ├── [  29]  nu.touch
    ├── [  76]  relabelhypos.touch
    ├── [ 236]  rh.aparc2.touch
    ├── [ 200]  rh.aparcstats2.touch
    ├── [ 206]  rh.aparcstats3.touch
    ├── [ 183]  rh.aparcstats.touch
    ├── [ 226]  rh.aparc.touch
    ├── [ 136]  rh.avgcurv.touch
    ├── [ 119]  rh.curvstats.touch
    ├── [ 146]  rh.final_surfaces.touch
    ├── [  79]  rh.inflate1.touch
    ├── [ 172]  rh.inflate2.touch
    ├── [  68]  rh.inflate.H.K.touch
    ├── [  88]  rh.jacobian_white.touch
    ├── [  44]  rh.pctsurfcon.touch
    ├── [ 146]  rh.pial_surface.touch
    ├── [  77]  rh.qsphere.touch
    ├── [  75]  rh.smoothwm1.touch
    ├── [  78]  rh.smoothwm2.touch
    ├── [ 179]  rh.sphmorph.touch
    ├── [ 255]  rh.sphreg.touch
    ├── [  44]  rh.surfvolume.touch
    ├── [  72]  rh.tessellate.touch
    ├── [  23]  rh.topofix.touch
    ├── [  36]  rh.white.H.K.touch
    ├── [ 135]  rh.white_surface.touch
    ├── [ 271]  rusage.mri_ca_register.dat
    ├── [ 271]  rusage.mri_em_register.dat
    ├── [ 271]  rusage.mri_em_register.skull.dat
    ├── [ 264]  rusage.mris_fix_topology.lh.dat
    ├── [ 262]  rusage.mris_fix_topology.rh.dat
    ├── [ 261]  rusage.mris_inflate.lh.dat
    ├── [ 259]  rusage.mris_inflate.rh.dat
    ├── [ 268]  rusage.mris_register.lh.dat
    ├── [ 270]  rusage.mris_register.rh.dat
    ├── [ 264]  rusage.mris_sphere.lh.dat
    ├── [ 264]  rusage.mris_sphere.rh.dat
    ├── [ 262]  rusage.mri_watershed.dat
    ├── [ 379]  segstats.touch
    ├── [ 253]  skull.lta.touch
    ├── [ 272]  skull_strip.touch
    ├── [  58]  talairach.touch
    ├── [ 280]  wmaparc.stats.touch
    ├── [ 128]  wmaparc.touch
    └── [  47]  wmsegment.touch

 221M used in 7 directories, 305 files
```

**Comment by effigies** [comment]
Yeah, this is definitely not a normal FreeSurfer directory. If we want to use this, we'll need to be able to identify it to avoid re-running FreeSurfer, and also identify a T1w image that we can use as a registration target to ensure that any discrepancies between that and the BIDS T1w.nii.gz are accounted for. I can't quickly find any description of their surface processing, and the paper doesn't mention "surface" or "FreeSurfer".

**Comment by alexlicohen** [comment]
They distribute FS, mind boggle, and ANTs output for each of the T1s they obtained, a strategy for saving space probably became necessary (they’re scaring up to 10k subjects). Let me loop them into this conversation and see if they can share what they did, so the end-user can potentially undo it or compensate.

**Comment by effigies** [comment]
We definitely need the `T1.mgz`, which is almost certainly what they removed. However, if they're distributing the defaced `T1w.nii.gz` (and there's only one...) in the BIDS data, then you should be able to re-run `-autorecon1`:

```
recon-all -sd <subject_dir> -s <subject> -i <defaced-t1>
recon-all -sd <subject_dir> -s <subject> -autorecon1 -noskullstrip
```

The list of files we check for are those listed at https://surfer.nmr.mgh.harvard.edu/fswiki/ReconAllTableStableV6.0. They are encoded in [this section](https://github.com/nipy/nipype/blob/e722d6170593583f16ddfcb95473e5d30b5f1d7c/nipype/interfaces/freesurfer/preprocess.py#L954-L1122) of Nipype.

I would see if re-creating T1.mgz is correctly aligned with the surfaces in FreeView, and then see if fMRIPrep interprets the directories as fully run.

It's possible that the modification time (`mtime`) checks will cause it to attempt to rerun all steps, so if that doesn't work on the first try, I would `touch -mt` the newly created files with a sufficiently old `mtime` and try again.

If that doesn't work, it probably makes sense to think about an alternative interface to `ReconAll` that will simply check that the files we need exist. As noted above, the full list of files we need is (likely):

```
sub-<label>/
  mri/
    T1.mgz
  surf/
    lh.pial
    lh.smoothwm
    lh.sphere
    lh.sphere.reg
    lh.white
    rh.pial
    rh.smoothwm
    rh.sphere
    rh.sphere.reg
    rh.white
```

I added `*.sphere.reg`, which I believe is the file needed for transforming between surfaces.

**Comment by alexlicohen** [comment]
Thanks Chris,
I will try just remaking the T1.mgz and see what happens.
