### ISSUE TITLE
indexed_gzip ZranError -3

### ISSUE THREAD

**Issue by sciencecasey** [poldracklab/fmriprep#1717]
File "indexed_gzip/indexed_gzip.pyx", line 554, in indexed_gzip.indexed_gzip._IndexedGzipFile.readinto
indexed_gzip.indexed_gzip.ZranError: zran_read returned error (-3)

The Full Output::
RUNNING: docker run --rm -it -e DOCKER_VERSION_8395080871=18.09.2 -v /Users/casey/Desktop/working_folder/BIDs_format_fmriprep-master/license.txt:/opt/freesurfer/license.txt:ro -v /Users/casey/Desktop/working_folder/bids_structure_practice/nifti/BDD:/data:ro -v /Users/casey/Desktop/working_folder/bids_structure_practice/derivatives:/out -v /Users/casey/Desktop/working_folder/bids_structure_practice/nifti/BDD/scratch:/scratch poldracklab/fmriprep:1.4.1 /data /out participant --use-syn-sdc --use-aroma --participant_label 10001 -w /scratch
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
	1: [ERR] This file ends in the .gz extension but is not actually gzipped. (code: 28 - GZ_NOT_GZIPPED)
		./sub-10001/anat/sub-10001_T1w.nii.gz
		./sub-10001/func/sub-10001_task-FASTRISS_bold.nii.gz
		./sub-10001/func/sub-10001_task-VISMOD1Nat_bold.nii.gz
		./sub-10001/func/sub-10001_task-VISMOD2VM_bold.nii.gz
		./sub-10001/func/sub-10001_task-VISMOD3Nat_bold.nii.gz
		./sub-10001/func/sub-10001_task-VISNat_bold.nii.gz

	Please visit https://neurostars.org/search?q=GZ_NOT_GZIPPED for existing conversations about this issue.

	1: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

	Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.

        Summary:                Available Tasks:        Available Modalities: 
        12 Files, 1.96GB        FASTRISS                T1w                   
        1 - Subject             VISMOD1Nat              bold                  
        1 - Session                                                           

	If you have any questions, please post on https://neurostars.org/tags/bids.

Although ``--fs-no-reconall`` was not set (i.e., FreeSurfer is to be run), no FreeSurfer output space (valid values are: fsnative, fsaverage, fsaverage5, fsaverage6) was selected. Adding default "fsaverage5" to the list of output spaces.
Option "--use-aroma" requires functional images to be resampled to MNI152NLin6Asym space. The argument "MNI152NLin6Asym:res-2" has been automatically added to the list of output spaces (option ``--output-spaces``).
190725-21:17:14,700 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.4.1:
      * BIDS dataset path: /data.
      * Participant list: ['10001'].
      * Run identifier: 20190725-211714_e64faf53-b0ba-4d23-87fc-d6b96464bbda.
    
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 610, in build_workflow
    work_dir=str(work_dir),
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 259, in init_fmriprep_wf
    use_syn=use_syn,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 609, in init_single_subject_wf
    use_syn=use_syn,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 289, in init_func_preproc_wf
    bold_tlen, mem_gb = _create_mem_gb(ref_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 972, in _create_mem_gb
    bold_tlen = nb.load(bold_fname).shape[-1]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/loadsave.py", line 47, in load
    is_valid, sniff = image_klass.path_maybe_image(filename, sniff)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/filebasedimages.py", line 510, in path_maybe_image
    sniff)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/filebasedimages.py", line 458, in _sniff_meta_for
    binaryblock = fobj.read(sniff_nbytes)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/openers.py", line 214, in read
    return self.fobj.read(*args, **kwargs)
  File "indexed_gzip/indexed_gzip.pyx", line 554, in indexed_gzip.indexed_gzip._IndexedGzipFile.readinto
indexed_gzip.indexed_gzip.ZranError: zran_read returned error (-3)

**Comment by oesteban** [comment]
As per the beginning of your traceback:

```
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
1: [ERR] This file ends in the .gz extension but is not actually gzipped. (code: 28 - GZ_NOT_GZIPPED)
./sub-10001/anat/sub-10001_T1w.nii.gz
./sub-10001/func/sub-10001_task-FASTRISS_bold.nii.gz
./sub-10001/func/sub-10001_task-VISMOD1Nat_bold.nii.gz
./sub-10001/func/sub-10001_task-VISMOD2VM_bold.nii.gz
./sub-10001/func/sub-10001_task-VISMOD3Nat_bold.nii.gz
./sub-10001/func/sub-10001_task-VISNat_bold.nii.gz
```

The BIDS validator is telling you that some files have the .gz extension but are not compressed. Please fix that before you run fmriprep.
