### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: .... unfinished.json

### ISSUE THREAD

**Issue by dmd** [poldracklab/fmriprep#1780]
In 1.5.0, I'm getting:

```
$ cat /data/ddrucker/testing/derivatives/fmriprep/sub-acj/log/20190917-102450_234554e0-3572-4773-9070-09ebb07bea01/crash-20190917-103025-ddrucker-bids_info-5eccfd72-fb37-442c-82d0-d2127cde5582.txt
Node: fmriprep_wf.single_subject_acj_wf.bids_info
Working directory: /data/ddrucker/testing/fmriprep-work/fmriprep_wf/single_subject_acj_wf/bids_info

Node inputs:

bids_dir = /data/ddrucker/testing
bids_validate = False
in_file = /data/ddrucker/testing/sub-acj/anat/sub-acj_T1w.nii.gz

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 649, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 376, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/bids.py", line 165, in _run_interface
    self.inputs.bids_validate)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/bids.py", line 213, in _init_layout
    layout = BIDSLayout(str(bids_dir), validate=validate)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 212, in __init__
    indexer.index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 207, in index_metadata
    with open(bf.path, 'r') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/data/ddrucker/testing/fmriprep-work/fmriprep_wf/single_subject_acj_wf/func_preproc_task_cue_wf/bold_split/_0xca3dc0d25055795133385b837b4d35b0_unfinished.json'
```

What should I do?

My command was:

```
export SINGULARITYENV_https_proxy=http://micc:8899
export SINGULARITYENV_TEMPLATEFLOW_HOME=/data/TemplateFlow
/cm/shared/singularity/bin/singularity run \
    -B /data:/data -B /data1:/data1 -B /data2:/data2 -B /data3:/data3 -B /cm/shared:/cm/shared \
    -B /data/TemplateFlow:/data/TemplateFlow \
    -B $HOME/.cache:/home/fmriprep/.cache \
    --cleanenv \
    /cm/shared/singularity/images/fmriprep-1.5.0.simg \
    /data/ddrucker/testing \
    /data/ddrucker/testing/derivatives \
    participant \
    --fs-license-file /cm/shared/freesurfer-6.0.1/license.txt \
    --participant_label acj \
    --output-spaces "MNI152NLin2009cAsym:res-2 anat func fsaverage" \
    --n_cpus 4 \
    --mem-mb 8192 \
    --notrack \
    --use-plugin /data/ddrucker/workaround.yml \
    --use-aroma --ignore-aroma-denoising-errors \
    --use-syn-sdc \
    -w  /data/ddrucker/testing/fmriprep-work
```

**Comment by effigies** [comment]
Oh, I'm pretty sure this is a result of keeping your working directory inside your data directory again. This is occurring when trying to index your input data, and it's finding JSON files inside your working directory.

**Comment by dmd** [comment]
Ah, ok. I'll make sure that's not our default.

**Comment by dmd** [comment]
For others' reference, this is a dupe of #1760
