### ISSUE TITLE
Tries to consider sourcedata/ (for T1s)

### ISSUE THREAD

**Issue by yarikoptic** [poldracklab/fmriprep#1787]
Might be reincarnation of #1178

I am trying to make fmriprep work on [///labs/haxby/life](http://datasets.datalad.org/?dir=/labs/haxby/life) dataset.  With 1.4.1 I had another (I think) issue so moved on to 1.5.0.

Here is a full recipe (just BYOFL -- bring your own freesurfer license):
```shell
$> cat ./replicate-fmriprepkaboom.sh
#!/bin/bash
set -eu
datalad install ///labs/haxby/life
cd life
datalad install -d . ///repronim/containers  # to get fmriprep, execution in isolation etc
datalad get containers/images/bids/bids-fmriprep--1.5.0.sing
datalad get sub-rid000001  # one subject to start with
cp ${FREESURFER_HOME}/.license containers/licenses/freesurfer

mkdir -p derivatives/{work,fmriprep-1.5.0}
# manual execution to ease troubleshooting
#  --skip-bids-validation  since we did not get/process all the subjects, and 
#   https://github.com/bids-standard/bids-validator/issues/769 still scares me a lot ;)
containers/scripts/singularity_cmd run containers/images/bids/bids-fmriprep--1.5.0.sing . 'derivatives/fmriprep-1.5.0/' participant --skip-bids-validation --participant-label 'rid000001' -w derivatives/work --notrack --skull-strip-fixed-seed --ignore slicetiming --fs-license-file=containers/licenses/freesurfer --bold2t1w-dof 9 --output-space fsnative fsaverage fsaverage6 fsaverage5 T1w template --n_cpus 2 --nthreads 2 --omp-nthreads 1

```

<details>
<summary>running which results in (click to expand)</summary>

```
...
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 541, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 279, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 400, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_types.py", line 2336, in validate
    return TraitListObject( self, object, name, value )
  
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2313, in __init__
    raise excp
  
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2305, in __init__
    value = [ validate( object, name, val ) for val in value ]
  
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2305, in <listcomp>
    value = [ validate( object, name, val ) for val in value ]
  
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 317, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 141, in validate
    self.error(objekt, name, str(value))

  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )

traits.trait_errors.TraitError: Each element of the 't1w_list' trait of a TemplateDimensionsInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/mnt/scrap/tmp/life/sourcedata/sub-rid000001/anat/sub-rid000001_T1w.nii.gz' <class 'str'> was specified.

Error setting node input:
Node: t1_template_dimensions
input: t1w_list
results_file: /mnt/scrap/tmp/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/bidssrc/result_bidssrc.pklz
value: ['/mnt/scrap/tmp/life/sourcedata/sub-rid000001/anat/sub-rid000001_T1w.nii.gz', '/mnt/scrap/tmp/life/sub-rid000001/anat/sub-rid000001_T1w.nii.gz']

190925-03:01:25,165 nipype.workflow INFO:
         [Node] Setting-up "fmriprep_wf.single_subject_rid000001_wf.anat_preproc_wf.anat_template_wf.t1_template_dimensions" in "/mnt/scrap/tmp/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/anat_preproc_wf/anat_template_wf/t1_template_dimensions".
190925-03:01:26,981 nipype.workflow ERROR:
         Node t1_template_dimensions failed to run on host smaug.
190925-03:01:26,983 nipype.workflow ERROR:
         Saving crash info to /mnt/scrap/tmp/life/derivatives/fmriprep-1.5.0/fmriprep/sub-rid000001/log/20190925-022748_b465aee2-674d-4451-ada6-7267be8fa73d/crash-20190925-030126-yoh-t1_template_dimensions-50934f1e-a11d-4b52-b669-6d68e817b4fb.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 411, in run
    cached, updated = self.is_cached()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 297, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 494, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 541, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 279, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 400, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_types.py", line 2336, in validate
    return TraitListObject( self, object, name, value )
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2313, in __init__
    raise excp
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2305, in __init__
    value = [ validate( object, name, val ) for val in value ]
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2305, in <listcomp>
    value = [ validate( object, name, val ) for val in value ]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 317, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 141, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: Each element of the 't1w_list' trait of a TemplateDimensionsInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/mnt/scrap/tmp/life/sourcedata/sub-rid000001/anat/sub-rid000001_T1w.nii.gz' <class 'str'> was specified.

Error setting node input:
Node: t1_template_dimensions
input: t1w_list
results_file: /mnt/scrap/tmp/life/derivatives/work/fmriprep_wf/single_subject_rid000001_wf/bidssrc/result_bidssrc.pklz
value: ['/mnt/scrap/tmp/life/sourcedata/sub-rid000001/anat/sub-rid000001_T1w.nii.gz', '/mnt/scrap/tmp/life/sub-rid000001/anat/sub-rid000001_T1w.nii.gz']
```
</details>

with the error 
```
traits.trait_errors.TraitError: Each element of the 't1w_list' trait of a TemplateDimensionsInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/mnt/scrap/tmp/life/sourcedata/sub-rid000001/anat/sub-rid000001_T1w.nii.gz' <class 'str'> was specified.
```
hinting on it looking into `sourcedata/` which it shouldn't do IMHO.

well, the dataset has some IMHO minor BIDS noncompliances such as 
```
        3: [ERR] Sub label contain an Illegal Character hyphen or underscore. Please edit the filename as per BIDS spec. (code: 62 - SUBJECT_VALUE_CONTAINS_ILLEGAL_CHARACTER)
                ./sub-rid000001/anat/sub-rid000001_T1w_defacemask.nii.gz
                        Evidence: sub name contains illegal character:/sub-rid000001/anat/sub-rid000001_T1w_defacemask.nii.gz
```
which I will fix up later, but I think that should be unrelated

Meanwhile I will fix the defacemask naming and add sourcedata to bidsignore and see how it goes

**Comment by yarikoptic** [comment]
FWIW, adding sourcedata to .bidsignore had no (positive) effect. Next step -- `git rm sourcedata`

**Comment by effigies** [comment]
No, pybids doesn't respect `.bidsignore`.

I think this will be resolved with an upgrade to the latest pybids, which restored (bids-standard/pybids#495) the default ignores (they got lost somewhere), or manually adding in the default ignores.

Given poldracklab/niworkflows#404, we should probably manually add for now.
