### ISSUE TITLE
Non-reliable plotting functions in ICA-AROMA

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1833]
The addition of plots in ICA-AROMA 4.4.0-beta has made it more prone to fail at that point. I've seen several types of error, generally at some point of the kernel density estimation of seaborn.

About 2/3 of ds000114 subjects (e.g., sub-02) on TACC with 1.5.1rc1 gave me:

```
Node: fmriprep_wf.single_subject_02_wf.func_preproc_ses_test_task_overtwordrepetition_wf.ica_aroma_wf.ica_aroma
Working directory: /scratch/03763/oesteban/fmriprep-work/ds114-sub-02/fmriprep_wf/single_subject_02_wf/func_preproc_ses_test_task_overtwordrepetition_wf/ica_aroma_wf/ica_aroma

Node inputs:

TR = 5.0
args = <undefined>
compress_report = auto
denoise_type = nonaggr
dim = <undefined>
environ = {}
feat_dir = <undefined>
fnirt_warp_file = <undefined>
in_file = <undefined>
mask = <undefined>
mat_file = <undefined>
melodic_dir = <undefined>
motion_parameters = <undefined>
out_dir = out
out_report = ica_aroma_reportlet.svg
report_mask = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 569, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 662, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 382, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 767, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 704, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
ICA_AROMA.py -tr 5.000 -den nonaggr -i /scratch/03763/oesteban/fmriprep-work/ds114-sub-02/fmriprep_wf/single_subject_02_wf/func_preproc_ses_test_task_overtwordrepetition_wf/ica_aroma_wf/smooth/vol0000_xform-00000_merged_cut_smooth.nii.gz -m /scratch/03763/oesteban/fmriprep-work/ds114-sub-02/fmriprep_wf/single_subject_02_wf/func_preproc_ses_test_task_overtwordrepetition_wf/bold_std_trans_wf/_key_MNI152NLin6Asym/mask_std_tfm/ref_bold_corrected_brain_mask_maths_trans.nii.gz -meldir /scratch/03763/oesteban/fmriprep-work/ds114-sub-02/fmriprep_wf/single_subject_02_wf/func_preproc_ses_test_task_overtwordrepetition_wf/ica_aroma_wf/melodic -mc /scratch/03763/oesteban/fmriprep-work/ds114-sub-02/fmriprep_wf/single_subject_02_wf/func_preproc_ses_test_task_overtwordrepetition_wf/bold_hmc_wf/normalize_motion/motion_params.txt -o /scratch/03763/oesteban/fmriprep-work/ds114-sub-02/fmriprep_wf/single_subject_02_wf/func_preproc_ses_test_task_overtwordrepetition_wf/ica_aroma_wf/ica_aroma/out
Standard output:

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
  - The existing/specified MELODIC directory will be used.
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
  - classification
Found 1 file(s)
Found 10 head motion-related components in a total of 25 components.
Standard error:
/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py:2400: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py:2401: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)
/opt/ICA-AROMA/ICA_AROMA_functions.py:287: RuntimeWarning: Mean of empty slice
  return np.nanmean(max_correls, axis=0)
/opt/ICA-AROMA/ICA_AROMA_functions.py:498: RuntimeWarning: invalid value encountered in greater
  motionICs = np.squeeze(np.array(np.where((proj > 0) + (csfFract > thr_csf) + (HFC > thr_HFC))))
/usr/local/miniconda/lib/python3.7/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)
/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
Traceback (most recent call last):
  File "/opt/ICA-AROMA/ICA_AROMA.py", line 215, in <module>
    outDir)
  File "/opt/ICA-AROMA/classification_plots.py", line 164, in classification_plot
    hist_kws={'alpha': 0.2})
  File "/usr/local/miniconda/lib/python3.7/site-packages/seaborn/distributions.py", line 215, in distplot
    bins = min(_freedman_diaconis_bins(a), 50)
  File "/usr/local/miniconda/lib/python3.7/site-packages/seaborn/distributions.py", line 39, in _freedman_diaconis_bins
    return int(np.ceil((a.max() - a.min()) / h))
ValueError: cannot convert float NaN to integer
Return code: 1
```

Another example: https://circleci.com/gh/oesteban/fmriprep/4286

**Comment by oesteban** [comment]
https://github.com/maartenmennes/ICA-AROMA/pull/43
