### ISSUE TITLE
OSError: [Errno 16] Device or resource busy: '.nfs0000001807639d980000059d'

### ISSUE THREAD

**Issue by dmd** [poldracklab/fmriprep#1841]
I'm currently trying to get the Singularity fmriprep working using the `--contain` option, because I believe that the purpose of a container is to contain :) 

With just `--contain`, it fails fairly quickly because `/tmp` is a 16 MB tmpfs.  However, if I map `/tmp` to somewhere with space:

```
$ ls -ld /data/tmp
drwxrwxrwt 8 root root 4096 Oct 22 10:09 /data/tmp

$ df -h /data/tmp
Filesystem                       Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup01-LogVol01   33T   30T  2.9T  92% /data
```

using `-B /data/tmp:/tmp` then fairly early on I get:

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/managers.py", line 577, in _run_server
    server.serve_forever()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/managers.py", line 173, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/util.py", line 265, in _run_finalizers
    finalizer()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/util.py", line 189, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 485, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 443, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/miniconda/lib/python3.7/shutil.py", line 441, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs0000001807639d980000059d'
```

Processing appears to continue (I just encountered this a few minutes ago; I'll update this ticket when the job either succeeds or fails), but this is worrying.

**Comment by dmd** [comment]
Answering my own question: `/tmp` on NFS is not a good idea.

**Comment by YeGuoZJU** [comment]
How do you solve it? I also get this error now
