### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9

### ISSUE THREAD

**Issue by JMb63** [poldracklab/fmriprep#1850]
Hello,
When executing :
`fmriprep-docker /home/jmbonny/Documents/Viewing_food_cues/ /home/jmbonny/Documents/Viewing_food_cues/Derivatives/ --output-spaces MNI152NLin2009cAsym fsaverage5 --fs-license-file /home/jmbonny/Documents/FreeSurfer/license.txt`

I was getting this error 
```Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 547, in build_workflow
    layout = BIDSLayout(str(bids_dir), validate=False)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 185, in __init__
    self._validate_root()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 330, in _validate_root
    self.description = json.load(desc_fd)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/miniconda/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 175: invalid continuation byte
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues
```
It appears to be a badly encoded data ... May you guide me ? Thank you

**Comment by effigies** [comment]
Looks like your `dataset_description.json` file has a bad character in it. You could try pasting it into a JSON validator to see what the issue is. `0xe9` is `é` in Latin-1, so if that's in your JSON file, you'll probably want to re-save as UTF-8.

**Comment by JMb63** [comment]
That's right. A bad character `é` in the json. It works now. Thank you very much.

**Comment by ikrammohamdi** [comment]
@effigies  when i enter text  in textbox  , Iam facing this problem
![10](https://github.com/nipreps/fmriprep/assets/161083938/762b409f-8125-43d2-8ed7-088565d689e0)

**Comment by ikrammohamdi** [comment]
@effigies how can I resolve this UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 122: invalid continuation byte
