### ISSUE TITLE
RuntimeError: EchoTime2 metadata field not found. Please consult the BIDS specification.

### ISSUE THREAD

**Issue by soichih** [poldracklab/fmriprep#1867]
I am trying to run fmriprep the OpenNeuro published dataset (like https://openneuro.org/datasets/ds001454)

The fmap data on this dataset seems to be stored in non-BIDS compatible format, and fmriprep fails with the following error message.

```
fMRIPrep failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 569, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 662, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 382, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/interfaces/fmap.py", line 204, in _run_interface
    _delta_te(self.inputs.metadata),
  File "/usr/local/miniconda/lib/python3.7/site-packages/sdcflows/interfaces/fmap.py", line 529, in _delta_te
    'EchoTime2 metadata field not found. Please consult the BIDS specification.')
RuntimeError: EchoTime2 metadata field not found. Please consult the BIDS specification.
```

The EchoTime1/2 are basically stored under magnitude1.json and magnitude2.json respectively, and on phasediff.json, it just has "EchoTime" (from magnitude2). According to BIDS specification, EchoTime1/2 should be stored on phasediff.json, and there should be no magnitude1/2.json.  

I think I have 3 options..

1) Run fmriprep without fmap
2) Download the dataset, modify the fmap json manually, and run fmriprep
3) Have fmriprep updated so that it will look for magnitude1/2.json if EchoTime1/2 are not specified in the phasediff.json - although it's not BIDS compatible..

In general, I believe there are a lot of datasets published on OpenNeuro that are not BIDS compatible *anymore*? How should it be handled?

**Comment by kimsin98** [comment]
Editing phasediff.json files should be the right approach. Batch editing JSON files is simple if you use bash (jq) or python (json module)
