### ISSUE TITLE
[BUG] SortFmaps function node fails with the BEAST

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#189]
```
         Executing node SortFmaps in dir: /scratch/workflow_enumerator/387/phase_diff_and_magnitudes/SortFmaps
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 9, in <module>
    load_entry_point('fmriprep', 'console_scripts', 'fmriprep')()
  File "/root/src/fmriprep/fmriprep/run_workflow.py", line 73, in main
    create_workflow(opts)
  File "/root/src/fmriprep/fmriprep/run_workflow.py", line 149, in create_workflow
    preproc_wf.run(**plugin_settings)
  File "/root/src/nipype/nipype/pipeline/engine/workflows.py", line 578, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/root/src/nipype/nipype/pipeline/plugins/base.py", line 260, in run
    result=result))
  File "/root/src/nipype/nipype/pipeline/plugins/base.py", line 294, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/root/src/nipype/nipype/pipeline/plugins/base.py", line 249, in run
    result=result))
  File "/root/src/nipype/nipype/pipeline/plugins/base.py", line 294, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/root/src/nipype/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 367, in run
    self._run_interface()
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 1279, in _run_interface
    updatehash=updatehash))
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 1143, in _collate_results
    self._result.runtime.insert(i, None)
AttributeError: 'Bunch' object has no attribute 'insert'
```

**Comment by oesteban** [comment]
Now this is pybids :)
