### ISSUE TITLE
fmriprep errors

### ISSUE THREAD

**Issue by YeYeLab** [poldracklab/fmriprep#1891]
Hey there,
We are having an error in our fmriprep tries:

```
Node Name: fmriprep_wf.single_subject_1_wf.func_preproc_ses_01_task_meretzavoda_run_01_wf.bold_hmc_wf.mcflirt
Working Directory: /scratch/fmriprep_wf/single_subject_1_wf/func_preproc_ses_01_task_meretzavoda_run_01_wf/bold_hmc_wf/mcflirt
Inputs:
    args:
    bins:
    cost:
    dof:
    environ: {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
    in_file:
    init:
    interpolation:
    mean_vol:
    out_file:
    output_type: NIFTI_GZ
    ref_file:
    ref_vol:
    rotation:
    save_mats: True
    save_plots: True
    save_rms:
    scaling:
    smooth:
    stages:
    stats_imgs:
    use_contour:
    use_gradient:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 585, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 678, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 382, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 767, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 704, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
mcflirt -in /data/sub-1/ses-01/func/sub-1_ses-01_task-meretzavoda_run-01_bold.nii.gz -out /scratch/fmriprep_wf/single_subject_1_wf/func_preproc_ses_01_task_meretzavoda_run_01_wf/bold_hmc_wf/mcflirt/sub-1_ses-01_task-meretzavoda_run-01_bold_mcf.nii.gz -reffile /scratch/fmriprep_wf/single_subject_1_wf/func_preproc_ses_01_task_meretzavoda_run_01_wf/bold_reference_wf/gen_ref/ref_sbref.nii.gz -mats -plots
Standard output:

Standard error:
Killed
Return code: 137

```
This type of error appeared on 3 different tasks in the same run and resulted with no functional files for these tasks (and only for these tasks).

Another error that happens on every run we made in the 1.5 (and 1.5.1) versions of the fmriprep is that the anatomical file ''sub-1_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz" is not skull striped (like it supposed to be). 
We already tried to use previous versions of the fmriprep (version 1.3.2) but it resulted with multiply error as well (except of the skull strip file that was good). 

We would really appreciate your help.

Thank you very much,
Sharon & Noa.

**Comment by effigies** [comment]
This is very likely an out-of-memory issue. Can you share your configuration?

> the anatomical file ''sub-1_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz" is not skull striped (like it supposed to be).

It is not supposed to be skullstripped.

**Comment by YeYeLab** [comment]
Tommorow I'll be in the lab and I'll send the specs.

Meanwhile, regarding "'sub-1_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz" file:
I am following mumfurd university guide for fmri prepossessing. The registration part require a skull-stripped anatomical file as an input in the "Main structural Image" section ([see here](https://youtu.be/aB-bmcp5ET4?t=1066)). Which anatomical output file should I choose? When using fmriprep 1.3.2, the file stated above worked just fine, but now in the updated version (1.5.1) we cant find such file in the output anatomy directory.

Thanks again for the kind and fast help.
Noa & Sharon

**Comment by YeYeLab** [comment]
The desktop computer specs are: 

> vendor: | LENOVO
> version: | ThinkCentre M920t
> 
> RAM Memory:
> size: | 16GiB
> 
> CPU
> id: | cpu
> description: | CPU
> product: | Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
> vendor: | Intel Corp.
> physical id: | 4a
> bus info: | cpu@0
> version: | Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
> serial: | To Be Filled By O.E.M.
> slot: | U3E1
> size: | 3334MHz
> capacity: | 4600MHz
> width: | 64 bits
> clock: | 100MHz
> capabilities: | x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d cpufreq
> configuration: | cores=6enabledcores=6threads=12 | cores | = | 6 | enabledcores | = | 6 | threads | = | 12
> cores | = | 6
> enabledcores | = | 6
> threads | = | 12

Let me know if any other information is needed.
TNX!
