### ISSUE TITLE
 fsaverage_den = output_spaces.get('fsaverage', {}).get('den') AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by dmd** [poldracklab/fmriprep#1895]
In 1.5.1, but not in 1.5.0, we get:

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 692, in build_workflow
    work_dir=str(work_dir),
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 261, in init_fmriprep_wf
    use_syn=use_syn,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 618, in init_single_subject_wf
    use_syn=use_syn,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 436, in init_func_preproc_wf
    fsaverage_den = output_spaces.get('fsaverage', {}).get('den')
AttributeError: 'NoneType' object has no attribute 'get'
```

From the following call:

```
export SINGULARITYENV_TEMPLATEFLOW_HOME=/home/fmriprep/.cache/templateflow
/cm/shared/singularity/bin/singularity run \
    --contain \
    --cleanenv \
    -B /tmp -B /data -B /data1 -B /data2 -B /data3 -B /cm/shared \
    -B /home/frederic/.cache/fmriprep:/home/fmriprep/.cache/fmriprep \
    /cm/shared/singularity/images/fmriprep-1.5.1.simg \
    /data1/frederic/Axial \
    /data1/frederic/Axial/derivatives \
    participant \
    --fs-license-file /cm/shared/freesurfer-6.0.1/license.txt \
    --participant_label 005 \
    --output-spaces "MNI152NLin6Asym:res-2 MNI152NLin2009cAsym:res-2 anat func fsaverage" \
    --n_cpus 4 \
    --mem-mb 16384 \
    --notrack \
    --use-aroma --ignore-aroma-denoising-errors \
    --use-syn-sdc \
    -w  /data1/frederic/workdirs/Axial
```

We also tried the exact same call except:

```
    --output-spaces "MNI152NLin2009cAsym:res-2 anat func fsaverage" \
```

and received the same error.

**Comment by dmd** [comment]
@bbfrederick
