### ISSUE TITLE
The 'moving_image' trait of a _GenerateSamplingReferenceInputSpec instance must be a pathlike  object or string representing an existing file, but a value of '/' <class 'str'> was specified.

### ISSUE THREAD

**Issue by dmd** [poldracklab/fmriprep#1924]
I'm seeing this:

```
exception calling callback for <Future at 0x2aaad980b208 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 450, in run
    self._get_hashval()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 499, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 562, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 279, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 317, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 144, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'moving_image' trait of a _GenerateSamplingReferenceInputSpec instance must be a pathlike
 object or string representing an existing file, but a value of '/' <class 'str'> was specified.

Error setting node input:
Node: gen_ref
input: moving_image
results_file: /data/jfanning/fmriprep-working/fmriprep_wf/single_subject_035_wf/func_preproc_task_ftrt_zshim_wf/bold_split/re
sult_bold_split.pklz
value: /
```

Full log:

[fmriprep.e509697.txt](https://github.com/poldracklab/fmriprep/files/4020680/fmriprep.e509697.txt)
[fmriprep.o509697.txt](https://github.com/poldracklab/fmriprep/files/4020681/fmriprep.o509697.txt)

**Comment by dmd** [comment]
I see https://github.com/poldracklab/fmriprep/issues/1798 and https://github.com/nipy/nipype/issues/3014 might be related but I don't see anything in there that would help me solve this.

**Comment by oesteban** [comment]
Hi @dmd, can you post a tree of the BIDS structure for subject 035? I'm a bit surprised about the workflow name for the functional run (`func_preproc_task_ftrt_zshim_wf`). That might be confusing fMRIPrep.

What you see is an interface complaining for one input, which was generated in a previous node (in this case, `bold_split`). So the problem happened there. I'll wait for your feedback to learn more about this issue.

**Comment by dmd** [comment]
```
sub-035
├── anat
│   ├── sub-035_T1w.json
│   └── sub-035_T1w.nii.gz
├── fmap
│   ├── sub-035_dir-ap_epi.json
│   ├── sub-035_dir-ap_epi.nii.gz
│   ├── sub-035_dir-pa_epi.json
│   ├── sub-035_dir-pa_epi.nii.gz
│   ├── sub-035_magnitude1.json
│   ├── sub-035_magnitude1.nii.gz
│   ├── sub-035_magnitude2.json
│   ├── sub-035_magnitude2.nii.gz
│   ├── sub-035_phase1.json
│   ├── sub-035_phase1.nii.gz
│   ├── sub-035_phase2.json
│   └── sub-035_phase2.nii.gz
├── func
│   ├── sub-035_task-ftrt_bold.json
│   ├── sub-035_task-ftrt_bold.nii.gz
│   ├── sub-035_task-ftrt_bold_ph.json
│   ├── sub-035_task-ftrt_bold_ph.nii.gz
│   ├── sub-035_task-ftrt_zshim_bold_Eq_1.nii.gz
│   ├── sub-035_task-ftrt_zshim_bold.json
│   └── sub-035_task-ftrt_zshim_bold.nii.gz
└── other
    ├── sub-035_local_i00001.json
    ├── sub-035_local_i00001.nii.gz
    ├── sub-035_local_i00004.json
    ├── sub-035_local_i00004.nii.gz
    ├── sub-035_local_i00007.json
    └── sub-035_local_i00007.nii.gz
```

**however** `.bidsignore` contains:
```
*/fmap
```

**Comment by oesteban** [comment]
I don't think the dataset is valid. In particular, fmriprep is attempting to interpret ``sub-035_task-ftrt_zshim_bold.nii.gz`` as a bold run, but that `zshim` particle makes it invalid. It's not failing with the `_ph` or `_1` files because those are not selected as BOLD runs by pybids.

* Regarding your bidsignore - the safest way to preempt SDC execution is to use the `--ignore fieldmaps` flag of fmriprep.

**Comment by dmd** [comment]
I renamed to:
```
/data/jfanning/bids/sub-035
├── anat
│   ├── sub-035_T1w.json
│   └── sub-035_T1w.nii.gz
├── fmap
│   ├── sub-035_dir-ap_epi.json
│   ├── sub-035_dir-ap_epi.nii.gz
│   ├── sub-035_dir-pa_epi.json
│   ├── sub-035_dir-pa_epi.nii.gz
│   ├── sub-035_magnitude1.json
│   ├── sub-035_magnitude1.nii.gz
│   ├── sub-035_magnitude2.json
│   ├── sub-035_magnitude2.nii.gz
│   ├── sub-035_phase1.json
│   ├── sub-035_phase1.nii.gz
│   ├── sub-035_phase2.json
│   └── sub-035_phase2.nii.gz
├── func
│   ├── sub-035_task-ftrt_bold.json
│   ├── sub-035_task-ftrt_bold.nii.gz
│   ├── sub-035_task-ftrt_bold_ph.json
│   ├── sub-035_task-ftrt_bold_ph.nii.gz
│   ├── sub-035_task-ftrtzshim_bold_Eq_1.nii.gz
│   ├── sub-035_task-ftrtzshim_bold.json
│   └── sub-035_task-ftrtzshim_bold.nii.gz
└── other
    ├── sub-035_local_i00001.json
    ├── sub-035_local_i00001.nii.gz
    ├── sub-035_local_i00004.json
    ├── sub-035_local_i00004.nii.gz
    ├── sub-035_local_i00007.json
    └── sub-035_local_i00007.nii.gz
```

but I'm still getting the same error:
```
exception calling callback for <Future at 0x2aaadc49b5c0 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 450, in run
    self._get_hashval()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 499, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 562, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 279, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 317, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 144, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'moving_image' trait of a _GenerateSamplingReferenceInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/' <class 'str'> was specified.

Error setting node input:
Node: gen_ref
input: moving_image
results_file: /data/jfanning/fmriprep-working/fmriprep_wf/single_subject_035_wf/func_preproc_task_ftrtzshim_wf/bold_split/result_bold_split.pklz
value: /

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 72, in run_node
    result['result'] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 198, in result
    op.join(self.output_dir(), 'result_%s.pklz' % self.name))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 304, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /data/jfanning/fmriprep-working/fmriprep_wf/single_subject_035_wf/func_preproc_task_ftrtzshim_wf/bold_std_trans_wf/_key_MNI152NLin2009cAsym/gen_ref/result_gen_ref.pklz
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 149, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: /data/jfanning/fmriprep-working/fmriprep_wf/single_subject_035_wf/func_preproc_task_ftrtzshim_wf/bold_std_trans_wf/_key_MNI152NLin2009cAsym/gen_ref/result_gen_ref.pklz
```

Did I not change enough things?

**Comment by dmd** [comment]
Is there something else wrong about `sub-035_task-ftrtzshim_bold.nii.gz`, or .. what am I missing here?

**Comment by effigies** [comment]
Oh, I think I understand. There's a bug here:

https://github.com/poldracklab/fmriprep/blob/63a661b20ec68e1aa08949d5dd6fd17381ea1d52/fmriprep/workflows/bold/resampling.py#L404

It's expecting a list of paths, and taking the first. Instead, it's getting a single path, and taking the first character. Hence the `/`.

Is this a single volume BOLD series?

**Comment by dmd** [comment]
Yes, it's a single volume BOLD series. Come to think of it, it probably should be ignored? It is the pre-scan zshim. Should that get a different BIDS naming (i.e., not ending in `_bold`?) Or ignored some other way?

**Comment by effigies** [comment]
If you don't want it resampled to other spaces, then yes, giving it something like a `_zshim` suffix, and adding it to your `.bidsignore` file would probably be the cleanest option.

**Comment by effigies** [comment]
I opened #1931. Feel free to chime in there, if you have any thoughts on how you'd prefer fMRIPrep handled this case.

**Comment by dmd** [comment]
Great, thank you.
