### ISSUE TITLE
Error when calling fmriprep with --use-aroma

### ISSUE THREAD

**Issue by helloTC** [poldracklab/fmriprep#1972]
Hi, I called fmriprep to preprocess my data with --use-aroma, while the workflow did not execute cleanly. Here is the crash log:

Node: fmriprep_wf.single_subject_M01_wf.func_preproc_ses_01_task_motor_run_9_wf.bold_confounds_wf.compcor_plot
Working directory: /nfs/h1/workingshop/huangtaicheng/try_htc/work/fmriprep_wf/single_subject_M01_wf/func_preproc_ses_01_task_motor_run_9_wf/bold_confounds_wf/compcor_plot

Node inputs:

metadata_files = ['/nfs/h1/workingshop/huangtaicheng/try_htc/work/fmriprep_wf/single_subject_M01_wf/func_preproc_ses_01_task_motor_run_9_wf/bold_confounds_wf/tcompcor/component_metadata.tsv', '/nfs/h1/workingshop/huangtaicheng/try_htc/work/fmriprep_wf/single_subject_M01_wf/func_preproc_ses_01_task_motor_run_9_wf/bold_confounds_wf/acompcor/component_metadata.tsv']
metadata_sources = ['tCompCor', 'aCompCor']
out_file = None
variance_thresholds = (0.5, 0.7, 0.9)

Traceback (most recent call last):
  File "/usr/local/neurosoft/miniconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/neurosoft/miniconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/usr/local/neurosoft/miniconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/usr/local/neurosoft/miniconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/neurosoft/miniconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/neurosoft/miniconda3/lib/python3.6/site-packages/niworkflows/interfaces/plotting.py", line 118, in _run_interface
    varexp_thresh=self.inputs.variance_thresholds
  File "/usr/local/neurosoft/miniconda3/lib/python3.6/site-packages/niworkflows/viz/plots.py", line 647, in compcor_variance_plot
    ax[m].text(varexp[thr][0], 25,
IndexError: invalid index to scalar variable.

Could someone give me some suggestions on how to solve this issue?

Thank you!
Taicheng

**Comment by jdkent** [comment]
Hi Taicheng,

What version of fmriprep are you using? If it's before `v1.5.0`, then this appears to be a bug that was fixed in the `v1.5.0` release. Could you upgrade your installation of fmriprep?

Here is the related issue: #1680

**Comment by helloTC** [comment]
> Hi Taicheng,
> 
> What version of fmriprep are you using? If it's before `v1.5.0`, then this appears to be a bug that was fixed in the `v1.5.0` release. Could you upgrade your installation of fmriprep?
> 
> Here is the related issue: #1680
> 
> Best,
> James

Hi James, 
Thank you for your reply, I installed a newer version and no further questions happened. 

Best,
Taicheng
