### ISSUE TITLE
Illegal value 1006.49 in tpattern file slice_timing.1D

### ISSUE THREAD

**Issue by soichih** [poldracklab/fmriprep#1974]
Hello. I am trying to run fmriprep on this dataset
> https://brainlife.io/datasets/5e2f913057e7f20020083083#%7B%22query%22%3A%22%20ADHD200%22%2C%22datatypes%22%3A%5B%5D%7D

This dataset is hosted via datalad `datasets.datalad.org/adhd200/RawDataBIDS/NeuroIMAGE`

When I run fmriprep, I run into the following error message.

```
singularity exec -e docker://poldracklab/fmriprep:1.5.5 /usr/local/miniconda/bin/fmriprep --notrack --resource-monitor --skip-bids-validation --md-only-boilerplate --stop-on-first-crash --use-plugin=multi_proc.yml --output-spaces fsaverage5 MNI152NLin2009cAsym --force-bbr --use-syn-sdc --fs-license-file=license.txt --skull-strip-template=NKI --work-dir=fmripworkdir --participant_label=sub-TTTEMPSUB fmripinput fmripout participant
You are using fMRIPrep-1.5.5, and a newer version of fMRIPrep is available: 1.5.8.
...
fMRIPrep failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 395, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/afni/base.py", line 119, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 724, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
3dTshift -ignore 0 -prefix sub-TTTEMPSUB_ses-SSSES_task-rest_run-1_bold_tshift.nii.gz -tpattern @slice_timing.1D -TR 1.96s /export/prod/5e173a9f6bb29c4e81abc464/5e41bf4540771e72b0344109/fmripworkdir/fmriprep_wf/single_subject_TTTEMPSUB_wf/func_preproc_ses_SSSES_task_rest_run_1_wf/bold_stc_wf/slice_timing_correction/sub-TTTEMPSUB_ses-SSSES_task-rest_run-1_bold.nii.gz
Standard output:

Standard error:
++ 3dTshift: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
[7m** FATAL ERROR:[0m Illegal value 1006.49 in tpattern file slice_timing.1D
** Program compile date = Jun 12 2017
Return code: 1
```

This dataset contains fmri data with SliceTiming that looks like this.

```
  "SliceTiming": [
    0,
    1006.49,
    52.97,
    1059.46,
    105.95,
    1112.43,
    158.92,
    1165.41,
    211.89,
    1218.38,
    264.86,
    1271.35,
    317.84,
    1324.32,
...
```

According to BIDS specification, SliceTiming should be stored in second, but this seems to be stored in millisecond. 

> https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#timing-parameters

I am trying to determine if this is fmriprep issue, or incorrect SliceTiming issue (not clear from the error message I am seeing). 

I appreciate your assistance!

**Comment by effigies** [comment]
Yes, this is incorrect `SliceTiming` information. It should be converted to seconds.

**Comment by soichih** [comment]
I see this in the sidecar

```
"RepetitionTime": 1.96,
"PixelSpacing": "3.5x3.5",
```

And from NifTI headers

```
pixdim          : [-1.    3.5   3.5   3.51  1.96  0.    0.    0.  ]
xyzt_units      : 10
```

mrinfo

```
************************************************
Image:               "bold.nii.gz"
************************************************
  Dimensions:        64 x 64 x 37 x 261
  Voxel size:        3.5 x 3.5 x 3.51 x 1.96
  Data strides:      [ -1 2 3 4 ]
  Format:            NIfTI-1.1 (GZip compressed)
  Data type:         32 bit float (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1          -0          -0      -108.5
                                0           1          -0      -61.61
                               -0           0           1      -65.35

```

When I find data issue, I don't know where to go from here.. I can think of the following.

1) Try to contact the author listed in the datalad dataset.
2) Contact datalad (yaroslav, michael, etc..) and let them route the issue (as it is hosted on datalad?)
3) Author of bids_validator (I am guessing the author ran it and passed it before publishing it.. so something needs to be updated with bids_validator?)
4) Maintainers(/childmind) of INDI datasets who hosts the data?

**Comment by effigies** [comment]
Thanks for the information.

1/2/4: I would probably ping @yarikoptic to see who is responsible for changes to the dataset, in case its not the author. This is on the pragmatic grounds that I know he reads his email.
3: Re-reading the spec again, it's not clear that the data is actually invalid in the sense of violating the spec. It's just non-sensical. So if we want to make it an error in the validator, we presumably first need to update the spec to say "These values MUST NOT exceed RepetitionTime". I think this is probably a good idea...

Given that the validator is letting this through, we should handle the case and say that we're ignoring the `SliceTiming`.

**Comment by yarikoptic** [comment]
Don't shoot the messenger! ;-)
I just crawl that dataset from s3 bucket and thus not the original author of the changes. 
Good point though - I might ideally need to set author of commits to somebody who might actually be related to the changes, but that would be more work, since s3 I think doesn't provide that info, heh heh
