### ISSUE TITLE
ValueError: 'MNI152NLin2009cAsym' is not in list when running with --output-spaces "MNI152NLin6Asym"

### ISSUE THREAD

**Issue by dmd** [poldracklab/fmriprep#1992]
When running with:

```
--output-spaces "MNI152NLin6Asym"
```

we get:

```
Node Name: fmriprep_wf.single_subject_01_wf.func_preproc_task_rest_run_01_wf.sdc_select_std
File: /data/eaolson/K23_bids/derivatives/fmriprep/sub-01/log/20200219-184546_097331ea-fe14-4dab-9baf-a7fd395867c4/crash-20200219-185037-eaolson-sdc_select_std-35b5402d-32f5-41fd-a247-9a2c5ba13486.txt
Working Directory: /data/eaolson/K23_bids_work/fmriprep_wf/single_subject_01_wf/func_preproc_task_rest_run_01_wf/sdc_select_std
Inputs:
key: MNI152NLin2009cAsym
keys: ['MNI152NLin6Asym']
std2anat_xfm: ['/data/eaolson/K23_bids_work/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym./registration/ants_t1_to_mniInverseComposite.h5']
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 399, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 476, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utility.py", line 144, in _list_outputs
    index = self.inputs.keys.index(self.inputs.key)
ValueError: 'MNI152NLin2009cAsym' is not in list
```

What should we be specifying to use that space?

**Comment by mgxd** [comment]
Hi @dmd - what version are you running? This should be fixed in the upcoming 20.0.x series, but earlier versions might require you to add MNI152NLin2009cAsym to your output spaces.

**Comment by dmd** [comment]
1.5.8

**Comment by mgxd** [comment]
A new release is out, which should not require you to add `MNI152NLin2009cAsym` as an output space.
