### ISSUE TITLE
OrientationError('Cannot drop coordinates when ' nibabel.orientations.OrientationError

### ISSUE THREAD

**Issue by heyeh** [poldracklab/fmriprep#2035]
Hi, I am running fMRIPrep 1.5.8. I got this orientation error for only one subject. I checked the T1 image looks fine.

In the output report, the error is,
Node Name: fmriprep_wf.single_subject_C01071_wf.anat_preproc_wf.anat_template_wf.t1w_ref_dimensions

In the log, it shows,
 
fMRIPrep failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/images.py", line 188, in _run_interface
    reoriented = np.vectorize(nb.as_closest_canonical)(orig_imgs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 1972, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2048, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/funcs.py", line 209, in as_closest_canonical
    img = img.as_reoriented(io_orientation(img.affine))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/nifti1.py", line 2011, in as_reoriented
    img = super(Nifti1Pair, self).as_reoriented(ornt)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/spatialimages.py", line 634, in as_reoriented
    t_arr = apply_orientation(np.asanyarray(self.dataobj), ornt)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/orientations.py", line 163, in apply_orientation
    raise OrientationError('Cannot drop coordinates when '
nibabel.orientations.OrientationError: Cannot drop coordinates when applying orientation to data

**Comment by effigies** [comment]
Can you provide the header? `head -c 348 img.nii > img.hdr` (May need to gunzip it...)

**Comment by heyeh** [comment]
Thanks for your reply. The header is attached.
[img.hdr.gz](https://github.com/poldracklab/fmriprep/files/4331631/img.hdr.gz)

**Comment by effigies** [comment]
Do you have multiple T1w images? This one looks fine.

**Comment by heyeh** [comment]
Thanks for checking. Only one T1w is in anat.

**Comment by effigies** [comment]
Okay. I'm not able to reproduce the issue. Can you try re-running fMRIPrep? Removing the `fmriprep_wf/single_subject_C01071_wf/anat_preproc_wf` folder from your working directory should ensure that the anatomical part is started from scratch.

**Comment by heyeh** [comment]
I found out it did have two T1. This is a longitudinal dataset that all subjects have single T1 but only this subject has another T1 in one of the sessions. Sorry for missing that. Really appreciate your help!
