### ISSUE TITLE
Do not use setuptools.LooseVersion in version check

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2059]
If fails with development versions:
```
Traceback (most recent call last):
  File "/home/oesteban/.anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/oesteban/.anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/oesteban/workspace/fmriprep/fmriprep/cli/workflow.py", line 80, in build_workflow
    retval['workflow'] = init_fmriprep_wf()
  File "/home/oesteban/workspace/fmriprep/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    spaces=config.workflow.spaces.get_fs_spaces()),
  File "/home/oesteban/workspace/nipype/nipype/interfaces/base/core.py", line 611, in __init__
    from_file=from_file, resource_monitor=resource_monitor, **inputs
  File "/home/oesteban/workspace/nipype/nipype/interfaces/base/core.py", line 178, in __init__
    BaseInterface._etelemetry_version_data = check_latest_version()
  File "/home/oesteban/workspace/nipype/nipype/__init__.py", line 98, in check_latest_version
    if LooseVersion(__version__) != LooseVersion(latest["version"]):
  File "/home/oesteban/.anaconda3/lib/python3.7/distutils/version.py", line 46, in __eq__
    c = self._cmp(other)
  File "/home/oesteban/.anaconda3/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by mgxd** [comment]
this should have been addressed in https://github.com/nipy/nipype/commit/e6ed8c6c30fa1386d4820024ab29907274dd0109
