### ISSUE TITLE
Issue with seg_report when using --skull-strip-t1w skip

### ISSUE THREAD

**Issue by andrew-stier** [poldracklab/fmriprep#2061]

**Comment by andrew-stier** [comment]
What version of fMRIPrep are you using?
20.1.0rc1

What were you trying to do?
run fMRIPrep on skull stripped images

```
exception calling callback for <Future at 0x7f6aa5488ef0 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 128, in validate
    value = Path(value)  # Use pathlib's validation
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 994, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 649, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 633, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 486, in run
    self._get_hashval()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 538, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 609, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 302, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 329, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 130, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'in_file' trait of a _ROIsPlotInputSpecRPT instance must be a pathlike object or string representing an existing file, but a value of "['/scratch/fmriprep_wf/single_subject_RTC01_wf/anat_preproc_wf/n4_only_wf/inu_n4_final/mapflow/_inu_n4_final0/sub-RTC01_ses-func02_T1w_valid_corrected.nii.gz']" <class 'str'> was specified.

```

**Comment by mgxd** [comment]
Thanks for the report (and using the release candidate)!

I think I see the problem, I'll push a second rc this week to see

**Comment by mgxd** [comment]
@andrew-stier I've pushed a new pre-release `20.1.0rc2` that hopefully fixes the problem. Can you try that version and report back?

**Comment by andrew-stier** [comment]
will do

**Comment by andrew-stier** [comment]
@mgxd I got this error running with 20.1.0rc2:

200410-08:41:14,880 nipype.workflow CRITICAL:
         fMRIPrep failed: Does not support two inline functions in series ('def _pop(in_files):
    if isinstance(in_files, (list, tuple)):
        return in_files[0]
    return in_files
'  and 'def _pop(inlist):
    if isinstance(inlist, (list, tuple)):
        return inlist[0]
    return inlist
'), found when connecting fmriprep_wf.single_subject_RTC01_wf.anat_preproc_wf.n4_only_wf.inu_n4_final to fmriprep_wf.single_subject_RTC01_wf.anat_preproc_wf.anat_norm_wf.inputnode. Please use a Function node.

**Comment by mgxd** [comment]
thanks for following up on this - a (real) fix is in the works.

**Comment by oesteban** [comment]
> thanks for following up on this - a (real) fix is in the works.

Is this done?

**Comment by mgxd** [comment]
it should be resolved - @andrew-stier when you get a chance, could you try with the master branch (`poldracklab/fmriprep:unstable` image)?

**Comment by oesteban** [comment]
@andrew-stier, please reopen if this has not been resolved. Thanks for posting!
