### ISSUE TITLE
Using fsaverage5 freesurfer output for fsaverage6 run?

### ISSUE THREAD

**Issue by nicolocin** [poldracklab/fmriprep#2072]
Hi,

I'm trying to run fmriprep v.20.0.5 on ABIDE data and so far all subjects I ran crashed.  Sample crash report:

```
Node: _sampler0
Working directory: /workdir/fmriprep/fmriprep_wf/single_subject_0050551_wf/func_preproc_task_rest_run_1_wf/bold_surf_wf/_target_fsaverage/sampler/mapflow/_sampler0

Node inputs:

apply_rot = <undefined>
apply_trans = <undefined>
args = <undefined>
cortex_mask = True
environ = {'SUBJECTS_DIR': '/opt/freesurfer/subjects'}
fix_tk_reg = <undefined>
float2int_method = <undefined>
frame = <undefined>
hemi = lh
hits_file = <undefined>
hits_type = <undefined>
ico_order = <undefined>
interp_method = trilinear
mask_label = <undefined>
mni152reg = <undefined>
no_reshape = <undefined>
out_file = <undefined>
out_type = gii
override_reg_subj = True
projection_stem = <undefined>
reference_file = <undefined>
reg_file = /workdir/fmriprep/fmriprep_wf/single_subject_0050551_wf/func_preproc_task_rest_run_1_wf/bold_surf_wf/set_xfm_source/out_concat.lta
reg_header = <undefined>
reshape = <undefined>
reshape_slices = <undefined>
sampling_method = average
sampling_range = (0.0, 1.0, 0.2)
sampling_units = frac
scale_input = <undefined>
smooth_surf = <undefined>
smooth_vol = <undefined>
source_file = /workdir/fmriprep/fmriprep_wf/single_subject_0050551_wf/func_preproc_task_rest_run_1_wf/bold_surf_wf/_target_fsaverage/rename_src/fsaverage.nii
subject_id = sub-0050551
subjects_dir = /mnt/abide_fs
surf_reg = <undefined>
surface = <undefined>
target_subject = fsaverage
vox_file = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/freesurfer/base.py", line 146, in run
    return super(FSCommand, self).run(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
mri_vol2surf --cortex --hemi lh --interp trilinear --o /workdir/fmriprep/fmriprep_wf/single_subject_0050551_wf/func_preproc_task_rest_run_1_wf/bold_surf_wf/_target_fsaverage/sampler/mapflow/_sampler0/lh.fsaverage.gii  --srcsubject sub-0050551 --reg /workdir/fmriprep/fmriprep_wf/single_subject_0050551_wf/func_preproc_task_rest_run_1_wf/bold_surf_wf/set_xfm_source/out_concat.lta --projfrac-avg 0.000 1.000 0.200 --mov /workdir/fmriprep/fmriprep_wf/single_subject_0050551_wf/func_preproc_task_rest_run_1_wf/bold_surf_wf/_target_fsaverage/rename_src/fsaverage.nii --trgsubject fsaverage
Standard output:
srcvol = /workdir/fmriprep/fmriprep_wf/single_subject_0050551_wf/func_preproc_task_rest_run_1_wf/bold_surf_wf/_target_fsaverage/rename_src/fsaverage.nii
srcreg = /workdir/fmriprep/fmriprep_wf/single_subject_0050551_wf/func_preproc_task_rest_run_1_wf/bold_surf_wf/set_xfm_source/out_concat.lta
srcregold = 0
srcwarp unspecified
surf = white
hemi = lh
trgsubject = fsaverage
surfreg = sphere.reg
ProjFrac = 0.5
thickness = thickness
reshape = 0
interp = trilinear
float2int = round
GetProjMax = 0
INFO: float2int code = 0
niiRead(): NIFTI_UNITS_UNKNOWN, assuming mm
Done loading volume
INFO: overriding regsubject  with sub-0050551
Input reg is LTA
-------- original matrix -----------
-1.00000   0.00010   0.00062   5.26261;
 0.00062   0.00048   1.00000  -18.06525;
-0.00010  -1.00000   0.00048   4.36404;
 0.00000   0.00000   0.00000   1.00000;
-------- original matrix -----------
Loading label /mnt/abide_fs/fsaverage/label/lh.cortex.label
Standard error:
No such file or directory
mri_vol2surf: could not open label file /mnt/abide_fs/fsaverage/label/lh.cortex.label
Invalid argument
mri_vol2surf: could not load label file /mnt/abide_fs/fsaverage/label/lh.cortex.label
Invalid argument
Return code: 255
```

I'm wondering if it's because I used the freesurfer output from an old run of the same data with a earlier version of fmriprep and `fsaverage5`, but we're using `fsaverage6` this time round?   `fsaverage/label/lh.cortex.label` doesn't exist in our old freesurfer output. 

![Screen Shot 2020-04-10 at 8 16 52 PM](https://user-images.githubusercontent.com/30167129/78991494-a51bc880-7b6b-11ea-8e82-616ef7251ad0.png)

**Comment by mgxd** [comment]
@nicolocin it looks like there are files missing from your copy of `fsaverage` @ `/mnt/abide_fs/fsaverage`.

Clearing it and replacing it with a new copy should do the trick - there is a copy within the container located at `/opt/freesurfer/subjects/fsaverage`

**Comment by mgxd** [comment]
^ this did the trick
