### ISSUE TITLE
Possible bug introduced in previous PR

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#2085]
[this build](https://app.circleci.com/pipelines/github/oesteban/fmriprep/77/workflows/055aac45-8a0a-4707-b5bb-9c7863781fdb/jobs/5307) is failing with:

```
200416-02:16:22,290 nipype.workflow CRITICAL:
	 fMRIPrep failed: Does not support two inline functions in series ('def _pop(inlist):
    if isinstance(inlist, (list, tuple)):
        return inlist[0]
    return inlist
'  and 'def _pop(inlist):
    if isinstance(inlist, (list, tuple)):
        return inlist[0]
    return inlist
'), found when connecting fmriprep_wf.single_subject_100185_wf.anat_preproc_wf.brain_extraction_wf.copy_xform to fmriprep_wf.single_subject_100185_wf.func_preproc_task_machinegame_run_02_wf.inputnode. Please use a Function node.
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 86, in main
    fmriprep_wf.run(**config.nipype.get_plugin())
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 622, in run
    execgraph = generate_expanded_graph(deepcopy(flatgraph))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 975, in generate_expanded_graph
    graph_in = _remove_nonjoin_identity_nodes(graph_in, keep_iterables=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 854, in _remove_nonjoin_identity_nodes
    _remove_identity_node(graph, node)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 881, in _remove_identity_node
    _propagate_internal_output(graph, node, field, connections, portinputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 939, in _propagate_internal_output
    "node.".format(src_func, dst_func, srcnode, destnode)
ValueError: Does not support two inline functions in series ('def _pop(inlist):
    if isinstance(inlist, (list, tuple)):
        return inlist[0]
    return inlist
'  and 'def _pop(inlist):
    if isinstance(inlist, (list, tuple)):
        return inlist[0]
    return inlist
'), found when connecting fmriprep_wf.single_subject_100185_wf.anat_preproc_wf.brain_extraction_wf.copy_xform to fmriprep_wf.single_subject_100185_wf.func_preproc_task_machinegame_run_02_wf.inputnode. Please use a Function node.
```
Potentially introduced by [this change](https://github.com/poldracklab/smriprep/pull/174/commits/7ba712d03c38044f5f251fe99c5dc0a02a8f9223) in sMRIPrep.

The problem has gone unnoticed because of previously cached results, most likely. It is also possible that this is only happening on my dev branch.

**Comment by mgxd** [comment]
https://github.com/poldracklab/fmriprep/pull/2073 will fix this
