### ISSUE TITLE
fmriprep version: 20.1.0

### ISSUE THREAD

**Issue by shilpitju** [poldracklab/fmriprep#2163]
Hi,

Thanks so much for the much awaited version.  As mentioned in the documentation, to ensure long-term stability, the LTS nomination to 20.2 has been postponed to allow unlocking the 20.1 earlier. Can you please clarify a bit further on this? I mean will it be fine using the current 20.1.0 version in my project data so that I can use the pre-processed data later with HCP Pipelines?

Secondly, is MultiModal Surface Matching (MSM) being used in fmriprep?

Thanks

**Comment by mgxd** [comment]
@shilpitju there was interest in having a long term release (1+ year of actively solving issues and backporting bug fixes), and 20.1.0 was the intended target. While 20.1.0 is not marked as an LTS, we still include support for it, and it should be fine to use it for your analysis.

MSM is not being used. We generate our fsLR outputs as recommended by:
https://wiki.humanconnectome.org/download/attachments/63078513/Resampling-FreeSurfer-HCP.pdf

**Comment by shilpitju** [comment]
Thanks

**Comment by shilpitju** [comment]
Hi,

I am able to understand what is referred here as a working directory. My data is in E directory (with 2.69 TB space free) and my C directory has 136 GB free space.

Running again the dataset results in the following error:

         [Node] Finished "fmriprep_wf.single_subject_LTLE50_wf.func_preproc_ses_1_task_SC_acq_TR2500_wf.bold_std_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.apply_mask".
200824-21:44:33,541 nipype.workflow INFO:
         [Node] Setting-up "fmriprep_wf.single_subject_LTLE50_wf.func_preproc_ses_1_task_SC_acq_TR2500_wf.bold_t1_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.unifize" in "/tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_t1_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/unifize".
200824-21:44:33,545 nipype.workflow INFO:
         [Node] Running "unifize" ("nipype.interfaces.afni.utils.Unifize"), a CommandLine Interface with command:
3dUnifize -clfrac 0.2 -rbt 18.3 65.0 90.0 -prefix uni.nii.gz -T2 -input /tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_t1_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/unifize/ref_bold_corrected_brain_masked.nii.gz
200824-21:44:35,234 nipype.workflow WARNING:
         Storing result file without outputs
200824-21:44:35,237 nipype.workflow WARNING:
         [Node] Error on "fmriprep_wf.single_subject_LTLE50_wf.func_preproc_ses_1_task_rest_acq_TR2500_wf.bold_std_trans_wf.merge" (/tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_rest_acq_TR2500_wf/bold_std_trans_wf/_std_target_MNI152NLin6Asym.resnative/merge)
exception calling callback for <Future at 0x7f34b7614f60 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/nilearn.py", line 161, in _run_interface
    new_nii.to_filename(self._results["out_file"])
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/filebasedimages.py", line 334, in to_filename
    self.to_file_map()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/analyze.py", line 1047, in to_file_map
    arr_writer.to_fileobj(imgf)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/arraywriters.py", line 561, in to_fileobj
    nan2zero=self._needs_nan2zero())
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/volumeutils.py", line 659, in array_to_file
    pre_clips=pre_clips)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/volumeutils.py", line 832, in _write_data
    fileobj.write(dslice.tobytes())
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/openers.py", line 163, in write
    return self.fobj.write(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/gzip.py", line 264, in write
    self.fileobj.write(self.compress.compress(data))
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/gzip.py", line 309, in close
    fileobj.write(self.compress.flush())
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    rebase=str2bool(self.config["execution"]["use_relative_paths"]),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 235, in save_resultfile
    savepkl(resultsfile, result)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 726, in savepkl
    pkl_file.write(content)
  File "/usr/local/miniconda/lib/python3.7/gzip.py", line 319, in close
    myfileobj.close()
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 217, in result
    op.join(self.output_dir(), "result_%s.pklz" % self.name)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_rest_acq_TR2500_wf/bold_std_trans_wf/_std_target_MNI152NLin6Asym.resnative/merge/result_merge.pklz
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: /tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_rest_acq_TR2500_wf/bold_std_trans_wf/_std_target_MNI152NLin6Asym.resnative/merge/result_merge.pklz
200824-21:44:36,897 nipype.workflow WARNING:
         [Node] Error on "fmriprep_wf.single_subject_LTLE50_wf.func_preproc_ses_1_task_SC_acq_TR2500_wf.bold_t1_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.unifize" (/tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_t1_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/unifize)
exception calling callback for <Future at 0x7f34b75bc0b8 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 770, in _run_command
    rebase=str2bool(self.config["execution"]["use_relative_paths"]),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 245, in save_resultfile
    savepkl(resultsfile, result)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 726, in savepkl
    pkl_file.write(content)
  File "/usr/local/miniconda/lib/python3.7/gzip.py", line 319, in close
    myfileobj.close()
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 217, in result
    op.join(self.output_dir(), "result_%s.pklz" % self.name)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_t1_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/unifize/result_unifize.pklz
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: /tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_t1_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/unifize/result_unifize.pklz
200824-21:44:38,771 nipype.workflow WARNING:
         [Node] Error on "_sampler1" (/tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_surf_wf/_target_fsaverage/sampler/mapflow/_sampler1)
exception calling callback for <Future at 0x7f34b7532e80 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 770, in _run_command
    rebase=str2bool(self.config["execution"]["use_relative_paths"]),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 245, in save_resultfile
    savepkl(resultsfile, result)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 726, in savepkl
    pkl_file.write(content)
  File "/usr/local/miniconda/lib/python3.7/gzip.py", line 319, in close
    myfileobj.close()
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 217, in result
    op.join(self.output_dir(), "result_%s.pklz" % self.name)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_surf_wf/_target_fsaverage/sampler/mapflow/_sampler1/result__sampler1.pklz
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: /tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_surf_wf/_target_fsaverage/sampler/mapflow/_sampler1/result__sampler1.pklz
200824-21:44:39,127 nipype.workflow WARNING:
         [Node] Error on "_sampler0" (/tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_surf_wf/_target_fsaverage/sampler/mapflow/_sampler0)
exception calling callback for <Future at 0x7f34c42b66a0 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 770, in _run_command
    rebase=str2bool(self.config["execution"]["use_relative_paths"]),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 245, in save_resultfile
    savepkl(resultsfile, result)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 726, in savepkl
    pkl_file.write(content)
  File "/usr/local/miniconda/lib/python3.7/gzip.py", line 319, in close
    myfileobj.close()
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 217, in result
    op.join(self.output_dir(), "result_%s.pklz" % self.name)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_surf_wf/_target_fsaverage/sampler/mapflow/_sampler0/result__sampler0.pklz
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: /tmp/work/fmriprep_wf/single_subject_LTLE50_wf/func_preproc_ses_1_task_SC_acq_TR2500_wf/bold_surf_wf/_target_fsaverage/sampler/mapflow/_sampler0/result__sampler0.pklz

**Comment by shilpitju** [comment]
I just want to point out that when I look into the Derivatives folder, I see that pre-processed files are created in the MNI152NLin6Asym space and there are no files in the HCP cifti space.

Thanks

**Comment by shilpitju** [comment]
Hi,

I figured that most of the space allocated for disk image size for docker desktop was used. I increased the allocated space and fmriprep worked. 

Does that mean, each time I run fmriprep, the disk image size will keep on growing? Guidance is required in the matter.

Thanks

**Comment by mgxd** [comment]
@shilpitju please have a look at https://github.com/poldracklab/fmriprep/issues/2075#issuecomment-613018109

**Comment by oesteban** [comment]
> Does that mean, each time I run fmriprep, the disk image size will keep on growing?

No, that's not how containers work. The disk image size will remain the same because the image is unique. The **container** will keep growing. You can ensure containers are cleared up after execution with the `--rm` flag. Please refer to Docker's documentation.

Additional documentation is found here (https://www.nipreps.org/apps/docker/).


Because the follow-up questions are deviating from the original post, I'll go ahead and close this. Please feel free to reopen if some additional clarification is needed regarding the original question or open any new issues you must if new questions pop up.
