### ISSUE TITLE
Premature Docker Exit (137) during Robust Template Creation

### ISSUE THREAD

**Issue by seldamat** [poldracklab/fmriprep#2186]
### What version of fMRIPrep are you using?
latest:20.1.1

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Docker Container

### What is the exact command-line you used?
```
docker run --rm -v /Users/admin/Anvil/opt/freesurfer/7.1.0/license.txt:/opt/freesurfer/license.txt:ro -v /Volumes/Anvil/sync/furnace/ads/data/bids:/data:ro -v /Volumes/Anvil/sync/furnace/ads/data/derivatives:/out -v /Volumes/Anvil/sync/furnace/ads/data/derivatives/freesurfer:/opt/subjects -v /Volumes/Anvil/sync/furnace/ads/data/derivatives/workdir:/scratch poldracklab/fmriprep:20.1.1 /data /out participant --participant-label sub-151031 --nthreads 8 --mem_mb 21 -t rest --skip-bids-validation --resource-monitor --error-on-aroma-warnings --cifti-output --use-aroma --return-all-components --fs-subjects-dir /opt/subjects -w /scratch --output-spaces MNIPediatricAsym:cohort-1 fsnative anat
```

### Have you checked that your inputs are BIDS valid?
Yes

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
[report-link](https://drive.google.com/file/d/1Igki_OaGTPK9TvLWjYGsKkY6UAt2P8bB/view?usp=sharing)

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```

File: /out/fmriprep/sub-151031/log/20200609-183432_4f9f678d-75dc-4e88-b77f-cd8882a4d8dd/crash-20200609-204325-root-t1w_merge-c261b9b2-b15d-45bf-a4f0-09372bc590ff.txt
Working Directory: /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/t1w_merge
Inputs:

    args:
    auto_detect_sensitivity: True
    average_metric:
    environ: {'SUBJECTS_DIR': '/opt/freesurfer/subjects', 'OMP_NUM_THREADS': '1'}
    fixed_timepoint: True
    in_files:
    in_intensity_scales:
    initial_timepoint: 1
    initial_transforms:
    intensity_scaling: True
    no_iteration: True
    num_threads: 1
    out_file: mri_robust_template_out.mgz
    outlier_sensitivity:
    scaled_intensity_outputs:
    subjects_dir: /opt/freesurfer/subjects
    subsample_threshold: 200
    transform_outputs: True

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/freesurfer/base.py", line 265, in run
    return super(FSCommandOpenMP, self).run(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/freesurfer/base.py", line 149, in run
    return super(FSCommand, self).run(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
mri_robust_template --satit --fixtp --mov /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-151031_ses-wave1_run-01_T1w_corrected.nii.gz /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-151031_ses-wave2_run-01_T1w_corrected.nii.gz /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct2/sub-151031_ses-wave3_run-01_T1w_corrected.nii.gz --inittp 1 --iscale --noit --template sub-151031_ses-wave1_run-01_T1w_template.nii.gz --subsample 200 --lta /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/t1w_merge/tp1.lta /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/t1w_merge/tp2.lta /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/t1w_merge/tp3.lta
Standard output:
$Id: mri_robust_template.cpp,v 1.54 2016/05/05 21:17:08 mreuter Exp $

--satit: Will estimate SAT iteratively!
--fixtp: Will map everything to init TP!
--mov: Using /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-151031_ses-wave1_run-01_T1w_corrected.nii.gz as movable/source volume.
--mov: Using /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-151031_ses-wave2_run-01_T1w_corrected.nii.gz as movable/source volume.
--mov: Using /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct2/sub-151031_ses-wave3_run-01_T1w_corrected.nii.gz as movable/source volume.
    Total: 3 input volumes
--inittp: Using TP 1 as target for initialization
--iscale: Enableing intensity scaling!
--noit: Will output only first template (no iterations)!
--template: Using sub-151031_ses-wave1_run-01_T1w_template.nii.gz as template output volume.
--subsample: Will subsample if size is larger than 200 on all axes!
--lta: Will output LTA transforms
Setting iscale ...
reading source '/scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-151031_ses-wave1_run-01_T1w_corrected.nii.gz'...
converting source '/scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-151031_ses-wave1_run-01_T1w_corrected.nii.gz' to bspline ...
MRItoBSpline degree 3
reading source '/scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-151031_ses-wave2_run-01_T1w_corrected.nii.gz'...
converting source '/scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-151031_ses-wave2_run-01_T1w_corrected.nii.gz' to bspline ...
MRItoBSpline degree 3
reading source '/scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct2/sub-151031_ses-wave3_run-01_T1w_corrected.nii.gz'...
converting source '/scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct2/sub-151031_ses-wave3_run-01_T1w_corrected.nii.gz' to bspline ...
MRItoBSpline degree 3

MultiRegistration::initializing Xforms (init 1 , maxres 0 , iterate 5 , epsit 0.01 ) : 

[init] ========================= TP 2 to TP 1 ==============================
         Register TP 2 ( /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-151031_ses-wave2_run-01_T1w_corrected.nii.gz )
          to      TP 1 ( /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-151031_ses-wave1_run-01_T1w_corrected.nii.gz )


[init] ========================= TP 3 to TP 1 ==============================
         Register TP 3 ( /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct2/sub-151031_ses-wave3_run-01_T1w_corrected.nii.gz )
          to      TP 1 ( /scratch/fmriprep_wf/single_subject_151031_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-151031_ses-wave1_run-01_T1w_corrected.nii.gz )

       -- Original : (1, 0.976562, 0.976562)mm and (176, 256, 256) voxels.
       -- Resampled: (0.976562, 0.976562, 0.976562)mm and (181, 256, 256) voxels.
       -- Reslicing using cubic bspline 
       -- Original : (1, 0.976562, 0.976562)mm and (176, 256, 256) voxels.
       -- Resampled: (0.976562, 0.976562, 0.976562)mm and (181, 256, 256) voxels.
       -- Reslicing using cubic bspline 
MRItoBSpline degree 3
MRItoBSpline degree 3
       -- Original : (1, 0.976562, 0.976562)mm and (176, 256, 256) voxels.
       -- Resampled: (0.976562, 0.976562, 0.976562)mm and (181, 256, 256) voxels.
       -- Reslicing using cubic bspline 
       -- Original : (1, 0.976562, 0.976562)mm and (176, 256, 256) voxels.
       -- Resampled: (0.976562, 0.976562, 0.976562)mm and (181, 256, 256) voxels.
       -- Reslicing using cubic bspline 
MRItoBSpline degree 3
MRItoBSpline degree 3

   - Max Resolution used: 2
     -- gpS ( 45 , 64 , 64 )
     -- gpT ( 45 , 64 , 64 )
   - running loop to estimate saturation parameter:

   - Max Resolution used: 2
     -- gpS ( 45 , 64 , 64 )
     -- gpT ( 45 , 64 , 64 )
Standard error:
Killed
Return code: 137

```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

Run docker image command, wait a few hours and crash occurs.

I've been able to "workaround" the crash by running the problem command outside the container
```
    mri_robust_template --satit --fixtp --mov workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-453604_ses-wave1_run-01_T1w_corrected.nii.gz workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-453604_ses-wave2_run-01_T1w_corrected.nii.gz workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct2/sub-453604_ses-wave3_run-01_T1w_corrected.nii.gz --inittp 1 --iscale --noit --template sub-453604_ses-wave1_run-01_T1w_template.nii.gz --subsample 200 --lta workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/t1w_merge/tp1.lta workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/t1w_merge/tp2.lta workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/t1w_merge/tp3.lta
7.1.0

--satit: Will estimate SAT iteratively!
--fixtp: Will map everything to init TP!
--mov: Using workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-453604_ses-wave1_run-01_T1w_corrected.nii.gz as movable/source volume.
--mov: Using workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-453604_ses-wave2_run-01_T1w_corrected.nii.gz as movable/source volume.
--mov: Using workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct2/sub-453604_ses-wave3_run-01_T1w_corrected.nii.gz as movable/source volume.
    Total: 3 input volumes
--inittp: Using TP 1 as target for initialization
--iscale: Enabling intensity scaling!
--noit: Will output only first template (no iterations)!
--template: Using sub-453604_ses-wave1_run-01_T1w_template.nii.gz as template output volume.
--subsample: Will subsample if size is larger than 200 on all axes!
--lta: Will output LTA transforms
Setting iscale ...
reading source 'workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-453604_ses-wave1_run-01_T1w_corrected.nii.gz'...
converting source 'workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-453604_ses-wave1_run-01_T1w_corrected.nii.gz' to bspline ...
MRItoBSpline degree 3
reading source 'workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-453604_ses-wave2_run-01_T1w_corrected.nii.gz'...
converting source 'workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-453604_ses-wave2_run-01_T1w_corrected.nii.gz' to bspline ...
MRItoBSpline degree 3
reading source 'workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct2/sub-453604_ses-wave3_run-01_T1w_corrected.nii.gz'...
converting source 'workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct2/sub-453604_ses-wave3_run-01_T1w_corrected.nii.gz' to bspline ...
MRItoBSpline degree 3

MultiRegistration::initializing Xforms (init 1 , maxres 0 , iterate 5 , epsit 0.01 ) : 

[init] ========================= TP 2 to TP 1 ==============================
         Register TP 2 ( workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct1/sub-453604_ses-wave2_run-01_T1w_corrected.nii.gz )
          to      TP 1 ( workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-453604_ses-wave1_run-01_T1w_corrected.nii.gz )

       -- Original : (1, 0.976562, 0.976562)mm and (176, 256, 256) voxels.
       -- Resampled: (0.976562, 0.976562, 0.976562)mm and (181, 256, 256) voxels.
       -- Reslicing using cubic bspline 
MRItoBSpline degree 3
       -- Original : (1, 0.976562, 0.976562)mm and (176, 256, 256) voxels.
       -- Resampled: (0.976562, 0.976562, 0.976562)mm and (181, 256, 256) voxels.
       -- Reslicing using cubic bspline 
MRItoBSpline degree 3

   - Max Resolution used: 2
     -- gpS ( 45 , 64 , 64 )
     -- gpT ( 45 , 64 , 64 )
   - running loop to estimate saturation parameter:
Adjusting final transform due to initial resampling (voxel or size changes) ...
Adjusting final transform due to initial resampling (voxel or size changes) ...

[init] ========================= TP 3 to TP 1 ==============================
         Register TP 3 ( workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct2/sub-453604_ses-wave3_run-01_T1w_corrected.nii.gz )
          to      TP 1 ( workdir/fmriprep_wf/single_subject_453604_wf/anat_preproc_wf/anat_template_wf/n4_correct/mapflow/_n4_correct0/sub-453604_ses-wave1_run-01_T1w_corrected.nii.gz )

       -- Original : (1, 0.976562, 0.976562)mm and (176, 256, 256) voxels.
       -- Resampled: (0.976562, 0.976562, 0.976562)mm and (181, 256, 256) voxels.
       -- Reslicing using cubic bspline 
MRItoBSpline degree 3
       -- Original : (1, 0.976562, 0.976562)mm and (176, 256, 256) voxels.
       -- Resampled: (0.976562, 0.976562, 0.976562)mm and (181, 256, 256) voxels.
       -- Reslicing using cubic bspline 
MRItoBSpline degree 3

   - Max Resolution used: 2
     -- gpS ( 45 , 64 , 64 )
     -- gpT ( 45 , 64 , 64 )
   - running loop to estimate saturation parameter:
Adjusting final transform due to initial resampling (voxel or size changes) ...
Adjusting final transform due to initial resampling (voxel or size changes) ...
mapping movs and creating initial template...
 allow intensity scaling
 using median 
       -- Template : (1, 0.976562, 0.976562)mm and (176, 256, 256) voxels.
Writing final template: sub-453604_ses-wave1_run-01_T1w_template.nii.gz
Writing final transforms (warps etc.)...
 Determinant( lta[ 0 ]) : 1

 Determinant( lta[ 1 ]) : 1

 Determinant( lta[ 2 ]) : 1

registration took 10 minutes and 9 seconds.

 Thank you for using RobustTemplate! 
 If you find it useful and use it for a publication, please cite: 

 Within-Subject Template Estimation for Unbiased Longitudinal Image Analysis
 M. Reuter, N.J. Schmansky, H.D. Rosas, B. Fischl. NeuroImage 2012.
 http://dx.doi.org/10.1016/j.neuroimage.2012.02.084
 http://reuter.mit.edu/papers/reuter-long12.pdf
```

**Comment by effigies** [comment]
I think the return code indicates a memory issue. How much memory is available to fmriprep?

**Comment by seldamat** [comment]
FYI for anyone who wanders unto this thread. I found the best performance for my use case was to run a single docker container with maximum memory (128GB in my case) and with all available processors. The load balancing appears to perform much better within docker than using a grid engine or something like GNU parallel to manage jobs. I believe the main issue is related to the high overhead associated with running multiple containers in OSX. I know that the docker documentation & support offers some very detailed information regarding optimizing docker for OSX but it may just be easier to run a single docker container and call it a day if you have enough resources on your system.
