### ISSUE TITLE
Mismatch in T1 and its mask affines

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#222]
As highlighted by: 

https://github.com/poldracklab/fmriprep/pull/220

failing test:

https://circleci.com/gh/poldracklab/fmriprep/383?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
161205-07:30:57,481 niworkflows INFO:

	 Retry #0, commandline: 

antsRegistration --collapse-output-transforms 1 --dimensionality 3 --masks [ /root/src/niworkflows/niworkflows/data/templates/mni_icbm152_nlin_asym_09c/2mm_brainmask.nii.gz, /scratch/workflow_enumerator/01/t1w_preprocessing/AFNISkullStripWorkflow/binarize/sub-01_T1w_out_corrected_calc_thresh.nii.gz ] --float 1 --initial-moving-transform [ /root/src/niworkflows/niworkflows/data/templates/mni_icbm152_nlin_asym_09c/2mm_T1.nii.gz, /scratch/workflow_enumerator/01/t1w_preprocessing/CorrectINU/sub-01_T1w_out_corrected.nii.gz, 1 ] --initialize-transforms-per-stage 0 --interpolation Linear --output [ ants_t1_to_mni, ants_t1_to_mni_Warped.nii.gz ] --transform Rigid[ 1.0 ] --metric Mattes[ /root/src/niworkflows/niworkflows/data/templates/mni_icbm152_nlin_asym_09c/2mm_T1.nii.gz, /scratch/workflow_enumerator/01/t1w_preprocessing/CorrectINU/sub-01_T1w_out_corrected.nii.gz, 1, 56, Random, 0.2 ] --convergence [ 20, 1e-07, 15 ] --smoothing-sigmas 4.0mm --shrink-factors 2 --use-estimate-learning-rate-once 1 --use-histogram-matching 0 --transform Affine[ 1.0 ] --metric Mattes[ /root/src/niworkflows/niworkflows/data/templates/mni_icbm152_nlin_asym_09c/2mm_T1.nii.gz, /scratch/workflow_enumerator/01/t1w_preprocessing/CorrectINU/sub-01_T1w_out_corrected.nii.gz, 1, 56, Random, 0.1 ] --convergence [ 15, 1e-08, 5 ] --smoothing-sigmas 2.0mm --shrink-factors 1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --winsorize-image-intensities [ 0.005, 0.995 ]  --write-composite-transform 0

161205-07:31:03,709 niworkflows INFO:

	 Successful spatial normalization (retry #0).

161205-07:31:03,712 niworkflows INFO:

	 Report - setting fixed (/root/src/niworkflows/niworkflows/data/templates/mni_icbm152_nlin_asym_09c/2mm_T1.nii.gz) and moving (/scratch/workflow_enumerator/01/t1w_preprocessing/T1_2_MNI_Registration/ants_t1_to_mni_Warped.nii.gz) images

/usr/local/miniconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.

  "This module will be removed in 0.20.", DeprecationWarning)

161205-07:31:04,28 niworkflows INFO:

	 Generating visual report

Traceback (most recent call last):

  File "/root/src/nipype/nipype/pipeline/plugins/base.py", line 249, in run

    result=result))

  File "/root/src/nipype/nipype/pipeline/plugins/base.py", line 294, in _clean_queue

    raise RuntimeError("".join(result['traceback']))

RuntimeError: Traceback (most recent call last):

  File "/root/src/nipype/nipype/pipeline/plugins/multiproc.py", line 52, in run_node

    result['result'] = node.run(updatehash=updatehash)

  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 367, in run

    self._run_interface()

  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 477, in _run_interface

    self._result = self._run_command(execute)

  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 607, in _run_command

    result = self._interface.run()

  File "/root/src/nipype/nipype/interfaces/base.py", line 1085, in run

    runtime = self._run_wrapper(runtime)

  File "/root/src/nipype/nipype/interfaces/base.py", line 1033, in _run_wrapper

    runtime = self._run_interface(runtime)

  File "/root/src/niworkflows/niworkflows/common/report.py", line 59, in _run_interface

    self._generate_report()

  File "/root/src/niworkflows/niworkflows/common/report.py", line 140, in _generate_report

    self._moving_image_mask),

  File "/usr/local/miniconda/lib/python3.5/site-packages/nilearn/masking.py", line 564, in apply_mask

    ensure_finite=ensure_finite)

  File "/usr/local/miniconda/lib/python3.5/site-packages/nilearn/masking.py", line 590, in _apply_mask_fmri

    str(get_affine(imgs_img))))

ValueError: Mask affine: 

[[  -4.           -0.           -0.           79.        ]

 [  -0.            4.           -0.         -133.00003052]

 [   0.            0.            4.         -129.00003052]

 [   0.            0.            0.            1.        ]]

 is different from img affine:

[[   2.     0.    -0.   -96.5]

 [   0.     2.    -0.  -132.5]

 [   0.     0.     2.   -78.5]

 [   0.     0.     0.     1. ]]

Interface RobustMNINormalizationRPT failed to run. 
```

**Comment by chrisfilo** [comment]
I don't see this problem in real data - I wonder if this has something to do with the downsampled nature of the test data.

**Comment by oesteban** [comment]
For some reason, nibabel is reporting  a weird affine. This is the output of mri_info on failing downsamlped data:

```
Volume information for /home/oesteban/tmp/fmriprep-tests/work/workflow_enumerator/119/t1w_preprocessing/AFNISkullStripWorkflow/binarize/sub-119_T1w_corrected_calc_thresh.nii.gz
          type: nii
    dimensions: 47 x 64 x 64
   voxel sizes: 3.6000, 3.5936, 3.5936
          type: FLOAT (3)
           fov: 169.200
           dof: 0
        xstart: -84.6, xend: 84.6
        ystart: -115.0, yend: 115.0
        zstart: -115.0, zend: 115.0
            TR: 0.00 msec, TE: 0.00 msec, TI: 0.00 msec, flip angle: 0.00 degrees
       nframes: 1
       PhEncDir: UNKNOWN
ras xform present
    xform info: x_r =   1.0000, y_r =   0.0000, z_r =   0.0000, c_r =    -3.3878
              : x_a =   0.0000, y_a =   1.0000, z_a =   0.0000, c_a =    19.1494
              : x_s =   0.0000, y_s =   0.0000, z_s =   1.0000, c_s =    -2.9576
Orientation   : RAS
Primary Slice Direction: axial

voxel to ras transform:
                3.6000   0.0000   0.0000   -87.9878
                0.0000   3.5936   0.0000   -95.8458
                0.0000   0.0000   3.5936  -117.9528
                0.0000   0.0000   0.0000     1.0000

voxel-to-ras determinant 46.4903

ras to voxel transform:
                0.2778  -0.0000  -0.0000    24.4411
               -0.0000   0.2783  -0.0000    26.6713
               -0.0000  -0.0000   0.2783    32.8230
                0.0000   0.0000   0.0000     1.0000
Volume information for /home/oesteban/tmp/fmriprep-tests/work/workflow_enumerator/119/t1w_preprocessing/CorrectINU/sub-119_T1w_corrected.nii.gz
          type: nii
    dimensions: 47 x 64 x 64
   voxel sizes: 3.6000, 3.5936, 3.5936
          type: FLOAT (3)
           fov: 169.200
           dof: 0
        xstart: -84.6, xend: 84.6
        ystart: -115.0, yend: 115.0
        zstart: -115.0, zend: 115.0
            TR: 0.00 msec, TE: 0.00 msec, TI: 0.00 msec, flip angle: 0.00 degrees
       nframes: 1
       PhEncDir: UNKNOWN
ras xform present
    xform info: x_r =   1.0000, y_r =   0.0000, z_r =  -0.0000, c_r =    -3.3878
              : x_a =   0.0000, y_a =   1.0000, z_a =  -0.0000, c_a =    19.1494
              : x_s =   0.0000, y_s =   0.0000, z_s =   1.0000, c_s =    -2.9576
Orientation   : RAS
Primary Slice Direction: axial

voxel to ras transform:
                3.6000   0.0000  -0.0000   -87.9878
                0.0000   3.5936  -0.0000   -95.8458
                0.0000   0.0000   3.5936  -117.9528
                0.0000   0.0000   0.0000     1.0000

voxel-to-ras determinant 46.4903

ras to voxel transform:
                0.2778  -0.0000  -0.0000    24.4411
               -0.0000   0.2783  -0.0000    26.6713
               -0.0000  -0.0000   0.2783    32.8230
                0.0000   0.0000   0.0000     1.0000
```

**Comment by oesteban** [comment]
Ok, we just figured it out. The moving image is not the original one, it is resampled into the fixed image space. That's why affines don't match.
