### ISSUE TITLE
Node summary failed to run on host dev1.soichi.us.

### ISSUE THREAD

**Issue by soichih** [poldracklab/fmriprep#2222]
Hello. 

I am running into an error message that says `Node summary failed to run on host dev1.soichi.us.` I am not sure what this means and I am hoping someone could help me troubleshoot it.

I am running fmriprep 20.1.1 via singularity like this

```
singularity exec -e docker://poldracklab/fmriprep:20.1.1 /usr/local/miniconda/bin/fmriprep --notrack --resource-monitor --skip-bids-validation --md-only-boilerplate --stop-on-first-crash --use-plugin=multi_proc.yml --output-spaces fsnative MNI152NLin2009cAsym --force-bbr --use-syn-sdc --fs-license-file=license.txt --skull-strip-template=NKI --work-dir=fmripworkdir --participant_label=1 bids fmripout participant
```

And I am seeing the following error message.

```
INFO:    Creating SIF file...
200722-04:01:49,410 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 20.1.1:
      * BIDS dataset path: /mnt/scratch/hayashis/syncthing/git/app-fmriprep/bids.
      * Participant list: ['1'].
      * Run identifier: 20200722-040140_e383e20a-5f01-499f-8cf5-cef723e43aec.
      * Output spaces: fsnative MNI152NLin2009cAsym:res-native.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripout/freesurfer.
200722-04:02:06,323 nipype.workflow INFO:
	 No single-band-reference found for sub-1_ses-1_run-1_task-rest_bold.nii.gz.
200722-04:02:23,453 nipype.workflow IMPORTANT:
	 Slice-timing correction will be included.
200722-04:02:33,985 nipype.workflow INFO:
	 fMRIPrep workflow graph with 382 nodes built successfully.
200722-04:02:42,250 nipype.workflow IMPORTANT:
	 fMRIPrep started!
Downloading https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T1w.nii.gz
1.72kB [00:00, 9.59kB/s]                                                                                                  
200722-04:02:52,147 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_1_wf.func_preproc_ses_1_run_1_task_rest_wf.func_derivatives_wf.raw_sources" in "/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/func_preproc_ses_1_run_1_task_rest_wf/func_derivatives_wf/raw_sources".
200722-04:02:52,152 nipype.workflow INFO:
	 [Node] Running "raw_sources" ("nipype.interfaces.utility.wrappers.Function")
200722-04:02:52,162 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_1_wf.func_preproc_ses_1_run_1_task_rest_wf.func_derivatives_wf.raw_sources".
200722-04:02:53,379 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_1_wf.anat_preproc_wf.brain_extraction_wf.lap_tmpl" in "/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/anat_preproc_wf/brain_extraction_wf/lap_tmpl".
200722-04:02:53,382 nipype.workflow INFO:
	 [Node] Running "lap_tmpl" ("niworkflows.interfaces.ants.ImageMath"), a CommandLine Interface with command:
ImageMath 3 tpl-NKI_res-01_T1w_maths.nii.gz Laplacian /home/hayashis/git/app-fmriprep/templateflow/tpl-NKI/tpl-NKI_res-01_T1w.nii.gz 1.5 1
200722-04:02:53,384 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_1_wf.func_preproc_ses_1_run_1_task_rest_wf.bold_reference_wf.validate" in "/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/func_preproc_ses_1_run_1_task_rest_wf/bold_reference_wf/validate".
200722-04:02:53,386 nipype.workflow INFO:
	 [Node] Running "validate" ("niworkflows.interfaces.images.ValidateImage")
200722-04:02:53,407 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_1_wf.func_preproc_ses_1_run_1_task_rest_wf.bold_reference_wf.validate".
200722-04:02:53,490 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_1_wf.anat_preproc_wf.brain_extraction_wf.res_tmpl" in "/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/anat_preproc_wf/brain_extraction_wf/res_tmpl".
200722-04:02:53,494 nipype.workflow INFO:
	 [Node] Running "res_tmpl" ("niworkflows.interfaces.ants.ResampleImageBySpacing"), a CommandLine Interface with command:
ResampleImageBySpacing 3 /home/hayashis/git/app-fmriprep/templateflow/tpl-NKI/tpl-NKI_res-01_T1w.nii.gz tpl-NKI_res-01_T1w_resampled.nii.gz 4 4 4 1
200722-04:02:53,960 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_1_wf.bidssrc" in "/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/bidssrc".
200722-04:02:53,962 nipype.workflow INFO:
	 [Node] Running "bidssrc" ("niworkflows.interfaces.bids.BIDSDataGrabber")
200722-04:02:53,964 nipype.interface INFO:
	 No "flair" images found for sub-1
200722-04:02:53,964 nipype.interface INFO:
	 No "sbref" images found for sub-1
200722-04:02:53,964 nipype.interface INFO:
	 No "roi" images found for sub-1
200722-04:02:53,968 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_1_wf.bidssrc".
200722-04:02:57,405 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_1_wf.anat_preproc_wf.brain_extraction_wf.res_tmpl".
200722-04:03:01,87 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_1_wf.func_preproc_ses_1_run_1_task_rest_wf.bold_reference_wf.gen_ref" in "/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/func_preproc_ses_1_run_1_task_rest_wf/bold_reference_wf/gen_ref".
200722-04:03:01,99 nipype.workflow INFO:
	 [Node] Running "gen_ref" ("niworkflows.interfaces.registration.EstimateReferenceImage")
200722-04:03:01,148 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_1_wf.anat_preproc_wf.anat_template_wf.t1w_ref_dimensions" in "/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/anat_preproc_wf/anat_template_wf/t1w_ref_dimensions".
200722-04:03:01,524 nipype.workflow INFO:
	 [Node] Running "t1w_ref_dimensions" ("niworkflows.interfaces.images.TemplateDimensions")
200722-04:03:01,639 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_1_wf.anat_preproc_wf.anat_template_wf.t1w_ref_dimensions".
200722-04:03:01,687 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_1_wf.bids_info" in "/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/bids_info".
200722-04:03:01,692 nipype.workflow INFO:
	 [Node] Running "bids_info" ("niworkflows.interfaces.bids.BIDSInfo")
200722-04:03:01,706 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_1_wf.bids_info".
200722-04:03:02,882 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_1_wf.anat_preproc_wf.anat_derivatives_wf.raw_sources" in "/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/anat_preproc_wf/anat_derivatives_wf/raw_sources".
200722-04:03:03,1 nipype.interface INFO:
	 stderr 2020-07-22T04:03:03.001351:++ 3dvolreg: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
200722-04:03:03,2 nipype.interface INFO:
	 stderr 2020-07-22T04:03:03.001351:++ Authored by: RW Cox
200722-04:03:03,22 nipype.interface INFO:
	 stderr 2020-07-22T04:03:03.022838:++ Coarse del was 10, replaced with 5
200722-04:03:04,49 nipype.workflow WARNING:
	 Storing result file without outputs
200722-04:03:04,49 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_1_wf.summary" (/mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripworkdir/fmriprep_wf/single_subject_1_wf/summary)
200722-04:03:04,51 nipype.workflow ERROR:
	 Node summary failed to run on host dev1.soichi.us.
200722-04:03:04,52 nipype.workflow ERROR:
	 Saving crash info to /mnt/scratch/hayashis/syncthing/git/app-fmriprep/fmripout/fmriprep/sub-1/log/20200722-040140_e383e20a-5f01-499f-8cf5-cef723e43aec/crash-20200722-040304-hayashis-summary-868d2c3a-58b1-4d2e-8cd2-8ba795ed4f7e.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 432, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 100, in _run_interface
    return super(SubjectSummary, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 64, in _run_interface
    segment = self._generate_segment()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 133, in _generate_segment
    for series in bold_series)
  File "/usr/local/miniconda/lib/python3.7/collections/__init__.py", line 566, in __init__
    self.update(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.7/collections/__init__.py", line 653, in update
    _count_elements(self, iterable)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 133, in <genexpr>
    for series in bold_series)
TypeError: 'NoneType' object is not subscriptable

200722-04:03:04,53 nipype.workflow CRITICAL:
	 fMRIPrep failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 432, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 100, in _run_interface
    return super(SubjectSummary, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 64, in _run_interface
    segment = self._generate_segment()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 133, in _generate_segment
    for series in bold_series)
  File "/usr/local/miniconda/lib/python3.7/collections/__init__.py", line 566, in __init__
    self.update(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.7/collections/__init__.py", line 653, in update
    _count_elements(self, iterable)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/interfaces/reports.py", line 133, in <genexpr>
    for series in bold_series)
TypeError: 'NoneType' object is not subscriptable

200722-04:03:04,152 nipype.workflow INFO:
	 [Node] Running "raw_sources" ("nipype.interfaces.utility.wrappers.Function")
200722-04:03:04,157 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_1_wf.anat_preproc_wf.anat_derivatives_wf.raw_sources".
200722-04:03:04,654 cli ERROR:
	 Preprocessing did not finish successfully. Errors occurred while processing data from participants: 1 (1). Check the HTML reports for details.

real	20m35.341s
user	47m27.968s
sys	3m52.274s
You have new mail in /var/mail/hayashis

```

My BIDS input directory contains the following files

```
bids/
├── dataset_description.json
├── derivatives
│   └── 5e00405dcc6723f5c2bd18e7
│       └── sub-1
│           └── ses-1
│               └── dt-58cb22c8e13a50849b25882e.todo
│                   ├── sub-1_ses-1_run-1_freesurfer.json
│                   └── sub-1_ses-1_run-1_output -> ../../../../../../testdata/freesurfer/output
└── sub-1
    └── ses-1
        ├── anat
        │   ├── sub-1_ses-1_run-1_T1w.json
        │   ├── sub-1_ses-1_run-1_T1w.nii.gz -> ../../../../testdata/t1/t1.nii.gz
        │   ├── sub-1_ses-1_run-1_T2w.json
        │   └── sub-1_ses-1_run-1_T2w.nii.gz -> ../../../../testdata/t2/t2.nii.gz
        ├── fmap
        │   ├── sub-1_ses-1_run-1_magnitude1.nii.gz -> ../../../../testdata/fmap/magnitude1.nii.gz
        │   ├── sub-1_ses-1_run-1_magnitude2.nii.gz -> ../../../../testdata/fmap/magnitude2.nii.gz
        │   ├── sub-1_ses-1_run-1_phase1.json -> ../../../../testdata/fmap/phase1.json
        │   ├── sub-1_ses-1_run-1_phase1.nii.gz -> ../../../../testdata/fmap/phase1.nii.gz
        │   ├── sub-1_ses-1_run-1_phase2.json -> ../../../../testdata/fmap/phase2.json
        │   └── sub-1_ses-1_run-1_phase2.nii.gz -> ../../../../testdata/fmap/phase2.nii.gz
        └── func
            ├── sub-1_ses-1_run-1_task-rest_bold.json
            └── sub-1_ses-1_run-1_task-rest_bold.nii.gz -> ../../../../testdata/bold/bold.nii.gz

11 directories, 14 files

```

bids-validator reports some error, but nothing that I believe is causing the error message I am seeing.

```
bids-validator@1.5.4

	1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
		./sub-1/ses-1/func/sub-1_ses-1_run-1_task-rest_bold.json
			Evidence: sub-1_ses-1_run-1_task-rest_bold.json
		./sub-1/ses-1/func/sub-1_ses-1_run-1_task-rest_bold.nii.gz
			Evidence: sub-1_ses-1_run-1_task-rest_bold.nii.gz

	Please visit https://neurostars.org/search?q=NOT_INCLUDED for existing conversations about this issue.

	2: [ERR] 'IntendedFor' field needs to point to an existing file. (code: 37 - INTENDED_FOR)
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase1.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-hands_bold.nii.gz
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase1.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-rest_bold.nii.gz
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase1.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-sleepiness_bold.nii.gz
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase2.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-hands_bold.nii.gz
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase2.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-rest_bold.nii.gz
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase2.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-sleepiness_bold.nii.gz

	Please visit https://neurostars.org/search?q=INTENDED_FOR for existing conversations about this issue.

	1: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

	Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.

	2: [WARN] The Authors field of dataset_description.json should contain an array of fields - with one author per field. This was triggered because there are no authors, which will make DOI registration from dataset metadata impossible. (code: 113 - NO_AUTHORS)

	Please visit https://neurostars.org/search?q=NO_AUTHORS for existing conversations about this issue.


        Summary:                  Available Tasks:        Available Modalities: 
        13 Files, 244.42MB                                T1w                   
        1 - Subject                                       T2w                   
        1 - Session                                       fieldmap              


	If you have any questions, please post on https://neurostars.org/tags/bids.

```

Thank you for your help!

**Comment by mgxd** [comment]
@soichih it looks like you have 2 errors with your dataset:

```
1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
		./sub-1/ses-1/func/sub-1_ses-1_run-1_task-rest_bold.json
			Evidence: sub-1_ses-1_run-1_task-rest_bold.json
		./sub-1/ses-1/func/sub-1_ses-1_run-1_task-rest_bold.nii.gz
			Evidence: sub-1_ses-1_run-1_task-rest_bold.nii.gz

	Please visit https://neurostars.org/search?q=NOT_INCLUDED for existing conversations about this issue.

	2: [ERR] 'IntendedFor' field needs to point to an existing file. (code: 37 - INTENDED_FOR)
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase1.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-hands_bold.nii.gz
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase1.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-rest_bold.nii.gz
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase1.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-sleepiness_bold.nii.gz
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase2.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-hands_bold.nii.gz
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase2.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-rest_bold.nii.gz
		./sub-1/ses-1/fmap/sub-1_ses-1_run-1_phase2.nii.gz
			Evidence: ses-1/func/sub-9001_ses-1_task-sleepiness_bold.nii.gz
```

You'll have to fix these, the first one is likely the reason for your error.

**Comment by soichih** [comment]
Thanks. I've fixed the first issue and it seems to be working now. I am closing this ticket.
