### ISSUE TITLE
Fieldmap JSON file error adding IntendedFor  and Units

### ISSUE THREAD

**Issue by mbichin** [poldracklab/fmriprep#2229]
Hello,
When I run FMRIPrep with this code:

```
fmriprep-docker /mnt/DATA/Trajectories_Data/Brain/rs_data_fmriprep_input/ /mnt/DATA/Trajectories_Data/Brain/rs_data_fmriprep_output/ participant --participant_label regtrj040 --task-id rest --fs-license-file /usr/local/freesurfer/license.txt --output-space MNI152NLin6Asym --use-aroma --fs-no-reconall --fd-spike-threshold 2 --force-bbr --dummy-scans 0 --n-cpus 7 --mem-mb 30000 -v --notrack 
```
I am getting this error:

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 226, in index_metadata
    payload = json.load(handle)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 11 column 2 (char 316)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 568, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 548, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 186, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 396, in init
    "derivatives", re.compile(r'^\.')))
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 262, in __init__
    indexer.index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 230, in index_metadata
    raise IOError(msg) from e
OSError: Error occurred while trying to decode JSON from file '/data/sub-regtrj040/fmap/sub-regtrj040_acq-b0mapsplit_run-01_fieldmap.json'.

```
which happens only after i add the units and IndtendedFor entries to the fieldmap json, otherwise it runs fine.

This is my json file:

```
{
	"Modality": "MR",
	"MagneticFieldStrength": 3,
	"Manufacturer": "GE",
	"ManufacturersModelName": "DISCOVERY_MR750",
	"InstitutionName": "XXX",
	"DeviceSerialNumber": "XXX",
	"StationName": "MR01OC01",
	"Units": "rad/s",
	"IntendedFor": "func/sub-regtrj050_task-rest  _bold.nii.gz"
	"PatientPosition": "HFS",
	"SoftwareVersions": "25_LX_MR_Software_release:DV25.0_R01_1451.a",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "B0map",
	"ProtocolName": "B0map",
	"ScanningSequence": "RM",
	"SequenceVariant": "NONE",
	"ScanOptions": "VB_GEMS_EDR_GEMS",
	"ImageType": ["ORIGINAL", "PRIMARY", "OTHER"],
	"SeriesNumber": 6,
	"AcquisitionTime": "10:55:11.000000",
	"AcquisitionNumber": 1,
	"SliceThickness": 3,
	"SpacingBetweenSlices": 3,
	"SAR": 0.252914,
	"EchoTime": 0.004608,
	"RepetitionTime": 0.575,
	"FlipAngle": 50,
	"PercentPhaseFOV": 100,
	"AcquisitionMatrixPE": 96,
	"ReconMatrixPE": 256,
	"EffectiveEchoSpacing": 0.002304,
	"TotalReadoutTime": 0.58752,
	"PixelBandwidth": 244.141,
	"PhaseEncodingAxis": "i",
	"ImageOrientationPatientDICOM": [
		0.987645,
		0.0994167,
		0.121138,
		-0.106643,
		0.992792,
		0.0546929	],
	"InPlanePhaseEncodingDirectionDICOM": "ROW",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20180404 Clang5.1.0"
}

```
Any insights as to what i am doing incorrectly?

**Comment by mbichin** [comment]
Nevermind... sorry, forgot the ","...
