### ISSUE TITLE
KeyError matplotlib

### ISSUE THREAD

**Issue by bdeck8317** [poldracklab/fmriprep#2273]
Hello, I am attempting to obtain processed resting state bold data. I keep running into this issue for a handful of subjects. Any thoughts?

### What version of fMRIPrep are you using?
fmriprep:20.1.2

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Docker
### What is the exact command-line you used?
```
screen  fmriprep-docker  /Users/neurouser1/Documents/DP5/bids_directory \
 /Users/neurouser1/Documents/DP5/xcp/fmriprep_out \
 --output-spaces fsaverage T1w \
 --participant_label sub-DP5030 sub-DP5047 sub-DP5037 sub-DP5035 sub-DP5033 sub-DP5032 sub-DP5027 \
 --fs-license-file /Applications/freesurfer/license.txt \
 --ignore slicetiming

```

### Have you checked that your inputs are BIDS valid?
Yes

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
Node: fmriprep_wf.single_subject_DP5037_wf.func_preproc_ses_NavonShamStim_task_rest_run_2_wf.sdc_unwarp_report_wf.bold_rpt
Working directory: /tmp/work/fmriprep_wf/single_subject_DP5037_wf/func_preproc_ses_NavonShamStim_task_rest_run_2_wf/sdc_unwarp_report_wf/bold_rpt

Node inputs:

after = <undefined>
after_label = after
before = <undefined>
before_label = before
compress_report = auto
out_report = report.svg
wm_seg = <undefined>


Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 420, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/registration.py", line 357, in _post_run_hook
    return super(SimpleBeforeAfterRPT, self)._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/report_base.py", line 79, in _generate_report
    compress=self.inputs.compress_report,
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 337, in plot_registration
    svg = extract_svg(display, compress=compress)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 124, in extract_svg
    image_svg = svg2str(display_object, dpi)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 117, in svg2str
    image_buf, dpi=dpi, format="svg", facecolor="k", edgecolor="k"
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/figure.py", line 2035, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/backends/backend_svg.py", line 1210, in print_svg
    result = self._print_svg(filename, fh, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/backends/backend_svg.py", line 1240, in _print_svg
    self.figure.draw(renderer)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2543, in draw
    pos = locator(self, renderer)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/plotting/displays.py", line 1649, in _locator
    return transforms.Bbox([[left_dict[axes], y0],
KeyError: <matplotlib.axes._axes.Axes object at 0x7f89e9425d68>

```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
Yes

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.
```
[environment]
cpu_count = 27
exec_docker_version = "19.03.12"
exec_env = "fmriprep-docker"
free_mem = 15.7
overcommit_policy = "always"
overcommit_limit = "50%"
nipype_version = "1.5.1"
templateflow_version = "0.6.3"
version = "20.1.2"

[execution]
bids_dir = "/data"
bids_description_hash = "a0cf9572d635349e5136a732c74e622b2123109962fa41c97b030cda51159bdb"
boilerplate_only = false
debug = false
fs_license_file = "/opt/freesurfer/license.txt"
fs_subjects_dir = "/out/freesurfer"
layout = "BIDS Layout: .../data | Subjects: 44 | Sessions: 64 | Runs: 88"
log_dir = "/out/fmriprep/logs"
log_level = 25
low_mem = false
md_only_boilerplate = false
notrack = false
output_dir = "/out"
output_spaces = "fsaverage:den-164k T1w"
reports_only = false
run_uuid = "20200915-185441_6a9f6eca-fcc5-4ab0-9519-07c14e4b160c"
participant_label = [ "DP5027", "DP5030", "DP5032", "DP5033", "DP5035", "DP5037", "DP5047",]
templateflow_home = "/home/fmriprep/.cache/templateflow"
work_dir = "/tmp/work"
write_graph = false


[workflow]
anat_only = false
aroma_err_on_warn = false
aroma_melodic_dim = -200
bold2t1w_dof = 6
bold2t1w_init = "register"
cifti_output = false
fmap_bspline = false
force_syn = false
hires = true
ignore = [ "slicetiming",]
longitudinal = false
medial_surface_nan = false
regressors_all_comps = false
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"
spaces = "fsaverage:den-164k T1w MNI152NLin2009cAsym"
use_aroma = false
use_syn_sdc = false

[nipype]
crashfile_format = "txt"
get_linked_libs = false
nprocs = 27
omp_nthreads = 8
plugin = "MultiProc"
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 7339
ants = 47963

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false

**Comment by oesteban** [comment]
This is an instance of nipreps/niworkflows#559 - Could you try fMRIPrep 20.1.3? this should be fixed in this latest stable release.

**Comment by bdeck8317** [comment]
@oesteban , thanks for the prompt response. Will let you know if it's still an issue.
