### ISSUE TITLE
Docs fail to build on RTD: AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#283]
https://readthedocs.org/projects/fmriprep/builds/4793152/
```
Running Sphinx v1.3.5
making output directory...
/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/src/nipype/nipype/workflows/dmri/mrtrix/group_connectivity.py:16: UserWarning: cmp not installed
  warnings.warn('cmp not installed')
161216-06:56:54,353 interface WARNING:
	 afni_vcheck executable not found.
161216-06:56:54,354 interface WARNING:
	 FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
161216-06:56:54,358 interface WARNING:
	 FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
161216-06:56:54,424 interface WARNING:
	 FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
161216-06:56:54,447 interface WARNING:
	 FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
161216-06:56:54,449 interface WARNING:
	 FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 315, in <module>
    ds005_wf = wf_ds005_type({'func': 'fake data'}, {'ants_nthreads': 1, 'output_dir': 'x', 'biggest_epi_file_size_gb': 1, 'skip_native': True})
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/fmriprep-0.1.2a3-py2.7.egg/fmriprep/workflows/base.py", line 181, in wf_ds005_type
    epi_2_t1 = epi_mean_t1_registration(settings=settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/fmriprep-0.1.2a3-py2.7.egg/fmriprep/workflows/epi.py", line 174, in epi_mean_t1_registration
    'etc/flirtsch/bbr.sch')
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
The full traceback has been saved in /tmp/sphinx-err-AX6Xe9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by oesteban** [comment]
Fixed in #284 ?
