### ISSUE TITLE
Installation problem: template not found

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#300]
In this second batch of fmriprep executions, none of the reports are generated for this problem:

```
Traceback (most recent call last):
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/bin/fmriprep", line 9, in <module>
    load_entry_point('fmriprep==0.1.2a3', 'console_scripts', 'fmriprep')()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/fmriprep-0.1.2a3-py2.7.egg/fmriprep/run_workflow.py", line 78, in main
    create_workflow(opts)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/fmriprep-0.1.2a3-py2.7.egg/fmriprep/run_workflow.py", line 167, in create_wor
kflow
    run_reports(settings['output_dir'])
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/fmriprep-0.1.2a3-py2.7.egg/fmriprep/viz/reports.py", line 147, in run_reports
    report.generate_report()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/fmriprep-0.1.2a3-py2.7.egg/fmriprep/viz/reports.py", line 129, in generate_re
port
    report_tpl = env.get_template('viz/report.tpl')
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: viz/report.tpl
```

**Comment by oesteban** [comment]
I guess that ```viz/*.tpl``` should be listed here https://github.com/poldracklab/fmriprep/blob/master/setup.py#L46 (?)
