### ISSUE TITLE
ImportError: cannot import name wf_ds005_type

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#372]
```
Running Sphinx v1.3.5
making output directory...
/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/src/nipype/nipype/workflows/dmri/mrtrix/group_connectivity.py:16: UserWarning: cmp not installed
  warnings.warn('cmp not installed')

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 18, in <module>
    from fmriprep.workflows.base import wf_ds005_type
ImportError: cannot import name wf_ds005_type

Exception occurred:
  File "conf.py", line 18, in <module>
    from fmriprep.workflows.base import wf_ds005_type
ImportError: cannot import name wf_ds005_type
The full traceback has been saved in /tmp/sphinx-err-Ff4ynh.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

@rwblair let me know if you need access to RTD.

**Comment by effigies** [comment]
Can we add a doc build to Circle? This has happened a couple times.
