### ISSUE TITLE
Reconstruction won't run on uh2/sub-s483

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#377]
Getting errors in an odd spot. Suspect it's an issue with content-based hashing, and thus an upstream problem, but in case somebody recognizes this error:

```
170228-03:34:50,282 workflow DEBUG:
	 setting nodelevel(Reconstruction) input T1_files = ['/data/sub-s483/ses-1/anat/sub-s483_T1w.nii.gz', '/data/sub-s483/ses-2/anat/sub-s483_T1w.nii.gz']
170228-03:34:50,282 workflow DEBUG:
	 input: flags
170228-03:34:50,282 workflow DEBUG:
	 results file: /scratch/workflow_enumerator/s483/t1w_preprocessing/ReconConfig/result_ReconConfig.pklz
170228-03:34:50,283 workflow DEBUG:
	 output: autorecon1_flags
170228-03:34:50,283 workflow DEBUG:
	 setting nodelevel(Reconstruction) input flags = -noskullstrip -hires
170228-03:34:50,283 workflow DEBUG:
	 input: subjects_dir
170228-03:34:50,283 workflow DEBUG:
	 results file: /scratch/workflow_enumerator/BIDSFreesurfer/result_BIDSFreesurfer.pklz
170228-03:34:50,284 workflow DEBUG:
	 output: subjects_dir
170228-03:34:50,284 workflow DEBUG:
	 setting nodelevel(Reconstruction) input subjects_dir = /out/freesurfer
170228-03:34:50,284 workflow DEBUG:
	 input: subject_id
170228-03:34:50,284 workflow DEBUG:
	 results file: /scratch/workflow_enumerator/s483/t1w_preprocessing/BIDSInfo/result_BIDSInfo.pklz
170228-03:34:50,285 workflow DEBUG:
	 Aggregate: True
170228-03:34:50,285 workflow ERROR:
	 ['Node Reconstruction failed to run on host faa084f17eb0.']
170228-03:34:50,285 workflow INFO:
	 Saving crash info to /out/fmriprep/sub-s483/log/20170228-033120_c8d8918e-da23-45b9-bb32-b6ff0a72100f/crash-20170228-033450-root-Reconstruction-4799e741-e2b5-4961-bc42-0c257dcb8a1e.pklz
170228-03:34:50,285 workflow INFO:
	 Traceback (most recent call last):
  File "/root/src/nipype/nipype/pipeline/plugins/multiproc.py", line 300, in _send_procs_to_workers
    jobid].hash_exists()
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 238, in hash_exists
    hashed_inputs, hashvalue = self._get_hashval()
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 401, in _get_hashval
    self._get_inputs()
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 456, in _get_inputs
    output_value = results.outputs.get()[output_name]
AttributeError: 'NoneType' object has no attribute 'get'

Traceback (most recent call last):
  File "/root/src/nipype/nipype/pipeline/plugins/multiproc.py", line 300, in _send_procs_to_workers
    jobid].hash_exists()
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 238, in hash_exists
    hashed_inputs, hashvalue = self._get_hashval()
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 401, in _get_hashval
    self._get_inputs()
  File "/root/src/nipype/nipype/pipeline/engine/nodes.py", line 456, in _get_inputs
    output_value = results.outputs.get()[output_name]
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 9, in <module>
    load_entry_point('fmriprep', 'console_scripts', 'fmriprep')()
  File "/root/src/fmriprep/fmriprep/run_workflow.py", line 88, in main
    create_workflow(opts)
  File "/root/src/fmriprep/fmriprep/run_workflow.py", line 187, in create_workflow
    preproc_wf.run(**plugin_settings)
  File "/root/src/nipype/nipype/pipeline/engine/workflows.py", line 583, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/root/src/nipype/nipype/pipeline/plugins/base.py", line 267, in run
    graph=graph)
  File "/root/src/nipype/nipype/pipeline/plugins/multiproc.py", line 312, in _send_procs_to_workers
    self._clean_queue(jobid, graph)
  File "/root/src/nipype/nipype/pipeline/plugins/base.py", line 300, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
TypeError: 'NoneType' object is not subscriptable
```

**Comment by chrisfilo** [comment]
Hard to gather from this what happened. Could you run it with Linear and
stop_on_first_crash?

**Comment by effigies** [comment]
Forgot Linear. Problem was in a different node.
