### ISSUE TITLE
FileNotFoundError: No functional images found for subject sub-<undefined>

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#399]
For some reason, the BIDSDataGrabber failed for this one subject (328) of the beast. Several issues seem wrong about the `subject_data` input of this case:

- the `'func'` key is empty (likely source of this error)
- the empty keys `'t1'`, and `'fieldmaps'` are generated and empty because values reside under `'t1w'` and `'fmap'`.

The `base_workflow_generator` function does not raise exceptions if no functional images were found. It should.

Finally, there are functional images for this case:

```
$ ls /scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/func
sub-328_task-Beast_run-1_bold.nii.gz   sub-328_task-Beast_run-2_events.tsv    sub-328_task-Beast_run-3_sbref.nii.gz  sub-328_task-reward_run-1_bold.nii.gz   sub-328_task-reward_run-3_bold.nii.gz
sub-328_task-Beast_run-1_events.tsv    sub-328_task-Beast_run-2_sbref.nii.gz  sub-328_task-Beast_run-4_bold.nii.gz   sub-328_task-reward_run-1_sbref.nii.gz  sub-328_task-reward_run-3_sbref.nii.gz
sub-328_task-Beast_run-1_sbref.nii.gz  sub-328_task-Beast_run-3_bold.nii.gz   sub-328_task-Beast_run-4_events.tsv    sub-328_task-reward_run-2_bold.nii.gz
sub-328_task-Beast_run-2_bold.nii.gz   sub-328_task-Beast_run-3_events.tsv    sub-328_task-Beast_run-4_sbref.nii.gz  sub-328_task-reward_run-2_sbref.nii.gz
```

So it seems like `collect_bids_data` is failing for this subject.

```
File: /scratch/03763/oesteban/beast-1subj-20170319/out/fmriprep/sub-328/log/20170320-001800_ce25379e-cece-4c31-92ca-92541fcb5f6e/crash-20170320-001815-oesteban-BIDSDatasource-f4d20017-c78e-4602-89bb-66b1df591514.pklz
Node: workflow_enumerator.328.BIDSDatasource
Working directory: /scratch/03763/oesteban/beast-1subj-20170319/work/workflow_enumerator/328/BIDSDatasource


Node inputs:

ignore_exception = False
sort = False
subject_data = {
    u'fmap': ['/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/fmap/sub-328_epi.nii.gz', '/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/fmap/sub-328_fieldmap.nii.gz', '/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/fmap/sub-328_magnitude.nii.gz'],
    u't1w': ['/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/anat/sub-328_T1w.nii.gz'], 
    u'func': [],
    u'sbref': ['/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/func/sub-328_task-Beast_run-1_sbref.nii.gz', '/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/func/sub-328_task-Beast_run-2_sbref.nii.gz', '/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/func/sub-328_task-Beast_run-3_sbref.nii.gz', '/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/func/sub-328_task-Beast_run-4_sbref.nii.gz', '/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/func/sub-328_task-reward_run-1_sbref.nii.gz', '/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/func/sub-328_task-reward_run-2_sbref.nii.gz', '/scratch/03763/oesteban/beast-1subj-20170319/data/sub-328/func/sub-328_task-reward_run-3_sbref.nii.gz'],
    u'fieldmaps': [],
    u't2w': [],
    u't1': []}
subject_id = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/fmriprep-99.99.99-py2.7-linux-x86_64.egg/fmriprep/interfaces/bids.py", line 79, in _run_interface
    self.inputs.subject_id))
FileNotFoundError: No functional images found for subject sub-<undefined>
Interface BIDSDataGrabber failed to run. 
```

**Comment by chrisfilo** [comment]
I wonder if this is related to the recent pybids update.

**Comment by oesteban** [comment]
Same for subject 356:
```
$ ls /scratch/03763/oesteban/beast-1subj-20170319/data/sub-356/func/
sub-356_task-Beast_run-1_bold.nii.gz   sub-356_task-Beast_run-2_events.tsv    sub-356_task-Beast_run-3_sbref.nii.gz  sub-356_task-reward_run-1_bold.nii.gz
sub-356_task-Beast_run-1_events.tsv    sub-356_task-Beast_run-2_sbref.nii.gz  sub-356_task-Beast_run-4_bold.nii.gz   sub-356_task-reward_run-1_sbref.nii.gz
sub-356_task-Beast_run-1_sbref.nii.gz  sub-356_task-Beast_run-3_bold.nii.gz   sub-356_task-Beast_run-4_events.tsv    sub-356_task-reward_run-2_bold.nii.gz
sub-356_task-Beast_run-2_bold.nii.gz   sub-356_task-Beast_run-3_events.tsv    sub-356_task-Beast_run-4_sbref.nii.gz  sub-356_task-reward_run-2_sbref.nii.gz
```
@chrisfilo: possibly the opposite:
```
$ python -c 'import bids; print bids.__version__'
0.0.1
```

**Comment by oesteban** [comment]
I've upgraded pybids, let's see if it happens again.

**Comment by chrisfilo** [comment]
It could be also a temporary storage failure.

**Comment by effigies** [comment]
The empty `'t1'` bit is due to https://github.com/poldracklab/fmriprep/blob/45fff14d301d976d71a03c6e400946457507fddf/fmriprep/utils/misc.py#L12

But it looks like `subject_id` is failing to be defined. Which it should be passed in manually, not through reading anything off storage.

**Comment by chrisfilo** [comment]
I just tried locally with master branch and freshly build container - cannot replicate this on subject 387 (the only one I had locally). Everything seems to work fine for ds005 as well.

My best guess is - either some changes in the fieldmap branch you are using or something with the environment you set up (I presume this is ls5 and no containers).
