### ISSUE TITLE
FileNotFoundError with --no-freesurfer flag

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#401]
```
File: /scratch/03763/oesteban/beast-1subj-20170319/out/fmriprep/sub-309/log/20170320-142723_78fb3ce5-5682-4afe-bece-a892daef3579/crash-20170320-142739-oesteban-Ants_T1_Brain_Extraction-d76a2ab8-e2e0-421d-af5d-9e615a009b2c.pklz
Node: workflow_enumerator.309.t1w_preprocessing.ANTsBrainExtraction.Ants_T1_Brain_Extraction
Working directory: /scratch/03763/oesteban/beast-1subj-20170319/work/workflow_enumerator/309/t1w_preprocessing/ANTsBrainExtraction/Ants_T1_Brain_Extraction


Node inputs:

anatomical_image = /scratch/03763/oesteban/beast-1subj-20170319/work/workflow_enumerator/309/t1w_preprocessing/MergeT1s/sub-309_T1w_ras.nii.gz
args = <undefined>
brain_probability_mask = /scratch/03763/oesteban/beast-1subj-20170319/work/workflow_enumerator/309/t1w_preprocessing/ANTsBrainExtraction/Ants_T1_Brain_Extraction/T_template0_BrainCerebellumProbabilityMask.nii.gz
brain_template = /home1/03763/oesteban/.cache/stanford-crn/ants_oasis_template_ras/T_template0.nii.gz
compress_report = auto
debug = False
dimension = 3
environ = {u'NSLOTS': u'12'}
extraction_registration_mask = /home1/03763/oesteban/.cache/stanford-crn/ants_oasis_template_ras/T_template0_BrainCerebellumRegistrationMask.nii.gz
generate_report = True
ignore_exception = False
image_suffix = nii.gz
keep_temporary_files = 1
num_threads = 12
out_prefix = highres001_
out_report = report.html
terminal_output = stream
use_floatingpoint_precision = 1
use_random_seeding = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/interfaces/base.py", line 1728, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/niworkflows-99.99.99-py2.7.egg/niworkflows/common/report.py", line 63, in _run_interface
    self._post_run_hook(runtime)
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/niworkflows-99.99.99-py2.7.egg/niworkflows/interfaces/masks.py", line 69, in _post_run_hook
    brain_extraction_mask = self.aggregate_outputs().BrainExtractionMask
  File "/work/01329/poldrack/software/anaconda2-4.2.0/lib/python2.7/site-packages/nipype-0.13.0_ga9b6ac0.dev-py2.7.egg/nipype/interfaces/base.py", line 1180, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: File/Directory '/scratch/03763/oesteban/beast-1subj-20170319/work/workflow_enumerator/309/t1w_preprocessing/ANTsBrainExtraction/Ants_T1_Brain_Extraction/highres001_BrainExtractionPrior1Warp.nii.gz' not found for BrainExtractionRPT output 'BrainExtractionPrior1Warp'.
Interface BrainExtractionRPT failed to run. 
```

**Comment by chrisfilo** [comment]
Is the file there?

**Comment by oesteban** [comment]
Nope, the file is not generated.

**Comment by chrisfilo** [comment]
Just to clarify - this is happening for all subjects using master branch?

**Comment by oesteban** [comment]
Can't tell: I made 4 subjects, only the "rest" task-id, and 2 of them failed before with #399. The other two failed with this one.

**Comment by oesteban** [comment]
Using the fieldmaps branch, but with latest master merged in.

**Comment by chrisfilo** [comment]
I'm running one beast subject locally to see if I can replicate.

**Comment by chrisfilo** [comment]
I cannot replicate this locally with current master (using Docker and Best subject).

**Comment by oesteban** [comment]
It also happened to me with sub-387. Investigating.

**Comment by oesteban** [comment]
Long story short:

```
$ antsBrainExtraction.sh -h
we cant find the N4 program -- does not seem to exist. please (re)define $ANTSPATH in your environment.
$ echo $?
0
```
I'll fix the environment in ls5. This should be OK for the docker image as long as `$ANTSPATH` is defined.

Opened nipype#1901
