### ISSUE TITLE
0.3.0 seems not to be running

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#407]
```Shell
$ docker run --rm -it -v /data/scratch/beast_test:/scratch -v /data/bids/rewardBeastBIDS:/data:ro -v /data/out/beast_test/derivatives:/out poldracklab/fmriprep:0.3.0 /data /out participant --participant_label 387 -w /scratch
/usr/local/miniconda/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/usr/local/miniconda/lib/python3.6/site-packages/nipype/workflows/dmri/mrtrix/group_connectivity.py:16: UserWarning: cmp not installed
  warnings.warn('cmp not installed')
170323-19:10:33,419 interface WARNING:
	 AFNI is outdated, detected version Debian-16.2.07~dfsg.1-2~nd16.04+1 and AFNI_17.0.16 is available.
170323-19:10:34,291 interface WARNING:
	 AFNI is outdated, detected version Debian-16.2.07~dfsg.1-2~nd16.04+1 and AFNI_17.0.16 is available.
/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/fsl/preprocess.py:1587: UserWarning: This has not been fully tested. Please report any failures.
  warn('This has not been fully tested. Please report any failures.')
/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py:431: UserWarning: Input convergence_threshold requires inputs: number_of_iterations
  warn(msg)
/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py:431: UserWarning: Input metric_weight requires inputs: metric
  warn(msg)
/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py:431: UserWarning: Input sigma_units requires inputs: smoothing_sigmas
  warn(msg)
/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py:431: UserWarning: Input concat_xfm requires inputs: in_file2
  warn(msg)
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: 
epi_mask = <undefined>
fmri_file = <undefined>
motion_confounds_file = <undefined>
movpar_file = <undefined>
source_file = <undefined>
t1_tpms = <undefined>
t1_transform_flags = [False, True]
, trait: trait_added, old value: <undefined>, new value: t1_transform
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 784, in _set_input
    object.traits()[name].node.set_input(name, newvalue)
AttributeError: 'NoneType' object has no attribute 'set_input'
170323-19:10:34,811 traits ERROR:
	 Exception occurred in traits notification handler for object: 
epi_mask = <undefined>
fmri_file = <undefined>
motion_confounds_file = <undefined>
movpar_file = <undefined>
source_file = <undefined>
t1_tpms = <undefined>
t1_transform_flags = [False, True]
, trait: trait_added, old value: <undefined>, new value: t1_transform
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 784, in _set_input
    object.traits()[name].node.set_input(name, newvalue)
AttributeError: 'NoneType' object has no attribute 'set_input'
Exception occurred in traits notification handler for object: 
epi_mask = <undefined>
fmri_file = <undefined>
motion_confounds_file = <undefined>
movpar_file = <undefined>
source_file = <undefined>
t1_tpms = <undefined>
t1_transform_flags = [False, True]
, trait: trait_added, old value: <undefined>, new value: reference_image
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 784, in _set_input
    object.traits()[name].node.set_input(name, newvalue)
AttributeError: 'NoneType' object has no attribute 'set_input'
170323-19:10:34,824 traits ERROR:
	 Exception occurred in traits notification handler for object: 
epi_mask = <undefined>
fmri_file = <undefined>
motion_confounds_file = <undefined>
movpar_file = <undefined>
source_file = <undefined>
t1_tpms = <undefined>
t1_transform_flags = [False, True]
, trait: trait_added, old value: <undefined>, new value: reference_image
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/local/miniconda/lib/python3.6/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 784, in _set_input
    object.traits()[name].node.set_input(name, newvalue)
AttributeError: 'NoneType' object has no attribute 'set_input'
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==99.99.99', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/run_workflow.py", line 88, in main
    create_workflow(opts)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/run_workflow.py", line 164, in create_workflow
    settings=settings, run_uuid=run_uuid)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 43, in base_workflow_enumerator
    settings=settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 71, in base_workflow_generator
    return basic_fmap_sbref_wf(subject_data, settings, name=subject_id)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 172, in basic_fmap_sbref_wf
    (t1w_pre, confounds_wf, [('outputnode.t1_tpms', 'inputnode.t1_tpms')]),
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 233, in connect
    infostr))
Exception: Some connections were not found
Module ConfoundDiscoverer has no input called inputnode.t1_transform

Module ConfoundDiscoverer has no input called inputnode.reference_image
```

**Comment by chrisfilo** [comment]
--ignore fieldmaps

On Thu, Mar 23, 2017 at 12:14 PM, Chris Markiewicz <notifications@github.com

**Comment by effigies** [comment]
Oh right... My brain is just shot, today, I guess.
