### ISSUE TITLE
RTD doc building is failing due to missing extensions

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#412]
https://readthedocs.org/projects/fmriprep/builds/5199479/

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 199, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 516, in setup_extension
    err)
ExtensionError: Could not import extension sphinxarg.ext (exception: No module named sphinxarg.ext)

Extension error:
Could not import extension sphinxarg.ext (exception: No module named sphinxarg.ext)
```

**Comment by oesteban** [comment]
Rolling: http://fmriprep.readthedocs.io/en/latest/usage.html
