### ISSUE TITLE
participant ID with "sub-" breaks reports

### ISSUE THREAD

**Issue by poldrack** [poldracklab/fmriprep#416]
I used the folllowing command line with ds005:

docker run -ti --rm \
    -v /home/poldrack/mriqc/ds000005_R2.0.1:/data:ro \
    -v /home/poldrack/fmriprep/dockerout:/out \
    -v /home/poldrack/fmriprep/scratch:/scratch \
    -w /scratch \
    poldracklab/fmriprep:latest \
    /data /out/out \
    participant \
    --participant_label sub-01 \
    --ignore fieldmaps

it ran for a long time but then crashed with the following error:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.3.1', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/run_workflow.py", line 88, in main
    create_workflow(opts)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/run_workflow.py", line 183, in create_workflow
    subject_label, run_uuid=run_uuid)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 174, in run_reports
    report = Report(reportlet_path, config, out_dir, run_uuid, out_filename)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 93, in __init__
    self._load_config(config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 106, in _load_config
    self.index()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/viz/reports.py", line 124, in index
    subject = re.search('^(?P<subject_id>sub-[a-zA-Z0-9]+)$', subject_dir).group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by effigies** [comment]
This should have been fixed in #410.
