### ISSUE TITLE
Cannot run pipeline, deprecation error

### ISSUE THREAD

**Issue by mfalkiewicz** [poldracklab/fmriprep#540]
Hello guys,
  I am trying to run the fmriprep to preprocess some data, but I get the following error. I am using the 0.4.4 version installed with pip. Any ideas what might be the cause?

mfalkiewicz@medusa:~/experiments/SDT3/BIDS$ fmriprep -v
fmriprep v0.4.4

> mfalkiewicz@:~/experiments/data/BIDS$ fmriprep  `pwd` output participant --participant_label '01'
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: 
compress_report = auto
explicit_masking = True
flavor = precise
generate_report = True
ignore_exception = False
initial_moving_transform = <undefined>
moving = T1
moving_image = <undefined>
moving_mask = <undefined>
num_threads = 8
orientation = RAS
out_report = report.svg
reference = T1
reference_image = <undefined>
reference_mask = <undefined>
settings = <undefined>
template = mni_icbm152_linear
template_resolution = 1
testing = False
, trait: testing, old value: <undefined>, new value: False
Traceback (most recent call last):
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 448, in _deprecated_warn
    raise TraitError(msg)
TraitError: Input testing in interface RobustMNINormalization is deprecated. Will be removed or raise an error as of release 0.0.7 
170529-13:13:07,205 traits ERROR:
	 Exception occurred in traits notification handler for object: 
compress_report = auto
explicit_masking = True
flavor = precise
generate_report = True
ignore_exception = False
initial_moving_transform = <undefined>
moving = T1
moving_image = <undefined>
moving_mask = <undefined>
num_threads = 8
orientation = RAS
out_report = report.svg
reference = T1
reference_image = <undefined>
reference_mask = <undefined>
settings = <undefined>
template = mni_icbm152_linear
template_resolution = 1
testing = False
, trait: testing, old value: <undefined>, new value: False
Traceback (most recent call last):
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 448, in _deprecated_warn
    raise TraitError(msg)
TraitError: Input testing in interface RobustMNINormalization is deprecated. Will be removed or raise an error as of release 0.0.7 
Traceback (most recent call last):
  File "/home/mfalkiewicz/.local/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.4.4', 'console_scripts', 'fmriprep')()
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/fmriprep/cli/run.py", line 139, in main
    create_workflow(opts)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/fmriprep/cli/run.py", line 224, in create_workflow
    fmap_demean=opts.fmap_no_demean)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/fmriprep/workflows/base.py", line 61, in init_fmriprep_wf
    output_grid_ref=output_grid_ref)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/fmriprep/workflows/base.py", line 121, in init_single_subject_wf
    output_dir=output_dir)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/fmriprep/workflows/anatomical.py", line 84, in init_anat_preproc_wf
    testing=debug,
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/niworkflows/common/report.py", line 138, in __init__
    super(RegistrationRC, self).__init__(**inputs)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/niworkflows/common/report.py", line 44, in __init__
    super(ReportCapableInterface, self).__init__(**inputs)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/niworkflows/anat/mni.py", line 78, in __init__
    super(RobustMNINormalization, self).__init__(**inputs)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 772, in __init__
    self.inputs = self.input_spec(**inputs)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 370, in __init__
    self.set(**kwargs)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/util/deprecated.py", line 32, in wrapper
    return fn(*args, **kw)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/has_traits.py", line 1552, in set
    trait_change_notify=trait_change_notify, **traits)
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/has_traits.py", line 1544, in trait_set
    setattr( self, name, value )
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 474, in __call__
    self.notify_listener( self, object, trait_name, old, new )
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 545, in _notify_method_listener
    listener )
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 526, in _dispatch_change_event
    handle_exception( object, trait_name, old, new )
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/home/mfalkiewicz/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 448, in _deprecated_warn
    raise TraitError(msg)
traits.trait_errors.TraitError: Input testing in interface RobustMNINormalization is deprecated. Will be removed or raise an error as of release 0.0.7

**Comment by effigies** [comment]
This is an issue with nipype/niworkflows which was recently [fixed](https://github.com/nipy/nipype/pull/2028).

Generally speaking, we recommend that people run with Docker or Singularity. If running Docker, we provide a [wrapper](https://pypi.python.org/pypi/fmriprep-docker) that allows you to run the Docker container as if it were a native installation.

If you're running fmriprep 0.4.4 natively, the following versions of nipype, niworkflows and pybids are recommended: https://github.com/poldracklab/fmriprep/blob/0.4.4/requirements.txt These projects evolve more quickly than their release cycles, so we pin to specific git commits.

**Comment by mfalkiewicz** [comment]
Hello effigies,
  thank you for the explanation. I will upgrade the libraries accordingly. 
Regarding Docker - II would love to use it, but unfortunately admin of the HPC clusters that I'm using are not very fond of it. Docker might be suitable for small calculations that can be done on a local node, but that's rare these days. I know about Singularity, but see the previous caveat. I know you guys are really excited about Docker and it solves a lot of problems with dependencies, but please don't forget about users that can't use it:-)

**Comment by chrisfilo** [comment]
Just to clarify - I would not recommend using Docker on multi user clusters due to security concerns and dependency on kernel features. Singularity, however, does not have those limitations (it was designed with HPC in mind). It has been successfully run on many systems including some HPCs from the TOP500 list and even the main cluster at the NIH. 

In contrast to Docker I don't see any reason for admins not to install singularity and help users like you. BTW Singularity team just published a paper outlining (among other things) difference between singularity and Docker http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0177459 it might be worth sending it to your admin. Maybe this will change their mind.
