### ISSUE TITLE
networkx.exception.NetworkXError: Graph has no nodes or edges

### ISSUE THREAD

**Issue by LJWilliams** [poldracklab/fmriprep#555]
Nipype fails within docker container for a BIDS compatible multi-session dataset that includes anat (T1w, T2w), func (task-mentrot, task-addt, task-rest), dwi, and fieldmap (GE magnitude + fieldmap image). 

Pipeline runs if you remove fieldmaps and dwi from the BIDS compatible folder. 

Please find full error log below

```
RUNNING: docker run --rm -it -v /Volumes/NeuroImaging/Groups/BjornsonLab/Lynne/Studies/REGTRJ:/data:ro -v /Volumes/NeuroImaging/Groups/BjornsonLab/Lynne/Studies/REGTRJ/derivatives:/out poldracklab/fmriprep:0.4.5 /data /out participant
170612-17:09:47,165 workflow INFO:
	 Workflow fmriprep_wf settings: ['check', 'execution', 'logging']
170612-17:09:47,168 workflow INFO:
	 Running in parallel.
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 457, in _generate_dependency_list
    format='lil')
  File "/usr/local/miniconda/lib/python3.6/site-packages/networkx/convert_matrix.py", line 693, in to_scipy_sparse_matrix
    raise nx.NetworkXError("Graph has no nodes or edges")
networkx.exception.NetworkXError: Graph has no nodes or edges

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.4.5', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 139, in main
    create_workflow(opts)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 239, in create_workflow
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 590, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 236, in run
    self._generate_dependency_list(graph)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 460, in _generate_dependency_list
    nodelist=self.procs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/networkx/convert_matrix.py", line 693, in to_scipy_sparse_matrix
    raise nx.NetworkXError("Graph has no nodes or edges")
networkx.exception.NetworkXError: Graph has no nodes or edges
fmriprep: Please report errors to https://github.com/poldracklab/fmriprep/issues
```
```
cfri1919:func lwilliams$ fmriprep-docker /Volumes/NeuroImaging/Groups/BjornsonLab/Lynne/Studies/REGTRJ /Volumes/NeuroImaging/Groups/BjornsonLab/Lynne/Studies/REGTRJ/derivatives participant
RUNNING: docker run --rm -it -v /Volumes/NeuroImaging/Groups/BjornsonLab/Lynne/Studies/REGTRJ:/data:ro -v /Volumes/NeuroImaging/Groups/BjornsonLab/Lynne/Studies/REGTRJ/derivatives:/out poldracklab/fmriprep:0.4.5 /data /out participant
170612-17:12:51,616 workflow INFO:
	 Workflow fmriprep_wf settings: ['check', 'execution', 'logging']
170612-17:12:51,619 workflow INFO:
	 Running in parallel.
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 457, in _generate_dependency_list
    format='lil')
  File "/usr/local/miniconda/lib/python3.6/site-packages/networkx/convert_matrix.py", line 693, in to_scipy_sparse_matrix
    raise nx.NetworkXError("Graph has no nodes or edges")
networkx.exception.NetworkXError: Graph has no nodes or edges

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.4.5', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 139, in main
    create_workflow(opts)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 239, in create_workflow
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 590, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 236, in run
    self._generate_dependency_list(graph)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 460, in _generate_dependency_list
    nodelist=self.procs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/networkx/convert_matrix.py", line 693, in to_scipy_sparse_matrix
    raise nx.NetworkXError("Graph has no nodes or edges")
networkx.exception.NetworkXError: Graph has no nodes or edges
fmriprep: Please report errors to https://github.com/poldracklab/fmriprep/issues
```

**Comment by chrisfilo** [comment]
Thanks for reporting. Could you provide a few more details:

- Does the dataset pass validation without errors and warnings? https://github.com/INCF/bids-validator
- Could you share the folder structure of a single full subject (with fieldmaps and dwi)? The `tree` comman on linux can be helpful here.
- Does the pipeline work on the original dataset (without removing fieldmaps or dwi) when `--ignore fieldmaps` argument is passed?

**Comment by LJWilliams** [comment]
Thanks for the quick response

1. Here's a directory tree for a single session
REGTRJ/
    dataset_description.json
    participants.tsv
    task-addt_bold.json
    task-mentrot_bold.json
    task-rest_bold.json
    sub-regtrj004/
        ses-01/
            anat/
                sub-regtrj004_ses-01_T1w.nii
                sub-regtrj004_ses-01_T2w.nii
            dwi/
                sub-regtrj004_ses-01_dwi.bval
                sub-regtrj004_ses-01_dwi.bvec
                sub-regtrj004_ses-01_dwi.json
                sub-regtrj004_ses-01_dwi.nii
            fmap/
                sub-regtrj004_ses-01_fieldmap.json
                sub-regtrj004_ses-01_fieldmap.nii
                sub-regtrj004_ses-01_magnitude.nii
            func/
                sub-regtrj004_ses-01_task-addt_bold.nii
                sub-regtrj004_ses-01_task-addt_events.tsv
                sub-regtrj004_ses-01_task-mentrot_bold.nii
                sub-regtrj004_ses-01_task-mentrot_events.tsv
                sub-regtrj004_ses-01_task-rest_bold.nii

2. It passes the online BIDS validator without error or warning.
REGTRJ
Summary

19 Files, 668.79MB
1 - Subject
1 - Session
Available Tasks

Auditory Description Decision Task
Mental Rotation of Hands
Resting State Functional Connectivity
Available Modalities

bold
dwi
T1w
T2w
fieldmap
This is a valid BIDS dataset!

3. It still comes up with the same error on the original dataset if the --ignore fieldmaps flag is entered

Lynne

**Comment by chrisfilo** [comment]
Thank you. We have ruled out a few things (BTW excellent bidsification job!) Could you also share the contents of sub-regtrj004_ses-01_fieldmap.json file?

**Comment by LJWilliams** [comment]
Here are the contents of the fieldmap.json file (I have included the screenshot just in case the formatting doesn't come out correctly).

![screen shot 2017-06-12 at 10 40 42 am](https://user-images.githubusercontent.com/2395147/27047131-cd1a6718-4f5b-11e7-96b4-9f18ccf2d2b1.png)

{
    "Units": "Hz",
    "IntendedFor": ["ses-01/func/sub-regtrj004_ses-01_task-rest_bold.nii"],
    "Manufacturer": "GE",
    "ManufacturersModelName": "DISCOVERY_MR750",
    "AcquisitionNumber": 1,
    "InstitutionName": "BC_CHILDRENS_HOSPITAL",
    "DeviceSerialNumber": "00000604875MR750",
    "SoftwareVersions": "24_LX_MR_Software_release:DV24.0_R01_1344.a",
    "ScanningSequence": "RM",
    "SequenceVariant": "NONE",
    "SeriesDescription": "B0map",
    "ProtocolName": "B0map",
    "ImageType": ["ORIGINAL", "PRIMARY", "OTHER"],
    "AcquisitionTime": "11:01:45.000000",
    "MagneticFieldStrength": 3,
    "FlipAngle": 50,
    "EchoTime": 0.004608,
    "RepetitionTime": 0.575,
    "ConversionSoftware": "dcm2niix",
        "ConversionSoftwareVersion": "v1.0.20170528 (OpenJPEG build) GCC6.1.0"
}

**Comment by chrisfilo** [comment]
@oesteban any ideas?

**Comment by oesteban** [comment]
One surprising thing is that the log does not show [this trace](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/cli/run.py#L201)

For some reason, the individual workflows per participant seem not to be created.

**Comment by chrisfilo** [comment]
I managed to replicate this on ds000114

```
PS D:\drive\workspace\fmriprep> docker run -ti --rm -v D:\:/d poldracklab/fmriprep:reconform \d\data\ds000114_R2.0.1 \d\scratch\ds000114_R2.0.1\out participant -w \d\scratch\work --no-freesurfer
170613-19:42:53,403 workflow INFO:
         Workflow fmriprep_wf settings: ['check', 'execution', 'logging']
170613-19:42:53,425 workflow INFO:
         Running in parallel.
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 457, in _generate_dependency_list
    format='lil')
  File "/usr/local/miniconda/lib/python3.6/site-packages/networkx/convert_matrix.py", line 693, in to_scipy_sparse_matrix
    raise nx.NetworkXError("Graph has no nodes or edges")
networkx.exception.NetworkXError: Graph has no nodes or edges

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.4.6.dev0', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 139, in main
    create_workflow(opts)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 239, in create_workflow
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 590, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 236, in run
    self._generate_dependency_list(graph)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 460, in _generate_dependency_list
    nodelist=self.procs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/networkx/convert_matrix.py", line 693, in to_scipy_sparse_matrix
    raise nx.NetworkXError("Graph has no nodes or edges")
networkx.exception.NetworkXError: Graph has no nodes or edges
```

**Comment by chrisfilo** [comment]
It seems like this error is triggered by pointing fmriprep to an input directory that does not exist. Easiest way to replicate `docker run -ti --rm poldracklab/fmriprep:reconform /bogus /bogus participant`.


@LJWilliams could you confirm this by running (and telling us the outputs of)

```
docker run --rm -it -v /Volumes/NeuroImaging/Groups/BjornsonLab/Lynne/Studies/REGTRJ:/data:ro -v /Volumes/NeuroImaging/Groups/BjornsonLab/Lynne/Studies/REGTRJ/derivatives:/out --entrypoint=ls poldracklab/fmriprep:0.4.5 /data
```

My best guess is that you did not configure Docker on Mac to share ` /Volumes`. Easy thing to fix in the settings.

Nonetheless we need to give better error messages in such case.

**Comment by effigies** [comment]
@oesteban The reason that log isn't showing is because the [logger is "cli" and the default level is `WARNING`](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/cli/run.py#L152-L155) so an `info` call won't show unless debugging is on.

Running with the `--debug` flag should produce output.

**Comment by LJWilliams** [comment]
the output of 

`docker run --rm -it -v /Volumes/NeuroImaging/Groups/BjornsonLab/Lynne/Studies/REGTRJ:/data:ro -v /Volumes/NeuroImaging/Groups/BjornsonLab/Lynne/Studies/REGTRJ/derivatives:/out --entrypoint=ls poldracklab/fmriprep:0.4.5 /data`

is

`derivatives`

**Comment by chrisfilo** [comment]
Ok this confirms my theory. Did changing the Docker for Mac settings for shared volumes help?

**Comment by LJWilliams** [comment]
I'm using the Docker Toolbox on Mavericks and it is not letting me change settings just yet. Will update you as soon as I get the VM to recognize /Volumes

**Comment by LJWilliams** [comment]
Once I set up access in the VirtualBox, it runs.

Thank-you very much for your help.

Lynne
