### ISSUE TITLE
crash with anatomical file - unable to look into crashfile

### ISSUE THREAD

**Issue by rschmaelzle** [poldracklab/fmriprep#567]
HI, 
fmriprep does a fantastic job with my data - expect for 1 subj where it repeatedly fails with the anatomy. I tried reorienting - did not help. I then tried to do brain extraction by hand first and giving it the already extracted anat-file. That got it to work, but in the end the normalized brain was far too aggressively treated - all grey matter was removed - though it was in nice MNI-shape. 
 I'd love to find out what I can do, so I tried to open the crash file. That seemed to result in a version conflict (3 vs. 2 python). I tried to source a venv, but was still unable to open the crashfile. I am not familiar enough with docker to enter the container and run the nipype_display_crash command, so the question #2 is how to look at the crashfile? (question #1 being if there is a hunch on what to change to get the anat to work other that manual bet).
Thanks for the great tool, R

**Comment by chrisfilo** [comment]
I glad you enjoying FMRIPREP. The countent of the error should be included at the end of the HTML report produced by FMRIPREP. Sharing the report would be the first step in figuring out what went wrong.

**Comment by effigies** [comment]
I wonder if this, like #552, might be improved with the NKI template.

**Comment by rschmaelzle** [comment]
thanks for getting back! 
The report says: 

```
Errors
Node Name: fmriprep_wf.single_subject_05_wf.anat_preproc_wf.t1_conform
File: crash-20170618-051103-root-t1_conform-87f859ec-9ebf-4381-ac44-2970f51b1ba6.pklz
Working Directory: /root/src/fmriprep/work/fmriprep_wf/single_subject_05_wf/anat_preproc_wf/t1_conform
Inputs: 
ignore_exception: False
t1w_list: ['/data/sub-05/anat/sub-05_T1w.nii']
            Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1031, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/images.py", line 144, in _run_interface
    orig_imgs = [nb.load(fname) for fname in in_names]
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/images.py", line 144, in 
    orig_imgs = [nb.load(fname) for fname in in_names]
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/loadsave.py", line 48, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/data/sub-05/anat/sub-05_T1w.nii"
Interface ConformSeries failed to run. 
```
I'd be happy to try out if it works with the NKI template but don't know how to do that...
the command I am submitting is
`fmriprep-docker /Users/Ralf/p/data/source /Users/Ralf/p/data/fmriprep participant --participant 05 --no-freesurfer`
thank you again. r

**Comment by effigies** [comment]
Actually, that looks like an invalid T1w nifti file. Can you open it with a normal viewer?

**Comment by chrisfilo** [comment]
It could also be .nii.gz with a .nii extension. I've see such mistake
before.

**Comment by rschmaelzle** [comment]
that was indeed the case! As always, som mystery remains as to why this happens with this file and not the others, but it worked now after changing the extension - making sure it is .nii proper! Thanks a ton. r
