### ISSUE TITLE
Documentation failure

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#579]
`sphinx-argparse` depends on `CommonMark>=0.5.6` while ReadTheDocs uses `recommonmark`, which depends on `CommonMark<=0.5.4`.

The latter is installed later, so ReadTheDocs is failing [here](https://github.com/poldracklab/fmriprep/blob/master/docs/usage.rst#command-line-arguments):

```RST
Command-Line Arguments
~~~~~~~~~~~~~~~~~~~~~~

.. argparse::
   :ref: fmriprep.cli.run.get_parser
   :prog: fmriprep
   :nodefault:
   :nodefaultconst:
```

**Comment by effigies** [comment]
Opened an issue: rtfd/recommonmark#78

**Comment by effigies** [comment]
Even if they do release an update, I think we're going to have an issue as long as something induces pip to try to upgrade setuptools, which fails sometimes, maybe (see [fix-docs](https://readthedocs.org/projects/fmriprep/builds/) builds)?

I guess as long as the failures are stochastic instead of permanent, we can just keep rebuilding until something works.

**Comment by oesteban** [comment]
Seems to be building (http://fmriprep.readthedocs.io/en/fix-docs-579/), but now we get a bunch of these:

```
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/fmriprep/checkouts/fix-docs-579/docs/workflows.rst:15: (WARNING/2) Exception occurred in plotting workflows-1
 from /home/docs/checkouts/readthedocs.org/user_builds/fmriprep/checkouts/fix-docs-579/docs/workflows.rst:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/fix-docs-579/lib/python3.5/site-packages/nipype/sphinxext/plot_workflow.py", line 464, in run_code
    exec(code, ns)
  File "<string>", line 25, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/fix-docs-579/lib/python3.5/site-packages/fmriprep/workflows/base.py", line 158, in init_single_subject_wf
    ignore_aroma_err=ignore_aroma_err)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/fix-docs-579/lib/python3.5/site-packages/fmriprep/workflows/epi.py", line 143, in init_func_preproc_wf
    name='discover_wf')
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/fix-docs-579/lib/python3.5/site-packages/fmriprep/workflows/confounds.py", line 62, in init_discover_wf
    percentile_threshold=.05),
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/fix-docs-579/lib/python3.5/site-packages/niworkflows/common/report.py", line 45, in __init__
    super(ReportCapableInterface, self).__init__(**inputs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/fix-docs-579/lib/python3.5/site-packages/niworkflows/nipype/algorithms/confounds.py", line 487, in __init__
    super(TCompCor, self).__init__(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/fix-docs-579/lib/python3.5/site-packages/niworkflows/nipype/algorithms/confounds.py", line 376, in __init__
    super(CompCor, self).__init__(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/fix-docs-579/lib/python3.5/site-packages/niworkflows/nipype/interfaces/base.py", line 774, in __init__
    self.inputs = self.input_spec(**inputs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fmriprep/envs/fix-docs-579/lib/python3.5/site-packages/niworkflows/nipype/interfaces/base.py", line 364, in __init__
    super(BaseTraitedSpec, self).__init__(**kwargs)
traits.trait_errors.TraitError: Cannot set the undefined 'pre_filter' attribute of a 'TCompCorInputSpecRPT' object.
```

**Comment by oesteban** [comment]
Seems like nipype is outdated in readthedocs, isn't it? @effigies

**Comment by effigies** [comment]
Might need to upgrade to niworkflows>=0.1.4. #587 includes it, but the tests are still running. (Crashed because pypi package wasn't ready when they started.)
