### ISSUE TITLE
nipype config file crash

### ISSUE THREAD

**Issue by bkraft4257** [poldracklab/fmriprep#597]
I am new to fmriprep and nipype. I am trying to understand both how they work and how to debug problems that I am encountering. I am trying run the first three subjects from the BIDS Example data set ds003 (sub-01, sub-02, and sub-03).  I was able to run the basic workflow using the default settings in fmriprep-docker.  There are still things that I don't understand about the output and the individual workflows. I am trying to understand how it works in greater details 

As a first step,  I wanted to write the output to a log file. I created the nipype.cfg file.  Contents of the file from  cat nipype.cfg

```
[logging]
log_to_file=true
log_directory=/Users/bkraft/tic/data/ds003/log/`
```

I then ran fmriprep-docker as follows

>> fmriprep-docker /Users/bkraft/tic/data/ds003/data/ /Users/bkraft/tic/data/ds003/output2/ -w  /Users/bkraft/tic/data/ds003/work2/  --config nipype.cfg

The output2 and work2 directories were created. The directories are empty (determined by ls -a).  The error message was reported

```
RUNNING: docker run --rm -it -v /Users/bkraft/tic/data/ds003/data/:/data:ro -v /Users/bkraft/tic/data/ds003/output2/:/out -v /Users/bkraft/tic/data/ds003/work2/:/scratch -v /Users/bkraft/tic/data/ds003/nipype.cfg:/root/.nipype/nipype.cfg:ro poldracklab/fmriprep:0.5.4 /data /out participant -w /scratch
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.5.4', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/__init__.py", line 33, in <module>
    from niworkflows.nipype.interfaces.afni import Info  # noqa: E402
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/__init__.py", line 25, in <module>
    logging = Logging(config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/utils/logger.py", line 43, in __init__
    self.update_logging(self._config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/utils/logger.py", line 77, in update_logging
    self.enable_file_logging()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/utils/logger.py", line 52, in enable_file_logging
    'log_rotate')))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/external/cloghandler.py", line 158, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding)
  File "/usr/local/miniconda/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/miniconda/lib/python3.6/logging/__init__.py", line 1025, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/miniconda/lib/python3.6/logging/__init__.py", line 1054, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bkraft/tic/data/ds003/log/pypeline.log'
**fmriprep: Please report errors to https://github.com/poldracklab/fmriprep/issues**

```
The directory /Users/bkraft/tic/data/ds003/log/ exists with permission 777.   

I am reporting this error as suggested by the error message.

**Comment by effigies** [comment]
Thanks for the report. The issue here is that the location `/Users/bkrafft/tic/data/ds003/log/` doesn't exist in your docker container. Since that directory isn't a subdirectory of any of the docker mounts you've created, we'll need to change something in this configuration; I would recommend just changing the location of your log directory.

I would set the log directory to `/scratch/log/`, and making sure that `/Users/bkrafft/tic/data/ds003/work2/log/` exists. This also has the advantage that when you change datasets, you will not need to change configuration files; it will always look for a `log` directory in your working directory.

**Comment by effigies** [comment]
If the above was clear, feel free to ignore this comment, but in case that was a confusing suggestion, I'll walk through what the `fmriprep-docker` command is actually doing.

Consider the first line of output (reformatted):

```Shell
$> fmriprep-docker /Users/bkraft/tic/data/ds003/data/ /Users/bkraft/tic/data/ds003/output2/ \
    -w /Users/bkraft/tic/data/ds003/work2/ --config nipype.cfg
RUNNING: docker run --rm -it \
    -v /Users/bkraft/tic/data/ds003/data/:/data:ro \
    -v /Users/bkraft/tic/data/ds003/output2/:/out \
    -v /Users/bkraft/tic/data/ds003/work2/:/scratch \
    -v /Users/bkraft/tic/data/ds003/nipype.cfg:/root/.nipype/nipype.cfg:ro \
    poldracklab/fmriprep:0.5.4 /data /out participant -w /scratch
[...]
```

So `fmriprep-docker` simply creates a `docker` command line that runs `fmriprep` for you.

The option string `-v /Users/bkraft/tic/data/ds003/data/:/data:ro` says that the first location in the outside will be mapped to the `/data` directory inside the container. At the end of the command, you see we now use `/data` as the first argument after `poldracklab/fmriprep:0.5.4`. Similarly, you see arguments for `/out`, `/scratch`, and `nipype.cfg`.

These are the full set of locations in your "host" computer that are accessible from within the docker container. Notice that there is no `/Users/bkraft` on the inside; so the location of the file you want needs to be with respect to the paths *inside* the container. Since no parent directories of your log directory are included, rewriting the path isn't sufficient; you need to choose a new path. The alternative would be to add a new `-v <HOST>:<CONTAINER>` flag, but that would involve using docker directly, not through `fmriprep-docker`.

**Comment by bkraft4257** [comment]
Thank you for your quick reply. I am new to fmriprep, docker, and nipype so I really appreciate your patience.  

I have made the directory /scratch/log  and   /Users/bkraft/tic/data/ds003/work2/log/.  I then reran the command 

`fmriprep-docker /Users/bkraft/tic/data/ds003/data/ /Users/bkraft/tic/data/ds003/output2/ -w  /Users/bkraft/tic/data/ds003/work2/ --participant_label sub-01  --config nipype.cfg`

I encountered a similar error message.

```
RUNNING: docker run --rm -it -v /Users/bkraft/tic/data/ds003/data/:/data:ro -v /Users/bkraft/tic/data/ds003/output2/:/out -v /Users/bkraft/tic/data/ds003/work2/:/scratch -v /Users/bkraft/tic/data/ds003/nipype.cfg:/root/.nipype/nipype.cfg:ro poldracklab/fmriprep:0.5.4 /data /out participant --participant_label sub-01 -w /scratch
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.5.4', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/__init__.py", line 33, in <module>
    from niworkflows.nipype.interfaces.afni import Info  # noqa: E402
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/__init__.py", line 25, in <module>
    logging = Logging(config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/utils/logger.py", line 43, in __init__
    self.update_logging(self._config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/utils/logger.py", line 77, in update_logging
    self.enable_file_logging()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/utils/logger.py", line 52, in enable_file_logging
    'log_rotate')))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/external/cloghandler.py", line 158, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding)
  File "/usr/local/miniconda/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/miniconda/lib/python3.6/logging/__init__.py", line 1025, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/miniconda/lib/python3.6/logging/__init__.py", line 1054, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bkraft/tic/data/ds003/work2/log/pypeline.log'
fmriprep: Please report errors to https://github.com/poldracklab/fmriprep/issues
```

What am I doing wrong?

**Comment by effigies** [comment]
Ah, sorry for not being clear. What you need to do is update the path in `nipype.cfg`:

```
[logging]
log_to_file=true
log_directory=/scratch/log
```

Because nipype is running within the container, it needs a path that exists inside the container, such as `/scratch/log`. Docker will then do the work of mapping that to `/Users/bkraft/tic/data/ds003/work2/log` on your machine. You do not need a `/scratch/log` directory on your actual machine.

**Comment by bkraft4257** [comment]
Now I understand.  Thank you so much.  It's working now.
