### ISSUE TITLE
Ants nifti_image_write_hdr_img error

### ISSUE THREAD

**Issue by jokedurnez** [poldracklab/fmriprep#616]
Hi,

With the motto: analyse all the data, I'm running fmriprep on the NKI dataset as well :-p . Full logs attached (header says myconnectome but that's wrong).
Running into an ants error (I think):

```
170727-19:37:24,887 workflow INFO:
	 Running: antsBrainExtraction.sh -a /oak/stanford/groups/russpold/data/NKI_preprocessed_0.5.3/temp/fmriprep_wf/single_subject_A00008399_wf/anat_preproc_wf/t1_merge/sub-A00008399_ses-DS2_T1w_ras_template.nii.gz -m /oak/stanford/groups/russpold/data/NKI_preprocessed_0.5.3/temp/fmriprep_wf/single_subject_A00008399_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/T_template0_BrainCerebellumProbabilityMask.nii.gz -e /niworkflows_data/ants_oasis_template_ras/T_template0.nii.gz -d 3 -f /niworkflows_data/ants_oasis_template_ras/T_template0_BrainCerebellumRegistrationMask.nii.gz -s nii.gz -k 1 -o highres001_ -q 1
170727-19:37:35,557 interface INFO:
	 stderr 2017-07-27T19:37:35.557730:++ Max displacement in automask = 0.12 (mm) at sub-brick 7
170727-19:37:35,558 interface INFO:
	 stderr 2017-07-27T19:37:35.557730:++ Max delta displ  in automask = 0.08 (mm) at sub-brick 12
170727-19:37:35,558 interface INFO:
	 stderr 2017-07-27T19:37:35.557730:** ERROR: nifti_image_write_hdr_img: NBL does not match nim
170727-19:37:36,81 workflow ERROR:
	 ['Node gen_ref failed to run on host sh-1-18.local.']
170727-19:37:36,83 workflow INFO:
	 Saving crash info to /oak/stanford/groups/russpold/data/NKI_preprocessed_0.5.3/fmriprep/fmriprep/sub-A00008399/log/20170727-193624_d009e8aa-558a-4a6a-8c44-5378805fb259/crash-20170727-193736-jdurnez-gen_ref-81e1076f-dfca-44ce-b172-5eeb258f5ac3.pklz
170727-19:37:36,83 workflow INFO:
	 Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1031, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/registration.py", line 314, in _run_interface
    mc_slice_nii = nb.load(res.outputs.out_file)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/loadsave.py", line 48, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/oak/stanford/groups/russpold/data/NKI_preprocessed_0.5.3/temp/fmriprep_wf/single_subject_A00008399_wf/func_preproc_ses_DS2_task_rest_acq_CAP_wf/epi_hmc_wf/gen_ref/slice_volreg.nii.gz"
Interface EstimateReferenceImage failed to run. 

170727-19:37:36,313 workflow INFO:
	 [Job finished] jobname: fsdir jobid: 128
```
[NKI_fmriprep_1.out.txt](https://github.com/poldracklab/fmriprep/files/1181246/NKI_fmriprep_1.out.txt)

**Comment by effigies** [comment]
Pretty sure it's that same function again, this time [this line](https://github.com/poldracklab/niworkflows/blob/master/niworkflows/interfaces/registration.py#L314).

In this case, the incoming file has AFNI extensions, which confuses `3dvolreg` when we take a slice without also adjusting the size of its internal data structure:

```xml
<?xml version='1.0' ?>
<AFNI_attributes
  self_idcode="XYZ_UyewKOD2JXopJcplaRGY-g"
  NIfTI_nums="112,112,64,198,1,4"
  ni_form="ni_group" >
<AFNI_atr
  ni_type="String"
  ni_dimen="1"
  atr_name="DATASET_NAME" >
 "none"
</AFNI_atr>
[...]
```

I think for these purposes, it makes more sense for us to strip the header extension.
