### ISSUE TITLE
error in installation/ python setup.py egg_info

### ISSUE THREAD

**Issue by yidilozdemir** [poldracklab/fmriprep#626]
This is probably not the best place to ask this question, but I was wondering if anyone came across this or know what this error points to during installation. The command line is  

>>**pip install --user --upgrade fmriprep-docker**

>>Collecting fmriprep-docker
  Using cached fmriprep-docker-0.5.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Qvo5S9/fmriprep-docker/setup.py", line 43, in <module>
        main()
      File "/tmp/pip-build-Qvo5S9/fmriprep-docker/setup.py", line 14, in main
        info = runpy.run_path(op.join(this_path, 'fmriprep_docker.py'))
      File "/usr/lib/python2.7/runpy.py", line 252, in run_path
        return _run_module_code(code, init_globals, run_name, path_name)
      File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/pip-build-Qvo5S9/fmriprep-docker/fmriprep_docker.py", line 3, in <module>
        from builtins import int, map, input, zip
    ImportError: No module named builtins

 >>**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ypLRg8/fmriprep/.** 

Both docker and manually prepared environment routes produce the same error in installation. I have some restriction issues in this computer and I ran it with sudo but I am still wondering if that might be a cause. Thank you for the help!

**Comment by effigies** [comment]
```Shell
pip install future
```

This should be automatically installed when you try to install fmriprep-docker... I'll see if I can figure out why it's not working.

Also, this is a great place to ask the question. :-)

**Comment by yidilozdemir** [comment]
That command helped. Thank you!

**Comment by effigies** [comment]
We should revisit this after 0.6.1 is released, to verify that it can be installed without pre-installing `future`. (See #631.)

**Comment by effigies** [comment]
Alright, it looks like #631 had no effect:

```Shell
$ docker run --rm -it continuumio/miniconda
root@20b4fbe854c7:/# pip install fmriprep-docker==1.0.0rc1
Collecting fmriprep-docker==1.0.0rc1
  Downloading fmriprep-docker-1.0.0rc1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1QAk0K/fmriprep-docker/setup.py", line 43, in <module>
        main()
      File "/tmp/pip-build-1QAk0K/fmriprep-docker/setup.py", line 14, in main
        info = runpy.run_path(op.join(this_path, 'fmriprep_docker.py'))
      File "/opt/conda/lib/python2.7/runpy.py", line 252, in run_path
        return _run_module_code(code, init_globals, run_name, path_name)
      File "/opt/conda/lib/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/opt/conda/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/pip-build-1QAk0K/fmriprep-docker/fmriprep_docker.py", line 3, in <module>
        from builtins import int, map, input, zip
    ImportError: No module named builtins
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1QAk0K/fmriprep-docker/
```

Perhaps we should just update the docs to say 'pip install --user --upgrade future fmriprep-docker`?

**Comment by oesteban** [comment]
FMRIPREP does not support python < 3 anymore.
