### ISSUE TITLE
ModuleNotFoundError: No module named 'fmriprep.cli'

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#630]
`poldracklab/fmriprep:dev` was built using `D:\drive\workspace\fmriprep`

```
PS D:\drive\workspace\fmriprep> fmriprep-docker -i poldracklab/fmriprep:dev -w D:\scratch\ds000030\fmriprep\work -f D:\drive\workspace\fmriprep -n D:\drive\workspace\niworkflows D:\data\ds000030_R1.0.3 D:\scratch/ds000030/fmriprep/out participant --nthreads 1 --omp-nthreads 6 --no-freesurfer --participant_label 10225 --use-aroma
RUNNING: docker run --rm -it -v D:\drive\workspace\fmriprep:/usr/local/miniconda/lib/python3.6/site-packages/fmriprep:ro -v D:\drive\workspace\niworkflows:/usr/local/miniconda/lib/python3.6/site-packages/niworkflows:ro -v D:\data\ds000030_R1.0.3:/data:ro -v D:\scratch/ds000030/fmriprep/out:/out -v D:\scratch\ds000030\fmriprep\work:/scratch poldracklab/fmriprep:dev /data /out participant --nthreads 1 --omp-nthreads 6 --no-freesurfer --participant_label 10225 --use-aroma -w /scratch
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.5.5.dev0', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
ModuleNotFoundError: No module named 'fmriprep.cli'
fmriprep: Please report errors to https://github.com/poldracklab/fmriprep/issues
```

**Comment by effigies** [comment]
Can you try using `-f D:\drive\workspace\fmriprep\fmriprep`? There was a change (25702391bfde13e67c51ff6933bd733024650b6b) a while back to patch in the installed directory, which is `<repo base>/fmriprep` instead of the repository base itself.

**Comment by chrisfilo** [comment]
I did try this with a new error:

```
PS D:\drive\workspace\fmriprep> fmriprep-docker -i poldracklab/fmriprep:dev -w D:\scratch\ds000030\fmriprep\work -f D:\drive\workspace\fmriprep\fmriprep -n D:\drive\workspace\niworkflows\niworkflows D:\data\ds000030_R1.0.3 D:\scratch/ds000030/fmriprep/out participant --nthreads 1 --omp-nthreads 6 --no-freesurfer --participant_label 10225 --use-aroma
RUNNING: docker run --rm -it -v D:\drive\workspace\fmriprep\fmriprep:/usr/local/miniconda/lib/python3.6/site-packages/fmriprep:ro -v D:\drive\workspace\niworkflows\niworkflows:/usr/local/miniconda/lib/python3.6/site-packages/niworkflows:ro -v D:\data\ds000030_R1.0.3:/data:ro -v D:\scratch/ds000030/fmriprep/out:/out -v D:\scratch\ds000030\fmriprep\work:/scratch poldracklab/fmriprep:dev /data /out participant --nthreads 1 --omp-nthreads 6 --no-freesurfer --participant_label 10225 --use-aroma -w /scratch
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.5.5.dev0', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/__init__.py", line 33, in <module>
    from niworkflows.nipype.interfaces.afni import Info  # noqa: E402
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/__init__.py", line 16, in <module>
    from niworkflows.info import(
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/info.py", line 17, in <module>
    'nipype', 'info.py'))
  File "/usr/local/miniconda/lib/python3.6/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/local/miniconda/lib/python3.6/runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/info.py'
fmriprep: Please report errors to https://github.com/poldracklab/fmriprep/issues
```

**Comment by chrisfilo** [comment]
(please note that I applied the suggestion to both fmriprep and niworkflows)

**Comment by chrisfilo** [comment]
update - this works:

`fmriprep-docker -i poldracklab/fmriprep:dev -w D:\scratch\ds000030\fmriprep\work -f D:\drive\workspace\fmriprep\fmriprep D:\data\ds000030_R1.0.3 D:\scratch/ds000030/fmriprep/out participant --nthreads 1 --omp-nthreads 6 --no-freesurfer --participant_label 10225 --use-aroma`

**Comment by chrisfilo** [comment]
However:

```
PS D:\drive\workspace\fmriprep> fmriprep-docker -i poldracklab/fmriprep:dev -w D:\scratch\ds000030\fmriprep\work -f D:\drive\workspace\fmriprep\fmriprep -n D:\drive\workspace\niworkflows D:\data\ds000030_R1.0.3 D:\scratch/ds000030/fmriprep/out participant --nthreads 1 --omp-nthreads 6 --no-freesurfer --participant_label 10225 --use-aroma
RUNNING: docker run --rm -it -v D:\drive\workspace\fmriprep\fmriprep:/usr/local/miniconda/lib/python3.6/site-packages/fmriprep:ro -v D:\drive\workspace\niworkflows:/usr/local/miniconda/lib/python3.6/site-packages/niworkflows:ro -v D:\data\ds000030_R1.0.3:/data:ro -v D:\scratch/ds000030/fmriprep/out:/out -v D:\scratch\ds000030\fmriprep\work:/scratch poldracklab/fmriprep:dev /data /out participant --nthreads 1 --omp-nthreads 6 --no-freesurfer --participant_label 10225 --use-aroma -w /scratch
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.5.5.dev0', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/__init__.py", line 33, in <module>
    from niworkflows.nipype.interfaces.afni import Info  # noqa: E402
ModuleNotFoundError: No module named 'niworkflows.nipype.interfaces'
fmriprep: Please report errors to https://github.com/poldracklab/fmriprep/issues
PS D:\drive\workspace\fmriprep> fmriprep-docker -i poldracklab/fmriprep:dev -w D:\scratch\ds000030\fmriprep\work -f D:\drive\workspace\fmriprep\fmriprep -n D:\drive\workspace\niworkflows\niworkflows D:\data\ds000030_R1.0.3 D:\scratch/ds000030/fmriprep/out participant --nthreads 1 --omp-nthreads 6 --no-freesurfer --participant_label 10225 --use-aroma
RUNNING: docker run --rm -it -v D:\drive\workspace\fmriprep\fmriprep:/usr/local/miniconda/lib/python3.6/site-packages/fmriprep:ro -v D:\drive\workspace\niworkflows\niworkflows:/usr/local/miniconda/lib/python3.6/site-packages/niworkflows:ro -v D:\data\ds000030_R1.0.3:/data:ro -v D:\scratch/ds000030/fmriprep/out:/out -v D:\scratch\ds000030\fmriprep\work:/scratch poldracklab/fmriprep:dev /data /out participant --nthreads 1 --omp-nthreads 6 --no-freesurfer --participant_label 10225 --use-aroma -w /scratch
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.5.5.dev0', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/__init__.py", line 33, in <module>
    from niworkflows.nipype.interfaces.afni import Info  # noqa: E402
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/__init__.py", line 16, in <module>
    from niworkflows.info import(
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/info.py", line 17, in <module>
    'nipype', 'info.py'))
  File "/usr/local/miniconda/lib/python3.6/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/local/miniconda/lib/python3.6/runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/info.py'
fmriprep: Please report errors to https://github.com/poldracklab/fmriprep/issues
```

**Comment by effigies** [comment]
Ah, it looks like you might not have checked out the git submodule in niworkflows.

```Shell
git submodule init
git submodule update
```

**Comment by chrisfilo** [comment]
I think this is a symbolic link Windows interaction. Is there a reason why https://github.com/poldracklab/niworkflows/blob/master/niworkflows/nipype is a symlink instead of the submodule itself? Is it because you need to check the root (/nipype) instead of the package folder (/nipype/nipype)?

**Comment by effigies** [comment]
Ah, yes. You can't direct the submodule to point to a subfolder, so we needed the symlink. I'm surprised git for Windows doesn't have some hack to make symlinks work. There are those text file symlinks that CIFS uses, which should be how Docker handles them under the hood. I wonder if there's a way to get git to use those...

**Comment by chrisfilo** [comment]
I got it to work.
