### ISSUE TITLE
MemoryError in SignalExtraction

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#657]
```
170809-20:04:16,30 workflow INFO:
	 Executing node signals in dir: /scratch/fmriprep_wf/single_subject_03_wf/func_preproc_task_mapper_run_02_wf/bold_confounds_wf/signals
170809-20:05:06,645 workflow ERROR:
	 ['Node signals failed to run on host 2fae67b907ed.']
170809-20:05:06,778 workflow INFO:
	 Saving crash info to /out/fmriprep/sub-03/log/20170809-192806_05fb6cec-029a-492e-9ec1-2a9d20efb32b/crash-20170809-200506-root-signals-2ea82a32-de8b-4ab4-990e-5f40755db365.txt
170809-20:05:06,779 workflow INFO:
	 Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1031, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/nilearn.py", line 83, in _run_interface
    signals.append(masker.fit_transform(self.inputs.in_file))
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/input_data/nifti_maps_masker.py", line 214, in fit_transform
    return self.fit().transform(imgs, confounds=confounds)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/input_data/base_masker.py", line 176, in transform
    return self.transform_single_imgs(imgs, confounds)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/input_data/nifti_maps_masker.py", line 254, in transform_single_imgs
    imgs_ = _utils.check_niimg_4d(imgs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/_utils/niimg_conversions.py", line 361, in check_niimg_4d
    dtype=dtype)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/_utils/niimg_conversions.py", line 271, in check_niimg
    niimg = load_niimg(niimg, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/_utils/niimg.py", line 116, in load_niimg
    dtype = _get_target_dtype(niimg.get_data().dtype, dtype)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/spatialimages.py", line 572, in get_data
    data = np.asanyarray(self._dataobj)
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/core/numeric.py", line 583, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 145, in __array__
    raw_data = self.get_unscaled()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 140, in get_unscaled
    mmap=self._mmap)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/volumeutils.py", line 523, in array_from_file
    data_bytes = bytearray(n_bytes)
MemoryError: 
Interface SignalExtraction failed to run.
```

While looking into #652, I also ran across this error. On a 16GB system w/ 16GB swap, memory and most (~13GB) of swap filled before failure. Had closed all large apps before running.

**Comment by Gilles86** [comment]
This was run on a dataset I am working (amd which I can not share publicly right now).

It is a 3T-dataset, but at relatively high resolution, short TR, and long runs. Specifically, we have a resolution of 1.875x1.875x3.0 mm, TR is 0.97 s. Runs consist of approx 720 volumes of 128x128x17 voxels.

Here at the cluster in Amsterdam I could only get the workflow to run on nodes with 64 GB RAM and using only 4 cpu's (--n_cpus) and even that it would crash for one subject.

**Comment by effigies** [comment]
Confirmed that the `signals` node consumes a large amount of memory (>16GB at times).

**Comment by effigies** [comment]
It doesn't look like a simple case where we can let images and arrays get garbage collected. However, I am able to keep memory usage *much* lower by `gunzip`ping the file that's being imported, and letting nibabel mmap the data.

**Comment by effigies** [comment]
Thinking more about this, I think it'd be useful to at least allow an option to use unzipped NIfTIs for large intermediate files. The final outputs should still be `.nii.gz`, but giving users the option of whether to trade gigabytes of disk space for gigabytes of memory during preprocessing would accommodate the most use cases.

At the moment, the only real targets of decompression that have the potential for significant memory load reduction that I can see are:

* The original BOLD series
  * Read in to estimate reference image
  * Slice-timing correction (afni.Tshift)
  * Splitting (fsl.Split)
* Aligned-and-merged BOLD series in T1w space
  * Pretty much all confounds but ICA-AROMA
* Aligned-and-merged BOLD series in MNI space
  * ICA-AROMA

I'm not sure that the first is worth it. We'd need to profile `fslsplit` and `3dTshift` on large files. I think the second is obviously worth it, given this issue. The final we'd need to profile ICA-AROMA, but I suspect it'll end up the same.

One way to simplify this is to modify `DerivativesDataSink` to automatically `gzip` a `.nii` file. Then if we use an unzipped file internally, we don't need to add nodes.

**Comment by effigies** [comment]
@Gilles86 If you want to give this a try: https://github.com/effigies/fmriprep/archive/enh/unzip_option.tar.gz

Adding a `--low-mem` flag to your command line should help cut down your memory usage drastically.

**Comment by Gilles86** [comment]
That version worked for me. Although still one subject crashes when I use the --use-syn-sdc argument (see https://github.com/poldracklab/fmriprep/issues/665).
