### ISSUE TITLE
Invalid SliceTiming data should result in skipped STC instead of crash

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#693]
`ds000237/task-MemorySpan_acq-multiband_bold.json:`
```JSON
{
  "RepetitionTime": 1.0,
  "EchoTime": 0.03,
  "FlipAngle": 60,
  "SliceTiming": [0.0, 0.0],
  "MultibandAccellerationFactor": 3,
  "PhaseEncodingDirection": "j",
  "TaskDescription": "sdfsd",
  "TaskName": "MemorySpan"
}
```

Example crashfile:

```
Node: fmriprep_wf.single_subject_03_wf.func_preproc_task_MemorySpan_acq_multiband_run_06_wf.bold_hmc_wf.slice_timing_correction
Working directory: /work/03843/crn_plab/stampede2/fmriprep-rc1/scratch/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_hmc_wf/slice_timing_correction

Node inputs:

args = <undefined>
environ = {}
ignore = 1
ignore_exception = False
in_file = /work/03843/crn_plab/stampede2/fmriprep-rc1/bids/ds000237/sub-03/func/sub-03_task-MemorySpan_acq-multiband_run-06_bold.nii.gz
interp = <undefined>
out_file = <undefined>
outputtype = NIFTI_GZ
rlt = <undefined>
rltplus = <undefined>
terminal_output = stream
tpattern = @/work/03843/crn_plab/stampede2/fmriprep-rc1/scratch/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_hmc_wf/create_custom_slice_timing_file/timings.1D
tr = 1.0s
tslice = <undefined>
tzero = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1757, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/afni/base.py", line 195, in _run_interface
    return super(AFNICommand, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/afni/base.py", line 132, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1791, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1715, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
3dTshift -ignore 1 -prefix sub-03_task-MemorySpan_acq-multiband_run-06_bold_tshift.nii.gz -tpattern @/work/03843/crn_plab/stampede2/fmriprep-rc1/scratch/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_hmc_wf/create_custom_slice_timing_file/timings.1D -TR 1.0s /work/03843/crn_plab/stampede2/fmriprep-rc1/scratch/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_hmc_wf/slice_timing_correction/sub-03_task-MemorySpan_acq-multiband_run-06_bold.nii.gz
Standard output:

Standard error:
++ 3dTshift: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
** AFNI converts NIFTI_datatype=4 (INT16) in file /work/03843/crn_plab/stampede2/fmriprep-rc1/scratch/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_hmc_wf/slice_timing_correction/sub-03_task-MemorySpan_acq-multiband_run-06_bold.nii.gz to FLOAT32
     Warnings of this type will be muted for this session.
     Set AFNI_NIFTI_TYPE_WARN to YES to see them all, NO to see none.
^[[7m*+ WARNING:^[[0m   If you are performing spatial transformations on an oblique dset,
  such as /work/03843/crn_plab/stampede2/fmriprep-rc1/scratch/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_hmc_wf/slice_timing_correction/sub-03_task-MemorySpan_acq-multiband_run-06_bold.nii.gz,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running:
     3dWarp -deoblique
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:/work/03843/crn_plab/stampede2/fmriprep-rc1/scratch/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_hmc_wf/slice_timing_correction/sub-03_task-MemorySpan_acq-multiband_run-06_bold.nii.gz is 6.333821 degrees from plumb.
^[[7m** FATAL ERROR:^[[0m tpattern file /work/03843/crn_plab/stampede2/fmriprep-rc1/scratch/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_hmc_wf/create_custom_slice_timing_file/timings.1D has 2 values but have 48 slices
** Program compile date = Jun 12 2017

Return code: 1
Interface TShift failed to run.
```

**Comment by chrisfilo** [comment]
But should it? The fact the field is there indicates there was intention to provide this metadata. We could return a more meaningful error message.

If a warning is desired it should be a big red warning in the report file.

Related to: https://github.com/INCF/bids-validator/issues/304

**Comment by effigies** [comment]
I'm okay with leaving this to the validator.

**Comment by effigies** [comment]
In addition to the validator warning, I think getting crashfiles fixed (current priority) should provide the error reporting we need here. Closing in favor of #686.
