### ISSUE TITLE
TemplateDimensions crash: 'tuple' object has no attribute 'tolist'

### ISSUE THREAD

**Issue by stjep** [poldracklab/fmriprep#705]
Got the following crash for one of one participant's data using the current fmriprep and the default parameters:

```
Node: fmriprep_wf.single_subject_08_wf.anat_preproc_wf.t1_template_dimensions
Working directory: /scratch/fmriprep_wf/single_subject_08_wf/anat_preproc_wf/t1_template_dimensions

Node inputs:

ignore_exception = False
max_scale = 3.0
t1w_list = ['/data/sub-08/ses-day1/anat/sub-08_ses-day1_T1w.nii.gz', '/data/sub-08/ses-day2/anat/sub-08_ses-day2_T1w.nii.gz']

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1031, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/images.py", line 211, in _run_interface
    self._results['target_shape'] = tuple(target_shape.tolist())
AttributeError: 'tuple' object has no attribute 'tolist'
Interface TemplateDimensions failed to run.
```

**Comment by stjep** [comment]
Hi. I'm on fmriprep v1.0.0-rc3. Turns out that that particular participant had their T1w and T2w images swapped. I've flipped them back and am re-running fmriprep to see if it makes it to the end.

**Comment by effigies** [comment]
@stjep did re-running resolve your issue?

**Comment by stjep** [comment]
It run fine when I pushed that single participant through with the correct file as the T1w image.
