### ISSUE TITLE
Error with --anat-only ?

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#727]
Getting this:

```
Node: _autorecon30
Working directory: /scratch/users/oesteban/francisco/work/fmriprep_wf/single_subject_P01_wf/anat_preproc_wf/surface_recon_wf/autorecon_resume_wf/autorecon3/mapflow/_autorecon30

Node inputs:

T1_files = <undefined>
T2_file = <undefined>
args = <undefined>
big_ventricles = <undefined>
brainstem = <undefined>
directive = autorecon3
environ = {}
expert = <undefined>
flags = <undefined>
hemi = lh
hippocampal_subfields_T1 = <undefined>
hippocampal_subfields_T2 = <undefined>
hires = <undefined>
ignore_exception = False
mprage = <undefined>
mri_aparc2aseg = <undefined>
mri_ca_label = <undefined>
mri_ca_normalize = <undefined>
mri_ca_register = <undefined>
mri_edit_wm_with_aseg = <undefined>
mri_em_register = <undefined>
mri_fill = <undefined>
mri_mask = <undefined>
mri_normalize = <undefined>
mri_pretess = <undefined>
mri_remove_neck = <undefined>
mri_segment = <undefined>
mri_segstats = <undefined>
mri_tessellate = <undefined>
mri_watershed = <undefined>
mris_anatomical_stats = <undefined>
mris_ca_label = <undefined>
mris_fix_topology = <undefined>
mris_inflate = <undefined>
mris_make_surfaces = <undefined>
mris_register = <undefined>
mris_smooth = <undefined>
mris_sphere = <undefined>
mris_surf2vol = <undefined>
mrisp_paint = <undefined>
openmp = 8
parallel = <undefined>
subject_id = sub-P01
subjects_dir = /out/freesurfer
talairach = <undefined>
terminal_output = stream
use_T2 = False
xopts = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1757, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1791, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1715, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
RuntimeError: Command:
recon-all -autorecon3 -hemi lh -openmp 8 -subjid sub-P01 -sd /out/freesurfer -nosphere -nosurfreg -nojacobian_white -noavgcurv -nocortparc -nopial
Standard output:
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
INFO: SUBJECTS_DIR is /out/freesurfer
Actual FREESURFER_HOME /opt/freesurfer
-rw-rw----+ 1 oesteban russpold 148252 Sep 27 21:59 /out/freesurfer/sub-P01/scripts/recon-all.log
Linux sh-104-55.int 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
'/opt/freesurfer/bin/recon-all' -> '/out/freesurfer/sub-P01/scripts/recon-all.local-copy'
#--------------------------------------------
#@# Cortical ribbon mask Wed Sep 27 23:16:06 UTC 2017
/out/freesurfer/sub-P01/mri

 mris_volmask --aseg_name aseg.presurf --label_left_white 2 --label_left_ribbon 3 --label_right_white 41 --label_right_ribbon 42 --save_ribbon sub-P01

SUBJECTS_DIR is /out/freesurfer
loading input data...

---------------------------------- typical recon-all output -----------------------------

 mri_label2label --srcsubject fsaverage --srclabel /out/freesurfer/fsaverage/label/lh.BA3b_exvivo.label --trgsubject sub-P01 --trglabel ./lh.BA3b_exvivo.label --hemi lh --regmethod surface

No such file or directory
mri_label2label.bin: could not open label file /out/freesurfer/fsaverage/label/lh.BA3b_exvivo.label

srclabel = /out/freesurfer/fsaverage/label/lh.BA3b_exvivo.label
srcsubject = fsaverage
trgsubject = sub-P01
trglabel = ./lh.BA3b_exvivo.label
regmethod = surface

srchemi = lh
trghemi = lh
trgsurface = white
srcsurfreg = sphere.reg
trgsurfreg = sphere.reg
usehash = 1
Use ProjAbs  = 0, 0
Use ProjFrac = 0, 0
DoPaint 0

SUBJECTS_DIR    /out/freesurfer
FREESURFER_HOME /opt/freesurfer
Loading source label.
Invalid argument
ERROR reading /out/freesurfer/fsaverage/label/lh.BA3b_exvivo.label
Linux sh-104-55.int 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-P01 exited with ERRORS at Wed Sep 27 23:42:54 UTC 2017

For more details, see the log file /out/freesurfer/sub-P01/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting


Standard error:
mv: cannot move '/out/freesurfer/sub-P01/scripts/recon-all.env' to '/out/freesurfer/sub-P01/scripts/recon-all.env.bak': No such file or directory

Return code: 1
Interface ReconAll failed to run.
```

**Comment by effigies** [comment]
File quota?


-------- Original message --------

**Comment by effigies** [comment]
Also, if this was on Sherlock, I think @jokedurnez had issues where occasionally a file would fail to write correctly. Re-running fixed the issue.

**Comment by jokedurnez** [comment]
Those errors are driving me CRAZY ! This happens in about 25% of the analyses on sherlock (fmriprep on NKI).  Very often at a different point during recon, and as @effigies says, just re-running helps.

**Comment by oesteban** [comment]
Ugh, thanks! I'll probably drop an email to Killian about this.
