### ISSUE TITLE
Missing T1 Images or BOLD Images

### ISSUE THREAD

**Issue by sadevp** [poldracklab/fmriprep#764]
The datasets below on OpenNeuro are failing fmriprep due to errors indicating missing scans. I am logging them here for the record. 

Missing BOLD images:

https://openneuro.org/datasets/ds001091/versions/00001

Example:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.6.5', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 207, in main
    create_workflow(opts)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 315, in create_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 185, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 336, in init_single_subject_wf
    subject_id, task_id if task_id else '<all>'))
Exception: No BOLD images found for participant 01 and task <all>. All workflows require BOLD images.
9ba44d35-c478-40de-8887-25f9110296d8-lock

Missing T1W images: 

https://openneuro.org/datasets/ds001107/versions/00001

Example: 

^@Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==0.6.5', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 207, in main
    create_workflow(opts)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 225, in create_workflow
    bids_dir, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/utils/bids.py", line 87, in collect_participants
    'may need to adjust your "File sharing" preferences.', bids_dir)
fmriprep.utils.bids.BIDSError: 
---------- BIDS root folder: "/snapshot/data" ----------
           Could not find participants. Please make sure the BIDS data structure is present and correct. Datasets can be validated online using the BIDS Validator (http://incf.github.io/bids-validator/).
If you are using Docker for Mac or Docker for Windows, you may need to adjust your "File sharing" preferences.
--------------------------------------------------------

**Comment by chrisfilo** [comment]
This is not per se an error with FMRIPREP. One thing that could be done is better reporting of missing T1w images (right now the error message is not very informative). I'll rename the issue.
