### ISSUE TITLE
LTA2FSL - LTAchangeType: dst geometry must be valid

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#768]
```
Node: fmriprep_wf.single_subject_18_wf.func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_09_wf.bold_reg_wf.bbreg_wf.lta2fsl_fwd
Working directory: /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_18_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobject
vgreeblejudgment_run_09_wf/bold_reg_wf/bbreg_wf/lta2fsl_fwd

Node inputs:

args = <undefined>
environ = {}
ignore_exception = False
in_fsl = <undefined>
in_itk = <undefined>
in_lta = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_18_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreebleju
dgment_run_09_wf/bold_reg_wf/bbreg_wf/lta_concat/out.lta
in_mni = <undefined>
in_niftyreg = <undefined>
in_reg = <undefined>
invert = <undefined>
ltavox2vox = <undefined>
out_fsl = True
out_itk = <undefined>
out_lta = <undefined>
out_mni = <undefined>
out_reg = <undefined>
source_file = <undefined>
...skipping...
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1657, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1603, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
lta_convert --inlta /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_18_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjec
tvgreeblejudgment_run_09_wf/bold_reg_wf/bbreg_wf/lta_concat/out.lta --outfsl /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_18_wf/func_preproc_task
_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_09_wf/bold_reg_wf/bbreg_wf/lta2fsl_fwd/out.mat
Standard output:
$Id: lta_convert.cpp,v 1.9.2.1 2016/08/09 02:33:22 zkaufman Exp $

--inlta: /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_18_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreebleju
dgment_run_09_wf/bold_reg_wf/bbreg_wf/lta_concat/out.lta input LTA transform.
--outfsl: /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_18_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblej
udgment_run_09_wf/bold_reg_wf/bbreg_wf/lta2fsl_fwd/out.mat output FSL matrix.

Standard error:
LTAchangeType: dst geometry must be valid


Return code: 252
```

**Comment by effigies** [comment]
Could you post the contents of the LTA file?

`/scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_18_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreebleju
dgment_run_09_wf/bold_reg_wf/bbreg_wf/lta_concat/out.lta`

**Comment by oesteban** [comment]
These may be downstream errors from memory issues.

That said, the content of the LTA file:

```
type      = 0 # LINEAR_VOX_TO_VOX
nxforms   = 1
mean      = 0.0000 0.0000 0.0000
sigma     = 1.0000
1 4 4
2.338993072509766e+00 3.371065109968185e-02 8.153776824474335e-02 -1.258421707153320e+01 
-8.531279861927032e-02 3.767331361770630e+00 8.781138658523560e-01 6.457527160644531e+00 
-1.081499904394150e-01 -7.494003772735596e-01 4.720997333526611e+00 1.022592163085938e+02 
0.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00 9.999999403953552e-01 
src volume info
valid = 1  # volume info valid
filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_18_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_09_wf/bold_reg_wf/bbreg_wf/bbregister/ants_susceptibility_War
volume = 64 64 30
voxelsize = 3.437500000000000e+00 3.437500000000000e+00 4.000000000000000e+00
xras   = 1.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00
yras   = 0.000000000000000e+00 9.961723685264587e-01 -8.741080015897751e-02
zras   = 0.000000000000000e+00 8.741079270839691e-02 9.961723685264587e-01
cras   = 3.437500000000000e+00 8.990036010742188e+00 3.509156036376953e+01
dst volume info
valid = 1  # volume info valid
filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_18_wf/anat_preproc_wf/t1_merge/sub-18_T1w_ras_template.nii.gz
volume = 124 256 256
voxelsize = 1.500000000000000e+00 8.593999743461609e-01 8.593999743461609e-01
xras   = 9.996861815452576e-01 1.847218908369541e-02 1.692104153335094e-02
yras   = -2.005212754011154e-02 9.949318170547485e-01 9.853213280439377e-02
zras   = -1.501517929136753e-02 -9.884050488471985e-02 9.949899911880493e-01
cras   = -1.622680664062500e+00 -1.621986389160156e+00 -1.976274871826172e+01
subject sub-18
fscale 0.100000
```

**Comment by effigies** [comment]
That's really odd, because I believe we're looking at [this line](https://github.com/freesurfer/freesurfer/blob/5cb50794483a79ae4823389f660211e8047eed35/utils/transform.c#L3753), which is just checking the `valid` field, both of which are set to 1.

**Comment by oesteban** [comment]
You were right, now I'm getting the error without previous memory problems:

```
171018-05:55:31,227 workflow ERROR:
         Node lta2fsl_inv failed to run on host nid00855.
171018-05:55:31,228 workflow ERROR:
         Saving crash info to /scratch/03763/oesteban/fmriprep-phase1/out/ds000110/fmriprep/sub-09/log/20171018-043333_96c77624-afea-49ed-ba59-fa7ac6458686/crash-20171018-055531-oesteban-lta2fsl_inv-6d531356-c
b57-44dd-8081-7d9e5a0f90fc.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1657, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1603, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
lta_convert --inlta /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_10_wf/
bold_reg_wf/bbreg_wf/lta_concat/out.lta --invert --outfsl /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadig
mwithobjectvgreeblejudgment_run_10_wf/bold_reg_wf/bbreg_wf/lta2fsl_inv/out.mat
Standard output:
$Id: lta_convert.cpp,v 1.9.2.1 2016/08/09 02:33:22 zkaufman Exp $

--inlta: /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_10_wf/bold_reg_wf
/bbreg_wf/lta_concat/out.lta input LTA transform.
--invert: will invert transform.
--outfsl: /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_10_wf/bold_reg_w
f/bbreg_wf/lta2fsl_inv/out.mat output FSL matrix.

Standard error:
LTAchangeType: dst geometry must be valid

Return code: 252
```
And the **--inlta** matrix:
```
/scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_10_wf/bold_reg_wf/bbreg_wf/lta_concat/out.lta
type      = 0 # LINEAR_VOX_TO_VOX
nxforms   = 1
mean      = 0.0000 0.0000 0.0000
sigma     = 1.0000
1 4 4
2.315566301345825e+00 2.085748128592968e-02 4.045203700661659e-02 -9.294662475585938e+00 
-2.344581671059132e-02 3.830733537673950e+00 -9.479558467864990e-01 1.720880126953125e+01 
-6.433360278606415e-02 7.806813716888428e-01 4.657511234283447e+00 4.599908447265625e+01 
0.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00 1.000000000000000e+00 
src volume info
valid = 1  # volume info valid
filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_10_wf/bold_reg_
wf/bbreg_wf/bbregister/ants_susceptibility_War
volume = 64 64 30
voxelsize = 3.437500000000000e+00 3.437500000000000e+00 4.000000000000000e+00
xras   = 1.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00
yras   = 0.000000000000000e+00 9.862141609191895e-01 1.654739677906036e-01
zras   = 0.000000000000000e+00 -1.654739826917648e-01 9.862141609191895e-01
cras   = 3.437500000000000e+00 3.781204223632812e-01 3.082973480224609e+01
dst volume info
valid = 1  # volume info valid
filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_merge/sub-09_T1w_ras_template.nii.gz
volume = 124 256 256
voxelsize = 1.500000000000000e+00 8.593999743461609e-01 8.593999743461609e-01
xras   = 9.999932646751404e-01 -9.467887575738132e-04 3.551774658262730e-03
yras   = 1.491618808358908e-03 9.876472353935242e-01 -1.566865593194962e-01
zras   = -3.359551541507244e-03 1.566908061504364e-01 9.876419901847839e-01
cras   = -3.667686462402344e+00 4.914848327636719e+00 -5.992797851562500e+00
subject sub-09
fscale 0.100000
```

**Comment by oesteban** [comment]
BTW, this error is happening on 174 runs (I cannot tell the total number of runs)

**Comment by effigies** [comment]
That's displeasing. Is it succeeding on any?

**Comment by oesteban** [comment]
Yes! A rough estimation is that 174 runs must be nearing 1/4 of all runs.

**Comment by effigies** [comment]
I copied the text of that LTA into `test.lta`:

```Shell
$ lta_convert --inlta test.lta --outfsl test.mat
$Id: lta_convert.cpp,v 1.9.2.1 2016/08/09 02:33:22 zkaufman Exp $

--inlta: test.lta input LTA transform.
--outfsl: test.mat output FSL matrix.
 LTA read, type : 1
 1.01047   0.00783   0.01298  -1.46301;
-0.00927   0.97034   0.11782  -0.30286;
-0.01138  -0.12668   1.01327  -27.54115;
 0.00000   0.00000   0.00000   1.00000;
FSLOUTPUTTYPE NIFTI_GZ 
tkreg2FSL: mov det = 47.2656, ref det = 1.10785
INFO: FSL2FreeSurfer: Mov volume is NIFTI with positive det,
      applying LR flip to registration matrix.
INFO: FSL2FreeSurfer: Ref volume is NIFTI with positive det,
      applying LR flip to registration matrix.
lta_convert successful.
```

That's really weird.

**Comment by oesteban** [comment]
I'm afraid the `--invert` flag has to do with it

**Comment by effigies** [comment]
```Shell
$ lta_convert --inlta test.lta --invert --outfsl test.mat 
$Id: lta_convert.cpp,v 1.9.2.1 2016/08/09 02:33:22 zkaufman Exp $

--inlta: test.lta input LTA transform.
--invert: will invert transform.
--outfsl: test.mat output FSL matrix.
 LTA read, type : 1
 1.01047   0.00783   0.01298  -1.46301;
-0.00927   0.97034   0.11782  -0.30286;
-0.01138  -0.12668   1.01327  -27.54115;
 0.00000   0.00000   0.00000   1.00000;
FSLOUTPUTTYPE NIFTI_GZ 
tkreg2FSL: mov det = 1.10785, ref det = 47.2656
INFO: FSL2FreeSurfer: Mov volume is NIFTI with positive det,
      applying LR flip to registration matrix.
INFO: FSL2FreeSurfer: Ref volume is NIFTI with positive det,
      applying LR flip to registration matrix.
lta_convert successful.
```

**Comment by oesteban** [comment]
Yep, I was trying exactly the same:

```
$ docker run -it --rm --entrypoint=lta_convert -v $PWD:/work -w /work poldracklab/fmriprep:1.0.0-rc6 --inlta test.lta --invert --outfsl out.mat
$Id: lta_convert.cpp,v 1.9.2.1 2016/08/09 02:33:22 zkaufman Exp $

--inlta: test.lta input LTA transform.
--invert: will invert transform.
--outfsl: out.mat output FSL matrix.
 LTA read, type : 1
 1.01047   0.00783   0.01298  -1.46301;
-0.00927   0.97034   0.11782  -0.30286;
-0.01138  -0.12668   1.01327  -27.54115;
 0.00000   0.00000   0.00000   1.00000;
FSLOUTPUTTYPE NIFTI_GZ 
tkreg2FSL: mov det = 1.10785, ref det = 47.2656
INFO: FSL2FreeSurfer: Mov volume is NIFTI with positive det,
      applying LR flip to registration matrix.
INFO: FSL2FreeSurfer: Ref volume is NIFTI with positive det,
      applying LR flip to registration matrix.
lta_convert successful.
```

**Comment by effigies** [comment]
Could it be memory corruption, then? That's a troubling thought.

**Comment by oesteban** [comment]
Using singularity it doesn't work:

```
singularity exec /work/03843/crn_plab/singularity/poldracklab_fmriprep_1.0.0-rc7-747-2017-10-17-103f7749e329 lta_convert --inlta /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_05_wf/bold_reg_wf/bbreg_wf/lta_concat/out.lta --invert --outfsl /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_05_wf/bold_reg_wf/bbreg_wf/lta2fsl_inv/out.mat
$Id: lta_convert.cpp,v 1.9.2.1 2016/08/09 02:33:22 zkaufman Exp $

--inlta: /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_05_wf/bold_reg_wf/bbreg_wf/lta_concat/out.lta input LTA transform.
--invert: will invert transform.
--outfsl: /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_05_wf/bold_reg_wf/bbreg_wf/lta2fsl_inv/out.mat output FSL matrix.
LTAchangeType: dst geometry must be valid
```

**Comment by effigies** [comment]
What's your $FREESURFER_HOME environment look like?

**Comment by oesteban** [comment]
Good catch. It's unset!

```
singularity exec /work/03843/crn_plab/singularity/poldracklab_fmriprep_1.0.0-rc7-747-2017-10-17-103f7749e329 echo $FREESURFER_HOME

```

**Comment by oesteban** [comment]
Oh, wait. Using env it seems to be set.
More about the envs:

```
$ singularity exec /work/03843/crn_plab/singularity/poldracklab_fmriprep_1.0.0-rc7-747-2017-10-17-103f7749e329 env | grep FSL
FSLDIR=/usr/share/fsl/5.0
FSLMULTIFILEQUIT=TRUE
FSLTCLSH=/usr/bin/tclsh
FSLOUTPUTTYPE=NIFTI_GZ
FSLWISH=/usr/bin/wish
FSL_DIR=/usr/share/fsl/5.0
```

And
```
singularity exec /work/03843/crn_plab/singularity/poldracklab_fmriprep_1.0.0-rc7-747-2017-10-17-103f7749e329 env | grep FREE
FREESURFER_HOME=/opt/freesurfer
```

**Comment by effigies** [comment]
I wonder if it's a dynamic linking issue. Can you open a shell, run `ldconfig`, and then try the  `lta_convert` call?

**Comment by oesteban** [comment]
You are right. That works.

**Comment by oesteban** [comment]
How can we go about this?, add an ldconfig call after installing freesurfer in the dockerfile?

**Comment by effigies** [comment]
There's an ldconfig at the end of the Dockerfile, already. We discussed in #749 whether adding `sync` afterwards might help. Are you in a position to try this?

**Comment by effigies** [comment]
Alternatively, see https://github.com/poldracklab/fmriprep/issues/749#issuecomment-336170941 for a simple Singularity recipe that runs `ldconfig` after converting from Docker.

**Comment by oesteban** [comment]
This should do?

```
# Installing freesurfer
RUN curl -sSL https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz | tar zxv -C /opt \
    --exclude='freesurfer/trctrain' \
    --exclude='freesurfer/subjects/fsaverage_sym' \
    --exclude='freesurfer/subjects/fsaverage3' \
    --exclude='freesurfer/subjects/fsaverage4' \
    --exclude='freesurfer/subjects/cvs_avg35' \
    --exclude='freesurfer/subjects/cvs_avg35_inMNI152' \
    --exclude='freesurfer/subjects/bert' \
    --exclude='freesurfer/subjects/V1_average' \
    --exclude='freesurfer/average/mult-comp-cor' \
    --exclude='freesurfer/lib/cuda' \
    --exclude='freesurfer/lib/qt' && \
    sync; sync; sync; \
    ldconfig && \
    sync; sync; sync;
```

**Comment by effigies** [comment]
No idea. Out of curiosity, why is it not enough to do it here?

https://github.com/poldracklab/fmriprep/blob/3b144c57f04105e1e48ea2f7f052267a1509da82/Dockerfile#L168

**Comment by oesteban** [comment]
No idea, I'm going to first make sure this new ldconfig addresses the problem at hand. Then we can get deeper into #749

**Comment by oesteban** [comment]
Ok, for some reason the `ldconfig` trick does not work anymore.

**Comment by effigies** [comment]
I can't reproduce this issue on either stampede2 or ls5.

```Shell
$ idev
$ module load tacc-singularity
$ singularity exec /work/03843/crn_plab/singularity//poldracklab_fmriprep_1.0.0-rc7-747-2017-10-17-cc920f8dcef8.img
$ cat > test.lta
[LTA TEXT FROM ABOVE]
^D
$ lta_convert --inlta test.lta --invert --outfsl test.mat
$Id: lta_convert.cpp,v 1.9.2.1 2016/08/09 02:33:22 zkaufman Exp $

--inlta: test.lta input LTA transform.
--invert: will invert transform.
--outfsl: test.mat output FSL matrix.
 LTA read, type : 1
 1.01047   0.00783   0.01298  -1.46301;
-0.00927   0.97034   0.11782  -0.30286;
-0.01138  -0.12668   1.01327  -27.54115;
 0.00000   0.00000   0.00000   1.00000;
FSLOUTPUTTYPE NIFTI_GZ 
tkreg2FSL: mov det = 1.10785, ref det = 47.2656
INFO: FSL2FreeSurfer: Mov volume is NIFTI with positive det,
      applying LR flip to registration matrix.
INFO: FSL2FreeSurfer: Ref volume is NIFTI with positive det,
      applying LR flip to registration matrix.
lta_convert successful.
```

I'm not running `ldconfig` and it's just working.

**Comment by oesteban** [comment]
thanks, I'll try to find out what is it with my environment.

**Comment by oesteban** [comment]
Ok, the filename fields are being cut:

This will work (test3.lta):

```
type      = 0 # LINEAR_VOX_TO_VOX
nxforms   = 1
mean      = 0.0000 0.0000 0.0000
sigma     = 1.0000
1 4 4
2.327464342117310e+00 4.245608299970627e-02 3.455499932169914e-02 -1.319661331176758e+01 
-7.824462652206421e-02 3.904805898666382e+00 2.233271896839142e-01 -5.291442871093750e-01 
-4.939173907041550e-02 -1.728723645210266e-01 4.818737983703613e+00 7.657078552246094e+01 
0.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00 1.000000000000000e+00 
src volume info
valid = 1  # volume info valid
filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_05_wf/bold_reg_wf/bbreg_wf/bbregister/ants_susceptibility_Warped_masked_bbreg_sub-07.lta
volume = 64 64 30
voxelsize = 3.437500000000000e+00 3.437500000000000e+00 4.000000000000000e+00
xras   = 1.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00
yras   = 0.000000000000000e+00 9.979115724563599e-01 -6.459446996450424e-02
zras   = 0.000000000000000e+00 6.459447741508484e-02 9.979115724563599e-01
cras   = 3.437500000000000e+00 8.357086181640625e-01 4.582891845703125e+01
dst volume info
valid = 1  # volume info valid
filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/anat_preproc_wf/t1_merge/sub-07_T1w_ras_template.nii.gz
volume = 124 256 256
voxelsize = 1.500000000000000e+00 8.593999743461609e-01 8.593999743461609e-01
xras   = 9.998608827590942e-01 1.065783575177193e-02 -1.283265277743340e-02
yras   = -9.511843323707581e-03 9.962262511253357e-01 8.627174794673920e-02
zras   = 1.370369549840689e-02 -8.613768219947815e-02 9.961889982223511e-01
cras   = -3.533935546875000e-01 5.862289428710938e+00 -1.128549194335938e+01
subject sub-07
fscale 0.100000
```

But please, double check that this one won't (test.lta):
```
type      = 0 # LINEAR_VOX_TO_VOX
nxforms   = 1
mean      = 0.0000 0.0000 0.0000
sigma     = 1.0000
1 4 4
2.327464342117310e+00 4.245608299970627e-02 3.455499932169914e-02 -1.319661331176758e+01 
-7.824462652206421e-02 3.904805898666382e+00 2.233271896839142e-01 -5.291442871093750e-01 
-4.939173907041550e-02 -1.728723645210266e-01 4.818737983703613e+00 7.657078552246094e+01 
0.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00 1.000000000000000e+00 
src volume info
valid = 1  # volume info valid
filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_05_wf/bold_reg_wf/bbreg_wf/bbregister/ants_susceptibility_War
volume = 64 64 30
voxelsize = 3.437500000000000e+00 3.437500000000000e+00 4.000000000000000e+00
xras   = 1.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00
yras   = 0.000000000000000e+00 9.979115724563599e-01 -6.459446996450424e-02
zras   = 0.000000000000000e+00 6.459447741508484e-02 9.979115724563599e-01
cras   = 3.437500000000000e+00 8.357086181640625e-01 4.582891845703125e+01
dst volume info
valid = 1  # volume info valid
filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/anat_preproc_wf/t1_merge/sub-07_T1w_ras_template.nii.gz
volume = 124 256 256
voxelsize = 1.500000000000000e+00 8.593999743461609e-01 8.593999743461609e-01
xras   = 9.998608827590942e-01 1.065783575177193e-02 -1.283265277743340e-02
yras   = -9.511843323707581e-03 9.962262511253357e-01 8.627174794673920e-02
zras   = 1.370369549840689e-02 -8.613768219947815e-02 9.961889982223511e-01
cras   = -3.533935546875000e-01 5.862289428710938e+00 -1.128549194335938e+01
subject sub-07
fscale 0.100000
```

```Diff
$ diff test.lta test3.lta 
12c12
< filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_05_wf/bold_reg_wf/bbreg_wf/bbregister/ants_susceptibility_War
---
> filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_05_wf/bold_reg_wf/bbreg_wf/bbregister/ants_susceptibility_Warped_masked_bbreg_sub-07.lta
```

**Comment by oesteban** [comment]
Hehehe:

```Python
print(len('filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_07_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_05_wf/bold_reg_wf/bbreg_wf/bbregister/ants_susceptibility_War'))
255
```

Ok, I think this is it. `mri_concatenate_lta` clips lines to be 255 characters long, and long paths get cropped. Interestingly, lta convert seems to accept files with lines >255 characters.

Does it make any sense @effigies ?

**Comment by effigies** [comment]
Yeah, it's 256 characters with the newline, which I suspect means the string isn't getting null-terminated. (Remove one character from the end of the line, and it works fine. Actually, add one character to the end of the line, and it works fine, too.)

So it's a bug on `mri_concatenate_lta` truncating lines (or, possibly, one of the concatenated files starting with a truncated line, and `mri_concatenate_lta` handles it smoothly), and `lta_convert` screwing something up when it has 255 character lines. We could probably modify the `ConcatenateLTA` interface to adjust these lines.

Okay with you to submit this without editing filenames to the FreeSurfer mailing list? (I could also just replace all of the non-slashes with `a`.)

**Comment by oesteban** [comment]
This doesn't work:

```
$ cat -An test_wrong.lta
     1  type      = 0 # LINEAR_VOX_TO_VOX$
     2  nxforms   = 1$
     3  mean      = 0.0000 0.0000 0.0000$
     4  sigma     = 1.0000$
     5  1 4 4$
     6  2.315566301345825e+00 2.085748128592968e-02 4.045203700661659e-02 -9.294662475585938e+00 $
     7  -2.344581671059132e-02 3.830733537673950e+00 -9.479558467864990e-01 1.720880126953125e+01 $
     8  -6.433360278606415e-02 7.806813716888428e-01 4.657511234283447e+00 4.599908447265625e+01 $
     9  0.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00 1.000000000000000e+00 $
    10  src volume info$
    11  valid = 1  # volume info valid$
    12  filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_10_wf/bold_reg_wf/bbreg_wf/bbregister/ants_susceptibility_War$
    13  volume = 64 64 30$
    14  voxelsize = 3.437500000000000e+00 3.437500000000000e+00 4.000000000000000e+00$
    15  xras   = 1.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00$
    16  yras   = 0.000000000000000e+00 9.862141609191895e-01 1.654739677906036e-01$
    17  zras   = 0.000000000000000e+00 -1.654739826917648e-01 9.862141609191895e-01$
    18  cras   = 3.437500000000000e+00 3.781204223632812e-01 3.082973480224609e+01$
    19  dst volume info$
    20  valid = 1  # volume info valid$
    21  filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_merge/sub-09_T1w_ras_template.nii.gz$
    22  volume = 124 256 256$
    23  voxelsize = 1.500000000000000e+00 8.593999743461609e-01 8.593999743461609e-01$
    24  xras   = 9.999932646751404e-01 -9.467887575738132e-04 3.551774658262730e-03$
    25  yras   = 1.491618808358908e-03 9.876472353935242e-01 -1.566865593194962e-01$
    26  zras   = -3.359551541507244e-03 1.566908061504364e-01 9.876419901847839e-01$
    27  cras   = -3.667686462402344e+00 4.914848327636719e+00 -5.992797851562500e+00$
    28  subject sub-09$
    29  fscale 0.100000$
```

while this works:

```
$ cat -An test_wrong_fixed.lta
     1  type      = 0 # LINEAR_VOX_TO_VOX$
     2  nxforms   = 1$
     3  mean      = 0.0000 0.0000 0.0000$
     4  sigma     = 1.0000$
     5  1 4 4$
     6  2.315566301345825e+00 2.085748128592968e-02 4.045203700661659e-02 -9.294662475585938e+00 $
     7  -2.344581671059132e-02 3.830733537673950e+00 -9.479558467864990e-01 1.720880126953125e+01 $
     8  -6.433360278606415e-02 7.806813716888428e-01 4.657511234283447e+00 4.599908447265625e+01 $
     9  0.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00 1.000000000000000e+00 $
    10  src volume info$
    11  valid = 1  # volume info valid$
    12  filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_10_wf/bold_reg_wf/bbreg_wf/bbregister/ants_susceptibility_Warp$
    13  volume = 64 64 30$
    14  voxelsize = 3.437500000000000e+00 3.437500000000000e+00 4.000000000000000e+00$
    15  xras   = 1.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00$
    16  yras   = 0.000000000000000e+00 9.862141609191895e-01 1.654739677906036e-01$
    17  zras   = 0.000000000000000e+00 -1.654739826917648e-01 9.862141609191895e-01$
    18  cras   = 3.437500000000000e+00 3.781204223632812e-01 3.082973480224609e+01$
    19  dst volume info$
    20  valid = 1  # volume info valid$
    21  filename = /scratch/03763/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_merge/sub-09_T1w_ras_template.nii.gz$
    22  volume = 124 256 256$
    23  voxelsize = 1.500000000000000e+00 8.593999743461609e-01 8.593999743461609e-01$
    24  xras   = 9.999932646751404e-01 -9.467887575738132e-04 3.551774658262730e-03$
    25  yras   = 1.491618808358908e-03 9.876472353935242e-01 -1.566865593194962e-01$
    26  zras   = -3.359551541507244e-03 1.566908061504364e-01 9.876419901847839e-01$
    27  cras   = -3.667686462402344e+00 4.914848327636719e+00 -5.992797851562500e+00$
    28  subject sub-09$
    29  fscale 0.100000$
```

So, even the newline is there. I'd really appreciate that you submitted this issue to FreeSurfer. You can point them to these latest comments.

In the short term, I guess we could add a preemptive patch in nipype. WDYT?

**Comment by effigies** [comment]
Ugh, it's this function: https://github.com/freesurfer/freesurfer/blob/5cb50794483a79ae4823389f660211e8047eed35/utils/transform.c#L374-L438

**Comment by oesteban** [comment]
My idea would be to use the `copy` meta for the inputs in the nipype interface, and then add `os.path.basename` filters in the `_format_args` so that names are easily < 255
