### ISSUE TITLE
STC Fallback

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#775]
Make a preemptive sanity check on the SliceTime metadata and skip STC if it is not correct:

```
171018-04:35:05,878 workflow ERROR:
         Saving crash info to /scratch/03763/oesteban/fmriprep-phase1/out/ds000237/fmriprep/sub-03/log/20171018-043320_6584c469-6f5f-48c3-b815-5bb307950caa/crash-20171018-043505-oesteban-slice_timing_correctio
n-98f4b9e7-2b1d-4d94-ac9b-03e1802d4ac6.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/afni/base.py", line 129, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1657, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1603, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
3dTshift -ignore 1 -prefix sub-03_task-MemorySpan_acq-multiband_run-06_bold_tshift.nii.gz -tpattern @/scratch/03763/oesteban/fmriprep-phase1/work/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_Mem
orySpan_acq_multiband_run_06_wf/bold_stc_wf/create_custom_slice_timing_file/timings.1D -TR 1.0s /scratch/03763/oesteban/fmriprep-phase1/work/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySp
an_acq_multiband_run_06_wf/bold_stc_wf/slice_timing_correction/sub-03_task-MemorySpan_acq-multiband_run-06_bold.nii.gz
Standard output:

Standard error:
++ 3dTshift: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
** AFNI converts NIFTI_datatype=4 (INT16) in file /scratch/03763/oesteban/fmriprep-phase1/work/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_stc_wf/slice_t
iming_correction/sub-03_task-MemorySpan_acq-multiband_run-06_bold.nii.gz to FLOAT32
     Warnings of this type will be muted for this session.
     Set AFNI_NIFTI_TYPE_WARN to YES to see them all, NO to see none.
ESC[7m*+ WARNING:ESC[0m   If you are performing spatial transformations on an oblique dset, 
  such as /scratch/03763/oesteban/fmriprep-phase1/work/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_stc_wf/slice_timing_correction/sub-03_task-MemorySpan_
acq-multiband_run-06_bold.nii.gz,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:/scratch/03763/oesteban/fmriprep-phase1/work/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_stc_wf/slice_timing_correction/sub-03_task-Me
morySpan_acq-multiband_run-06_bold.nii.gz is 6.333821 degrees from plumb.
ESC[7m** FATAL ERROR:ESC[0m tpattern file /scratch/03763/oesteban/fmriprep-phase1/work/ds000237/fmriprep_wf/single_subject_03_wf/func_preproc_task_MemorySpan_acq_multiband_run_06_wf/bold_stc_wf/create_custom_s
lice_timing_file/timings.1D has 2 values but have 48 slices
** Program compile date = Jun 12 2017

Return code: 1
```

This dataset has JSON sidecars with incorrect slice timing information. It should probably not validate (WDYT @chrisfilo?). I reported the issue about one week ago to OpenfMRI (ping @suyashdb). BUT, given that there is no slice timing info, fmriprep could just throw a WARNING and keep going.

**Comment by chrisfilo** [comment]
Such warning would easily be lost in the logs. Inclusion of slice timing
metadata indicates a desire to represent this metadata. The fact that it's
incorrect means the user did not follow the spec accurately (but not
intentionally). Personally I think this should be an error not a warning.

BTW it might be worth including the validator in the Docker image and
running it before the pipeline.

**Comment by effigies** [comment]
The warning would be easy to include in the functional report summary. We already report when the BOLD series is too short.

**Comment by oesteban** [comment]
What do you think? I'm still inclined to go for robustness (with a big fat warning in the report) rather than checking the inputs.

**Comment by chrisfilo** [comment]
I might come across too strict on this, but I have been struck by silent
errors or warnings that should have been errors too many time. I still
think we should fail when slice timing information is incorrect instead of
issuing a warning. Happy to discuss further during our next call.

Best,
Chris

**Comment by oesteban** [comment]
That's definitely easier to implement :D

**Comment by oesteban** [comment]
Let's reopen if somebody complains in neurostars or here.
