### ISSUE TITLE
aCompCor - numpy.linalg.linalg.LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#776]
DS105 / sub-6

Probably one that will pop up to nipype:
```
171018-06:23:12,950 workflow ERROR:
         Node acompcor failed to run on host nid00799.
171018-06:23:12,953 workflow ERROR:
         Saving crash info to /scratch/03763/oesteban/fmriprep-phase1/out/ds000105/fmriprep/sub-6/log/20171018-043321_cd7ae052-544c-497a-93d2-3b569f611033/crash-20171018-062312-oesteban-acompcor-ea1bbd45-3ed1-
4714-a7a1-52b68b13b70a.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/common/report.py", line 55, in _run_interface
    ReportCapableInterface, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 471, in _run_interface
    self.inputs.pre_filter, degree, self.inputs.high_pass_cutoff, TR)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 1070, in compute_noise_components
    u, _, _ = linalg.svd(M, full_matrices=False)
  File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/linalg/decomp_svd.py", line 119, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.linalg.LinAlgError: SVD did not converge
```

**Comment by oesteban** [comment]
https://stackoverflow.com/questions/21827594/raise-linalgerrorsvd-did-not-converge-linalgerror-svd-did-not-converge-in-m

**Comment by oesteban** [comment]
This issue could have been resolved by #807. Checking it now.

**Comment by oesteban** [comment]
The issue is not solved. Happened again (DS110/sub-09):

```
Node: fmriprep_wf.single_subject_09_wf.func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_07_wf.bold_confounds_wf.tcompcor
Working directory: /scratch/users/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_07_wf/bold_confounds_wf/tcompcor

Node inputs:

components_file = tcompcor.tsv
compress_report = auto
generate_report = True
header_prefix = <undefined>
high_pass_cutoff = 128.0
ignore_exception = False
ignore_initial_volumes = 0
mask_files = ['/scratch/users/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_07_wf/bold_confounds_wf/tcc_tfm/highres001_BrainExtractionMask_eroded_trans_boldmsk.nii.gz']
mask_index = <undefined>
merge_method = <undefined>
num_components = 6
out_report = report.html
percentile_threshold = 0.05
pre_filter = cosine
realigned_file = /scratch/users/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_07_wf/bold_bold_trans_wf/merge/vol0000_xform-00000_merged.nii.gz
regress_poly_degree = 1
repetition_time = 2.0
save_pre_filter = True
use_regress_poly = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/common/report.py", line 55, in _run_interface
    ReportCapableInterface, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 471, in _run_interface
    self.inputs.pre_filter, degree, self.inputs.high_pass_cutoff, TR)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 1071, in compute_noise_components
    u, _, _ = linalg.svd(M, full_matrices=False)
  File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/linalg/decomp_svd.py", line 119, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.linalg.LinAlgError: SVD did not converge
```

The issue is that
```Python
mask_files = ['/scratch/users/oesteban/fmriprep-phase1/work/ds000110/fmriprep_wf/single_subject_09_wf/func_preproc_task_IncidentalencodingtaskusingPosnercueingparadigmwithobjectvgreeblejudgment_run_07_wf/bold_confounds_wf/tcc_tfm/highres001_BrainExtractionMask_eroded_trans_boldmsk.nii.gz']
```
should contain two files: the tCompCor ROI and the brain mask. For this node only the brain mask was supplied.

My first impression is that this is a problem derived from re-running over pre-cached results.

**Comment by oesteban** [comment]
Cleaning up the work directory fixed this issue

**Comment by chrisfilo** [comment]
Just run into this with rc11: https://openneuro.org/datasets/ds000148/versions/00001?app=FMRIPREP&version=36&job=5980542c-d3c3-4cf6-87a1-e1f13a929215

**Comment by oesteban** [comment]
Same issue:

```
mask_files = ['/root/src/fmriprep/work/fmriprep_wf/single_subject_01_wf/func_preproc_task_figure2backwith1backlures_run_01_wf/bold_confounds_wf/tcc_tfm/highres001_BrainExtractionMask_eroded_trans_boldmsk.nii.gz']
```

`acc_msk` seems to have failed in generating two files instead of only one.

**Comment by mvdoc** [comment]
Got the same error on two subjects for two runs, and inspecting the crash file the `mask_file` has only one file as described above.

**Comment by oesteban** [comment]
thanks for reporting @mvdoc. Since it is happening to more and more users, we are definitely setting higher priority to this issue

**Comment by mvdoc** [comment]
@oesteban no problem. it worked fine for those subjects after removing the workdir and re-running fmriprep for that subject.

**Comment by effigies** [comment]
Do we have a reliably reproducing case at this point, or is this stochastic?

**Comment by oesteban** [comment]
Coming back to this. Running the interface isolated, same inputs, works like a charm.

Seems like a memory error.
