### ISSUE TITLE
t1_merge - Currently not supported, maybe first make conform?

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#777]
DS148 / sub-09

```
         Node t1_merge failed to run on host nid00835.
171018-08:10:24,613 workflow ERROR:
         Saving crash info to /work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000148/fmriprep/sub-09/log/20171018-081002_5ae7832f-adeb-488c-8387-73ec44c7e1fc/crash-20171018-081024-oesteban-t1_merg
e-d0294b4f-4545-483c-acbc-98f57a29aef2.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/freesurfer/base.py", line 286, in run
    return super(FSCommandOpenMP, self).run(**inputs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/freesurfer/base.py", line 162, in run
    return super(FSCommand, self).run(**inputs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1657, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1603, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
mri_robust_template --satit --fixtp --mov /scratch/03763/oesteban/fmriprep-phase2/work/ds000148/sub-09/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_conform/mapflow/_t1_conform0/sub-09_acq-axial_run-01_T
1w_ras.nii.gz /scratch/03763/oesteban/fmriprep-phase2/work/ds000148/sub-09/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_conform/mapflow/_t1_conform1/sub-09_acq-sagittal_run-01_T1w_ras.nii.gz --inittp 1 
--iscale --noit --template sub-09_acq-axial_run-01_T1w_ras_template.nii.gz --subsample 200
Standard output:
$Id: mri_robust_template.cpp,v 1.54 2016/05/05 21:17:08 mreuter Exp $

--satit: Will estimate SAT iteratively!
--fixtp: Will map everything to init TP!
--mov: Using /scratch/03763/oesteban/fmriprep-phase2/work/ds000148/sub-09/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_conform/mapflow/_t1_conform0/sub-09_acq-axial_run-01_T1w_ras.nii.gz as movable/sour
ce volume.
--mov: Using /scratch/03763/oesteban/fmriprep-phase2/work/ds000148/sub-09/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_conform/mapflow/_t1_conform1/sub-09_acq-sagittal_run-01_T1w_ras.nii.gz as movable/s
ource volume.
    Total: 2 input volumes
--inittp: Using TP 1 as target for initialization
--iscale: Enableing intensity scaling!
--noit: Will output only first template (no iterations)!
--template: Using sub-09_acq-axial_run-01_T1w_ras_template.nii.gz as template output volume.
--subsample: Will subsample if size is larger than 200 on all axes!
Setting iscale ...
reading source '/scratch/03763/oesteban/fmriprep-phase2/work/ds000148/sub-09/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_conform/mapflow/_t1_conform0/sub-09_acq-axial_run-01_T1w_ras.nii.gz'...
converting source '/scratch/03763/oesteban/fmriprep-phase2/work/ds000148/sub-09/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_conform/mapflow/_t1_conform0/sub-09_acq-axial_run-01_T1w_ras.nii.gz' to bspli
ne ...
MRItoBSpline degree 3
reading source '/scratch/03763/oesteban/fmriprep-phase2/work/ds000148/sub-09/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_conform/mapflow/_t1_conform1/sub-09_acq-sagittal_run-01_T1w_ras.nii.gz'...
converting source '/scratch/03763/oesteban/fmriprep-phase2/work/ds000148/sub-09/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_conform/mapflow/_t1_conform1/sub-09_acq-sagittal_run-01_T1w_ras.nii.gz' to bs
pline ...
MRItoBSpline degree 3

Standard error:

  Currently not supported, maybe first make conform?
  Debug info: size(1) = 0.9375, 0.9375, 0.9766   size(0) = 0.9375, 0.9375, 1
MultiRegistration::loadMovables: voxel size is different /scratch/03763/oesteban/fmriprep-phase2/work/ds000148/sub-09/fmriprep_wf/single_subject_09_wf/anat_preproc_wf/t1_conform/mapflow/_t1_conform1/sub-09_acq
-sagittal_run-01_T1w_ras.nii.gz.

No such file or directory

Return code: 251
```

**Comment by oesteban** [comment]
WDYT @effigies ?

**Comment by effigies** [comment]
The originals have these shapes:

Axial: 0.9375 x 0.9375 x 1.0000
Sagittal: 1.0000 x 0.9766 x 0.9766

The sagittal gets correctly dropped down to 0.9375 x 0.9375 x 0.9766, but (1.0000 - 0.9766) < 0.05, which is the threshold we used for deciding whether or not to resample. It seems this threshold is too liberal for `mri_robust_template`. Maybe consider making the threshold 0.02mm?

https://github.com/poldracklab/fmriprep/blob/31b1536b5cf1a794bb8db3d2ec57ed29110cd4ac/fmriprep/interfaces/images.py#L243

**Comment by oesteban** [comment]
The tolerance change didn't help.

@satra, how did you fix this? (https://mail.nmr.mgh.harvard.edu/pipermail//freesurfer/2016-May/045778.html)

**Comment by satra** [comment]
@oesteban - unfortunately, for mri_robust register to work in this case, you need to have all images with the same resolution. you can do this with mri_convert or some such. perhaps the tolerance should be more along the lines of `np.allclose`

```
> Hi Satra
>
> it will probably reject this by default, which you can get around be
> reslicing one of them to be like the other. Or "conforming" both of them.
>
> cheers
> Bruce
```

**Comment by effigies** [comment]
@oesteban Clear out your scratch. At least the subject discussed in the initial post of this issue runs fine for me once I do. (The inputs to conformation are the same, and nipype doesn't recognize the change in interface, so doesn't re-run by default.)

**Comment by oesteban** [comment]
What you mean is that our `t1_merge` already resamples if the affines are different given a certain tolerance?

**Comment by effigies** [comment]
`t1_conform` resamples if the zooms are different from the target zooms. (It decides this on a per-dimension basis.) `t1_merge` does not resample, but `mri_robust_template` can handle small differences. I don't know what their tolerance is, but apparently it's smaller than .02mm.

**Comment by oesteban** [comment]
I see, thanks!

**Comment by oesteban** [comment]
@effigies, clearing up my work directory did it. Thanks!
