### ISSUE TITLE
ERROR: there is a pre-existing expert options file

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#781]
When trying to re-run the anatomical workflow of a dataset:

```
171020-17:42:15,132 workflow ERROR:
         Saving crash info to /work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000224/fmriprep/sub-MSC05/log/20171020-174146_866ea71c-1e79-4415-96a4-bfd5d1a8ac49/crash-2
0171020-174215-oesteban-autorecon1-40cc1575-ae95-45dd-950d-7e2eaf97e6a7.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1654, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1600, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1654, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1600, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
recon-all -autorecon1 -T2 /work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000224/sub-MSC05/ses-struct01/anat/sub-MSC05_ses-struct01_run-01_T2w.nii.gz -noskullstrip -h
ires -openmp 8 -subjid sub-MSC05 -sd /work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000224/freesurfer -expert /scratch/03763/oesteban/fmriprep-phase2/work/ds000224/sub
-MSC05/fmriprep_wf/single_subject_MSC05_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts -nomotioncor
Standard output:
INFO: hi-res volumes are conformed to the min voxel size
ERROR: there is a pre-existing expert options file and
you have specified an expert options file on the command-line.
If you want to use the file specified on the command-line,
you must run with -xopts-overwrite, or you may edit the
existing file /scratch/03763/oesteban/fmriprep-phase2/work/ds000224/sub-MSC05/fmriprep_wf/single_subject_MSC05_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts (and not us
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1600, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
recon-all -autorecon1 -T2 /work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000224/sub-MSC05/ses-struct01/anat/sub-MSC05_ses-struct01_run-01_T2w.nii.gz -noskullstrip -h
ires -openmp 8 -subjid sub-MSC05 -sd /work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000224/freesurfer -expert /scratch/03763/oesteban/fmriprep-phase2/work/ds000224/sub
-MSC05/fmriprep_wf/single_subject_MSC05_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts -nomotioncor
Standard output:
INFO: hi-res volumes are conformed to the min voxel size
ERROR: there is a pre-existing expert options file and
you have specified an expert options file on the command-line.
If you want to use the file specified on the command-line,
you must run with -xopts-overwrite, or you may edit the
existing file /scratch/03763/oesteban/fmriprep-phase2/work/ds000224/sub-MSC05/fmriprep_wf/single_subject_MSC05_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts (and not us
e the -expert option).
Standard error:

Return code: 1

171020-17:42:25,258 workflow ERROR:
         could not run node: fmriprep_wf.single_subject_MSC05_wf.anat_preproc_wf.surface_recon_wf.autorecon1
171020-17:42:25,311 cli WARNING:
         Errors occurred while generating reports for participants: MSC05 (1)
```

**Comment by effigies** [comment]
Need to compare: 

* `fmriprep_wf/single_subject_MSC05_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts`
* `/work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000224/freesurfer/sub-MSC05/scripts/expert.opts` (Pretty sure that's where it should be; for some reason the error message is using the input location where it should describe the existing file location)

**Comment by oesteban** [comment]
`/scratch/03763/oesteban/fmriprep-phase2/work/ds000224/sub-MSC05/fmriprep_wf/single_subject_MSC05_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts` ::

```
mris_inflate -n 50
```

`/work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000224/freesurfer/sub-MSC05/scripts/expert-options` exists and it's empty.

**Comment by effigies** [comment]
What happened during the previous run? That looks like something went wrong.

I would just delete the old `expert-options` and re-run. In general, we can't handle all of the ways in which people might give us a broken FreeSurfer directory.

**Comment by oesteban** [comment]
Ok, so this is probably an outcome of a faulty execution. Will re-run without the file.

**Comment by oesteban** [comment]
This seems to be fixed by sanitizing freesurfer's output directory.
