### ISSUE TITLE
Error applying transforms

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#784]
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/itk.py", line 260, in _applytfms
    runtime = xfm.run().runtime
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/fixes.py", line 29, in _run_interface
    self.__class__.__name__, __version__))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/utils.py", line 147, in _copyxform
    resampled = nb.load(out_image)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/loadsave.py", line 48, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/root/src/fmriprep/work/fmriprep_wf/single_subject_098_wf/func_preproc_ses_01_task_MGT_run_02_wf/bold_reg_wf/bold_to_t1w_transform/vol0371_xform-00371.nii.gz"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/itk.py", line 143, in _run_interface
    for i, (in_file, in_xfm) in enumerate(zip(in_files, xfms_list))]
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/root/src/fmriprep/work/fmriprep_wf/single_subject_098_wf/func_preproc_ses_01_task_MGT_run_02_wf/bold_reg_wf/bold_to_t1w_transform/vol0371_xform-00371.nii.gz"
```

**Comment by oesteban** [comment]
I haven't seen this again. I'll close for now.
