### ISSUE TITLE
Autorecon segfault - MRInormalize(): No such file or directory

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#789]
DS000221 / sub-010251

(multisession, includes T2w)

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1654, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1600, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
recon-all -autorecon1 -T2 /work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000221/sub-010251/ses-01/anat/sub-010251_ses-01_T2w.nii.gz -noskullstrip -openmp 8 -subjid sub-010251 -sd /work/03843/cr
n_plab/stampede2/fmriprep-phase2/derivatives/ds000221/freesurfer -nomotioncor -notalairach -nonuintensitycor
Standard output:
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
INFO: SUBJECTS_DIR is /work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000221/freesurfer
Actual FREESURFER_HOME /opt/freesurfer
-rw-rw----+ 1 oesteban G-802037 94522 Oct 20 17:42 /work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000221/freesurfer/sub-010251/scripts/recon-all.log
Linux nid00091 3.0.101-0.46.1_1.0502.8871-cray_ari_c #1 SMP Sat Oct 22 15:27:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
'/opt/freesurfer/bin/recon-all' -> '/work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000221/freesurfer/sub-010251/scripts/recon-all.local-copy'
#--------------------------------------------
#@# T2/FLAIR Input Wed Oct 25 17:24:32 UTC 2017
/work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000221/freesurfer/sub-010251

 mri_convert --no_scale 1 /work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000221/sub-010251/ses-01/anat/sub-010251_ses-01_T2w.nii.gz /work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds
000221/freesurfer/sub-010251/mri/orig/T2raw.mgz 

mri_convert.bin --no_scale 1 /work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000221/sub-010251/ses-01/anat/sub-010251_ses-01_T2w.nii.gz /work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives
/ds000221/freesurfer/sub-010251/mri/orig/T2raw.mgz 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /work/03843/crn_plab/stampede2/fmriprep-phase2/data/openfmri/ds000221/sub-010251/ses-01/anat/sub-010251_ses-01_T2w.nii.gz...
TR=3200.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (0.997129, -0.0593039, -0.0470769)
j_ras = (0.0593698, 0.998236, -1.77311e-09)
k_ras = (0.0469938, -0.00279494, 0.998891)
writing to /work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000221/freesurfer/sub-010251/mri/orig/T2raw.mgz...
#--------------------------------------------
#@# Intensity Normalization Wed Oct 25 17:24:34 UTC 2017
/work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000221/freesurfer/sub-010251/mri

 mri_normalize -g 1 -mprage nu.mgz T1.mgz 

using max gradient = 1.000
assuming input volume is MGH (Van der Kouwe) MP-RAGE
reading from nu.mgz...
normalizing image...
talairach transform
 0.39721   0.42635  -0.25834  -5.05436;
-0.49783   0.32203  -0.23398  -59.85409;
-0.02598   0.34758   0.53366   185.32791;
 0.00000   0.00000   0.00000   1.00000;
processing without aseg, no1d=0
MRInormInit(): 
INFO: Modifying talairach volume c_(r,a,s) based on average_305
MRInormalize: could not find any valid peaks.

Make sure the Talairach alignment is correct!

MRInormalize(): 
No such file or directory
1d normalization failed - trying no1d...
Segmentation fault
Linux nid00091 3.0.101-0.46.1_1.0502.8871-cray_ari_c #1 SMP Sat Oct 22 15:27:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-010251 exited with ERRORS at Wed Oct 25 17:25:01 UTC 2017

For more details, see the log file /work/03843/crn_plab/stampede2/fmriprep-phase2/derivatives/ds000221/freesurfer/sub-010251/scripts/recon-all.log

To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Standard error:

Return code: 1
```
[recon-all.log.gz](https://github.com/poldracklab/fmriprep/files/1415648/recon-all.log.gz)

**Comment by oesteban** [comment]
This error has been replaced with the one above my comment for DS000221 / sub-010251, after cleaning up both `work/` and `out/` directories. I will close this one and keep discussion under that issue.
