### ISSUE TITLE
Memory issues compressing SVGs

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#799]
I think this is now unrelated to the size of nifti files:

```
Node: fmriprep_wf.single_subject_29_wf.func_preproc_task_onebacktask_run_01_wf.bold_confounds_wf.acompcor
Working directory: /scratch/03763/oesteban/fmriprep-phase1/work/ds000107/fmriprep_wf/single_subject_29_wf/func_preproc_task_onebacktask_run_01_wf/bold_confounds_wf/acompcor

Node inputs:

components_file = acompcor.tsv
compress_report = auto
generate_report = True
header_prefix = <undefined>
high_pass_cutoff = 128.0
ignore_exception = False
ignore_initial_volumes = 0
mask_files = ['/scratch/03763/oesteban/fmriprep-phase1/work/ds000107/fmriprep_wf/single_subject_29_wf/func_preproc_task_onebacktask_run_01_wf/bold_confounds_wf/combine_rois/logical_or.nii.gz']
mask_index = <undefined>
merge_method = <undefined>
num_components = 6
out_report = report.html
pre_filter = cosine
realigned_file = /scratch/03763/oesteban/fmriprep-phase1/work/ds000107/fmriprep_wf/single_subject_29_wf/func_preproc_task_onebacktask_run_01_wf/bold_reg_wf/merge/vol0000_xform-00000_merged.nii.gz
regress_poly_degree = 1
repetition_time = 3.0
save_pre_filter = True
use_regress_poly = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/common/report.py", line 75, in _run_interface
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/common/report.py", line 202, in _generate_report
    compress=self.inputs.compress_report
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 314, in plot_segs
    cuts, segs=seg_niis, **plot_params)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 333, in plot_xyz
    plot_func(image, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 296, in _plot_anat_with_contours
    svgs_list.append(extract_svg(svg, compress=compress))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 211, in extract_svg
    image_svg = svg_compress(image_svg, compress)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 174, in svg_compress
    stdout=subprocess.PIPE, check=True).stdout
  File "/usr/local/miniconda/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/miniconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/miniconda/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

WDYT @chrisfilo ? Does it make sense?

**Comment by oesteban** [comment]
`/scratch/03763/oesteban/fmriprep-phase1/work/ds000107/fmriprep_wf/single_subject_29_wf/func_preproc_task_onebacktask_run_01_wf/bold_reg_wf/merge/vol0000_xform-00000_merged.nii.gz` is 31MB.

**Comment by chrisfilo** [comment]
I think your diagnosis is accurate, but I don't have an immediate solution.
There are no memory related issues reported on SVGO github
https://github.com/svg/svgo/issues?utf8=%E2%9C%93&q=is%3Aissue%20memory%20.
It might be worth trying to update node.js and SVGO.

Best,
Chris

**Comment by oesteban** [comment]
Seems to be happening only in LS5, on my desktop with half the total memory it works. Closing as it is not an fmriprep issue itself.
