### ISSUE TITLE
Regression from #710 fix: some xforms don't match

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#800]
Highly related to #745 . Also the error should be improved.

```
Node: fmriprep_wf.single_subject_01_wf.func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf.bold_reg_wf.gen_ref
Working directory: /scratch/03763/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_01_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/bold_reg_wf/g
en_ref

Node inputs:

fixed_image = /scratch/03763/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/highres001_BrainExtractionBrain.nii.gz
fov_mask = /scratch/03763/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/highres001_BrainExtractionMask.nii.gz
ignore_exception = False
moving_image = /scratch/03763/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_01_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/nonlinear_sdc_wf/
skullstrip_bold_wf/apply_mask/ants_susceptibility_Warped_masked.nii.gz
xform_code = None

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/utils.py", line 153, in _run_interface
    message='%s (niworkflows v%s)' % (self.__class__.__name__, __version__))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/utils.py", line 205, in _gen_reference
    assert np.allclose(masknii.affine, fixednii.affine)
AssertionError
```

Where fixednii is:
```Python
>>> im1 = nb.load('/scratch/03763/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/highres001_BrainExtractionBrain.nii.gz')
>> im2 = nb.load('/scratch/03763/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/highres001_BrainExtractionMask.nii.gz')
>>> im1.affine
array([[ 1.        ,  0.        , -0.        , -0.        ],
       [ 0.        ,  1.33333325, -0.        , -0.        ],
       [ 0.        ,  0.        ,  1.33333325,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

>>> im2.affine
array([[  1.00000000e+00,   0.00000000e+00,  -0.00000000e+00, -0.00000000e+00],
       [  0.00000000e+00,   1.33333325e+00,  -0.00000000e+00, 4.76837158e-07],
       [  0.00000000e+00,   0.00000000e+00,   1.33333325e+00, 4.76837158e-07],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, 1.00000000e+00]])
>>> np.isclose(im1.affine, im2.affine)
array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]], dtype=bool)
```

**Comment by oesteban** [comment]
Fixed via f1980f570665f883943a9c05746d99a30ff632c7
