### ISSUE TITLE
TypeError: ufunc 'isfinite' not supported for the input types

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#822]
On DS121 (all subjects):

(relates to #820)
```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/images.py", line 321, in _run_interface
    normalized = normalize_xform(reoriented)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/images.py", line 507, in normalize_xform
    if all((np.allclose(qform, xform), np.allclose(sform, xform),
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/core/numeric.py", line 2478, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/core/numeric.py", line 2557, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by chrisfilo** [comment]
@oesteban Just run into with rc10. We should mint a new release with this fixed.
