### ISSUE TITLE
DS006/sub-14 - Clueless error in bold_to_t1w_transform

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#831]
```
Node: fmriprep_wf.single_subject_14_wf.func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf.bold_reg_wf.bold_to_t1w_transform
Working directory: /scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/bold_reg_wf/bold_to_t1w_transform

Node inputs:

args = <undefined>
copy_dtype = True
default_value = 0.0
dimension = <undefined>
environ = {}
float = True
ignore_exception = False
input_image = ['/scratch/users/o <...> bold_hmc_wf/split/vol0204.nii.gz']
input_image_type = <undefined>
interpolation = LanczosWindowedSinc
interpolation_parameters = <undefined>
invert_transform_flags = <undefined>
num_threads = 8
out_postfix = _trans
output_image = <undefined>
print_out_composite_warp_file = <undefined>
reference_image = /scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/bold_reg_wf/ge
n_ref/highres001_BrainExtractionBrain_reference.nii.gz
save_cmd = True
terminal_output = <undefined>
transforms = ['/scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/bold_reg_wf/bbreg
_wf/fsl2itk_fwd/affine.txt', '/scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/no
nlinear_sdc_wf/syn/ants_susceptibility0Warp.nii.gz', '/scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorr
eversedtext_run_06_wf/bold_hmc_wf/fsl2itk/mat2itk.txt']

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/itk.py", line 143, in _run_interface
    for i, (in_file, in_xfm) in enumerate(zip(in_files, xfms_list))]
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/itk.py", line 262, in _applytfms
    runtime = xfm.run().runtime
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/fixes.py", line 24, in _run_interface
    runtime, correct_return_codes)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1671, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1617, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
antsApplyTransforms --default-value 0 --float 1 --input /scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/bold_hmc_wf/split/vol0024.nii.gz --interpolation LanczosWindowedSinc --output /scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/bold_reg_wf/bold_to_t1w_transform/vol0024_xform-00024.nii.gz --reference-image /scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/bold_reg_wf/gen_ref/highres001_BrainExtractionBrain_reference.nii.gz --transform /scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/bold_reg_wf/bbreg_wf/fsl2itk_fwd/affine.txt --transform /scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/nonlinear_sdc_wf/syn/ants_susceptibility0Warp.nii.gz --transform /scratch/users/oesteban/fmriprep-phase1/work/ds000006/fmriprep_wf/single_subject_14_wf/func_preproc_ses_test_task_livingnonlivingdecisionwithplainormirrorreversedtext_run_06_wf/bold_reg_wf/bold_to_t1w_transform/tmp-j1s07dp5/mat2itk_pos-002_xfm-00024.txt
Standard output:

Standard error:

Return code: -9
```

**Comment by oesteban** [comment]
This is likely that applyTransforms was killed. Will reopen if this is not a duplicate of #833

**Comment by effigies** [comment]
Marking issues like this as invalid so we don't count them accidentally when looking for "bugs fixed". If reopening, remove tag.

**Comment by oesteban** [comment]
Sounds very good!
