### ISSUE TITLE
Error in parsing SVG: Unclosed root tag

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#832]
DS017/sub-2
DS114/sub-05

This is on the standard error captured by slurm:
```
Error: Error in parsing SVG: Unclosed root tag
Line: 356
Column: 9201
Char:
    at error (/usr/lib/node_modules/svgo/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/usr/lib/node_modules/svgo/node_modules/sax/lib/sax.js:677:7)
    at end (/usr/lib/node_modules/svgo/node_modules/sax/lib/sax.js:658:47)
    at SAXParser.write (/usr/lib/node_modules/svgo/node_modules/sax/lib/sax.js:975:14)
    at SAXParser.close (/usr/lib/node_modules/svgo/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/usr/lib/node_modules/svgo/lib/svgo/svg2js.js:182:28)
    at module.exports.SVGO._optimizeOnce (/usr/lib/node_modules/svgo/lib/svgo.js:59:5)
    at Promise (/usr/lib/node_modules/svgo/lib/svgo.js:52:14)
    at module.exports.SVGO.optimize (/usr/lib/node_modules/svgo/lib/svgo.js:25:12)
    at processSVGData (/usr/lib/node_modules/svgo/lib/svgo/coa.js:394:17)
```

Nipype does not report any failed node and seems to get stalled, until the job hits the the wall-clock time. `top` reports a `load average: 0.01, 0.02, 0.00`, so the compute node seems idle.

**Comment by oesteban** [comment]
Seems like a memory issue. I would say the process writing the SVG file was a victim of the OOM and left the file unfinished. I'll reopen if this is not a duplicate of #833
