### ISSUE TITLE
AFNI's 3dTshift fails with some oblique datasets

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#843]
DS000053/sub-003/task-training_run-05
DS000053/sub-006/task-training_run-03

```
Node: fmriprep_wf.single_subject_003_wf.func_preproc_task_training_run_05_wf.bold_stc_wf.slice_timing_correction
Working directory: /scratch/users/oesteban/fmriprep-phase2/work/ds000053/fmriprep_wf/single_subject_003_wf/func_preproc_task_training_run_05_wf/bold_stc_wf/slice_timing_correction

Node inputs:

args = <undefined>
environ = {}
ignore = 1
ignore_exception = False
in_file = /oak/stanford/groups/russpold/data/openfmri/ds000053/sub-003/func/sub-003_task-training_run-05_bold.nii.gz
interp = <undefined>
num_threads = 1
out_file = <undefined>
outputtype = NIFTI_GZ
rlt = <undefined>
rltplus = <undefined>
terminal_output = <undefined>
tpattern = @/scratch/users/oesteban/fmriprep-phase2/work/ds000053/fmriprep_wf/single_subject_003_wf/func_preproc_task_training_run_05_wf/bold_stc_wf/create_custom_slice_timing_file/timings.1D
tr = 1.16s
tslice = <undefined>
tzero = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 405, in run
    self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 508, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 640, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/afni/base.py", line 110, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1671, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1617, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
3dTshift -ignore 1 -prefix sub-003_task-training_run-05_bold_tshift.nii.gz -tpattern @/scratch/users/oesteban/fmriprep-phase2/work/ds000053/fmriprep_wf/single_subject_003_wf/func_preproc_task_training_run_05_wf/bold_stc_wf/create_custom_slice_timing_file/timings.1D -TR 1.16s /scratch/users/oesteban/fmriprep-phase2/work/ds000053/fmriprep_wf/single_subject_003_wf/func_preproc_task_training_run_05_wf/bold_stc_wf/slice_timing_correction/sub-003_task-training_run-05_bold.nii.gz
Standard output:

Standard error:
++ 3dTshift: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
[7m*+ WARNING:[0m   If you are performing spatial transformations on an oblique dset,
  such as /scratch/users/oesteban/fmriprep-phase2/work/ds000053/fmriprep_wf/single_subject_003_wf/func_preproc_task_training_run_05_wf/bold_stc_wf/slice_timing_correction/sub-003_task-training_run-05_bold.nii.gz,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running:
     3dWarp -deoblique
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:/scratch/users/oesteban/fmriprep-phase2/work/ds000053/fmriprep_wf/single_subject_003_wf/func_preproc_task_training_run_05_wf/bold_stc_wf/slice_timing_correction/sub-003_task-training_run-05_bold.nii.gz is 23.156860 degrees from plumb.
[7m** FATAL ERROR:[0m Illegal value 2.28 in tpattern file /scratch/users/oesteban/fmriprep-phase2/work/ds000053/fmriprep_wf/single_subject_003_wf/func_preproc_task_training_run_05_wf/bold_stc_wf/create_custom_slice_timing_file/timings.1D
** Program compile date = Jun 12 2017
Return code: 1
```

**Comment by chrisfilo** [comment]
I don't think it has anything to do with obliqueness.

"FATAL ERROR:�[0m Illegal value 2.28 in tpattern file
/scratch/users/oesteban/fmriprep-phase2/work/ds000053/
fmriprep_wf/single_subject_003_wf/func_preproc_task_
training_run_05_wf/bold_stc_wf/create_custom_slice_timing_file/timings.1D"

What's the TR?

Best,
Chris

**Comment by oesteban** [comment]
In both the nifti and the json files it is consistently 1.16s. And it seems correctly set in the nipype interface, isn't it?

**Comment by oesteban** [comment]
Ok, it seems to be the SliceTiming field that is wrong:

```
    "SliceTiming": [
        2.2800000000000002,
        0.0,
        2.3525,
        0.0725,
        2.4225,
        0.14250000000000002,
        2.495,
        0.215,
        2.565,
        0.28500000000000003,
        2.6375,
        0.35750000000000004,
        2.7075000000000005,
        0.4275,
        2.7800000000000002,
        0.5,
        2.85,
        0.5700000000000001,
        2.9225,
        0.6425,
        2.9925,
        0.7125,
        3.065,
        0.785,
        3.1350000000000002,
        0.855,
        3.2075000000000005,
        0.9275000000000001,
        3.2775,
        0.9975000000000002,
        3.35,
        1.07,
        3.42,
        1.1400000000000001,
        3.4925,
        1.2125000000000004,
        3.5625,
        1.2825,
        3.6350000000000002,
        1.355,
        3.705,
        1.425,
        3.7775,
        1.4975,
        3.8475,
        1.5675000000000001,
        3.92,
        1.6400000000000001,
        3.9900000000000007,
        1.71,
        4.0625,
        1.7825,
        4.132500000000001,
        1.8525,
        4.205,
        1.925,
        4.275,
        1.9950000000000003,
        4.3475,
        2.0675,
        4.4175,
        2.1375,
        4.4875,
        2.21
    ],
```

Does it look like it were in ms?

**Comment by chrisfilo** [comment]
Slice timing is time in seconds of acqusition of each slice. It can never
be larger than repetition time. This is a problem with the dataset.

Best,
Chris

**Comment by chrisfilo** [comment]
Please report this with the openfmri team :)

Best,
Chris
