### ISSUE TITLE
[BUG] 3dAutomask empty bold mask

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#844]
DS000140/sub-05
```
Node: fmriprep_wf.single_subject_05_wf.func_preproc_task_heatpainwithregulationandratings_run_08_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.skullstrip_second_pass
Working directory: /scratch/users/oesteban/fmriprep-phase2/work/ds000140/fmriprep_wf/single_subject_05_wf/func_preproc_task_heatpainwithregulationandratings_run_08_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_second_pass

Node inputs:

args = <undefined>
brain_file = <undefined>
clfrac = <undefined>
dilate = 1
environ = {}
erode = <undefined>
ignore_exception = False
in_file = /scratch/users/oesteban/fmriprep-phase2/work/ds000140/fmriprep_wf/single_subject_05_wf/func_preproc_task_heatpainwithregulationandratings_run_08_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/fixhdr_unifize/uni_xform.nii.gz
num_threads = 1
out_file = <undefined>
outputtype = NIFTI_GZ
terminal_output = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 405, in run
    self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 508, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 640, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/afni/base.py", line 110, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1671, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1617, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
3dAutomask -apply_prefix uni_xform_masked.nii.gz -dilate 1 -prefix uni_xform_mask.nii.gz /scratch/users/oesteban/fmriprep-phase2/work/ds000140/fmriprep_wf/single_subject_05_wf/func_preproc_task_heatpainwithregulationandratings_run_08_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_second_pass/uni_xform.nii.gz
Standard output:

Standard error:
++ 3dAutomask: AFNI version=Debian-16.2.07~dfsg.1-5~nd16.04+1 (Jun 12 2017) [64-bit]
++ Authored by: Emperor Zhark
++ Loading dataset /scratch/users/oesteban/fmriprep-phase2/work/ds000140/fmriprep_wf/single_subject_05_wf/func_preproc_task_heatpainwithregulationandratings_run_08_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/skullstrip_second_pass/uni_xform.nii.gz
++ Forming automask
 + Fixed clip level = 695.080078
 + Used gradual clip level = 231.461670 .. 2784.203369
 + Number voxels above clip level = 71
 + Clustering voxels ...
 + Largest cluster has 71 voxels
 + Clustering voxels ...
 + Largest cluster has 0 voxels
 + Clustering voxels ...
 + Largest cluster has 0 voxels
 + Clustering non-brain voxels ...
 + Clustering voxels ...
 + Largest cluster has 268800 voxels
 + Mask now has 0 voxels
++ Dilating automask
 + Clustering voxels ...
 + Largest cluster has 268800 voxels
++ 0 voxels in the mask [out of 268800: 0.00%]
[7m** FATAL ERROR:[0m No voxels? Quitting without saving mask
** Program compile date = Jun 12 2017
Return code: 1
```

**Comment by oesteban** [comment]
Seems to be fixed now. Again, cleaning up the work directory should do.
