### ISSUE TITLE
[BUG] Negative quaternions break CopyXForm

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#845]
DS000168/sub-08
DS000168/sub-27
DS000168/sub-30

/cc @effigies 
```
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/utils.py", line 51, in _run_interface
message='CopyXForm (niworkflows v%s)' % __version__)
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/utils.py", line 168, in _copyxform
qform, qform_code = orig.header.get_qform(coded=True)
File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/nifti1.py", line 917, in get_qform
quat = self.get_qform_quaternion()
File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/nifti1.py", line 892, in get_qform_quaternion
return fillpositive(bcd, self.quaternion_threshold)
File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/quaternions.py", line 100, in fillpositive
raise ValueError('w2 should be positive, but is %e' % w2)
ValueError: w2 should be positive, but is -3.845952e-07
```

**Comment by effigies** [comment]
So this is happening in `get_qform`, not `set_qform`, which means it looks like this is an issue with the source file. Can you verify that?

**Comment by oesteban** [comment]
Confirmed:

```
In [1]: import os

In [2]: import nibabel as nb

In [3]: nb.load(os.path.expandvars('$OAK/data/openfmri/ds000168/sub-08/func/sub-08_task-OP_bold.nii.gz')).get_qform()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-677a08557128> in <module>()
----> 1 nb.load(os.path.expandvars('$OAK/data/openfmri/ds000168/sub-08/func/sub-08_task-OP_bold.nii.gz')).get_qform()

/share/PI/russpold/software/anaconda3-5.0.0/lib/python3.6/site-packages/nibabel/nifti1.py in get_qform(self, coded)
   1819         get_sform
   1820         """
-> 1821         return self._header.get_qform(coded)
   1822 
   1823     def set_qform(self, affine, code=None, strip_shears=True, **kwargs):

/share/PI/russpold/software/anaconda3-5.0.0/lib/python3.6/site-packages/nibabel/nifti1.py in get_qform(self, coded)
    915         if code == 0 and coded:
    916             return None, 0
--> 917         quat = self.get_qform_quaternion()
    918         R = quat2mat(quat)
    919         vox = hdr['pixdim'][1:4].copy()

/share/PI/russpold/software/anaconda3-5.0.0/lib/python3.6/site-packages/nibabel/nifti1.py in get_qform_quaternion(self)
    890         bcd = [hdr['quatern_b'], hdr['quatern_c'], hdr['quatern_d']]
    891         # Adjust threshold to precision of stored values in header
--> 892         return fillpositive(bcd, self.quaternion_threshold)
    893 
    894     def get_qform(self, coded=False):

/share/PI/russpold/software/anaconda3-5.0.0/lib/python3.6/site-packages/nibabel/quaternions.py in fillpositive(xyz, w2_thresh)
     98     if w2 < 0:
     99         if w2 < w2_thresh:
--> 100             raise ValueError('w2 should be positive, but is %e' % w2)
    101         w = 0
    102     else:

ValueError: w2 should be positive, but is -9.083008e-07
```

Is there a way to fix these files? (cc @suyashdb)

**Comment by effigies** [comment]
I'm okay with treating this as an invalid qform and copying in the sform... But it should be done ASAP, e.g. in the ValidateImage interface.

**Comment by oesteban** [comment]
Changing this in the `ValidateImage` did not fix the issue. Will require further investigation.
