### ISSUE TITLE
Indexing error in pepolar_unwarp_wf.prepare_epi_opposite/matching_wf.merge

### ISSUE THREAD

**Issue by MetaD** [poldracklab/fmriprep#858]
Hi,
I'm running fmriprep on a dataset with AP/PA fieldmaps, and got a same error in `pepolar_unwarp_wf.prepare_epi_opposite_wf.merge` and `pepolar_unwarp_wf.prepare_epi_matching_wf.merge` for all of my functional runs. I wonder if you know what caused this error or how to fix it...

Here's the error information:
```
Node Name: fmriprep_wf.single_subject_133_wf.func_preproc_task_face_run_01_wf.pepolar_unwarp_wf.prepare_epi_opposite_wf.merge
File: /u/project/CCN/cparkins/data/hierarchy/fmriprep/output_shortcmd_133/fmriprep/sub-133/log/20171129-020515_bf1f0454-c454-4555-9aea-a47d85aaf584/crash-20171129-021319-mengdu-merge-69a145ee-c129-4150-a591-fdc5c8bf3d59.txt
Working Directory: /u/scratch/m/mengdu/short_cmd_133/fmriprep_wf/single_subject_133_wf/func_preproc_task_face_run_01_wf/pepolar_unwarp_wf/prepare_epi_opposite_wf/merge
Inputs: 
  args: <undefined>
  auto_detect_sensitivity: True
  average_metric: <undefined>
  environ: {'SUBJECTS_DIR': '/u/project/CCN/apps/freesurfer/6.0.0/subjects', 'OMP_NUM_THREADS': '1'}
  fixed_timepoint: True
  ignore_exception: False
  in_files: ['/u/scratch/scratch2/m/mengdu/short_cmd_133/fmriprep_wf/single_subject_133_wf/func_preproc_task_face_run_01_wf/pepolar_unwarp_wf/prepare_epi_opposite_wf/split/mapflow/_split0/vol0000.nii.gz']
  in_intensity_scales: <undefined>
  initial_timepoint: 1
  initial_transforms: <undefined>
  intensity_scaling: True
  no_iteration: True
  num_threads: 1
  out_file: template.nii.gz
  outlier_sensitivity: <undefined>
  scaled_intensity_outputs: <undefined>
  subjects_dir: /u/project/CCN/apps/freesurfer/6.0.0/subjects
  subsample_threshold: 200
  terminal_output: <undefined>
  transform_outputs: <undefined>

Traceback (most recent call last):
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/freesurfer/base.py", line 268, in run
    return super(FSCommandOpenMP, self).run(**inputs)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/freesurfer/base.py", line 144, in run
    return super(FSCommand, self).run(**inputs)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1089, in run
    outputs = self.aggregate_outputs(runtime)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1154, in aggregate_outputs
    predicted_outputs = self._list_outputs()
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/fmriprep/interfaces/freesurfer.py", line 73, in _list_outputs
    transform_file = outputs['transform_outputs'][0]
TypeError: '_Undefined' object does not support indexing
```

I've also tried to use `--ignore fieldmaps ` and `--no-freesurfer `, but the same error is still there.  The version of fmriprep I'm using is 1.0.0-rc11, and my dataset has passed the BIDS validator.

It seems to me that it's due to indexing `outputs['transform_outputs']`, which is undefined because the node input `transform_outputs` is undefined. When you [instantiate the StructuralReference class here](https://github.com/poldracklab/fmriprep/blob/797a0202b4c57cd858dfa7e1419be38c0a7c328e/fmriprep/workflows/fieldmap/pepolar.py#L230), is there supposed to be a `transform_outputs` passed to the constructor?

Please let me know if you know more information about the error or a way fix it. Thanks a lot!!!

**Comment by oesteban** [comment]
Could you send us some data so that we reproduce this?

**Comment by MetaD** [comment]
Yes, I've uploaded one subject's data [here](https://drive.google.com/open?id=1fw1O47ZBOSFiyPaYBH7Gya086IjI01A5).

Thanks for your help!

**Comment by effigies** [comment]
What version of fmriprep are you using, and are you running it locally, or through Docker/Singularity?

My initial thought is that your niworkflows doesn't include a recent enough version of nipype, which suggests you're running locally with an older version of niworkflows. I suspect that `pip install --upgrade niworkflows` will fix your issue.

**Comment by MetaD** [comment]
I've been using fmriprep v1.0.0-rc11 and running it locally (rather than docker/singularity). My nipype version is 0.13.1, and niworkflows version was 0.1.10. I just updated niworkflows to 0.1.11 so I can try again (is that where you think the issue is?).

**Comment by effigies** [comment]
Hmm. That should be new enough. Let me have a look.

**Comment by MetaD** [comment]
Okay thank you!

**Comment by effigies** [comment]
Think I figured out the problem. Are you able to install from a branch and test?

**Comment by MetaD** [comment]
Cool I'll try that. Thank you!

**Comment by MetaD** [comment]
Hey, I'm running it and now getting a new error at the same places, which seems probably still related to the last issue (?):

```
Node: fmriprep_wf.single_subject_133_wf.func_preproc_task_face_run_01_wf.pepolar_unwarp_wf.prepare_epi_matching_wf.merge
Working directory: /u/scratch/m/mengdu/short_cmd_133_fix/fmriprep_wf/single_subject_133_wf/func_preproc_task_face_run_01_wf/pepolar_unwarp_wf/prepare_epi_matching_wf/merge

Node inputs:

args = <undefined>
auto_detect_sensitivity = True
average_metric = <undefined>
environ = {'SUBJECTS_DIR': '/u/project/CCN/apps/freesurfer/6.0.0/subjects', 'OMP_NUM_THREADS': '1'}
fixed_timepoint = True
ignore_exception = False
in_files = ['/u/scratch/scratch2/m/mengdu/short_cmd_133_fix/fmriprep_wf/single_subject_133_wf/func_preproc_task_face_run_01_wf/pepolar_unwarp_wf/prepare_epi_matching_wf/split/mapflow/_split0/vol0000.nii.gz']
in_intensity_scales = <undefined>
initial_timepoint = 1
initial_transforms = <undefined>
intensity_scaling = True
no_iteration = True
num_threads = 1
out_file = template.nii.gz
outlier_sensitivity = <undefined>
scaled_intensity_outputs = <undefined>
subjects_dir = /u/project/CCN/apps/freesurfer/6.0.0/subjects
subsample_threshold = 200
terminal_output = <undefined>
transform_outputs = <undefined>

Traceback (most recent call last):
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/freesurfer/base.py", line 268, in run
    return super(FSCommandOpenMP, self).run(**inputs)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/freesurfer/base.py", line 144, in run
    return super(FSCommand, self).run(**inputs)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1090, in run
    outputs = self.aggregate_outputs(runtime)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1177, in aggregate_outputs
    raise error
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1171, in aggregate_outputs
    setattr(outputs, key, val)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/traits_extension.py", line 92, in validate
    self.info_text, value))
traits.trait_errors.TraitError: The trait 'out_file' of a RobustTemplateOutputSpec instance is an existing file name, but the path  '/u/scratch/scratch2/m/mengdu/short_cmd_133_fix/fmriprep_wf/single_subject_133_wf/func_preproc_task_face_run_01_wf/pepolar_unwarp_wf/prepare_epi_matching_wf/merge/template.nii.gz' does not exist.
```

**Comment by effigies** [comment]
Yeah, sorry, that was the error I referred to in https://github.com/poldracklab/fmriprep/pull/859#issuecomment-348062753. Grab that branch again and it should be fixed.

**Comment by MetaD** [comment]
Yes this is fixed! Thank you.

**Comment by oesteban** [comment]
Hi @MetaD, could I ask you to tell your experience here -> https://neurostars.org/t/fmriprep-success-stories/1111?u=oesteban ?

**Comment by MetaD** [comment]
Sure :)
