### ISSUE TITLE
FMRIPREP breaking x-forms

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#873]
This happened to DS000116/sub-17:

```
Node: fmriprep_wf.single_subject_17_wf.func_preproc_task_visualoddballwithbuttonresponsetotargetstimuli_run_03_wf.bold_reg_wf.bbreg_wf.mri_coreg
Working directory: /scratch/users/oesteban/fmriprep-phase2-2/work/ds000116/fmriprep_wf/single_subject_17_wf/func_preproc_task_visualoddballwithbuttonresponsetotargetstimuli_run_03_wf/bold_reg_wf/bbreg_wf/mri_coreg

Node inputs:

args = <undefined>
brute_force_limit = <undefined>
brute_force_samples = <undefined>
compress_report = auto
conform_reference = <undefined>
dof = 9
environ = {'SUBJECTS_DIR': '/opt/freesurfer/subjects'}
ftol = 0.0001
generate_report = True
ignore_exception = False
initial_rotation = <undefined>
initial_scale = <undefined>
initial_shear = <undefined>
initial_translation = <undefined>
linmintol = 0.01
max_iters = <undefined>
no_brute_force = <undefined>
no_coord_dithering = <undefined>
no_cras0 = <undefined>
no_intensity_dithering = <undefined>
no_smooth = <undefined>
num_threads = 8
out_lta_file = True
out_params_file = <undefined>
out_reg_file = <undefined>
out_report = report.svg
ref_fwhm = <undefined>
reference_file = <undefined>
reference_mask = <undefined>
saturation_threshold = <undefined>
sep = [4]
source_file = /scratch/users/oesteban/fmriprep-phase2-2/work/ds000116/fmriprep_wf/single_subject_17_wf/func_preproc_task_visualoddballwithbuttonresponsetotargetstimuli_run_03_wf/nonlinear_sdc_wf/skullstrip_bold_wf/apply_mask/ants_susceptibility_Warped_masked.nii.gz
source_mask = <undefined>
source_oob = <undefined>
subject_id = sub-17
subjects_dir = /oak/stanford/groups/russpold/data/openfmri/derivatives/ds000116/freesurfer
terminal_output = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 62, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 404, in run
    self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 508, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 639, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/freesurfer/base.py", line 144, in run
    return super(FSCommand, self).run(**inputs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 485, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/report_base.py", line 65, in _run_interface
    self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/registration.py", line 244, in _post_run_hook
    res = mri_vol2vol.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/freesurfer/base.py", line 144, in run
    return super(FSCommand, self).run(**inputs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 485, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 972, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 911, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
mri_vol2vol --lta /scratch/users/oesteban/fmriprep-phase2-2/work/ds000116/fmriprep_wf/single_subject_17_wf/func_preproc_task_visualoddballwithbuttonresponsetotargetstimuli_run_03_wf/bold_reg_wf/bbreg_wf/mri_coreg/registration.lta --mov /scratch/users/oesteban/fmriprep-phase2-2/work/ds000116/fmriprep_wf/single_subject_17_wf/func_preproc_task_visualoddballwithbuttonresponsetotargetstimuli_run_03_wf/bold_reg_wf/bbreg_wf/mri_coreg/ants_susceptibility_Warped_masked.nii.gz --targ /oak/stanford/groups/russpold/data/openfmri/derivatives/ds000116/freesurfer/sub-17/mri/brainmask.mgz --o /scratch/users/oesteban/fmriprep-phase2-2/work/ds000116/fmriprep_wf/single_subject_17_wf/func_preproc_task_visualoddballwithbuttonresponsetotargetstimuli_run_03_wf/bold_reg_wf/bbreg_wf/mri_coreg/ants_susceptibility_Warped_masked_warped.nii.gz
Standard output:
ERROR LTA /scratch/users/oesteban/fmriprep-phase2-2/work/ds000116/fmriprep_wf/single_subject_17_wf/func_preproc_task_visualoddballwithbuttonresponsetotargetstimuli_run_03_wf/bold_reg_wf/bbreg_wf/mri_coreg/registration.lta has no valid src geometry!
Standard error:

Return code: 1
```
The LTA file is:
```
# transform file /scratch/users/oesteban/fmriprep-phase2-2/work/ds000116/fmriprep_wf/single_subject_17_wf/func_preproc_task_visualoddballwithbuttonresponsetotargetstimuli_run_03_wf/bold_reg_wf/bbreg_wf/mri_coreg/registration.lta
# created by oesteban on Tue Dec  5 08:53:15 2017

type      = 0 # LINEAR_VOX_TO_VOX
nxforms   = 1
mean      = 0.0000 0.0000 0.0000
sigma     = 10000.0000
1 4 4
7.021905422210693e+00 2.796710491180420e+00 -3.353350400924683e+00 -8.559801483154297e+01 
-2.367060184478760e+00 -9.808060526847839e-02 -8.957187652587891e+00 4.367626037597656e+02 
-2.557179689407349e+00 7.137063980102539e+00 1.062434792518616e+00 -3.696695709228516e+01 
0.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00 1.000000000000000e+00 
src volume info
valid = 0  # volume info invalid
filename = /scratch/users/oesteban/fmriprep-phase2-2/work/ds000116/fmriprep_wf/single_subject_17_wf/func_preproc_task_visualoddballwithbuttonresponsetotargetstimuli_run_03_wf/bold_reg_wf/bbreg_wf/mri_coreg/ants_susceptibility_Warped_masked.nii.gz
volume = 64 64 32
voxelsize = 3.000000000000000e+00 3.000000000000000e+00 4.000000000000000e+00
xras   = -1.000000000000000e+00 0.000000000000000e+00 0.000000000000000e+00
yras   = 0.000000000000000e+00 1.000000000000000e+00 0.000000000000000e+00
zras   = 0.000000000000000e+00 0.000000000000000e+00 1.000000000000000e+00
cras   = 9.600000000000000e+01 9.600000000000000e+01 6.400000000000000e+01
dst volume info
valid = 1  # volume info valid
filename = /oak/stanford/groups/russpold/data/openfmri/derivatives/ds000116/freesurfer/sub-17/mri/brainmask.mgz
volume = 256 256 256
voxelsize = 1.000000000000000e+00 1.000000000000000e+00 1.000000000000000e+00
xras   = -1.000000000000000e+00 6.548361852765083e-11 0.000000000000000e+00
yras   = 3.725290298461914e-09 0.000000000000000e+00 -1.000000000000000e+00
zras   = -7.275957614183426e-12 1.000000000000000e+00 0.000000000000000e+00
cras   = 8.674308776855469e+00 -1.424864196777344e+01 2.766365051269531e+00
subject sub-17
```

The src file has wrong x-form headers:
```
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [ 3 64 64 32  1  1  1  1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [ 1.  3.  3.  4.  0.  0.  0.  0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'FSL5.0'
aux_file        : b''
qform_code      : unknown
sform_code      : unknown
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : 0.0
qoffset_y       : 0.0
qoffset_z       : 0.0
srow_x          : [ 0.  0.  0.  0.]
srow_y          : [ 0.  0.  0.  0.]
srow_z          : [ 0.  0.  0.  0.]
intent_name     : b''
magic           : b'n+1'
```

The original BOLD run has these headers:
```
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  4  64  64  32 170   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [-1.  3.  3.  4.  2.  0.  0.  0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 31
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'Philips Medical Systems Achieva 2.6.3 '
aux_file        : b''
qform_code      : scanner
sform_code      : unknown
quatern_b       : 0.0003245746192988008
quatern_c       : -0.999137282371521
quatern_d       : -0.038106173276901245
qoffset_x       : 101.53397369384766
qoffset_y       : -109.06437683105469
qoffset_z       : -52.281314849853516
srow_x          : [ 1.  0.  0.  0.]
srow_y          : [ 0.  1.  0.  0.]
srow_z          : [ 0.  0.  1.  0.]
intent_name     : b''
magic           : b'n+1'
```

cc/ @effigies

**Comment by oesteban** [comment]
After the `validate` node, headers are:

```
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  4  64  64  32 170   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [-1.  3.  3.  4.  2.  0.  0.  0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 31
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'Philips Medical Systems Achieva 2.6.3 '
aux_file        : b''
qform_code      : unknown
sform_code      : unknown
quatern_b       : 0.0003245746192988008
quatern_c       : -0.999137282371521
quatern_d       : -0.038106173276901245
qoffset_x       : 101.53397369384766
qoffset_y       : -109.06437683105469
qoffset_z       : -52.281314849853516
srow_x          : [ 1.  0.  0.  0.]
srow_y          : [ 0.  1.  0.  0.]
srow_z          : [ 0.  0.  1.  0.]
intent_name     : b''
magic           : b'n+1'
```

**Comment by effigies** [comment]
Okay. So it either needs to happen while creating the reference (`bold_reference_wf/enhance_and_skullstrip_wf/apply_mask/*.nii.gz`) or when applying fieldmaps. Is this being done with SyN or other fieldmaps?

**Comment by oesteban** [comment]
I guess we didn't take into account this situation (#847). The image after the `validate` node has wrong headers.

- valid qform matrix + valid qform code but invalid sform (row 2). Let me reproduce the table you made here, with an extra column for "actions":

| valid quaternions | `qform_code > 0` | `sform_code > 0` | actions | warnings |
|-|-|-|-|-|
| True | True | True | None | None |
| True | True | False | sform, scode <- qform, qcode |  None |
| True | False | True | None | None |
| True | False | False | scode <- 2; qcode <- 2 | invalid codes |
| False | True | True | qform, qcode <- sform, scode | invalid qform |
| False | True | False | qform, sform <- best affine; qcode, scode <- 2 | invalid codes + invalid qforms |
| False | False | True |  qform, qcode <- sform, scode | invalid qform |
| False | False | False | qform, sform <- best affine; qcode, scode <- 2 | invalid codes |

**Comment by oesteban** [comment]
BTW, we are in row 2, but doing `qcode <- scode`

**Comment by effigies** [comment]
Oh, I see. I didn't catch that difference in the validated image.

**Comment by oesteban** [comment]
Do you think those actions are okay?

**Comment by effigies** [comment]
We still want to sync qform and sform. And I think we settled on `xcode = 1` to avoid indicating we have aligned to anatomical images.

I would separate the logic of sync actions and warnings, as different conditions can lead to the same action with different warnings and vice versa. Here are actions:

| valid quaternions | `qform_code > 0` | `sform_code > 0` | `qform == sform` | actions |
|-|-|-|-|-|
| True | True | True | True | None |
| True | True | False | * | sform, scode <- qform, qcode |
| * | * | True | False | qform, qcode <- sform, scode |
| * | False | True | * | qform, qcode <- sform, scode |
| * | False | False | * | sform, qform <- best affine; scode, qcode <- 1 |
| False | * | False | * | sform, qform <- best affine; scode, qcode <- 1 |

(I think all 16 cases are covered here.) Each sync should produce a message, but shouldn't necessarily be a "warning", since the incoming data isn't necessarily bad.

The following are warning-generating conditions.

| valid quaternions | `qform_code > 0` | `sform_code > 0` | warnings |
|-|-|-|-|
| * | False | False | invalid codes |
| False | * | False | invalid codes |
| False | True | * | invalid qform |

**Comment by effigies** [comment]
I think the first table is using `*` such that, if a condition matches two rows, both rows produce the same action.

The second table is not meant to be mutually exclusive, as both warnings can appear.
