### ISSUE TITLE
tCompCor - numpy.linalg.linalg.LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#940]
#776 (aka the revenant) is back. Now on tCompCor. I'll apply the same solution.

**Comment by DVSneuro** [comment]
Hi -- I think I'm getting the same error here:

    	 [Node] Error on "fmriprep_wf.single_subject_103_wf.func_preproc_task_ultimatum_run_01_wf.bold_confounds_wf.tcompcor" (/root/src/fmriprep/work/fmriprep_wf/single_subject_103_wf/func_preproc_task_ultimatum_run_01_wf/bold_confounds_wf/tcompcor)
    Traceback (most recent call last):
      File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
        load_entry_point('fmriprep==1.0.15', 'console_scripts', 'fmriprep')()
      File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 314, in main
        fmriprep_wf.run(**plugin_settings)
      File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 595, in run
        runner.run(execgraph, updatehash=updatehash, config=self.config)
      File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 168, in run
        self._clean_queue(jobid, graph, result=result))
      File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
        raise RuntimeError("".join(result['traceback']))
    RuntimeError: Traceback (most recent call last):
      File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
        result['result'] = node.run(updatehash=updatehash)
      File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 480, in run
        result = self._run_interface(execute=True)
      File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
        return self._run_command(execute)
      File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 644, in _run_command
        result = self._interface.run(cwd=outdir)
      File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 520, in run
        runtime = self._run_interface(runtime)
      File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/patches.py", line 51, in _run_interface
        runtime = super(RobustTCompCor, self)._run_interface(runtime)
      File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 539, in _run_interface
        self.inputs.pre_filter, degree, self.inputs.high_pass_cutoff, TR)
      File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 1189, in compute_noise_components
        u, _, _ = linalg.svd(M, full_matrices=False)
      File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/linalg/decomp_svd.py", line 119, in svd
        raise LinAlgError("SVD did not converge")
    numpy.linalg.linalg.LinAlgError: SVD did not converge

Here's my command for FMRIPREP:

      docker run -it --rm \
      -v /data/projects/srndna/bids:/data:ro \
      -v /data/projects/srndna/fmriprep:/out \
      -v /data/projects/srndna/fs_license.txt:/opt/freesurfer/fs_license.txt \
      poldracklab/fmriprep:latest \
      /data /out \
      participant --participant_label $sub --use-aroma --fs-no-reconall --fs-license-file /opt/freesurfer/fs_license.txt

Would be happy to share the data if it's helpful! Thanks!

**Comment by effigies** [comment]
Can you try running with the latest fMRIPrep, version 1.1.4? If you're still seeing the error, please open a new issue.

**Comment by DVSneuro** [comment]
Thanks! That fixed it. Sorry, I was confused about the 'latest' tag (e.g., fmriprep:latest) and will use specific versions from now on (e.g., fmriprep:1.1.4). Thanks again!

**Comment by effigies** [comment]
That's one of the issues with using Docker. If you've already pulled `:latest`, then it won't check for a newer one unless you use `docker pull poldracklab/fmriprep:latest`. This is another reason we recommend using the `fmriprep-docker` wrapper, and keeping it up to date with `pip install --upgrade fmriprep-docker`.
