### ISSUE TITLE
--write-graph fails for workflows with fieldmaps

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#970]
This problem started appeared with the [CI tests](https://circleci.com/gh/oesteban/fmriprep/1098?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) of #967. Not sure if it is a regression from this PR or a problem in Nipype's write_graph. By opening this PR I hope you agree with merging #967 and keep track of this separately (and also add the `--write-graph` back to the below command).

```
fmriprep-docker -i poldracklab/fmriprep:latest \
    --config $PWD/nipype.cfg -w /tmp/ds054/work \
    /tmp/data/ds054 /tmp/ds054/derivatives participant \
    --fs-no-reconall --debug --write-graph --force-syn \
    --mem_mb 4096 --nthreads 2 -vv
Warning: <8GB of RAM is available within your Docker environment.
Some parts of fMRIPrep may fail to complete.
RUNNING: docker run --rm -it -v /tmp/fslicense/license.txt:/opt/freesurfer/license.txt:ro -v /tmp/data/ds054:/data:ro -v /tmp/ds054/derivatives:/out -v /tmp/ds054/work:/scratch -v /tmp/ds054/nipype.cfg:/root/.nipype/nipype.cfg:ro poldracklab/fmriprep:latest /data /out participant --fs-no-reconall --debug --write-graph --force-syn --mem_mb 4096 --nthreads 2 -vv -w /scratch
^@^@180210-16:20:12,856 workflow IMPORTANT:
	 
    Running fMRIPREP version 1.0.6:
      * BIDS dataset path: /data.
      * Participant list: ['100185'].
      * Run identifier: 20180210-162012_fa6b2e66-3209-4b72-8b84-3b046036218e.
    
180210-16:20:13,35 workflow IMPORTANT:
	 Creating bold processing workflow for "/data/sub-100185/func/sub-100185_task-machinegame_run-01_bold.nii.gz" (0.00 GB / 5 TRs). Memory resampled/largemem=0.01/0.01 GB.
180210-16:20:13,540 workflow IMPORTANT:
	 Fieldmap estimation: type "phasediff" found
/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/fsl/preprocess.py:1893: UserWarning: This has not been fully tested. Please report any failures.
  warn('This has not been fully tested. Please report any failures.')
180210-16:20:17,789 workflow IMPORTANT:
	 Creating bold processing workflow for "/data/sub-100185/func/sub-100185_task-machinegame_run-02_bold.nii.gz" (0.00 GB / 5 TRs). Memory resampled/largemem=0.01/0.01 GB.
180210-16:20:18,293 workflow IMPORTANT:
	 Fieldmap estimation: type "phasediff" found
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.6', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 259, in main
    fmriprep_wf.write_graph(graph2use="colored", format='svg', simple_form=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 438, in write_graph
    outfname = format_dot(dotfilename, format=format)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/utils.py", line 1313, in format_dot
    formatted_dot, _ = _run_dot(dotfilename, format_ext=format)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/utils.py", line 1330, in _run_dot
    resource_monitor=False).run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 516, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 1023, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 960, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
dot -Tsvg -o"/scratch/fmriprep_wf/graph.svg" "/scratch/fmriprep_wf/graph.dot"
Standard output:

Standard error:
Error: trouble in init_rank
	%0 1
	%0 14
	%0 14
	%0 19
	%0 18
	%0 24
	%0 18
	%0 11
	%0 11
	%0 17
	%0 17
	%0 14
	%0 14
	%0 19
	%0 18
	%0 24
	%0 5
	%0 25
	%0 3
	%0 4
	%0 4
	%0 1
	%0 4
	%0 1
	%0 5
	%0 1
	%0 20
	%0 1
	%0 42
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_outputnode 3
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_apply_mask 3
	%0 1
	%0 3
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_combine_masks 1
	%0 1
	%0 1
	%0 3
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_fixhdr_skullstrip2 1
	%0 1
	%0 1
	%0 1
	%0 3
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_skullstrip_second_pass 1
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_fixhdr_unifize 3
	%0 1
	%0 3
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_unifize 1
	%0 1
	%0 3
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_skullstrip_first_mask 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_skullstrip_first_dilate 1
	%0 1
	%0 3
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_skullstrip_first_pass 1
	%0 1
	%0 3
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_n4_correct 1
	%0 1
	%0 3
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_n4_mask 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_inputnode 3
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_outputnode 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_gen_ref 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_validate 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_reference_wf_inputnode 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_outputnode 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_merge 2
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_bold_to_mni_transform 2
	%0 1
	%0 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_gen_ref 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_merge_xforms 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_mni_trans_wf_inputnode 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_outputnode 2
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_fsl2itk_inv 1
	%0 1
	%0 2
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_invt_bbr 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_fsl2itk_fwd 1
	%0 2
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_select_transform 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_select_report 2
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_compare_transforms 1
	%0 2
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_fsl_to_lta 1
	%0 2
	%0 1
	%0 1
	%0 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_transforms 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_reports 1
	%0 1
	%0 1
	%0 2
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_flt_bbr 1
	%0 1
	%0 1
	%0 2
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_flt_bbr_init 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_wm_mask 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_fsl_bbr_wf_inputnode 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_outputnode 4
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_merge 3
	%0 3
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_bold_to_t1w_transform 1
	%0 3
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_mask_t1w_tfm 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_merge_xforms 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_gen_ref 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_reg_wf_inputnode 3
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_outputnode 2
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_apply_mask 2
	%0 1
	%0 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_combine_masks 1
	%0 1
	%0 1
	%0 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_fixhdr_skullstrip2 1
	%0 1
	%0 1
	%0 1
	%0 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_skullstrip_second_pass 1
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_fixhdr_unifize 2
	%0 1
	%0 2
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_unifize 1
	%0 1
	%0 2
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_skullstrip_first_mask 1
	%0 1
	%0 2
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_skullstrip_first_dilate 1
	%0 1
	%0 2
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_skullstrip_first_pass 1
	%0 1
	%0 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_n4_correct 1
	%0 1
	%0 2
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_n4_mask 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_enhance_and_skullstrip_bold_wf_inputnode 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_outputnode 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_gen_ref 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_validate 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_reference_wf_inputnode 2
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_outputnode 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_merge 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_bold_transform 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_merge_xforms 1
	fmriprep_wf_single_subject_100185_wf_func_preproc_task_machinegame_run_01_wf_bold_bold_trans_wf_inputnode 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 3
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 1
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 1
	%0 2
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 1
	%0 2
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 1
	%0 2
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 2
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 2
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 2
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 2
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 2
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 2
	%0 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 2
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 3
	%0 1
	%0 1
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_reports_wf_ds_t1_conform_report 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_reports_wf_ds_t1_seg_mask_report 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_reports_wf_ds_t1_2_mni_report 3
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_reports_wf_inputnode 3
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_t1_preproc 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_t1_mask 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_t1_seg 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_t1_tpms 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_t1_mni_warp 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_t1_mni_inv_warp 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_t1_mni 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_mni_mask 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_mni_seg 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_mni_tpms 3
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_t1_name 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_ds_t1_template_transforms 3
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_derivatives_wf_inputnode 3
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_skullstrip_ants_wf_outputnode 3
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_skullstrip_ants_wf_t1_skull_strip 3
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_skullstrip_ants_wf_inputnode 3
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_template_wf_outputnode 3
	%0 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_template_wf_t1_conform 3
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_template_wf_t1_template_dimensions 3
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_anat_template_wf_inputnode 3
	%0 1
	%0 1
	%0 2
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_seg_rpt 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_outputnode 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_seg2msks 1
	%0 1
	%0 2
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_mni_seg 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_mni_tpms 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_mni_mask 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_t1_seg 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_t1_2_mni 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_buffernode 1
	%0 1
	%0 1
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 1
	%0 1
	%0 2
	%0 2
	%0 2
	%0 2
	fmriprep_wf_single_subject_100185_wf_anat_preproc_wf_inputnode 2
	fmriprep_wf_single_subject_100185_wf_ds_summary_report 2
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_summary 1
	%0 1
	%0 1
	%0 1
	fmriprep_wf_single_subject_100185_wf_bids_info 1
	fmriprep_wf_single_subject_100185_wf_ds_about_report 1
	fmriprep_wf_single_subject_100185_wf_inputnode 1
	fmriprep_wf_single_subject_100185_wf_about 1
	fmriprep_wf_single_subject_100185_wf_bidssrc 1
Return code: 1
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues
Exited with code 1
```

**Comment by effigies** [comment]
... Was this still an issue?

**Comment by oesteban** [comment]
I don't think this or #1028 are still happening. However, the output of ``--write-graph`` with many subjects is pretty ugly. We should think a bit more about that feature.

It would also be nice to identify irregularities across workflows (e.g. just one-of-many was run with ``--use-sdc`` with no fieldmaps in the dataset), which is related to questions like what graph should be plotted, what text should the boilerplate include, etc.

**Comment by carolinarsm** [comment]
Not a critical issue, just letting you know it could still be around. I ran into this today when adding the `--write-graph` flag.

- Version/Image: `fmriprep-20.2.1.simg`

- Command (from stdout, formatted for easier reading):

```
P50006
Running task 6
Commandline: singularity run --cleanenv \
-B /scratch/users/ramirezc/p50/data/bids-input:/data \
-B /scratch/users/ramirezc/p50/data/derivatives/fmriprep-20.2.1:/derivatives \
-B /home/users/ramirezc/.cache/templateflow:/templateflow \
-B /scratch/users/ramirezc/tmp_fmriprep_workflows/tmp_p50:/tmp \
/scratch/users/ramirezc/poldrack_containers/fmriprep-20.2.1.simg \
/scratch/users/ramirezc/p50/data/bids-input /scratch/users/ramirezc/p50/data/derivatives/fmriprep-20.2.1 \
participant --participant-label P50006 \
-w /tmp/tmp_workflow \
-vvv \
--nthreads 16 \
--mem_mb 30000 \
--output-spaces MNI152NLin2009cAsym:res-2 T1w fsnative fsaverage \
--use-aroma \
--cifti-output \
--skip_bids_validation \
--resource-monitor \
--medial-surface-nan \
--write-graph --notrack

210721-15:00:57,579 nipype.workflow IMPORTANT:
         
    Running fMRIPREP version 20.2.1:
      * BIDS dataset path: /scratch/users/ramirezc/p50/data/bids-input.
      * Participant list: ['P50006'].
      * Run identifier: 20210721-145940_ac16b105-ac00-454e-8c90-ca8a02ff367b.
      * Output spaces: MNI152NLin2009cAsym:res-2 T1w fsnative fsaverage:den-164k.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /scratch/users/ramirezc/p50/data/derivatives/fmriprep-20.2.1/freesurfer
 ```

- Error log:

```
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the 'config_filename', 'ignore', 'force_index', and 'index_metadata' arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
WARNING: Version 20.2.1 of fMRIPrep (current) has been FLAGGED
(reason: Functional outputs in standard space can be wrong depending on the original data's orientation headers - see https://github.com/nipreps/fmriprep/issues/2307).
That means some severe flaw was found in it and we strongly
discourage its usage.
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 56, in main
    fmriprep_wf.write_graph(graph2use="colored", format="svg", simple_form=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 459, in write_graph
    outfname = format_dot(dotfilename, format=format)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1405, in format_dot
    formatted_dot, _ = _run_dot(dotfilename, format_ext=format)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1421, in _run_dot
    res = CommandLine(cmd, terminal_output="allatonce", resource_monitor=False).run()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 814, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 745, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
dot -Tsvg -o"/tmp/tmp_workflow/fmriprep_wf/graph.svg" "/tmp/tmp_workflow/fmriprep_wf/graph.dot"
Standard output:

Standard error:
Error: /tmp/tmp_workflow/fmriprep_wf/graph.dot: syntax error in line 33426 near 'r_pe0_run_00_wf_sdc_estimate_wf_pepolar_unwarp_wf_prepare_epi_wf_ref_op_wf_outputnode'
Return code: 1```
