### ISSUE TITLE
Summary workflow crashes

### ISSUE THREAD

**Issue by mick-d** [poldracklab/fmriprep#991]
Hi,

With latest version of `fmriprep`, the `summary` workflow crashes with the error. I could not find why it was crashing. Any help would be greatly appreciated.

**Original command**: 
```
RUNNING: docker run --rm -it -v /my/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /my/raw/data:/data:ro -v /my/preproc/data:/out -v /my/tmp/data:/scratch poldracklab/fmriprep:1.0.7 /data /out participant --participant_label sub-mysubj001 --output-space T1w template --use-aroma --bold2t1w-dof 6 --fs-no-reconall --resource-monitor --write-graph --nthreads 10 -w /scratch
180217-16:40:28,921 workflow IMPORTANT:
	 
    Running fMRIPREP version 1.0.7:
      * BIDS dataset path: /data.
      * Participant list: ['mysubj001'].
      * Run identifier: 20180217-164028_5ea50acc-9dfe-4497-bdb6-9cd5b7d2c5e8.

```
**Error**
```
cat log/20180217-164028_5ea50acc-9dfe-4497-bdb6-9cd5b7d2c5e8/crash-20180217-164142-root-summary-de6f942d-7bbe-4cd1-82a0-b2a93681443d.txt 
Node: fmriprep_wf.single_subject_mysubj001_wf.summary
Working directory: /scratch/fmriprep_wf/single_subject_mysubj001_wf/summary

Node inputs:

bold = ['/data/sub-mysubj001/sec-a/func/sub-mysubj001_sec-a_task-rest_bold.nii.gz']
ignore_exception = False
output_spaces = ['T1w', 'template']
subject_id = sub-mysubj001
subjects_dir = <undefined>
t1w = ['/data/sub-mysubj001/sec-a/anat/sub-mysubj001_sec-a_T1w.nii.gz']
t2w = <undefined>
template = MNI152NLin2009cAsym

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 339, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 487, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 571, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 516, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 92, in _run_interface
    return super(SubjectSummary, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 61, in _run_interface
    segment = self._generate_segment()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 117, in _generate_segment
    for series in bold_series)
  File "/usr/local/miniconda/lib/python3.6/collections/__init__.py", line 534, in __init__
    self.update(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.6/collections/__init__.py", line 621, in update
    _count_elements(self, iterable)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/reports.py", line 117, in <genexpr>
    for series in bold_series)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by effigies** [comment]
From a quick glance, it looks like you don't have BOLD files. Can you run `tree /my/raw/data`?

If you don't have BOLD data, you can pass `--anat-only`.

**Comment by mick-d** [comment]
Thanks a lot for looking into it. I have BOLD resting state data. Is that a problem if I have other directories (not shown) inside `/my/raw/data`?

```
├── anat
│   ├── sub-mysubj001_sec-a_T1w.json
│   └── sub-mysubj001_sec-a_T1w.nii.gz
├── dwi
│   ├── sub-mysubj001_sec-a_dwi.bval
│   ├── sub-mysubj001_sec-a_dwi.bvec
│   ├── sub-mysubj001_sec-a_dwi.json
│   └── sub-mysubj001_sec-a_dwi.nii.gz
└── func
    ├── sub-mysubj001_sec-a_task-rest_bold.json
    └── sub-mysubj001_sec-a_task-rest_bold.nii.gz
```

**Comment by chrisfilo** [comment]
I don't see `sub-` or `ses-` folders. It's also `ses` not `sec`.

Try running the [bids-validator](https://github.com/INCF/bids-validator) to check if your file naming fixes worked.

Having said that I think we should give better error in such situation.

**Comment by mick-d** [comment]
(banghead) It is probably the `sec` mistake, my apologies, let me check the bids-validator.

**Comment by oesteban** [comment]
It is indeed taken into account: the first option where you can define the `'TaskName'` is `/task-rest_bold.json`, so the validator is telling you that you may place a file named `task-rest_bold.json` right under your `bids/` folder. And that file should, at the very least contain:

```Json
{
  "TaskName": "Resting-state"
}
```

**Comment by mick-d** [comment]
Ahhh, i see, thanks a lot for this, will add it right now, I don't remember having errors without it before.

Thanks again

**Comment by oesteban** [comment]
Did that solve the issue?

**Comment by mick-d** [comment]
There were other BIDS validation errors/warnings that I am still addressing and I only changed "sec" by "ses" for every folders and files. Just doing that fixed the initial error.

Thanks a lot for the help!
