### ISSUE TITLE
TraitError in release 1.0.7

### ISSUE THREAD

**Issue by MetaD** [poldracklab/fmriprep#992]
Hi, I wonder if anyone could help with this error I got in release 1.0.7. I have successfully processed the same subject data with 1.0.0 before, but with 1.0.7 I got a lot of these trait errors in a few different workflows (`prepare_epi_opposite_wf/split`, `prepare_epi_matching_wf/split`, `bold_reference_wf/gen_ref`, etc.). I'm running it on a dataset with AP/PA fieldmaps.

```
Node: fmriprep_wf.single_subject_132_wf.func_preproc_task_face_run_01_wf.pepolar_unwarp_wf.prepare_epi_opposite_wf.split
Working directory: /u/flashscratch/m/mengdu/r107test/fmriprep_wf/single_subject_132_wf/func_preproc_task_face_run_01_wf/pepolar_unwarp_wf/prepare_epi_opposite_wf/split

Node inputs:

args = <undefined>
dimension = t
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
ignore_exception = False
in_file = ['/u/project/CCN/cparkins/data/hierarchy/sub-132/fmap/sub-132_dir-PA_epi.nii.gz']
out_base_name = <undefined>
output_type = NIFTI_GZ
terminal_output = <undefined>

Traceback (most recent call last):
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/utils.py", line 106, in nodelist_runner
    result = node.run(updatehash=updatehash)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 487, in run
    result = self._run_interface(execute=True)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 571, in _run_interface
    return self._run_command(execute)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 668, in _run_command
    _save_resultfile(result, outdir, self.name)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/utils.py", line 244, in save_resultfile
    result.outputs.set(**modify_paths(outputs, relative=True, basedir=cwd))
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/traits/util/deprecated.py", line 32, in wrapper
    return fn(*args, **kw)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/traits/has_traits.py", line 1551, in set
    trait_change_notify=trait_change_notify, **traits)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/traits/has_traits.py", line 1543, in trait_set
    setattr( self, name, value )
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/traits_extension.py", line 335, in validate
    value = super(MultiPath, self).validate(object, name, newvalue)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/traits/trait_types.py", line 2336, in validate
    return TraitListObject( self, object, name, value )
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/traits/trait_handlers.py", line 2313, in __init__
    raise excp
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/traits/trait_handlers.py", line 2305, in __init__
    value = [ validate( object, name, val ) for val in value ]
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/traits/trait_handlers.py", line 2305, in <listcomp>
    value = [ validate( object, name, val ) for val in value ]
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/traits_extension.py", line 112, in validate
    self.info_text, value))
traits.trait_errors.TraitError: The trait 'out_files' of a SplitOutputSpec instance is an existing file name, but the path  '/u/flashscratch/flashscratch2/m/mengdu/r107test/fmriprep_wf/single_subject_132_wf/func_preproc_task_face_run_01_wf/pepolar_unwarp_wf/prepare_epi_opposite_wf/split/mapflow/_split0/vol0000.nii.gz' does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 487, in run
    result = self._run_interface(execute=True)
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 1265, in _run_interface
    self.config['execution']['stop_on_first_crash'])))
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 1140, in _collate_results
    for i, nresult, err in nodes:
  File "/u/home/m/mengdu/.local/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/utils.py", line 113, in nodelist_runner
    if result.runtime and hasattr(result.runtime, 'traceback'):
AttributeError: 'NoneType' object has no attribute 'runtime'
```

**Comment by chrisfilo** [comment]
To help debugging could you upload the problematic dataset (one subject
will suffice) to http://OpenNeuro.org and run FMRIPREP there?

**Comment by MetaD** [comment]
Hi @chrisfilo , it turned out that the dataset runs successfully on OpenNeuro, so I tested a little bit on my cluster, and this error occurs only when I specify a working directory with -w. Does that help debugging? It looks like I can't specify -w on OpenNeuro...

**Comment by chrisfilo** [comment]
I see. Could you share the exact command line you are using? Is there anything special about `/u/flashscratch/flashscratch2/m/mengdu/r107test`? How large is it? What sort of file system is it (try `mount`)?

**Comment by chrisfilo** [comment]
Do you get this error if you point -w to a different filesystem/mount?

**Comment by MetaD** [comment]
Yes I think they look like different filesystems of the same type... Here's the information from `mount`:
```
aff8080-2:/scratch2 on /u/flashscratch/flashscratch2 type nfs (rw,vers=3,proto=tcp,hard,intr,retrans=2,timeo=600,rsize=65536,wsize=65536,sloppy,addr=172.16.97.52)
hpcnas1:/u/project/FMRI on /u/project/CCN type nfs (rw,vers=3,proto=tcp,hard,intr,retrans=2,timeo=600,rsize=65536,wsize=65536,sloppy,addr=172.16.97.43)
```
My command was
```
fmriprep /u/project/CCN/cparkins/data/hierarchy/ /u/project/CCN/cparkins/data/hierarchy/fmriprep/r107_output/ participant --output-space T1w fsnative template fsaverage -w $SCRATCH/r107test --ignore slicetiming --fs-license-file $FREESURFER_HOME/.license --participant-label 132
```
I've run this exact command (except for directory names) with the same subject successfully with fmriprep 1.0.0 though.

**Comment by chrisfilo** [comment]
There is a chance that something changed in terms of the NFS configuration in the meantime. Could you try pointing `-w` to a local filesystem (for example `/tmp`)? This could help us narrow down the issue.

@oesteban you've been using `-w` with the latest release without issues?

**Comment by oesteban** [comment]
Yes, I am using it with singularity though

**Comment by chrisfilo** [comment]
I wonder if this is related to NFS synchronization issue and could be worked around by using [`job_finished_timeout` nipype config option](http://nipype.readthedocs.io/en/latest/users/config_file.html)

**Comment by MetaD** [comment]
Just tried a working directory in the same filesystem and it failed with the same error... Do you mean to create a `nipype.cfg` and set `job_finished_timeout` to another value?

**Comment by chrisfilo** [comment]
`~/.nipype/nipype.cfg` would be safer bet. See example syntax http://nipype.readthedocs.io/en/latest/users/config_file.html#example

However this will not work if you are getting this error when `-w` is pointing to a local filesystem (not NFS).

**Comment by MetaD** [comment]
It turned out that pointing -w to a local filesystem did work (although it eventually failed because I didn't have enough space in my home directory), but setting a `job_finished_timeout` in `~/.nipype/nipype.cfg` still resulted in the same error I posted...

My BIDS directory is in a mounted NFS filesystem (`/u/project/CCN/`) and I was running the fmriprep command from there -- would that possibly cause this problem?

**Comment by chrisfilo** [comment]
what did you set the `job_finished_timeout` to? worth trying a larger value

**Comment by MetaD** [comment]
I've tried 1000 and the error is still there...

**Comment by chrisfilo** [comment]
This seems like a NFS sync issue. Basically nipype writes some output files and then verifies if they exist. NFS  doesn't sync fast enough and files are "not there yet".

If you can avoid using network drives for workdir that would be ideal. You can also try to consult your sysadmin to try to debug this further.

**Comment by MetaD** [comment]
Okay thanks for the info

**Comment by effigies** [comment]
Closing for now. Please reopen if this turns out to be something we can handle on our end.
